### ISSUE TITLE
Combining @staticmethod with other decorators is broken

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1434]
Consider

```
def debug(fun):
    print(fun)
    return fun

class A(object):
    @staticmethod
    @debug
    def foo(self):
        return self
```

In Python, this correctly prints `<function foo at 0x7f4d305df410>`.
In Cython, this wrongly prints `<staticmethod object at 0x7f4d30e5e718>`.

When doing the same with a Cython `cdef class`, the decorators are somehow applied twice: the output becomes

```
<staticmethod object at 0x7f4d30e5eb40>
<staticmethod object at 0x7f4d305e52f0>
```

Migrated from http://trac.cython.org/ticket/880

**Comment by jdemeyer** [comment]
Working on this.

**Comment by jdemeyer** [comment]
> Working on this.

Not really, this is too hard for me.

**Comment by Anxuae** [comment]
Hello,

I have the same issue when I combine `@staticmethod` with an other one after my module is cythonized. There is any update about this issue?

Thanks

Here is my decorator:
```
def memoize(function):
    def wrapper(*args):
        print(args)

    return wrapper
```

Here is my class:
```
class HydraWrapper(object):

    @staticmethod
    @memoize
    def get_tags():
        return request().get("?", params={"get_tags": ''}).json()
```

I got the following error:

```
    def test_get_tags():
>       data = HydraWrapper.get_tags()
E       TypeError: unbound method cython_function_or_method object must be called with HydraWrapper instance as first argument (got nothing instead)
```

**Comment by jdemeyer** [comment]
"the decorators are somehow applied twice" is fixed by #1724.

**Comment by liudangyi** [comment]
Looks like Cython handles the order of multiple decorators incorrectly. 

```py
class A(object):
    @decorate
    @staticmethod
    def a(self):
        pass

    @staticmethod
    @decorate
    def b():
        pass
```

Python can tell the difference between `A.a` and `A.b` but Cython can't. 

This would cause much trouble since we used to use `functools.wraps` in every decorator to preserve the original signature and docstring but `wraps` can only be applied on function object but not staticmethod object.

**Comment by scoder** [comment]
See #1274 for the original ticket. Basically, your `A.b` should not be special cased as a `staticmethod` by Cython, whereas `A.a` should. For `A.b`, things should be left to the user entirely.

**Comment by joshuahaertel** [comment]
Just hit this same issue. In case there's an important nuance, I'll add my test case.

file: `static_cythonized.py`
```
import functools


class Foo:
    @staticmethod
    @functools.lru_cache(None)
    def bar():
        pass
```
`python -c 'from static_cythonized import Foo'` works fine

1. Compile the file with `cythonize static_cythonized.py -i -3`
2. Rerunning `python -c 'from static_cythonized import Foo'` will give this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "static_cythonized.py", line 5, in init static_cythonized
    @functools.lru_cache(None)
  File "/usr/lib/python3.6/functools.py", line 480, in decorating_function
    wrapper = _lru_cache_wrapper(user_function, maxsize, typed, _CacheInfo)
TypeError: the first argument must be callable
```

**Comment by linuxhenhao** [comment]
For peoplo who facing the same issue here, I got a method to work around this problem.  convert a 
```
class A:
    @staticmethod
    @decorator
    def test():
          pass
```
to 
```
class A:
    def test():
          pass
    test = staticmethod(decorator(test))
```
A simple implementation of this kind of conversion using ast and astunparse is:
```
import ast, astunparse


class RewriteFuncdef(ast.NodeTransformer):
    def visit_ClassDef(self, node):
        for index, sub_node in enumerate(node.body):
            if not isinstance(sub_node, ast.FunctionDef):
                continue
                
            decorators = sub_node.decorator_list
            if self.need_rewrite(decorators):
                new_funcdef, assign = self.convert_func_def(sub_node)
                node.body.pop(index)
                node.body.insert(index ,assign)
                node.body.insert(index, new_funcdef)
        return node
                
    def need_rewrite(self, decorators) -> bool:
        for decorator in decorators:
            if isinstance(decorator, ast.Name) and decorator.id == "staticmethod":
                return True
        return False
    
    def convert_func_def(self, func_def):
        new_funcd = ast.FunctionDef(name=func_def.name, body=func_def.body, args=func_def.args, returns=func_def.returns, decorator_list=[])
        decorators = func_def.decorator_list
        a_name = ast.Name(id=func_def.name)
        a_value = self.gen_assign_value(a_name, decorators)
        assign = ast.Assign(targets=[a_name], value=a_value)
        return new_funcd, assign
    
    def gen_assign_value(self, func_name, decorators):
        args = [func_name]
        for decorator in reversed(decorators):
            args = [ast.Call(func=decorator, args=args, keywords=[])]
        return args[0]

module = ast.parse(open("static.py").read())
transformer = RewriteFuncdef()
transformer.visit(module)
generated_content = astunparse.unparse(module)

with open("new_file.py", "w") as f:
      f.write(generated_content)
```

Hope this can help somebody.

**Comment by juliusHuelsmann** [comment]
[Another quick and dirty workaround](https://gist.github.com/juliusHuelsmann/01558ee5d9d4cfd97e39cc79a9f37c18) if you have access to the decorator implementation (and not to the code that uses the decorators): 

```python
# noinspection PyPep8Naming
class SM(staticmethod):
    """
    Quick workaround that allows us to use Cython and multiple decorators.
    """

    def __init__(self, *args, **kwargs):
        super(staticmethod, self).__init__(*args, **kwargs)
        self.__inds_static_hack__ = args[0]

__static = globals()['__builtins__'].staticmethod = SM

# This has to be done for every decorator
def deco(_fun):
    fun = getattr(_fun, '__inds_static_hack__', _fun)
    def f(*args, **kwargs):
        return fun(*args, **kwargs)

    f.__name__ = fun.__name__ # etc...
    return f

class C:
    @staticmethod
    @deco
    def f():
        return 'f_return_value'

    @deco
    @staticmethod
    def g():
        return 'g_return_value'

print(f'both is fine : {C.f.__name__} returns {C.f()}, \n'
      f'               {C.g.__name__} returns {C.g()}. \n'
      f'This can also be used in a different file.')

```

I'm unsure if what I do is advisable, but it works for now :)

**Comment by oxeye-daniel** [comment]
Is there any update on this issue?

**Comment by haobibo** [comment]
Using the deprecated `abstractstaticmethod` is a temp fix for now. Hoping the bug can be fixed soon.

**Comment by tanjuntao** [comment]
Hoping this bug will be fixed soon, it's annoying.

**Comment by da-woods** [comment]
FWIW there is a PR that should fix this issue https://github.com/cython/cython/pull/3966 - testing that PR and letting me know whether it works or not for your would be useful. We don't really need more comments saying "I hope this is fixed soon" though.

**Comment by eli-schwartz** [comment]
What's the story with that PR now? It seems to conflict, so it's not trivially testable.

**Comment by da-woods** [comment]
@eli-schwartz I think I've fixed the PR conflict so hopefully should be usable again.

I'm not sure what the status/priority of the PR is though. The "convert the first argument to fused" hack I adopted is honestly a little awkward (the one thing it has going for it is that it does work)

**Comment by samfrances** [comment]
I don't know if this is an example of this issue or a different issue, but I encountered problems with the following minimal example:

```
from functools import cache


class Foo:
    @staticmethod
    @cache
    def foo():
        return 5

    def bar(self):
        return self.foo()


class Foo2:
    @staticmethod
    def foo():
        return 5

    def bar(self):
        return self.foo()
```

Under Python, calling `Foo().bar()` and `Foo2().bar()` both returns 5.

Under Cython, calling `Foo().bar()` raises `TypeError: foo() takes no arguments (1 given)` (whereas `Foo2().bar()` still works.
