### ISSUE TITLE
pyximport regression between 0.24.1 and master

### ISSUE THREAD

**Issue by bjodah** [cython/cython#1494]
Using a `.pyxbld` file:

https://gist.github.com/bjodah/001633712d2531f20a74ab975bb08e62

code to reproduce:

```
$ git checkout 0.24.1
$ cd ~/tmp/001633712d2531f20a74ab975bb08e62-b7ea198f1f8c229de846d1fe59cf929e94ceae2c
$ python2 test_my.py
[1/1] Cythonizing /home/bjorn/tmp/001633712d2531f20a74ab975bb08e62-b7ea198f1f8c229de846d1fe59cf929e94ceae2c/my.pyx
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Success!
Success!
$ cd -; git checkout 0.25b2; cd -
$ rm -rf my.pyxbldc my.cpp __pycache__/; python test_my.py
Compiling /home/bjorn/tmp/001633712d2531f20a74ab975bb08e62-b7ea198f1f8c229de846d1fe59cf929e94ceae2c/my.pyx because it changed.
[1/1] Cythonizing /home/bjorn/tmp/001633712d2531f20a74ab975bb08e62-b7ea198f1f8c229de846d1fe59cf929e94ceae2c/my.pyx
Traceback (most recent call last):
  File "test_my.py", line 3, in <module>
    from my import PyClass, square_approximate_area
  File "/home/bjorn/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "/home/bjorn/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/home/bjorn/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/home/bjorn/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/home/bjorn/.local/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 90, in pyx_to_dll
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/lib/python2.7/distutils/dist.py", line 564, in _parse_command_opts
    (args, opts) = parser.getopt(args[1:])
  File "/usr/lib/python2.7/distutils/fancy_getopt.py", line 259, in getopt
    raise DistutilsArgError, msg
ImportError: Building module my failed: ['DistutilsArgError: option --pyrex-c-in-temp not recognized\n']
```

**Comment by robertwb** [comment]
I have been unable to reproduce this, either with a fresh install, or installing 0.24.1 then 0.25. How is Cython installed on your system?

**Comment by bjodah** [comment]
@robertwb I tried to reproduce this in a Dockerfile and I can't, I have installed cython using `python -m pip install --user -e .` in my git checkout of the Cython repo. Closing this since it's a local issue on my computer. Sorry about the noise.

**Comment by cython-notifications** [comment]
No problem. Thanks for following up (and for helping out on the list).
