### ISSUE TITLE
pyximport: pyimport = True is broken

### ISSUE THREAD

**Issue by anton-malakhov** [cython/cython#1527]
In short: cythonizing Dask does not work.

Versions:
python                    3.5.2
cython                    0.25.1
dask                      0.12.0

Just `conda install dask` or pip install it.

Log:
```
$ cat >cythonize_dask.py
import pyximport; pyximport.install(pyimport = True)
import dask
$ python cythonize_dask.py
/localdisk/work/amalakho/miniconda3/envs/anaconda/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
Exception ignored in: 'dask'
AttributeError: 'LibLoader' object has no attribute 'path'
Traceback (most recent call last):
  File "/localdisk/work/amalakho/miniconda3/envs/anaconda/lib/python3.5/site-packages/pyximport/pyximport.py", line 217, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/localdisk/work/amalakho/miniconda3/envs/anaconda/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "dask/__init__.py", line 3, in init dask.__init__ (/nfs/an/proj/scripting_tools/amalakho/home/.pyxbld/temp.linux-x86_64-3.5/pyrex/dask/__init__.c:930)
ImportError: No module named 'dask.core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cythonize_dask.py", line 2, in <module>
    import dask.core
  File "/localdisk/work/amalakho/miniconda3/envs/anaconda/lib/python3.5/site-packages/pyximport/pyximport.py", line 406, in load_module
    return load_module(fullname, source_path, so_path=so_path, is_package=is_package)
  File "/localdisk/work/amalakho/miniconda3/envs/anaconda/lib/python3.5/site-packages/pyximport/pyximport.py", line 232, in load_module
    raise exc.with_traceback(tb)
  File "/localdisk/work/amalakho/miniconda3/envs/anaconda/lib/python3.5/site-packages/pyximport/pyximport.py", line 217, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/localdisk/work/amalakho/miniconda3/envs/anaconda/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "dask/__init__.py", line 3, in init dask.__init__ (/nfs/an/proj/scripting_tools/amalakho/home/.pyxbld/temp.linux-x86_64-3.5/pyrex/dask/__init__.c:930)
ImportError: Building module dask failed: ["ImportError: No module named 'dask.core'\n"]
```

**Comment by grigi** [comment]
I found this issue as well on Cython 0.28 on Linux. using `pyximport.install(pyimport = True)` I have a package called 'stuff' with a `__init__.py` and a `utils.py`. (utils has a few constants)
Doing a ```import stuff.utils``` will always fail with ```AttributeError: 'LibLoader' object has no attribute 'path'``` and then complain with an import error as above.

If I rename the `utils.py` to `utils.pyx` and use pyximport without `pyimport = True` then it works as expected.

**Comment by schneiderfelipe** [comment]
Same error here, it seems that `pyimport=True` doesn't propagate the option to further `import`s inside the imported module?
