### ISSUE TITLE
Testsuite failure on 32-bit linux

### ISSUE THREAD

**Issue by vbraun** [cython/cython#1530]
Most of these are trivial but the `lshift_int` test looks like it could be a real issue (see also https://trac.sagemath.org/ticket/21830). This is on cython-0.25.1:
~~~~
======================================================================
FAIL: lshift_int (line 137) (pyintop.__test__)
Doctest: pyintop.__test__.lshift_int (line 137)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave-sage/slave/sage_git/build/local/lib/python/doctest.py", line 2226, in runTest
l    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pyintop.__test__.lshift_int (line 137)
  File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/c/pyintop/pyintop.so", line unknown line number, in lshift_int (line 137)

----------------------------------------------------------------------
File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/c/pyintop/pyintop.so", line ?, in pyintop.__test__.lshift_int (line 137)
Failed example:
    bigints(lshift_int(-1))
Expected:
    (-8, -2147483648, -9223372036854775808, -10633823966279326983230456482242756608)
Got:
    (-8, -2147483648, -2147483648, -10633823966279326983230456482242756608)
----------------------------------------------------------------------
File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/c/pyintop/pyintop.so", line ?, in pyintop.__test__.lshift_int (line 137)
Failed example:
    (2**28) << 3
Expected:
    2147483648
Got:
    2147483648L
----------------------------------------------------------------------
File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/c/pyintop/pyintop.so", line ?, in pyintop.__test__.lshift_int (line 137)
Failed example:
    (2**30) << 3
Expected:
    8589934592
Got:
    8589934592L


======================================================================
FAIL: lshift_int (line 137) (pyintop.__test__)
Doctest: pyintop.__test__.lshift_int (line 137)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave-sage/slave/sage_git/build/local/lib/python/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pyintop.__test__.lshift_int (line 137)
  File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/cpp/pyintop/pyintop.so", line unknown line number, in lshift_int (line 137)

----------------------------------------------------------------------
File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/cpp/pyintop/pyintop.so", line ?, in pyintop.__test__.lshift_int (line 137)
Failed example:
    bigints(lshift_int(-1))
Expected:
    (-8, -2147483648, -9223372036854775808, -10633823966279326983230456482242756608)
Got:
    (-8, -2147483648, -2147483648, -10633823966279326983230456482242756608)
----------------------------------------------------------------------
File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/cpp/pyintop/pyintop.so", line ?, in pyintop.__test__.lshift_int (line 137)
Failed example:
    (2**28) << 3
Expected:
    2147483648
Got:
    2147483648L
----------------------------------------------------------------------
File "/home/buildslave-sage/slave/sage_git/build/local/var/tmp/sage/build/cython-0.25.1.p0/src/TEST_TMP/run/cpp/pyintop/pyintop.so", line ?, in pyintop.__test__.lshift_int (line 137)
Failed example:
    (2**30) << 3
Expected:
    8589934592
Got:
    8589934592L


----------------------------------------------------------------------
Ran 10216 tests in 2973.938s

FAILED (failures=2, skipped=2)
~~~~

**Comment by robertwb** [comment]
Fix for the trailing `L`s: https://github.com/cython/cython/commit/ea1939d4e88c598dd9685ca5372d6da73e0b44b0

**Comment by robertwb** [comment]
@scoder

**Comment by tobihan** [comment]
I just did some test runs on i386. The commit ea1939d fixes the missing L's, but commit e4fcfa3b does not fix the two remaining tests. Changing the 63 in line 2939 of Cython/Compiler/Optimize.py to a 31 fixes them.

**Comment by scoder** [comment]
Hmm, I didn't actually mean to close this. Could someone try if commit afeb193f97a5f7b85f7128f252b6071127e4031a fixes this problem?

**Comment by tobihan** [comment]
Yes, afeb193 fixes the problem. Thanks!
