### ISSUE TITLE
cythonize doesn't work with cython_compile_time_env

### ISSUE THREAD

**Issue by sirfz** [cython/cython#1572]
The following works:

```python
from Cython.Distutils import build_ext  # old_build_ext
from Cython.Distutils import Extension

setup(name='test',
      cmdclass={'build_ext': build_ext},
      ext_modules=[Extension('test', sources=['test.pyx'], language='c++',
                             cython_compile_time_env={'TEST_ENV': 123})])
```

But the following doesn't:

```python
from setuptools.command.build_ext import build_ext
from Cython.Distutils import Extension

class my_build_ext(build_ext, object):
    def finalize_options(self):
        from Cython.Build.Dependencies import cythonize
        self.distribution.ext_modules[:] = cythonize(
            self.distribution.ext_modules)
        super(my_build_ext, self).finalize_options()

setup(name='test',
      cmdclass={'build_ext': my_build_ext},
      ext_modules=[Extension('test', sources=['test.pyx'], language='c++',
                             cython_compile_time_env={'TEST_ENV': 123})])
```
`cythonize` fails with error `Compile-time name 'TEST_ENV' not defined`.

`my_build_ext` is basically a copy of `Cython.Distutils.built_ext.new_build_ext` but it doesn't seem to be compatible with the `cython_compile_time_env` parameter which is essential for my package.

I'm trying to make my package compatible with `new_build_ext` but it seems that this is a missing feature or am I missing something?

**Comment by sirfz** [comment]
Follow-up, the proper parameter to pass to `cythonize` is `compile_time_env` instead of `cython_compile_time_env` but shouldn't this be automatically handled by `cythonize` when passed an `Extension` with the `cython_compile_time_env` attribute set?

**Comment by scoder** [comment]
Yes, it should. Pull request welcome.

**Comment by kif** [comment]
Our code is also broke due to missing compile time options. But we specified them as 
```
patched_exts = cythonize(
                [ext],
                compiler_directives={'embedsignature': True},
                force=self.force_cython,
                compile_time_env={"HAVE_OPENMP": self.use_openmp}
            )
```

**Comment by DBBrowne** [comment]
Apologies for resurecitng this, but:
How would you refernce those coimpile-time variable within the python code that will get compiled?

**Comment by dforero0896** [comment]
Hi, I've been having the same problem though it looks like the keword I should use is really `cython_compile_time_env`. 
When compiling I have:
```python
cython_compile_time_env = {}
pyfcfc_sky = Extension("pyfcfc.sky",
                  sources=[fcfc_pyx] + sources,
                  include_dirs=includes + default_includes,
                  library_dirs=['/usr/lib/x86_64-linux-gnu'],
                  language='c',
                  extra_compile_args=extra_compile_args,
                  extra_link_args=["-fopenmp"],
                  define_macros = define_macros,
                  cython_compile_time_env=cython_compile_time_env, # cython_compile_time_env["WITH_SIMD"] = 0
             )
```
and cythonizing I get the following. from `vars(pyfcfc_sky)`:
```python
python setup.py build_ext --inplace
{'name': 'pyfcfc.boxes', 'sources': ['FCFC-main/src/fcfc/2pt_box/pyfcfc.pyx', 'FCFC-main/src/fcfc/2pt_box/count_func.c', 'FCFC-main/src/fcfc/2pt_box/eval_cf.c', 'FCFC-main/src/fcfc/2pt_box/load_conf.c', 'FCFC-main/src/fcfc/2pt_box/save_res.c', 'FCFC-main/src/fcfc/2pt_box/setup_cf.c', 'FCFC-main/src/fcfc/2pt_box/build_tree.c', 'FCFC-main/src/fcfc/2pt_box/metric_common.c', 'FCFC-main/src/fcfc/2pt_box/metric_kdtree.c', 'FCFC-main/src/fcfc/2pt_box/fcfc.c', 'FCFC-main/src/fcfc/2pt_box/dual_tree.c', 'FCFC-main/src/fcfc/2pt_box/metric_balltree.c', 'FCFC-main/src/fcfc/2pt_box/read_res.c', 'FCFC-main/src/io/read_ascii.c', 'FCFC-main/src/io/read_hdf5.c', 'FCFC-main/src/io/write_file.c', 'FCFC-main/src/io/ascii_fmtr.c', 'FCFC-main/src/io/read_fits.c', 'FCFC-main/src/lib/timsort.c', 'FCFC-main/src/lib/libast.c', 'FCFC-main/src/lib/libcfg.c', 'FCFC-main/src/math/legauss.c', 'FCFC-main/src/math/cspline.c', 'FCFC-main/src/math/pca.c', 'FCFC-main/src/tree/kdtree.c', 'FCFC-main/src/tree/balltree.c', 'FCFC-main/src/tree/qselect.c', 'FCFC-main/src/util/parallel.c', 'FCFC-main/src/util/create_lut.c'], 'include_dirs': ['FCFC-main/src/fcfc/2pt_box', 'FCFC-main/src/io', 'FCFC-main/src/lib', 'FCFC-main/src/math', 'FCFC-main/src/tree', 'FCFC-main/src/util', '/global/homes/d/dforero/.conda/envs/nbk-env/lib/python3.8/site-packages/numpy/core/include', '/usr/include'], 'define_macros': [('OMP', None)], 'undef_macros': [], 'library_dirs': ['/usr/lib/x86_64-linux-gnu'], 'libraries': [], 'runtime_library_dirs': [], 'extra_objects': [], 'extra_compile_args': ['-fopenmp', '-march=native'], 'extra_link_args': ['-fopenmp'], 'export_symbols': [], 'swig_opts': [], 'depends': [], 'language': 'c', 'optional': None, 'cython_include_dirs': [], 'cython_directives': {}, 'cython_create_listing': False, 'cython_line_directives': False, 'cython_cplus': False, 'cython_c_in_temp': False, 'cython_gen_pxi': False, 'cython_gdb': False, 'no_c_in_traceback': False, 'cython_compile_time_env': {'WITH_SIMD': 0}}
```

So the `compile_time_env` is taken into account, but later I get:

```python
[1/2] Cythonizing FCFC-main/src/fcfc/2pt/pyfcfc.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    ctypedef struct DATA:
        size_t n;             # number of objects         
        real *x[3];   # coordinates               
        real *w;              # weights                   
        double wt;            # weighted number of objects
    IF WITH_SIMD == 1:
      ^
------------------------------------------------------------

FCFC-main/src/fcfc/2pt/pyfcfc.pyx:79:7: Compile-time name 'WITH_SIMD' not defined

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    ext_modules=cythonize([pyfcfc_box, pyfcfc_sky], gdb_debug=False),
  File "/global/homes/d/dforero/.conda/envs/nbk-env/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/global/homes/d/dforero/.conda/envs/nbk-env/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: FCFC-main/src/fcfc/2pt/pyfcfc.pyx
```

Do you know what is happening here?

Thanks in advance for your help.

**Comment by scoder** [comment]
As I wrote before:
> Pull request welcome.
