### ISSUE TITLE
`cythonize` crashes running `setup.py --version`

### ISSUE THREAD

**Issue by rainwoodman** [cython/cython#1593]
Backtrace:

```
(root) [yfeng1@waterfall pmesh]$ python setup.py --version
/home/yfeng1/anaconda3/install/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    ext_modules = cythonize(extensions)
  File "/home/yfeng1/anaconda3/install/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/yfeng1/anaconda3/install/lib/python3.5/distutils/dist.py", line 253, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/home/yfeng1/anaconda3/install/lib/python3.5/distutils/dist.py", line 1208, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/home/yfeng1/anaconda3/install/lib/python3.5/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-python'
```

setup.py script:

```
from distutils.core import setup
from Cython.Build import cythonize
from distutils.extension import Extension
import numpy
import os

def find_version(path):
    import re
    # path shall be a plain ascii text file.
    s = open(path, 'rt').read()
    version_match = re.search(r"^__version__ = ['\"]([^'\"]*)['\"]",
                              s, re.M)
    if version_match:
        return version_match.group(1)
    raise RuntimeError("Version not found")


extensions = [
        Extension("pmesh._domain", ["pmesh/_domain.pyx"], include_dirs=["./", numpy.get_include()]),
        Extension("pmesh._window", ["pmesh/_window.pyx", "pmesh/_window_imp.c"],
                depends=["pmesh/_window_imp.h", "pmesh/_window_generics.h", "pmesh/_window_wavelets.h", "pmesh/_window_lanczos.h"], include_dirs=["./", numpy.get_include()]),
        Extension("pmesh._whitenoise", ["pmesh/gsl/ranlxd.c", "pmesh/gsl/missing.c", "pmesh/gsl/rng.c", "pmesh/_whitenoise_imp.c", "pmesh/_whitenoise.pyx"],
                depends=["pmesh/gsl/config.h", "pmesh/gsl/gsl_errno.h",
                         "pmesh/gsl/gsl_inline.h", "pmesh/gsl/gsl_rng.h",
                         "pmesh/gsl/gsl_types.h",
                         "pmesh/_whitenoise_imp.h", "pmesh/_whitenoise_generics.h"
                        ],
                include_dirs=["pmesh/gsl", "pmesh", numpy.get_include()])
        ]
#print(find_version("pmesh/version.py"))

setup(
    name="pmesh", version=find_version("pmesh/version.py"),
    author="Yu Feng",
    description="Particle Mesh in Python",
    package_dir = {'pmesh': 'pmesh'},
    packages= ['pmesh', 'pmesh.tests'],
    install_requires=['cython', 'numpy', 'mpi4py', 'mpsort', 'pfft-python'],
    requires=['cython', 'numpy', 'mpi4py', 'mpsort', 'pfft-python'],
    ext_modules = cythonize(extensions)
)
```

**Comment by rainwoodman** [comment]
not due to cythonize.
