### ISSUE TITLE
Error message while accessing a non-existent method of a class without gil can be improved.

### ISSUE THREAD

**Issue by MechCoder** [cython/cython#1629]
Hi,

Thanks for the work! Here is a code snippet.

In example.pxd
```python
cdef class ParentClass:
    cdef void print_(self)
```

In example.pyx
```python
cdef class ParentClass:
    cdef void print_(self):
        print("here")

f = ParentClass()
with nogil:
    f.temp()
```

While compiling the sources, the error raised is Constructing Python tuple not allowed without gil, which is a bit confusing.

Thanks!

**Comment by scoder** [comment]
Might be as easy as changing the order in which the children of the syntax tree node are traversed here. Not sure, but it might generally be a good idea to report GIL errors top-down rather than bottom-up in the tree traversal.

**Comment by okar0** [comment]
Hi, does this issue still need fixing? I'd like to give it a go.

**Comment by da-woods** [comment]
I think so. There's a simple example that shows the problem in the issue description, so it's easy to test and see if you get the same message

**Comment by akettmann** [comment]
building the code as listed has 5 errors:

```python
setup.py build_ext --inplace 
Compiling example.pyx because it changed.
[1/1] Cythonizing example.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef void print_(self):
        print('here')

f = ParentClass()
with nogil:
    f.temp()          ^
------------------------------------------------------------

example.pyx:7:10: Discarding owned Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    cdef void print_(self):
        print('here')

f = ParentClass()
with nogil:
    f.temp()          ^
------------------------------------------------------------

example.pyx:7:10: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    cdef void print_(self):
        print('here')

f = ParentClass()
with nogil:
    f.temp()     ^
------------------------------------------------------------

example.pyx:7:5: Accessing Python attribute not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    cdef void print_(self):
        print('here')

f = ParentClass()
with nogil:
    f.temp()    ^
------------------------------------------------------------

example.pyx:7:4: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
    cdef void print_(self):
        print('here')

f = ParentClass()
with nogil:
    f.temp()          ^
------------------------------------------------------------

example.pyx:7:10: Constructing Python tuple not allowed without gil
Traceback (most recent call last):
  File "C:\Users\veigar\PycharmProjects\learn_cython\setup.py", line 5, in <module>
    ext_modules=cythonize(
        "example.pyx",
    )
  File "C:\Users\veigar\PycharmProjects\learn_cython\.venv\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
    ~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\veigar\PycharmProjects\learn_cython\.venv\Lib\site-packages\Cython\Build\Dependencies.py", line 1298, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: example.pyx
```

**Comment by akettmann** [comment]
Most of these errors don't actually make sense to me. However, comparing the syntax posted and the docs I think there are additional bits needed to release the GIL here. Including not using `print` (the source of `example.pyx:7:4: Accessing Python global or builtin not allowed without gil`)

**Comment by da-woods** [comment]
It'd work better if you had a newline at the end of the file (the `^` would point to the right place; although this is fixed in the master branch).

> Discarding owned Python object not allowed without gil

`f.temp()` returns a Python object - the reference for that needs to be dropped.

> Calling gil-requiring function not allowed without gil

That refers to calling `f.temp`.

> Accessing Python attribute not allowed without gil

That refers to looking up `temp` on `f`.

> Accessing Python global or builtin not allowed without gil

That refers to looking up `f` in the global namespace

> Constructing Python tuple not allowed without gil

This is less obvious, but it refers to generating the argument tuple for the function call.

In practice the call, attribute lookup and tuple are actually squashed together into a single operation on most versions of Python though.

Presentation could definitely be improved though - a lot of this really is internal detail.

**Comment by akettmann** [comment]
Yeah I think the OP's understanding was incorrect. The base code was broken. This functions to actually let you call `ParentClass.print_`:

example.pyx:
```python
cdef class ParentClass:
    cdef void print_(self) noexcept nogil:
        pass

cdef ParentClass f
f = ParentClass()
with nogil:
    f.print_()
```

example.pyd:
```python
cdef class ParentClass:
    cdef void print_(self) noexcept nogil
```

**Comment by akettmann** [comment]
Once I have working base code, the errors are a bit clearer:

```python
setup.py build_ext --inplace 
Compiling example.pyx because it changed.
[1/1] Cythonizing example.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        pass

cdef ParentClass f
f = ParentClass()
with nogil:
    f.not_there()
               ^
------------------------------------------------------------

example.pyx:8:15: Discarding owned Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        pass

cdef ParentClass f
f = ParentClass()
with nogil:
    f.not_there()
               ^
------------------------------------------------------------

example.pyx:8:15: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        pass

cdef ParentClass f
f = ParentClass()
with nogil:
    f.not_there()
     ^
------------------------------------------------------------

example.pyx:8:5: Accessing Python attribute not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        pass

cdef ParentClass f
f = ParentClass()
with nogil:
    f.not_there()
               ^
------------------------------------------------------------

example.pyx:8:15: Constructing Python tuple not allowed without gil
Traceback (most recent call last):
  File "C:\Users\veigar\PycharmProjects\learn_cython\setup.py", line 5, in <module>
    ext_modules=cythonize(
        "example.pyx",
    )
  File "C:\Users\veigar\PycharmProjects\learn_cython\.venv\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
    ~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\veigar\PycharmProjects\learn_cython\.venv\Lib\site-packages\Cython\Build\Dependencies.py", line 1298, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: example.pyx
```

**Comment by akettmann** [comment]
I read this like we are dipping out to Python land to see if someone assigned `f.not_there` while we weren't looking? Clarifying this error message to be something like:
>While in a nogil block, you attempted to access an attribute that doesn't exist, which generates GIL requiring actions by default. Please ensure you are interacting with objects and attributes that exist, and do not require the GIL.

Is that something actually reasonable to accomplish at all? Is it still a good "first issue"? I am very new on understanding anything internal to Cython.

**Comment by da-woods** [comment]
> Is that something actually reasonable to accomplish at all? Is it still a good "first issue"? I am very new on understanding anything internal to Cython.

Practically it's fairly easy to change. Find the old error message with a text search (it'll be in ExprNodes.py or Nodes.py) and replace it with the new error message. I find `git grep` useful for this type of search but use whatever...

> I read this like we are dipping out to Python land to see if someone assigned `f.not_there` while we weren't looking? Clarifying this error message to be something like:
> 
> > While in a nogil block, you attempted to access an attribute that doesn't exist, which generates GIL requiring actions by default. Please ensure you are interacting with objects and attributes that exist, and do not require the GIL.

Personally I think:
* that's a bit verbose,
* "doesn't exist" probably means "isn't known at compile time" or maybe just "an unknown attribute".
* "generates GIL requiring actions by default" implies there's a non-default option that doesn't need the GIL.

**Comment by akettmann** [comment]
Also, I want to explicitly ask:

I am new here. Do you see value to be gained by making changes here? If so what are they? I am happy to implement them, but since I am new to the project still, I am hesitant to go decide on my form of "reasonable change" without some form of feedback from someone more experienced. 

My goal here is to be forced to learn some nasty Cython internals while fixing a problem. Part of that is to ensure the problem I see is actually a problem and that my solution will be an acceptable one.

**Comment by da-woods** [comment]
> Do you see value to be gained by making changes here?

Yes - I agree with the issue, that the message displayed is confusing.

Of the 5 messages I think the most confusing are:

> Discarding owned Python object not allowed without gil

and

> Constructing Python tuple not allowed without gil

Unfortunately these are the first and last message, which are usually the one's that people read. It also means @scoder's suggestion of changing the order won't really help.  I don't think the other messages need (big) changes.

So I'd focus on those two messages.  For the "tuple" message it might be be useful to add a special-case for tuples that are constructed as function arguments (since those are hidden and most users won't realize they're creating a tuple)

**Comment by akettmann** [comment]
Ok I will go this direction. Sounds reasonable to me. I will likely have more questions, but I think I have a solid direction.

**Comment by akettmann** [comment]
What guides the order of error reporting? We report the issue of throwing away a tuple in `nogil` before we error on actually creating the tuple.

**Comment by da-woods** [comment]
It's essentially descending the tree of nodes.

This bit will be in the `GILCheck` step near the end of the pipeline:

https://github.com/cython/cython/blob/3ad07c266513f3dc30bc9254e98722d6282d765c/Cython/Compiler/Pipeline.py#L237

If you put a `PrintTree` step in there just before it you'll see what nodes there are. But it'll look something like

```
ExprStatNode (disposes of result)
- CallNode
  - AttributeNode
    - NameNode
  - TupleNode
```

**Comment by akettmann** [comment]
Oh awesome, looks like this is what the concerned portion compiles down to:

```
    - stats[2]: GILStatNode(pos=(example.pyx:7:5))
      - body: StatListNode(pos=(example.pyx:8:15))
        - stats[0]: ExprStatNode(pos=(example.pyx:8:15))
          - expr: PyMethodCallNode(type=<PyObjectType>)
            - function: AttributeNode(type=<PyObjectType>, attribute="not_there")
              - obj: NameNode(type=<PyExtensionType ParentClass>, name="f")
            - arg_tuple: TupleNode(type=<(&PyTuple_Type)>)
      - finally_clause: StatListNode(pos=(example.pyx:7:5))
        - stats[0]: GILExitNode(pos=(example.pyx:7:5))
      - finally_except_clause: StatListNode(pos=(example.pyx:7:5))
        - stats[0]: GILExitNode(pos=(example.pyx:7:5))
```
I think I understand now, the order is weird to me because parsing/compilation happens separately from finding and reporting errors. We make the tree, _then_ inspect it for validity. So the order of the validation code is what is guiding the order of the error reporting.

**Comment by akettmann** [comment]
Answering my own question:

> Why do we report this tuple disposal error first?

As always the answer is "The code says to". 

We are doing validation on the tree of parsed/transformed code. Current stage: `GilCheck` 

Walking the tree, using the Visitor pattern. More directly:

we take the `GILCheck` object and check it for the class names of our leaves of our tree. So a GILStatNode will look for `visit_GILStatNode`, if it doesn't exist, it checks the next class in the MRO, `Node`, then `Object`. If none, we don't do anything to that node I believe.

Handler lookup:
https://github.com/cython/cython/blob/e9af812c4135f88676495568abf4a4831721d029/Cython/Compiler/Visitor.py#L144-L159

So GILCheck gets to the ExprStatNode, and runs its handler, no ExprStatNode handler, so we `visit_Node`. 

https://github.com/cython/cython/blob/d9ca7d0f2cb951eeba7edfb71811c6f72ce86019/Cython/Compiler/ParseTreeTransforms.py#L3836-L3838

There is more code to that function, but it is all we are doing right now. Now we are using `ExprStatNode.nogil_check`

https://github.com/cython/cython/blob/d8f90740dbadcb7a951526e99c512e21179b7fa4/Cython/Compiler/Nodes.py#L6112-L6114


So the ExprStatNode reports the error and is higher in the tree than the PyMethodCallNode, so it goes first.
