### ISSUE TITLE
crash when specializing template with undefined name

### ISSUE THREAD

**Issue by llllllllll** [cython/cython#1647]
The following cython code causes the compiler to crash:

```
from libcpp.cast cimport static_cast

cdef int* value = NULL
static_cast[undefined_name](value)
```

the error is:

```
$ cythonize cython_crasher.pyx 
Compiling /home/joe/projects/tmp/cython_crasher.pyx because it changed.
[1/1] Cythonizing /home/joe/projects/tmp/cython_crasher.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.cast cimport static_cast

cdef int* value = NULL
static_cast[undefined_name](value)
                         ^
------------------------------------------------------------

cython_crasher.pyx:4:26: not parsable as a type

Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.cast cimport static_cast

cdef int* value = NULL
static_cast[undefined_name](value)
          ^
------------------------------------------------------------

cython_crasher.pyx:4:11: Compiler crash in AnalyseExpressionsTransform

File 'Nodes.py', line 430, in analyse_expressions: StatListNode(cython_crasher.pyx:1:0)
File 'Nodes.py', line 4746, in analyse_expressions: ExprStatNode(cython_crasher.pyx:4:27)
File 'ExprNodes.py', line 519, in analyse_expressions: SimpleCallNode(cython_crasher.pyx:4:27,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 5093, in analyse_types: SimpleCallNode(cython_crasher.pyx:4:27,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 3387, in analyse_types: IndexNode(cython_crasher.pyx:4:11,
    is_called = 1,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 3457, in analyse_base_and_index_types: IndexNode(cython_crasher.pyx:4:11,
    is_called = 1,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 3558, in analyse_as_c_function: IndexNode(cython_crasher.pyx:4:11,
    is_called = 1,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/home/joe/quantopian/fundamentals/submodules/cython/Cython/Compiler/ExprNodes.py", line 3558, in analyse_as_c_function
    elif len(base_type.templates) != len(self.type_indices):
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/joe/.virtualenvs/fundamentals/bin/cythonize", line 11, in <module>
    load_entry_point('Cython', 'console_scripts', 'cythonize')()
  File "/home/joe/quantopian/fundamentals/submodules/cython/Cython/Build/Cythonize.py", line 196, in main
    cython_compile(path, options)
  File "/home/joe/quantopian/fundamentals/submodules/cython/Cython/Build/Cythonize.py", line 90, in cython_compile
    **options.options)
  File "/home/joe/quantopian/fundamentals/submodules/cython/Cython/Build/Dependencies.py", line 935, in cythonize
    cythonize_one(*args)
  File "/home/joe/quantopian/fundamentals/submodules/cython/Cython/Build/Dependencies.py", line 1057, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/joe/projects/tmp/cython_crasher.pyx
```

We do get the correct error message: `cython_crasher.pyx:4:26: not parsable as a type` but it is harder to find with the crash traceback.

**Comment by llllllllll** [comment]
thanks!
