### ISSUE TITLE
segfault with asyncio

### ISSUE THREAD

**Issue by toriningen** [cython/cython#1685]
On macOS 10.12.4, Cython 0.25.2, Python 3.6.1, if you await asyncio.sleep() <= Cython <= Python chain, it will segfault. It won't die if you await Cython future right away, without first using Python.

Here is an example that reproduces this bug:

main.py:
```
WANT_CRASH = True

import asyncio
import cy_test

async def main():
    await cy_test.say()

loop = asyncio.get_event_loop()

if WANT_CRASH:
    loop.run_until_complete(main())
else:
    loop.run_until_complete(cy_test.say())

loop.close()
```

cy_test.pyx:
```
import asyncio
from py_test import py_async

async def cy_async():
    print("- this one is from Cython")

async def say():
    await cb()

async def cb(): # renaming this to "say" would prevent crash
    print("Async functions can be awaited without problem:")
    await cy_async()
    await py_async()
    print("And this will actually sleep for 3 seconds before crashing")
    await asyncio.sleep(3)
    print("I will be never output, because app has crashed already")
```

py_test.py:
```
async def py_async():
    print("- and this one is from Python")
```

Setup.py:
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

setup(
    name='asyncio_cb',
    ext_modules=cythonize([
        Extension("cy_test", ["cy_test.pyx"]),
    ]),
)
```

Makefile:
```
all:
	python3 Setup.py build_ext --inplace

test:	all
	python3 main.py

clean:
	@echo Cleaning
	@rm -f cy_*.c *.o *.so *~ core
	@rm -rf build
```

**Comment by chenfengyuan** [comment]
Maybe there is a typo in filename:   `py_test.pyx` should be `py_test.py`

**Comment by scoder** [comment]
Is this still an issue with latest master?
Could be that 3cd1e3da1766246b6b2fb053e651c1a2bed382b7 fixed it already.

**Comment by toriningen** [comment]
@chenfengyuan updated issue to fix that typo.

**Comment by toriningen** [comment]
@scoder I have just checked it — unfortunately, latest master (0.24-1755-g829d7bbef) is still segfaulting, macOS 10.12.6, Python 3.6.4.

Crashlog:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	000000000000000000 0 + 0
1   cy_test.cpython-36m-darwin.so 	0x000000010e612d60 __Pyx_CoroutineAwait_Next + 48
2   org.python.python             	0x000000010da8f44e _PyEval_EvalFrameDefault + 15238
3   org.python.python             	0x000000010da10d54 gen_send_ex + 214
4   _asyncio.cpython-36m-darwin.so	0x000000010e4e2e38 task_step + 446
5   _asyncio.cpython-36m-darwin.so	0x000000010e4e3bd4 task_wakeup + 346
6   _asyncio.cpython-36m-darwin.so	0x000000010e4e289e TaskWakeupMethWrapper_call + 134
7   org.python.python             	0x000000010d9f7942 PyObject_Call + 101
8   org.python.python             	0x000000010da8cdfc _PyEval_EvalFrameDefault + 5428
9   org.python.python             	0x000000010da94de3 _PyFunction_FastCall + 121
10  org.python.python             	0x000000010da93cb5 call_function + 448
11  org.python.python             	0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811
12  org.python.python             	0x000000010da94de3 _PyFunction_FastCall + 121
13  org.python.python             	0x000000010da93cb5 call_function + 448
14  org.python.python             	0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811
15  org.python.python             	0x000000010da94de3 _PyFunction_FastCall + 121
16  org.python.python             	0x000000010da93cb5 call_function + 448
17  org.python.python             	0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811
18  org.python.python             	0x000000010da94de3 _PyFunction_FastCall + 121
19  org.python.python             	0x000000010da93cb5 call_function + 448
20  org.python.python             	0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811
21  org.python.python             	0x000000010da94440 _PyEval_EvalCodeWithName + 1719
22  org.python.python             	0x000000010da8b84e PyEval_EvalCode + 42
23  org.python.python             	0x000000010dab419e run_mod + 54
24  org.python.python             	0x000000010dab31bf PyRun_FileExFlags + 160
25  org.python.python             	0x000000010dab289c PyRun_SimpleFileExFlags + 285
26  org.python.python             	0x000000010dac66c0 Py_Main + 3484
27  org.python.python             	0x000000010d9e9e1d 0x10d9e8000 + 7709
28  libdyld.dylib                 	0x00007fffa1f21235 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010e614d18  rbx: 0x000000010e5e37b8  rcx: 0x000000010da92fa0  rdx: 0x0000000000000000
  rdi: 0x000000010e5e3840  rsi: 0x0000000000000000  rbp: 0x00007fff52216b20  rsp: 0x00007fff52216b08
   r8: 0x000000010e4b9420   r9: 0x000000010e4b9448  r10: 0x0000000000000007  r11: 0x00200000000437cb
  r12: 0x000000010e500708  r13: 0x000000010e56b870  r14: 0x0000000000000048  r15: 0x000000010e56b760
  rip: 0x0000000000000000  rfl: 0x0000000000010202  cr2: 0x0000000000000000
  
Logical CPU:     6
Error Code:      0x00000014
Trap Number:     14
```

**Comment by chenfengyuan** [comment]
Amazon Linux AMI release 2017.09
Linux ip-172-18-1-195 4.9.62-21.56.amzn1.x86_64 #1 SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python 3.6.2 (default, Nov  2 2017, 19:34:31)
Cython==0.27.3
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffeb523eca in __Pyx_Generator_Next (self=0x7fffeb960d90) at cy_test.c:3307
#2  0x00007ffff7a044f3 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#3  0x00007ffff79749df in _PyGen_Send () from /usr/lib64/libpython3.6m.so.1.0
#4  0x00007fffebc554bc in ?? () from /xxxxxxxx/venv/lib64/python3.6/lib-dynload/_asyncio.cpython-36m-x86_64-linux-gnu.so
#5  0x00007fffebc55f1c in ?? () from /xxxxxxxx/venv/lib64/python3.6/lib-dynload/_asyncio.cpython-36m-x86_64-linux-gnu.so
#6  0x00007ffff7963bd3 in PyObject_Call () from /usr/lib64/libpython3.6m.so.1.0
#7  0x00007ffff7a006e6 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#8  0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0
#9  0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#10 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#11 0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0
#12 0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#13 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#14 0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0
#15 0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#16 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#17 0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0
#18 0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#19 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#20 0x00007ffff7a0a56f in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#21 0x00007ffff7a0affb in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0
#22 0x00007ffff7a910ae in ?? () from /usr/lib64/libpython3.6m.so.1.0
#23 0x00007ffff7945839 in PyRun_FileExFlags () from /usr/lib64/libpython3.6m.so.1.0
#24 0x00007ffff7945be9 in PyRun_SimpleFileExFlags () from /usr/lib64/libpython3.6m.so.1.0
#25 0x00007ffff7a979bb in Py_Main () from /usr/lib64/libpython3.6m.so.1.0
#26 0x0000000000400b19 in main ()
(gdb)
```

**Comment by scoder** [comment]
The test case did not fail [in travis](https://travis-ci.org/cython/cython/builds/348850856) either, neither on Linux nor MacOS-X (CPython 3.6.4).

**Comment by toriningen** [comment]
@scoder, I've bisected this bug, and it seems that commit 3cd1e3da1766246b6b2fb053e651c1a2bed382b7 is fixing it, just as you've said 3 weeks ago. Sorry for misleading you, I don't know exact reason why it had reproduced at my side since then, but most realistic explanation is that I've forgot to clean up lingering .c file, assuming it should be rebuilt each time.

Just to be sure, I've double-checked commit 829d7bbef with exact same test, it does not crash.

So, bug is seemingly fixed now, thankee-sai.

**Comment by scoder** [comment]
Thanks for reporting back, and for the test case.
