### ISSUE TITLE
Spurious warning "Unused entry 'genexpr'"

### ISSUE THREAD

**Issue by mhsmith** [cython/cython#1699]
Cython version 0.25.2

<pre>
l = [1,2,3]

def f():
    print(x for x in l)
</pre>

<pre>
$ cython -Wextra -Werror foo.pyx

Error compiling Cython file:
------------------------------------------------------------
...
l = [1,2,3]

def f():
    print(x for x in l)
           ^
------------------------------------------------------------

foo.pyx:4:12: Unused entry 'genexpr'
</pre>

This only happens when the generator expression is in a function, rather than at the module level. Surrounding the expression with parentheses doesn't help. Converting it to a list comprehension does remove the warning, but will make performance worse, especially if the generator expression would not have run to completion.

I like to use `-Wextra -Werror` because the "unused" warnings often indicate a genuine error in my code.

**Comment by LordAro** [comment]
Still getting this with 0.29.1, any chance of anyone looking at it? Having to wrap expressions in [] is unfortunate...

**Comment by DrissiReda** [comment]
Haven't there been fixes for this issue since? Still having it.

**Comment by scoder** [comment]
Probably not difficult to do. Might be enough to mark the Entry of the generator expression as `entry.used = True`.

**Comment by scoder** [comment]
Test could possibly be implemented by setting `-Werror` for the generator expression tests – unless that triggers other 'fatal' warnings.

**Comment by scoder** [comment]
Note also that short running list comprehensions can be much faster than the corresponding generator expression.

**Comment by scoder** [comment]
I tried enabling warning tracking for the entire test suite in #3788 and didn't see this specific warning anywhere. Weird. The OP's test case is simple enough to be covered.

**Comment by da-woods** [comment]
> The OP's test case is simple enough to be covered.

The one issue with OP's test case is that it doesn't actually run the generator expression - it just prints `<generator object at 0xSOME_ADDRESS>` so it's not likely to be tested. With that said, I see the same warning with the more useful `print(list(x for x in l))` (with `-Wexta` on the command-line)

**Comment by WillDaSilva** [comment]
This issue is still present in Cython 3.0a6

**Comment by WillDaSilva** [comment]
I created a fresh virtual environment on Python 3.9.2 as follows:
```console
will@will-desktop ~ $ python -V
Python 3.9.2
will@will-desktop ~ $ python -m venv venv
will@will-desktop ~ $ source venv/bin/activate
```

Then installed Cython checked out onto the commit with the fix:

```console
(venv) will@will-desktop ~ $ cd cython/
(venv) will@will-desktop ~/cython $ git rev-parse HEAD
da26b4a2131993df9e68c34213ca688b43b5970c
(venv) will@will-desktop ~/cython $ python setup.py install

<install output trimmed>

Installed /home/will/venv/lib/python3.9/site-packages/Cython-0.29.23-py3.9-linux-x86_64.egg
Processing dependencies for Cython==0.29.23
Finished processing dependencies for Cython==0.29.23
(venv) will@will-desktop ~/cython $
```

I then changed directories to the project I was working in where the warnings were showing up, and ran `setup.py build_ext`:

```console
(venv) will@will-desktop ~/pyproject $ python setup.py build_ext
Traceback (most recent call last):
  File "/home/will/pyproject/setup.py", line 24, in <module>
    from Cython.Build import cythonize
  File "/home/will/venv/lib/python3.9/site-packages/Cython-0.29.23-py3.9-linux-x86_64.egg/Cython/Build/__init__.py", line 1, in <module>
    from .Dependencies import cythonize
  File "/home/will/venv/lib/python3.9/site-packages/Cython-0.29.23-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 48, in <module>
    from ..Compiler.Main import Context, CompilationOptions, default_options
  File "/home/will/venv/lib/python3.9/site-packages/Cython-0.29.23-py3.9-linux-x86_64.egg/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
  File "Cython/Compiler/Scanning.py", line 1, in init Cython.Compiler.Scanning
  File "/home/will/venv/lib/python3.9/site-packages/Cython-0.29.23-py3.9-linux-x86_64.egg/Cython/Plex/__init__.py", line 36, in <module>
    from .Lexicons import Lexicon, State
  File "/home/will/venv/lib/python3.9/site-packages/Cython-0.29.23-py3.9-linux-x86_64.egg/Cython/Plex/Lexicons.py", line 14, in <module>
    from . import DFA
  File "Cython/Plex/DFA.py", line 1, in init Cython.Plex.DFA
AttributeError: module 'Cython.Plex.Actions' has no attribute 'Method'
(venv) will@will-desktop ~/pyproject $
```

**Comment by scoder** [comment]
That error makes no sense at all to me. Something must have gone wrong with the installation. Did you already retry this a second time? Could you also try `pip install .` instead to install Cython?

**Comment by WillDaSilva** [comment]
I tried twice with `python setup.py install`, as that was what the `INSTALL.txt` said to do. I tried again (in a new virtual environment) with `pip install .`, but it made no difference. I then tried with Python 3.6.10, 3.7.6, 3.8.8, and 3.9.2. For each of them I created a new virtual environment, ran `pip install -U pip setuptools wheel toml psutil numpy` (the build dependencies for my project), then `pip install .` to build Cython. I then ran `python setup.py build_ext` for my project, and each time the `Unused entry 'genexpr'` warnings were still present. Maybe the previous error was due to some missing/outdated build dependency? In hindsight I should've installed Cython before installing my project's build dependencies.

**Comment by da-woods** [comment]
This turns out to be a little more complicated:

https://github.com/cython/cython/blob/c830db8111be7a7eb1753f4c2fa04c4dbbe3ffdc/Cython/Compiler/Symtab.py#L774-L782

There are two entries created for the `GeneratorDefNode`. A "stub" entry that's put into the symtab but is not returned, and an anonymous entry that is returned. The "stub" entry is the one that's discovered and reported unused, while the other one is the one that `GeneratorDefNode` has access to.

I'm not really sure I understand the purpose of this scheme so I'm reluctant to mess with it. But that's the rough outline
