### ISSUE TITLE
Cython indexing is inconsistent with Python

### ISSUE THREAD

**Issue by bgedik** [cython/cython#1700]
In Python 2.7, we have:

```
[1, 2][-2]
```
Works, as expected.

```
[1, 2][-3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```
Fails with an index error, as expected.

```
[1, 2][-5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```
Fails with an index error, as expected.

In Cythonized code:

```
from Cython.Build.Inline import cython_inline
cython_inline("[1, 2][-2]", locals=locals(), globals=globals())
```
Works, as expected.

```
cython_inline("[1, 2][-3]", locals=locals(), globals=globals())
```
Works, but it **should fail** with an index error.

```
cython_inline("[1, 2][-5]", locals=locals(), globals=globals())
IndexError: list index out of range
```
Fails with an index error, as expected.

**Comment by robertwb** [comment]
Thanks!
