### ISSUE TITLE
Cython fails to run for a python3.6 installed in custom location.

### ISSUE THREAD

**Issue by gwk** [cython/cython#1727]
I have built/installed python from source on OSX to a custom framework location. The exact configure command is:

    CC=clang CXX=clang++ CFLAGS='-flto=thin -Wno-deprecated-declarations' MACOSX_DEPLOYMENT_TARGET=10.9 ../configure --cache-file=config.cache --prefix=/usr/local/py --enable-framework=/usr/local/py/Library/Frameworks --quiet --with-lto 

I then install cython using the corresponding pip:

    /usr/local/py/Library/Frameworks/Python.framework/Versions/3.6/bin/pip3 install cython

The cython install succeeds, but the installation is broken:

     $ cython
    Traceback (most recent call last):
      File "/usr/local/py/Library/Frameworks/Python.framework/Versions/3.6/bin/cython", line 7, in <module>
        from Cython.Compiler.Main import setuptools_main
      File     "/usr/local/py/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Cython/Compiler/Main.py",     line 30, in <module>
        from .Symtab import ModuleScope
      File     "/usr/local/py/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Cython/Compiler/Symtab.py",     line 18, in <module>
        from . import PyrexTypes
      File     "/usr/local/py/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Cython/Compiler/PyrexTypes.    py", line 17, in <module>
        from .Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
      File "Cython/Compiler/Code.py", line 39, in init Cython.Compiler.Code     (/private/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/pip-uioc89se-build/Cython/Compiler/Code.c:80038)
        def runsource(self, source, filename="<input>", symbol="single"):
    ModuleNotFoundError: No module named '__builtin__'

I believe this is a Cython bug, as I can successfully install many other packages using pip for custom python locations. If anyone has an idea of how to debug this issue please let me know; I realize that these setups can be time consuming to reproduce. Thanks!

**Comment by gwk** [comment]
I am able to work around this bug by installing cython in developer mode: `pip3 install -e .` from the cython project root, master branch.

From there I was able to build pyzmq using `pip3 install --no-binary=pyzmq pyzmq` (it fails without the --no-binary option).

**Comment by scoder** [comment]
The name "__builtin__" suggests that there is something going wrong at a Py2/Py3 compatibility level. It's supposed to use the name "builtins" in Py3 instead. Difficult to say how this could happen, but could you check in your install/build output if there is any hint of interference of a Python 2.x version? And could you make sure that the shebang lines in you Python installation all use the correct Python 3.6 runtime?

**Comment by yungszen** [comment]
hi.. i'm very new to python and i've installed cython into C: drive on a different computer (windows 10 OS) before without any problem.. on another set (also windows OS), i installed in into D:\ drive and cython was giving these errors:

C:\Users\Leo>cython
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\cython.exe\__main__.py", line 5, in <module>
  File "d:\python\lib\site-packages\Cython\Compiler\Main.py", line 30, in <module>
    from .Symtab import ModuleScope
  File "d:\python\lib\site-packages\Cython\Compiler\Symtab.py", line 19, in <module>
    from . import PyrexTypes
  File "d:\python\lib\site-packages\Cython\Compiler\PyrexTypes.py", line 17, in <module>
    from .Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
ImportError: DLL load failed: The specified procedure could not be found.

when i check the PATH for both computers, they are the same.. It sounds like my problem is related to this thread..  I apologise in advance if my posting here is violating any rules..

**Comment by ermeiyao** [comment]
I also encounter similar problem,as fallow：
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PYthon\Scripts\cython.exe\__main__.py", line 5, in <module>
  File "d:\python\lib\site-packages\Cython\Compiler\Main.py", line 30, in <module>
    from .Symtab import ModuleScope
  File "d:\python\lib\site-packages\Cython\Compiler\Symtab.py", line 19, in <module>
    from . import PyrexTypes
  File "d:\python\lib\site-packages\Cython\Compiler\PyrexTypes.py", line 17, in <module>
    from .Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
ImportError: DLL load failed: 找不到指定的程序。

 I solve this problem by upgrade my python version,which is 3.6.1,to 3.6.5.
so i think you also can take this method a try!

**Comment by yungszen** [comment]
Thank you! i actually gave up and uninstalled it but i will try it again to
install it into my d: drive.

Thanks!


~~~
*A lie can travel half way around the world while the truth is putting on
its shoes.*
*Mark Twain*
~~~

**Comment by yungszen** [comment]
It worked! Thank you very much!




~~~
*A lie can travel half way around the world while the truth is putting on
its shoes.*
*Mark Twain*
~~~
