### ISSUE TITLE
cython runtime error on Linux (CentOS) python2.7 build

### ISSUE THREAD

**Issue by wesbarris** [cython/cython#1741]
I have built cython like this:

cd /usr/local/src/python/Cython-0.25.2
/usr/local/bin/python2.7 setup.py build
sudo /usr/local/bin/python2.7 setup.py install --prefix=/usr/local | tee >junk.log

I received no errors during the install process.

When I try to run cython, I get this runtime error:

user@myhost> cython
Traceback (most recent call last):
  File "/usr/local/bin/cython", line 11, in <module>
    load_entry_point('Cython==0.25.2', 'console_scripts', 'cython')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 30, in <module>
    from .Symtab import ModuleScope
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Compiler/Symtab.py", line 18, in <module>
    from . import PyrexTypes
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Compiler/PyrexTypes.py", line 17, in <module>
    from .Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
  File "Cython/Compiler/Code.py", line 838, in init Cython.Compiler.Code (/usr/local/src/python/Cython-0.25.2/Cython/Compiler/Code.c:81208)
    possible_unicode_identifier = re.compile(br"(?![0-9])\w+$".decode('ascii'), re.U).match
  File "/usr/local/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

I am not a python (or cython) user.  I'm just trying to get it installed for my users.  What does the above error suggest?

**Comment by scoder** [comment]
Suggests nothing to me, at least. Could you check if you still get this in a fresh install of Cython 0.26?

**Comment by wesbarris** [comment]
I downloaded and built v0.26.  I got a few warnings but the cython executable now appears to work properly.  Thanks.

The warnings were:
user@host> sudo /usr/local/bin/python2.7 setup.py install --prefix=/usr/local | tee >junk.log
Unable to find pgen, not compiling formal grammar.
warning: no files found matching 'Doc/*'
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
