### ISSUE TITLE
Compiler crash in AnalyseExpressionsTransform

### ISSUE THREAD

**Issue by croth1** [cython/cython#1791]
I am getting following compiler crash when trying to compile this (probably still buggy) code.

```
[1/1] Cythonizing sequences.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef int* lengths = <int*> calloc(n_seq, sizeof(int))
    cdef int** sequences = <int**> calloc(n_seq, sizeof(int*))
    for i in range(10):
        lengths[i] = 20
        sequences[i] = <int*> calloc(lengths[i], sizeof(int))
    seqs = Sequences(n_seq, sequences, lengths)
                   ^
------------------------------------------------------------

sequences.pyx:20:20: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(sequences.pyx:4:0)
StatListNode.stats[1] = DefNode(sequences.pyx:13:0,
    modifiers = [...]/0,
    name = 'create_sequence',
    np_args_idx = [...]/0,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 413, in analyse_expressions: StatListNode(sequences.pyx:14:4,
    is_terminator = True)
File 'Nodes.py', line 4816, in analyse_expressions: SingleAssignmentNode(sequences.pyx:20:20)
File 'Nodes.py', line 4936, in analyse_types: SingleAssignmentNode(sequences.pyx:20:20)
File 'ExprNodes.py', line 5226, in analyse_types: SimpleCallNode(sequences.pyx:20:20,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 5160, in analyse_as_type_constructor: SimpleCallNode(sequences.pyx:20:20,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/Users/ch/miniconda/envs/sci35/lib/python3.5/site-packages/Cython/Compiler/ExprNodes.py", line 5160, in analyse_as_type_constructor
    self.function = RawCNameExprNode(self.function.pos, constructor.type)
AttributeError: 'NoneType' object has no attribute 'type'
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    ext_modules=cythonize(ext_modules))
  File "/Users/ch/miniconda/envs/sci35/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1016, in cythonize
    cythonize_one(*args)
  File "/Users/ch/miniconda/envs/sci35/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1138, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: sequences.pyx
```

# .pyx

```
# distutils: language = c++
# distutils: sources = src/Sequences.cpp

from libc.stdlib cimport calloc, free

cdef extern from "src/Sequences.h":
    cdef cppclass Sequences:
        int n_seq
        int** sequences
        int* lengths


def create_sequence():
    cdef int n_seq = 10
    cdef int* lengths = <int*> calloc(n_seq, sizeof(int))
    cdef int** sequences = <int**> calloc(n_seq, sizeof(int*))
    for i in range(10):
        lengths[i] = 20
        sequences[i] = <int*> calloc(lengths[i], sizeof(int))
    seqs = Sequences(n_seq, sequences, lengths)
    return 1
```

# .h
```
class Sequences {
public:
        Sequences(int n_seq, int** sequences, int* lengths);
        int n_seq;
        int** sequences;
        int* lengths;
};
```

# .cpp
```
#include "Sequences.h"

Sequences::Sequences(int n_seq, int** sequences, int* lengths) : n_seq{n_seq}, sequences{sequences}, lengths{lengths} {
}
```

**Comment by scoder** [comment]
Thanks for the report. The fix on your side is to declare the C++ constructor for the `Sequences` class, but it's a bug in Cython that this crashes instead of giving an understandable error message.
