### ISSUE TITLE
In a non-cdef subclass of a cdef class, __getattr__ is called twice if it raises AttributeError

### ISSUE THREAD

**Issue by mhsmith** [cython/cython#1793]
Cython 0.25.2, Python 2.7.13

```
cdef class Cdef(object):
    def __getattr__(self, name):
        print name
        raise AttributeError()

class NonCdef(Cdef):
    pass

NonCdef().foo
```

Output:
```
foo
foo
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "getattr.pxi", line 9, in init getattr (getattr.c:1253)
    NonCdef().foo
  File "getattr.pxi", line 4, in getattr.Cdef.__getattr__ (getattr.c:934)
    raise AttributeError()
AttributeError
```

If both classes are `cdef`, or neither class is `cdef`, then "foo" is only printed once, as it should be.

**Comment by mhsmith** [comment]
I expect this is something along the lines of https://github.com/python/cpython/pull/2282

**Comment by scoder** [comment]
Also see https://bugs.python.org/issue975646

**Comment by scoder** [comment]
I extended an existing test to reproduce this (failures commented out).
https://github.com/cython/cython/commit/cc52bac9c7d61c050213622c1755086fa3cd5169

The code that generates the method slots is here:
https://github.com/cython/cython/blob/cc52bac9c7d61c050213622c1755086fa3cd5169/Cython/Compiler/ModuleNode.py#L1726

It's not really obvious to me how this needs to be changed, also not from the documentation. Needs some investigation.
https://docs.python.org/3/reference/datamodel.html#object.__getattr__
