### ISSUE TITLE
Cython/PYX compilation failure tracebacks are excessively long.

### ISSUE THREAD

**Issue by fake-name** [cython/cython#1827]
Note: This is a very minor, quality-of-life annoyance.

I'm working on a relatively complex project that uses several cython modules, with additional `pyxbld` mediated c++ source files.

Right now, when I'm working on the C++ sources, cython compilation failures yield **massively long** tracebacks. The common failure output is *100+ lines*. 

This wouldn't be too much of a problem, if cython did not currently output the C++ compilation failure, and *then* the multiple python tracebacks it caused. As it is, basically all the information I need to actually fix the issue is inevitably scrolled off the screen. 

Here is an example failure:

```cythoning /home/pi/BatLogger/Interface/Hardware/interface_wrapper.pyx to /home/pi/.pyxbld/temp.linux-armv7l-3.4/pyrex/Hardware/interface_wrapper.cpp

Error compiling Cython file:
------------------------------------------------------------
...

                # Queue structure:
                # [USB Thread] -> [Parse Thread] -> [Log Thread]

                self.usb_thread.insert_output_queue(self.parse_thread.get_queue_reference())
                self.parse_thread.insert_output_queue(self.log_thread.get_queue_reference())
                  ^
------------------------------------------------------------

Hardware/interface_wrapper.pyx:138:19: Object of type 'BatParserThread' has no attribute 'insert_output_queue'

Error compiling Cython file:
------------------------------------------------------------
...

                # Queue structure:
                # [USB Thread] -> [Parse Thread] -> [Log Thread]

                self.usb_thread.insert_output_queue(self.parse_thread.get_queue_reference())
                self.parse_thread.insert_output_queue(self.log_thread.get_queue_reference())
                                                                          ^
------------------------------------------------------------

Hardware/interface_wrapper.pyx:138:75: Cannot convert 'ReaderWriterQueue[UsbMessageRecord] &' to Python object
building 'Hardware.interface_wrapper' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include/ -I/usr/lib/openmpi/include/ -I/usr/include/hdf5/serial -I/usr/include/python3.4m -c /home/pi/.pyxbld/temp.linux-armv7l-3.4/pyrex/Hardware/interface_wrapper.cpp -o /home/pi/.pyxbld/temp.linux-armv7l-3.4/home/pi/.pyxbld/temp.linux-armv7l-3.4/pyrex/Hardware/interface_wrapper.o -std=c++11 -O3 -Wall -Werror -lrt -lusb-1.0 -DLINUX
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/pi/.pyxbld/temp.linux-armv7l-3.4/pyrex/Hardware/interface_wrapper.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
Traceback (most recent call last):
  File "/usr/lib/python3.4/distutils/unixccompiler.py", line 116, in _compile
    extra_postargs)
  File "/usr/lib/python3.4/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.4/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.4/distutils/spawn.py", line 162, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/dist-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.4/dist-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.4/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.4/distutils/unixccompiler.py", line 118, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acquire_only.py", line 23, in <module>
    import Hardware.acq_hardware
  File "/home/pi/BatLogger/Interface/Hardware/acq_hardware.py", line 11, in <module>
    from . import interface_wrapper
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyximport.py", line 232, in load_module
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/local/lib/python3.4/dist-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.4/dist-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.4/dist-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.4/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.4/distutils/unixccompiler.py", line 118, in _compile
    raise CompileError(msg)
ImportError: Building module Hardware.interface_wrapper failed: ["distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1\n"]
```

I don't see why the later tracebacks couldn't just re-raise the initial error, preventing the additional clutter. As it is, I tend to do my test-building `python3 script_name.py 2>&1 | head -n 50`, but shell hacks seem kind of crude.

**Comment by scoder** [comment]
1) I do not recommend using `pyximport` as part of a build (but I guess that's just your example).
2) If you call cythonize() before setup(), the C compiler will not be run at all if the translation fails, so the error output will end with Cython's own output instead of the multi-step exception tracebacks above.

Apart from that, I agree that an exception trace is not helpful at the end of a failed Cython compilation. The exception should be caught instead and printed without the traceback.

**Comment by fake-name** [comment]
> I do not recommend using pyximport as part of a build (but I guess that's just your example).

Uh.... what? How do you use cython files without building them?

Basically, I have a project that's distributed as source. It is a bunch of python, a few pyx files, and a bunch of C++ files. You run the project, and if needed, it builds the pyx files, the c++ files, and glues them together using a `pyxbld` config file, and then executes. 

The point is, there's no needed separate build step. which is both very convenient (from a development perspective), and means you never have to worry about having an out-of-date version of the cython/c++ code. 

I suppose I could have the cython stuff be built by a setuptools command, but that'd be annoying with no benefit. Your comments about calling `cythonize()` is irrelevant unless you do that.

**Comment by cython-notifications** [comment]
On Sat, Aug 26, 2017 at 4:35 AM, Connor Wolf <notifications@github.com>
wrote:

> I do not recommend using pyximport as part of a build (but I guess that's
> just your example).
>
> Uh.... what? How do you use cython files without building them?
>
> Basically, I have a project that's distributed as source. It is a bunch of
> python, a few pyx files, and a bunch of C++ files. You run the project, and
> if needed, it builds the pyx files, the c++ files, and glues them together
> using a pyxbld config file, and then executes.
>
> The point is, there's no needed separate build step. which is both very
> convenient (from a development perspective), and means you never have to
> worry about having an out-of-date version of the cython/c++ code.
>
> I suppose I could have the cython stuff be built by a setuptools command,
> but that'd be annoying with no benefit. Your comments about calling
> cythonize() is irrelevant unless you do that.
>
Using a setup.py with setuptools is more robust (and well tested) than
pyximport, as well as being the standard way to do things.

**Comment by scoder** [comment]
> there's no needed separate build step. which is both very convenient (from a development perspective),

pyximport is ok for testing and developing. That's its main use case, IMHO. Pull requests that improve pyximport are welcome. It has not changed in years and is not up to date with the less old improvements in Cython's build support.

IMHO, pyximport should not be imposed on users of Cython code. Definitely not by libraries. Applications are different as they can control their runtime environment, but even there it still has the drawback of making imports more complex and less controllable by end users.

> and means you never have to worry about having an out-of-date version of the cython/c++ code.

People commonly include the generated (and tested) .c/.cpp files in the sdist that they publish on PyPI. That avoids a dependency on Cython and prevents users from accidentally using a different version of Cython to compile your code, which makes it more predictable what they get. If your code starts failing to build with a newer version of Cython, or if the Cython version that they happen to have installed has a bug that affects your code, users will be on their own to resolve it when they try to install an existing version of your code.

> I suppose I could have the cython stuff be built by a setuptools command, but that'd be annoying with no benefit.

People commonly distribute binary wheels these days, which are very fast to install and do not depend on compilers being installed on user side, be it Cython or a C compiler. I do not know about the specific constraints of your project, but this is a proven huge benefit for the large majority of users I heard of.

**Comment by fake-name** [comment]
In this case, the project is some custom hardware, C++ that talks to it, and python that manages the runtime. 

Development hasn't even reached the point where I'd vaguely considered trying to abstract everything up into a library that gets versioned separately from the entire hardware stack. 

I'd assume that the great majority of people *writing* cython code are **not** writing libraries, and as such pyximport is probably more broadly used/convenient then depending on distutils.

Note that there are probably more people *using* cython code via distutils then pyximport, but that's separate from people *writing* cython code.

**Comment by scoder** [comment]
> I'd assume that the great majority of people writing cython code are not writing libraries, and as such pyximport is probably more broadly used/convenient then depending on distutils.

While that is an unbacked opinion, I fully appreciate people who extend the applicable range of tools beyond what they where initially designed for.

That being said, I think this ticket is getting out of scope. I'd like to restrict it the initial intention of improving the error output of pyximport.

**Comment by fake-name** [comment]
> While that is an unbacked opinion, I fully appreciate people who extend the applicable range of tools beyond what they where initially designed for.

Hah, well, I did say I assume, so I'd happily admit I have little basis. 

> That being said, I think this ticket is getting out of scope. I'd like to restrict it the initial intention of improving the error output of pyximport.

Ok.
