### ISSUE TITLE
Symbol not found: __PyThreadState_UncheckedGet for compiled Cython, Python 3.5

### ISSUE THREAD

**Issue by matthew-brett** [cython/cython#1880]
There is a new error after the Cython 0.27 release, found here:

https://travis-ci.org/MacPython/h5py-wheels/jobs/278928715

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-66_llhko-build/setup.py", line 167, in <module>
      cmdclass = CMDCLASS,
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-66_llhko-build/setup_build.py", line 149, in run
      from Cython.Build import cythonize
    File "/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.5/site-packages/Cython/Build/__init__.py", line 1, in <module>
      from .Dependencies import cythonize
    File "/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 59, in <module>
      from ..Compiler.Main import Context, CompilationOptions, default_options
    File "/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>
      from .Scanning import PyrexScanner, FileSourceDescriptor
  ImportError: dlopen(/Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so, 2): Symbol not found: __PyThreadState_UncheckedGet
    Referenced from: /Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so
    Expected in: flat namespace
   in /Users/travis/build/MacPython/h5py-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.s
```

Testing locally this error does not occur when Cython is installed via:

```
pip install . --install-option="--no-cython-compile"
```

It does occur when installing without the ``--no-cython-compile`` module.

Any ideas what might be going on?

**Comment by matthew-brett** [comment]
Possibly relevant : https://github.com/pybind/pybind11/issues/314 and https://bugs.python.org/issue26154

**Comment by matthew-brett** [comment]
The failure is only for Python 3.5 on OSX.  The compilation there is for Python 3.5.1.   I think the Cython wheels are compiling against Python 3.5.3.  Am I right in thinking that https://github.com/cython/cython/blob/7cac3e06ff68d974d21a6efa258ccce0d487992f/Cython/Utility/Exceptions.c#L16 will pull in that symbol when compiling on any Python 3.5, but it will not be defined when running on Python 3.5 < 3.5.2?

**Comment by matthew-brett** [comment]
Sorry - to clarify, I think it's only failing on OSX, because on Manylinux, we are testing with Python 3.5.3, but with OSX we are testing with Python 3.5.1 (in the h5py case).

**Comment by scoder** [comment]
Thank you for your analysis.

**Comment by eugene-yang** [comment]
Is there any update about this issue? 
I used Python 3.7 with Cython 0.29.6 in OSX and still have the same problem.

**Comment by scoder** [comment]
The issue is resolved since 2017 (Cython 0.27.1) and it was never a problem with Python 3.6 or later. Please make sure you are correctly generating your .c files (look at the first like to see the Cython version that was used).

If you can provide information that suggests why there would still be a problem, please bring it up.

**Comment by sixtyfive** [comment]
Also a problem with ArchLinux's current Python 3.13.

**Comment by da-woods** [comment]
@sixtyfive Most likely you are using an old version of Cython. Specifically the 0.29.x branch does not support Python 3.13 (and isn't really updated any more in general). The most recent 3.0.11 release and the current master branch do not have this issue.

If you are able to get this in an up-to-date version of Cython then please open a new bug with enough information to reproduce it.
