### ISSUE TITLE
TypeError: can't pickle Cython.Compiler.FlowControl.NameAssignment objects

### ISSUE THREAD

**Issue by Wiadomy** [cython/cython#1884]
Hello, when I'm trying to install Cython such error appears:
```
TypeError: can't pickle Cython.Compiler.FlowControl.NameAssignment objects

`Running setup.py install for h5py ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t3e3ehc4/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8nclridu-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/h5py
    copying h5py/version.py -> build/lib.linux-x86_64-3.6/h5py
    copying h5py/ipy_completer.py -> build/lib.linux-x86_64-3.6/h5py
    copying h5py/highlevel.py -> build/lib.linux-x86_64-3.6/h5py
    copying h5py/__init__.py -> build/lib.linux-x86_64-3.6/h5py
    creating build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/selections.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/group.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/filters.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/files.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/dims.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/base.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-3.6/h5py/_hl
    creating build/lib.linux-x86_64-3.6/h5py/tests
    copying h5py/tests/common.py -> build/lib.linux-x86_64-3.6/h5py/tests
    copying h5py/tests/__init__.py -> build/lib.linux-x86_64-3.6/h5py/tests
    creating build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_slicing.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_selections.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_objects.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5t.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5p.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5f.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_h5.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_group.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_file.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_dimension_scales.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_datatype.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_dataset.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_base.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_attrs_data.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/test_attrs.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/common.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    copying h5py/tests/old/__init__.py -> build/lib.linux-x86_64-3.6/h5py/tests/old
    creating build/lib.linux-x86_64-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_file.py -> build/lib.linux-x86_64-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_swmr.py -> build/lib.linux-x86_64-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.linux-x86_64-3.6/h5py/tests/hl
    copying h5py/tests/hl/test_attribute_create.py -> build/lib.linux-x86_64-3.6/h5py/tests/hl
    copying h5py/tests/hl/__init__.py -> build/lib.linux-x86_64-3.6/h5py/tests/hl
    running build_ext
    Autodetected HDF5 1.10.1
    ********************************************************************************
                           Summary of the h5py configuration
    
        Path to HDF5: None
        HDF5 Version: '1.10.1'
         MPI Enabled: False
    Rebuild Required: False
    
    ********************************************************************************
    Executing api_gen rebuild of defs
    Executing cythonize()
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/defs.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/_errors.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/_objects.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/_proxy.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5fd.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5z.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5i.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5r.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/utils.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/_conv.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5t.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5s.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5p.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5d.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5a.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5f.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5g.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5l.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5o.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5ds.pyx because it changed.
    Compiling /tmp/pip-build-t3e3ehc4/h5py/h5py/h5ac.pyx because it changed.
    [ 1/22] Cythonizing /tmp/pip-build-t3e3ehc4/h5py/h5py/_conv.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t3e3ehc4/h5py/setup.py", line 140, in <module>
        cmdclass = CMDCLASS,
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-t3e3ehc4/h5py/setup_build.py", line 173, in run
        force=config.rebuild_required or self.force)
      File "/usr/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 877, in cythonize
        cythonize_one(*args)
      File "/usr/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 980, in cythonize_one
        result = compile([pyx_file], options)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 679, in compile
        return compile_multiple(source, options)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 657, in compile_multiple
        result = run_pipeline(source, options, context=context)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 487, in run_pipeline
        err, enddata = Pipeline.run_pipeline(pipeline, source)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 328, in run_pipeline
        data = phase(data)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
        module_node.process_implementation(options, result)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 118, in process_implementation
        self.generate_c_code(env, options, result)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 339, in generate_c_code
        self.body.generate_function_definitions(env, code)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1923, in generate_function_definitions
        self.generate_function_body(env, code)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1681, in generate_function_body
        self.body.generate_execution_code(code)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_execution_code
        stat.generate_execution_code(code)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 7098, in generate_execution_code
        fresh_finally_clause().generate_execution_code(code)
      File "/usr/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 7012, in fresh_finally_clause
        node_copy = copy.deepcopy(node)
      File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/lib/python3.6/copy.py", line 215, in _deepcopy_list
        append(deepcopy(a, memo))
      File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/lib/python3.6/copy.py", line 215, in _deepcopy_list
        append(deepcopy(a, memo))
      File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/lib/python3.6/copy.py", line 297, in _reconstruct
        item = deepcopy(item, memo)
      File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
        rv = reductor(4)
    TypeError: can't pickle Cython.Compiler.FlowControl.NameAssignment objects
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t3e3ehc4/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8nclridu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t3e3ehc4/h5py/`
```

**Comment by scoder** [comment]
Thanks for the report. I assume you were using Cython 0.27? I have no idea why that would happen as pickling is even explicitly supported for that class. But since there was a bit of duplication, I committed a little change, may or may not have an impact. Could you retry with latest master?

**Comment by Wiadomy** [comment]
Sorry, seems like I was trying to install old version. 2.3 or something.
New one is working fine.
