### ISSUE TITLE
undefined symbol: _PyThreadState_UncheckedGet

### ISSUE THREAD

**Issue by ThomasWaldmann** [cython/cython#1897]
Tried to install borgbackup on python 3.5.0 (for testing using the minimum 3.5 version):
```
==> wheezy64: Traceback (most recent call last):
==> wheezy64:   File "setup.py", line 80, in <module>
==> wheezy64:     import Cython.Compiler.Main as cython_compiler
==> wheezy64:   File "/home/vagrant/.pyenv/versions/3.5.0/envs/borg-env/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>
==> wheezy64:     from .Scanning import PyrexScanner, FileSourceDescriptor
==> wheezy64: ImportError: /home/vagrant/.pyenv/versions/3.5.0/envs/borg-env/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet
==> wheezy64: 
==> wheezy64: During handling of the above exception, another exception occurred:
==> wheezy64: 
==> wheezy64: Traceback (most recent call last):
==> wheezy64:   File "setup.py", line 126, in <module>
==> wheezy64:     raise ImportError('The GIT version of Borg needs Cython. Install Cython or use a released version.')
==> wheezy64: ImportError: The GIT version of Borg needs Cython. Install Cython or use a released version.
==> wheezy64: Obtaining file:///vagrant/borg/borg
==> wheezy64:     Complete output from command python setup.py egg_info:
==> wheezy64:     Traceback (most recent call last):
==> wheezy64:       File "/vagrant/borg/borg/setup.py", line 80, in <module>
==> wheezy64:         import Cython.Compiler.Main as cython_compiler
==> wheezy64:       File "/home/vagrant/.pyenv/versions/3.5.0/envs/borg-env/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>
==> wheezy64:         from .Scanning import PyrexScanner, FileSourceDescriptor
==> wheezy64:     ImportError: /home/vagrant/.pyenv/versions/3.5.0/envs/borg-env/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet
==> wheezy64:     
==> wheezy64:     During handling of the above exception, another exception occurred:
==> wheezy64:     
==> wheezy64:     Traceback (most recent call last):
==> wheezy64:       File "<string>", line 20, in <module>
==> wheezy64:       File "/vagrant/borg/borg/setup.py", line 126, in <module>
==> wheezy64:         raise ImportError('The GIT version of Borg needs Cython. Install Cython or use a released version.')
==> wheezy64:     ImportError: The GIT version of Borg needs Cython. Install Cython or use a released version.
```
In above case, the only pyenv-installed python is 3.5.0.

I've seen a similar error before in borg (using pyenv to get 3.4.0, 3.5.0, 3.6.0), see there:
https://github.com/borgbackup/borg/issues/3066

**Comment by ThomasWaldmann** [comment]
duplicate of #1880
