### ISSUE TITLE
install fails on Python 3.7

### ISSUE THREAD

**Issue by gronke** [cython/cython#1916]
```
# python3.7 --version
Python 3.7.0a1+

# python3.7 setup.py install
Unable to find pgen, not compiling formal grammar.
Traceback (most recent call last):
  File "setup.py", line 278, in <module>
    **setup_args
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 279, in run
    self.find_sources()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
    mm.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 533, in run
    self.add_defaults()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
    sdist.add_defaults(self)
  File "/usr/local/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/usr/local/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/local/src/cython/Cython/Distutils/build_ext.py", line 21, in finalize_options
    self.distribution.ext_modules, nthreads=nthreads)
  File "/usr/local/src/cython/Cython/Build/Dependencies.py", line 911, in cythonize
    ctx = c_options.create_context()
  File "/usr/local/src/cython/Cython/Compiler/Main.py", line 590, in create_context
    self.cplus, self.language_level, options=self)
  File "/usr/local/src/cython/Cython/Compiler/Main.py", line 75, in __init__
    from . import Builtin, CythonScope
  File "/usr/local/src/cython/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/local/src/cython/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/local/src/cython/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "/usr/local/src/cython/Cython/Compiler/Visitor.py", line 15, in <module>
    from . import ExprNodes
  File "/usr/local/src/cython/Cython/Compiler/ExprNodes.py", line 2876
    await = None
```

**Comment by scoder** [comment]
Thanks

**Comment by vinyll** [comment]
Similar issue with 

```
Package       Version
------------- -------
Cython        0.29.6
pip           18.1
pkg-resources 0.0.0
setuptools    40.6.2
```

```
 python -V
Python 3.7.3
```

```
      File "/tmp/pip-install-i10tgm43/cython/Cython/Compiler/Visitor.py", line 15, in <module>
        from . import ExprNodes
      File "/tmp/pip-install-i10tgm43/cython/Cython/Compiler/ExprNodes.py", line 2876
        await = None
              ^
    SyntaxError: invalid syntax
```

**Comment by scoder** [comment]
Check your pip output. You are not installing Cython 0.29.6 here.
