### ISSUE TITLE
Cython 0.27.1 fails to "pip install" on CPython 3.7 alpha 2

### ISSUE THREAD

**Issue by dstromberg** [cython/cython#1943]
It looks like "await" has become a reserved word:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_q273dth/cython/setup.py", line 278, in <module>
        **setup_args
      File "/usr/local/cpython-3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/cpython-3.7/lib/python3.7/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/cpython-3.7/lib/python3.7/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/cpython-3.7/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 279, in run
        self.find_sources()
      File "/usr/local/cpython-3.7/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
        mm.run()
      File "/usr/local/cpython-3.7/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 533, in run
        self.add_defaults()
      File "/usr/local/cpython-3.7/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/cpython-3.7/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/cpython-3.7/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/local/cpython-3.7/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/cpython-3.7/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-_q273dth/cython/Cython/Distutils/build_ext.py", line 19, in finalize_options
        self.distribution.ext_modules)
      File "/tmp/pip-build-_q273dth/cython/Cython/Build/Dependencies.py", line 911, in cythonize
        ctx = c_options.create_context()
      File "/tmp/pip-build-_q273dth/cython/Cython/Compiler/Main.py", line 590, in create_context
        self.cplus, self.language_level, options=self)
      File "/tmp/pip-build-_q273dth/cython/Cython/Compiler/Main.py", line 75, in __init__
        from . import Builtin, CythonScope
      File "/tmp/pip-build-_q273dth/cython/Cython/Compiler/CythonScope.py", line 5, in <module>
        from .UtilityCode import CythonUtilityCode
      File "/tmp/pip-build-_q273dth/cython/Cython/Compiler/UtilityCode.py", line 3, in <module>
        from .TreeFragment import parse_from_strings, StringParseContext
      File "/tmp/pip-build-_q273dth/cython/Cython/Compiler/TreeFragment.py", line 17, in <module>
        from .Visitor import VisitorTransform
      File "/tmp/pip-build-_q273dth/cython/Cython/Compiler/Visitor.py", line 15, in <module>
        from . import ExprNodes
      File "/tmp/pip-build-_q273dth/cython/Cython/Compiler/ExprNodes.py", line 2874
        await = None
              ^
    SyntaxError: invalid syntax

And:
$ /usr/local/cpython-3.7/bin/python3
below cmd output started 2017 Wed Oct 18 06:46:16 PM PDT
Python 3.7.0a2 (default, Oct 18 2017, 18:24:45)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> await = 'abc'
  File "<stdin>", line 1
    await = 'abc'
          ^
SyntaxError: invalid syntax

Thanks.

**Comment by scoder** [comment]
Already fixed, 0.27.2 will be released soon.

**Comment by AraHaan** [comment]
@scoder Can #1944 be implemented in 0.27.2 as well so I dont have to manually edit my cythonized C code for my custom embedded interpreters that I must use?

**Comment by scoder** [comment]
Duplicate of #1916.

**Comment by OptimusGREEN** [comment]
this is happening with lower versions too, specifically 0.24.1 and 0.25.2

**Comment by scoder** [comment]
Well, yes, obviously. It's only been fixed in later versions. Just use 0.29.

**Comment by OptimusGREEN** [comment]
I've used 0.25 for months without problem, seems strange how it's suddenly broken. Seems a 3rd party effect.

**Comment by scoder** [comment]
It's called "new Python release". :)
