### ISSUE TITLE
2 tests fail on Big Endian on 0.27.3

### ISSUE THREAD

**Issue by ignatenkobrain** [cython/cython#1982]
```python
======================================================================
FAIL: numpy_subarray ()
Doctest: numpy_subarray
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for numpy_subarray
  File "/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so", line 447, in numpy_subarray
----------------------------------------------------------------------
File "/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so", line 450, in numpy_subarray
Failed example:
    test_record_subarray()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest numpy_subarray[0]>", line 1, in <module>
        test_record_subarray()
      File "tests/run/numpy_subarray.pyx", line 23, in numpy_subarray.test_record_subarray
        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),
    AssertionError
======================================================================
FAIL: numpy_subarray ()
Doctest: numpy_subarray
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for numpy_subarray
  File "/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so", line 146, in numpy_subarray
----------------------------------------------------------------------
File "/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so", line 149, in numpy_subarray
Failed example:
    test_record_subarray()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest numpy_subarray[0]>", line 1, in <module>
        test_record_subarray()
      File "tests/run/numpy_subarray.pyx", line 23, in numpy_subarray.test_record_subarray
        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),
    AssertionError
----------------------------------------------------------------------
```

Happens only on ppc64 and s390x which are BE.

**Comment by scoder** [comment]
Thanks for the report. Could you retry it with the latest master? I added output to the assertions so that we can actually see what it wrong here. Interesting enough, that test has been around since 2013. Since I don't have such a system available, any debugging information that you could provide would be appreciated.

**Comment by tobihan** [comment]
Hi,
this test is still failing with cython 0.28.2 on big endian architectures (mips, hppa, powerpc, ppc64, sparc64), see https://buildd.debian.org/status/package.php?p=cython&suite=experimental&ver=0.28.2-2 for the build logs.

    ======================================================================
    FAIL: numpy_subarray ()
    Doctest: numpy_subarray
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
        raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for numpy_subarray
      File "/<<PKGBUILDDIR>>/build/work-dir/0/run/c/numpy_subarray/numpy_subarray.so", line 488, in numpy_subarray

    ----------------------------------------------------------------------
    File "/<<PKGBUILDDIR>>/build/work-dir/0/run/c/numpy_subarray/numpy_subarray.so", line 491, in numpy_subarray
    Failed example:
        test_record_subarray()
    Exception raised:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/doctest.py", line 1315, in __run
            compileflags, 1) in test.globs
          File "<doctest numpy_subarray[0]>", line 1, in <module>
            test_record_subarray()
          File "tests/run/numpy_subarray.pyx", line 23, in numpy_subarray.test_record_subarray
            assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),
        AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}


    ======================================================================
    FAIL: numpy_subarray ()
    Doctest: numpy_subarray
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
        raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for numpy_subarray
      File "/<<PKGBUILDDIR>>/build/work-dir/0/run/cpp/numpy_subarray/numpy_subarray.so", line 401, in numpy_subarray

    ----------------------------------------------------------------------
    File "/<<PKGBUILDDIR>>/build/work-dir/0/run/cpp/numpy_subarray/numpy_subarray.so", line 404, in numpy_subarray
    Failed example:
        test_record_subarray()
    Exception raised:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/doctest.py", line 1315, in __run
            compileflags, 1) in test.globs
          File "<doctest numpy_subarray[0]>", line 1, in <module>
            test_record_subarray()
          File "tests/run/numpy_subarray.pyx", line 23, in numpy_subarray.test_record_subarray
            assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),
        AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}

**Comment by hroncok** [comment]
On 0.29.3:

```
======================================================================
FAIL: numpy_subarray ()
Doctest: numpy_subarray
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for numpy_subarray
  File "/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so", line 231, in numpy_subarray
----------------------------------------------------------------------
File "/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so", line 234, in numpy_subarray
Failed example:
    test_record_subarray()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest numpy_subarray[0]>", line 1, in <module>
        test_record_subarray()
      File "tests/run/numpy_subarray.pyx", line 23, in numpy_subarray.test_record_subarray
        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),
    AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}
======================================================================
FAIL: numpy_subarray ()
Doctest: numpy_subarray
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for numpy_subarray
  File "/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so", line 228, in numpy_subarray
----------------------------------------------------------------------
File "/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so", line 231, in numpy_subarray
Failed example:
    test_record_subarray()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest numpy_subarray[0]>", line 1, in <module>
        test_record_subarray()
      File "tests/run/numpy_subarray.pyx", line 23, in numpy_subarray.test_record_subarray
        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),
    AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}
----------------------------------------------------------------------
Ran 11343 tests in 3764.831s
FAILED (failures=2, skipped=68)
```

**Comment by scoder** [comment]
Thanks for the reports, and sorry for not resolving the issue earlier.
