### ISSUE TITLE
SystemError or Compiler crash or errors in Code.py

### ISSUE THREAD

**Issue by cdeil** [cython/cython#2104]
With Gammapy, since a few days, our CI builds started to fail like this:
https://travis-ci.org/gammapy/gammapy/jobs/341491496#L1444
```
cythoning gammapy/detect/_test_statistics_cython.pyx to gammapy/detect/_test_statistics_cython.c
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    **package_info
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/build/gammapy/gammapy/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 125, in run
    self.run_command('build')
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/build/gammapy/gammapy/astropy_helpers/astropy_helpers/commands/build_ext.py", line 301, in run
    super(build_ext, self).run()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/travis/miniconda/envs/test/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    full_module_name=module_name)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 693, in compile
    return compile_single(source, options, full_module_name)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 643, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 460, in run_pipeline
    context = options.create_context()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 590, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 75, in __init__
    from . import Builtin, CythonScope
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 15, in init Cython.Compiler.Visitor
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 4561, in <module>
    class SliceIndexNode(ExprNode):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 4713, in SliceIndexNode
    "SliceObject", "ObjectHandling.c", context={'access': 'Get'})
  File "Cython/Compiler/Code.py", line 287, in Cython.Compiler.Code.UtilityCodeBase.load
  File "Cython/Compiler/Code.py", line 529, in Cython.Compiler.Code.TempitaUtilityCode.__init__
  File "Cython/Compiler/Code.py", line 521, in Cython.Compiler.Code.sub_tempita
SystemError: Objects/moduleobject.c:449: bad argument to internal function
```
or in other builds just segfault:
https://travis-ci.org/gammapy/gammapy/jobs/341491493#L1273
```
cythoning gammapy/detect/_test_statistics_cython.pyx to gammapy/detect/_test_statistics_cython.c
/home/travis/.travis/job_stages: line 57:  8942 Segmentation fault      (core dumped) $MAIN_CMD $SETUP_CMD
```
This is with the latest release Cython 0.27.3 from conda-forge.

I see a similar report #2039 by @pitrou but I don't know if it's the same issue, so I'm filing this separate issue.

I'm able to reproduce the crash locally, maybe someone from the Cython team could try this?
```
conda create -n cython-crash python=3.6 cython numpy astropy regions click -c conda-forge
git clone https://github.com/gammapy/gammapy.git
cd gammapy
python setup.py build_ext --inplace -vvv
# ---> segfault for me on latest macOS
```

**Comment by scoder** [comment]
The other ticket is unrelated.
I'd suggest trying it with a non-conda Cython installation first, to make sure it's not an issue on their side.

**Comment by cdeil** [comment]
The only other thing I have readily available is Macports, and there I'm not seeing this issue. So yes, it could be something wrong with the conda Cython, not Cython itself.

Maybe @jakirkham as https://github.com/conda-forge/cython-feedstock/ maintainer, could you try this please?
```
conda create -n cython-crash python=3.6 cython numpy astropy regions click -c conda-forge
git clone https://github.com/gammapy/gammapy.git
cd gammapy
python setup.py build_ext --inplace -vvv
# ---> segfault for me on latest macOS
```
Assuming you can reproduce it: do you know if it's a Cython issue or only with the Cython binary from conda-forge?

**Comment by jakirkham** [comment]
If you think there’s an issue with the `cython` package at `conda-forge`, can you please raise an issue on the feedstock? Thanks.

**Comment by cdeil** [comment]
@jakirkham - Like I said: I don't know if the issue is with Cython itself or with the package at conda-forge. I don't know how to debug it.

For now, I've opened another one at https://github.com/conda-forge/cython-feedstock/issues/28.
If you don't think it's an issue with your packaging or don't find the second issue helpful, feel free to close it of course.

**Comment by jakirkham** [comment]
Do you see the same issue if you use pip instead?

**Comment by cdeil** [comment]
I see the same issue if I install Cython 0.27.3 with pip:
```
(cython-crash) eduroam-3-163:gammapy deil$ pip install cython --ignore-installed 
Collecting cython
  Downloading Cython-0.27.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.7MB)
    100% |████████████████████████████████| 4.7MB 161kB/s 
Installing collected packages: cython
Successfully installed cython-0.27.3
(cython-crash) eduroam-3-163:gammapy deil$ python setup.py build_ext --inplace -vvv
Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
Freezing version number to ./gammapy/version.py
running build_ext
building 'gammapy._compiler' extension
creating build
creating build/temp.macosx-10.9-x86_64-3.6
creating build/temp.macosx-10.9-x86_64-3.6/gammapy
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/include -arch x86_64 -I/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/include -arch x86_64 -I/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/include/python3.6m -c gammapy/_compiler.c -o build/temp.macosx-10.9-x86_64-3.6/gammapy/_compiler.o
gcc -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -L/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -headerpad_max_install_names -Wl,-rpath,/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -L/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -headerpad_max_install_names -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/gammapy/_compiler.o -L/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -o /Users/deil/temp/gammapy/gammapy/_compiler.cpython-36m-darwin.so
cythoning gammapy/detect/_test_statistics_cython.pyx to gammapy/detect/_test_statistics_cython.c
building 'gammapy.detect._test_statistics_cython' extension
creating build/temp.macosx-10.9-x86_64-3.6/gammapy/detect
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/include -arch x86_64 -I/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/include -arch x86_64 -I/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib/python3.6/site-packages/numpy/core/include -I/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/include/python3.6m -c gammapy/detect/_test_statistics_cython.c -o build/temp.macosx-10.9-x86_64-3.6/gammapy/detect/_test_statistics_cython.o -Wp,-w -Wno-unused-function
gcc -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -L/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -headerpad_max_install_names -Wl,-rpath,/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -L/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -headerpad_max_install_names -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/gammapy/detect/_test_statistics_cython.o -L/Users/deil/software/anaconda3/anaconda3/envs/cython-crash/lib -o /Users/deil/temp/gammapy/gammapy/detect/_test_statistics_cython.cpython-36m-darwin.so
cythoning gammapy/maps/_sparse.pyx to gammapy/maps/_sparse.c
Segmentation fault: 11
```
So it doesn't seem to be an issue with the Cython package from conda-forge.

But I don't see the issue with the same Cython version 0.27.3 from Macports on the same machine.

So to me it's still not clear if this is an issue with Cython itself, Cython on conda-forge, or just some problem with my machine / install.

Did anyone try to reproduce the crash?

If you can't, then I would take this as a hint that there's a problem with my conda install, and just blow it away and do a re-install to see if that fixes the issue.

**Comment by cdeil** [comment]
Ah wait, I forgot: the issue first appeared and is still present on our Linux and Mac CI builds: https://travis-ci.org/gammapy/gammapy/jobs/341491496#L1444
They all use conda, and they fail in slightly different ways, but all crash somehow.
This started a week ago, not sure why this appeared now, my guess is that something changed in conda or conda-forge.

**Comment by jakirkham** [comment]
Well if you are seeing the issue with pip, I don’t think it is a conda-forge packaging issue. Sounds like it’s an actual Cython issue.

Is MacPorts actually on the latest Cython? If not, it’s not an apples to apples comparison. If so, maybe you can track down how they build it. Perhaps they have a useful patch that should be included in Cython.

**Comment by cdeil** [comment]
Yes, Macports is on the latest Cython 0.27.3 . They don't have any patches applied:
https://github.com/macports/macports-ports/blob/master/python/py-cython/Portfile

> Well if you are seeing the issue with pip, I don’t think it is a conda-forge packaging issue. Sounds like it’s an actual Cython issue.

Yes, it seems like an actual Cython issue. But given that there's not many people complaining, it's one that only raises it's head in special circumstances, so far only in combination with conda.

**Comment by jakirkham** [comment]
Have you explored the core dumps? Maybe they will provide a better idea as to where things are going wrong.

**Comment by cdeil** [comment]
I did obtain this corresponding crash report via the Mac Console app under "User Reports":
https://gist.github.com/cdeil/198fbf53c460745b94bfc6d78174bce3

@jakirkham - Is this useful? Or what else can / should I do?

---

@astrofrog  - Could you please try to reproduce the issue? 

I now noticed that I get the crash with:
```
conda create -n cython-crash python=3.6 cython numpy astropy regions click -c conda-forge
source activate cython-crash
git clone https://github.com/gammapy/gammapy.git
cd gammapy
python setup.py build_ext --inplace -vvv
# ---> segfault for me on latest macOS
```
but then if I do this I don't get it any more:
```
git clean -fdx
python setup.py build_ext --inplace -vvv
```
Log: https://gist.github.com/cdeil/4ebf15a08adb9bc4241ecf793df6cbe0

@astrofrog - Could this be a weird bug where astropy-helpers is running Cython in a broken way (possibly picking up another Cython or dependency on my system or executing something in a sub-shell), only in the case where it's on the first execution?

**Comment by astrofrog** [comment]
@cdeil - can you send me the output of ``conda list``? I can't reproduce this currently.

**Comment by astrofrog** [comment]
I can reproduce the issue, investigating

**Comment by astrofrog** [comment]
Just for the record, one of the times I ran it I got the following error instead of a segfault:

```
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    **package_info
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/tom/tmp/gammapy.2/astropy_helpers/astropy_helpers/commands/build_ext.py", line 301, in run
    super(build_ext, self).run()
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    full_module_name=module_name)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 693, in compile
    return compile_single(source, options, full_module_name)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 643, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 460, in run_pipeline
    context = options.create_context()
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 590, in create_context
    self.cplus, self.language_level, options=self)
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 75, in __init__
    from . import Builtin, CythonScope
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 15, in init Cython.Compiler.Visitor
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 4561, in <module>
    class SliceIndexNode(ExprNode):
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 4713, in SliceIndexNode
    "SliceObject", "ObjectHandling.c", context={'access': 'Get'})
  File "Cython/Compiler/Code.py", line 287, in Cython.Compiler.Code.UtilityCodeBase.load
    
  File "Cython/Compiler/Code.py", line 529, in Cython.Compiler.Code.TempitaUtilityCode.__init__
  File "Cython/Compiler/Code.py", line 521, in Cython.Compiler.Code.sub_tempita
```

**Comment by cdeil** [comment]
@astrofrog - This is what I have at the moment for conda list:
https://gist.github.com/cdeil/ea50bed7dc2cf90632d5abdb0bace39b

If you read on you'll see that `conda list` report Cython 0.27 from pip, but then `pip uninstall` tries to remove Cython 0.26 from the conda root env.

@astrofrog - Any chance there is a mix of two Cython installs, also on your machine and our conda install on travis-ci?

**Comment by astrofrog** [comment]
@cdeil - I'm not sure yet, but btw the only difference between running it the first time and running after ``git clean -fxd`` is that the second time astropy-helpers is already initialized, so I'm wondering if there is something going on there.

**Comment by astrofrog** [comment]
@cdeil - interestingly this seems similar to https://github.com/astropy/astropy-helpers/issues/302

**Comment by astrofrog** [comment]
Findings so far:

* To reproduce this without re-cloning, you can do:

```
git submodule deinit --all ; git clean -fxd ; python setup.py build_ext --inplace
```

* This seems to be indeed related to the use of the submodule, though it may still indicate some kind of bug with setuptools or Cython.

* With older versions of Cython, this raised an exception, and it was the commit 9262789c399291f1b84200281226e2e8bc71a52c in Cython that made it change to being a segmentation fault.

* Just prior to this, the error was:

```
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from astropy_helpers.setup_helpers import (
  File "/Users/tom/tmp/gammapy.8/astropy_helpers/astropy_helpers/setup_helpers.py", line 33, in <module>
    from .commands.build_ext import generate_build_ext_command
  File "/Users/tom/tmp/gammapy.8/astropy_helpers/astropy_helpers/commands/build_ext.py", line 13, in <module>
    from setuptools.command.build_ext import build_ext as SetuptoolsBuildExt
  File "/Users/tom/miniconda3/envs/cython-crash/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 20, in <module>
    __import__('Cython.Compiler.Main')
  File "/Users/tom/tmp/cython/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
  File "Cython/Compiler/Scanning.py", line 1, in init Cython.Compiler.Scanning
  File "/Users/tom/tmp/cython/Cython/Plex/__init__.py", line 35, in <module>
    from .Actions import TEXT, IGNORE, Begin
  File "Cython/Plex/Actions.py", line 9, in init Cython.Plex.Actions
AttributeError: type object 'Cython.Plex.Actions.Action' has no attribute '__reduce_cython__'
```

**Comment by astrofrog** [comment]
Another finding is that adding:

```python
import Cython.Plex
```

at the top of the ``setup.py`` file gets rid of the segfault and proceeds to the following error:

```
  File "/Users/tom/tmp/cython/Cython/Compiler/ExprNodes.py", line 4706, in SliceIndexNode
    "SliceObject", "ObjectHandling.c", context={'access': 'Get'})
  File "Cython/Compiler/Code.py", line 287, in Cython.Compiler.Code.UtilityCodeBase.load
    
  File "Cython/Compiler/Code.py", line 529, in Cython.Compiler.Code.TempitaUtilityCode.__init__
  File "Cython/Compiler/Code.py", line 521, in Cython.Compiler.Code.sub_tempita
SystemError: Objects/moduleobject.c:449: bad argument to internal function
```

**Comment by astrofrog** [comment]
Further update - I can trigger the issue with this simple script:

```
import os

with open('test.pyx', 'w') as f:
    f.write('cimport cython\n')

with open('test.py', 'w') as f:
    f.write('from setuptools.command.build_ext import build_ext as SetuptoolsBuildExt\n')

from setuptools.sandbox import run_setup
run_setup(os.path.join(os.path.abspath('.'), 'test.py'), ['egg_info'])

from Cython.Build import cythonize
cythonize('test.pyx')
```

However this only happens in certain conda environments, so I'm trying to track down why.

**Comment by astrofrog** [comment]
Ok, I've finally narrowed it down - I think this may be an issue that appears only with setuptools 35, which is only available in conda-forge, not defaults. To show that this is not a conda issue though, I installed setuptools and Cython with pip:

```
$ conda create -n reproduce-issue python=3.6
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/tom/miniconda3/envs/reproduce-issue:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0
    certifi:         2018.1.18-py36_0     
    libcxx:          4.0.1-h579ed51_0     
    libcxxabi:       4.0.1-hebd6815_0     
    libedit:         3.1-hb4e282d_0       
    libffi:          3.2.1-h475c297_4     
    ncurses:         6.0-hd04f020_2       
    openssl:         1.0.2n-hdbc3d79_0    
    pip:             9.0.1-py36h1555ced_4 
    python:          3.6.4-hc167b69_1     
    readline:        7.0-hc1231fa_4       
    setuptools:      38.4.0-py36_0        
    sqlite:          3.22.0-h3efe00b_0    
    tk:              8.6.7-h35a86e2_3     
    wheel:           0.30.0-py36h5eb2c71_1
    xz:              5.2.3-h0278029_2     
    zlib:            1.2.11-hf3cbc9b_2    

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate reproduce-issue
#
# To deactivate an active environment, use:
# > source deactivate
#

$ source activate reproduce-issue
$ conda remove --force setuptools
Fetching package metadata .............

Package plan for package removal in environment /Users/tom/miniconda3/envs/reproduce-issue:

The following packages will be REMOVED:

    setuptools: 38.4.0-py36_0

Proceed ([y]/n)? y

$ pip install setuptools Cython
Collecting setuptools
  Using cached setuptools-38.5.1-py2.py3-none-any.whl
Collecting Cython
  Using cached Cython-0.27.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: setuptools, Cython
Successfully installed Cython-0.27.3 setuptools-38.5.1
```

With this environment, I then run the following script which **has** to be called ``setup.py``:

```
```python
import os

with open('test.pyx', 'w') as f:
    f.write('cimport cython\n')

with open('test.py', 'w') as f:
    f.write('from setuptools.command.build_ext import build_ext as SetuptoolsBuildExt\n')

from setuptools.sandbox import run_setup
run_setup(os.path.join(os.path.abspath('.'), 'test.py'), ['egg_info'])

from Cython.Build import cythonize
cythonize('test.pyx')
```

and get:

```
$ python setup.py 
Compiling test.pyx because it changed.
[1/1] Cythonizing test.pyx
Fatal Python error: deallocating None

Current thread 0x00007fffa87c2340 (most recent call first):
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/TreeFragment.py", line 76 in parse_from_strings
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/TreeFragment.py", line 236 in __init__
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1561 in AnalyseDeclarationsTransform
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1553 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 143 in create_pipeline
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 250 in create_pyx_pipeline
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 491 in run_pipeline
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 673 in compile_multiple
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 695 in compile
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1144 in cythonize_one
  File "/Users/tom/miniconda3/envs/reproduce-issue/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1039 in cythonize
  File "setup.py", line 13 in <module>
Abort trap: 6
```

or

```
$ python setup.py 
Compiling test.pyx because it changed.
[1/1] Cythonizing test.pyx
Segmentation fault: 11
```

(it changes from run to run)

So at this point, I think this is either a setuptools or a Cython issue.

**Comment by astrofrog** [comment]
@scoder - I can also confirm that this happens with my default MacOS X Python 2.7 installation, so this is definitely not related to conda:

```
$ python setup.py 
Compiling test.pyx because it changed.
[1/1] Cythonizing test.pyx
Segmentation fault: 11
```

**Comment by astrofrog** [comment]
Here is the setuptools commit that caused the error: ca71bc26f65f1eac9f26b5e5b0d7b4109186fe59

```
commit ca71bc26f65f1eac9f26b5e5b0d7b4109186fe59
Author: Jason R. Coombs <jaraco@jaraco.com>
Date:   Sun Feb 4 16:36:23 2018 -0500

    Import Cython.Compiler.Main as recommended by Cython project to improve Cython detection. Fixes #1229.
```

cc @jaraco @scoder

**Comment by jaraco** [comment]
> issue that appears only with setuptools 35

I think you mean 38.5.

Hard to believe that change has broken Cython support. All Setuptools wishes to do at that point is detect if Cython is installed and a compiler is available. That technique was the one recommended here - https://github.com/cython/cython/issues/2061#issuecomment-359071601. The whole point of #2061 was to get a (supported) routine to determine if Cython is available and viable. If importing `Cython.Compiler.Main` is sufficient to cause Cython to crash, that's certainly not good, and we may need to revisit #2061 to develop further the detection routine.

I don't have any insight on the crashes.

**Comment by astrofrog** [comment]
@jaraco 

> I think you mean 38.5.

Yes, that's correct

So to follow up on this, I modified the example to be:

```python
import os

with open('test.pyx', 'w') as f:
    f.write('cimport cython\n')

with open('test.py', 'w') as f:
    f.write('import Cython.Compiler.Main')

from setuptools.sandbox import run_setup
run_setup(os.path.join(os.path.abspath('.'), 'test.py'), ['egg_info'])

from Cython.Build import cythonize
cythonize('test.pyx')
```

(notice the change in the content of ``test.py``) and indeed this still crashes, even with an older version of setuptools. So I agree that the change in setuptools 38.5 is not directly responsible for this but rather exposing a bug that existed previousy but just wasn't triggered by default before.

@cdeil - for now the easiest workaround is to pin setuptools to 38.4.1

**Comment by astrofrog** [comment]
And just to confirm, this happens on Linux and MacOS X

**Comment by cdeil** [comment]
@astrofrog - Thank you very much for all your work here, and in general on maintaining astropy-helpers and all things!!!

**Comment by scoder** [comment]
Thank you for the investigations. I added the reproducer script to the Cython test suite, but couldn't get it crash with the latest Cython master. Could you please also try that on your side?

**Comment by scoder** [comment]
Hmm, looks like travis managed to reproduce it. I'll give it another try.

**Comment by scoder** [comment]
Probably due to https://bugs.python.org/issue32973
I've committed a proposed fix in 71a8006 (which github picked up as final fix, sorry for the confusion).
