### ISSUE TITLE
AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by eliaperantoni** [cython/cython#2252]
After running `pyinstaller server.py` I launch the generated `server.exe` and I get this error

```
[992] Failed to execute script server
c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:714: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  module = loader.load_module(fullname)
Using TensorFlow backend.
Traceback (most recent call last):
  File "server.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\keras\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\keras\utils\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\keras\utils\conv_utils.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\keras\backend\__init__.py", line 83, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\tensorflow\__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\tensorflow\python\__init__.py", line 83, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\tensorflow\python\estimator\estimator_lib.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\tensorflow\python\estimator\inputs\inputs.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\tensorflow\python\estimator\inputs\pandas_io.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pandas\__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pandas\_libs\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "pandas\_libs\tslib.pyx", line 1510, in init pandas._libs.tslib
AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__'
```

Here's the output of `pip list`
```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alembic (0.9.9)
altgraph (0.15)
appdirs (1.4.3)
APScheduler (3.5.1)
argcomplete (1.9.4)
asn1crypto (0.24.0)
astroid (1.6.0)
Augmentor (0.1.10)
autopep8 (1.3.4)
Babel (2.5.3)
bcrypt (3.1.4)
bleach (1.5.0)
blinker (1.4)
bottle (0.12.13)
bottle-websocket (0.2.9)
certifi (2017.11.5)
cffi (1.11.2)
chardet (3.0.4)
click (6.7)
colorama (0.3.9)
colorpy (0.1.1)
cryptography (2.1.4)
curses (2.2)
cycler (0.10.0)
decorator (4.1.2)
docutils (0.14)
Eel (0.8.0)
entrypoints (0.2.3)
eventlet (0.22.0)
flake8 (3.5.0)
Flask (0.12.2)
Flask-Admin (1.5.0)
Flask-BabelEx (0.9.3)
Flask-JWT (0.3.2)
Flask-JWT-Simple (0.0.3)
Flask-Login (0.4.1)
Flask-Mail (0.9.1)
Flask-Principal (0.4.0)
Flask-Restless (0.17.0)
Flask-Security (3.0.0, c:\users\elia\documents\python\flask-security)
Flask-Session (0.3.1)
Flask-SocketIO (2.9.3)
Flask-SQLAlchemy (2.3.2)
Flask-WTF (0.14.2)
future (0.16.0)
gevent (1.2.2)
gevent-websocket (0.10.1)
greenlet (0.4.12)
h5py (2.7.1)
html5lib (0.9999999)
huepy (0.9.6)
idna (2.6)
imageio (2.1.2)
imgaug (0.2.5)
inflection (0.3.1)
inputs (0.1)
ipykernel (4.7.0)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.1.0)
isort (4.2.15)
itsdangerous (0.24)
jedi (0.11.1)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.2.1)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
Keras (2.1.2)
Kivy (1.10.0)
Kivy-Garden (0.1.4)
kivy.deps.glew (0.1.9)
kivy.deps.gstreamer (0.1.12)
kivy.deps.sdl2 (0.1.17)
lazy-object-proxy (1.3.1)
lxml (4.1.1)
macholib (1.9)
Mako (1.0.7)
Markdown (2.6.9)
markdown2 (2.3.5)
MarkupSafe (1.0)
matplotlib (2.1.0)
mccabe (0.6.1)
mimerender (0.6.0)
mistune (0.8.3)
more-itertools (4.0.1)
moviepy (0.2.3.2)
nbconvert (5.3.1)
nbformat (4.4.0)
ndg-httpsclient (0.4.3)
networkx (2.0)
notebook (5.2.2)
numpy (1.14.2)
olefile (0.44)
opencv-python (3.3.0.10)
pandas (0.21.0)
pandocfilters (1.4.2)
parso (0.1.1)
passlib (1.7.1)
peewee (3.0.7)
pefile (2017.11.5)
pew (1.1.2)
pickleshare (0.7.4)
Pillow (4.3.0)
pip (9.0.3)
pipenv (11.7.3)
plotly (2.4.1)
prompt-toolkit (1.0.15)
protobuf (3.5.0.post1)
psutil (5.3.1)
pyasn1 (0.4.2)
pycodestyle (2.3.1)
pycparser (2.18)
pyflakes (1.6.0)
Pygments (2.2.0)
PyInstaller (3.3.1)
PyJWT (1.4.2)
pylint (1.8.1)
pyminifier (2.1)
pymongo (3.6.1)
pyOpenSSL (17.5.0)
pyparsing (2.2.0)
pypiwin32 (220)
pyserial (3.4)
python-dateutil (2.6.1)
python-editor (1.0.3)
python-engineio (2.0.2)
python-escpos (3.0a3)
python-mimeparse (1.6.0)
python-socketio (1.8.4)
pytube (9.2.2)
pytz (2017.3)
pyusb (1.0.2)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (16.0.3)
qrcode (6.0)
qtconsole (4.3.1)
Quandl (3.3.0)
redis (2.10.6)
requests (2.18.4)
rope (0.10.7)
scikit-image (0.13.1)
scikit-learn (0.19.1)
scipy (1.0.1)
setuptools (38.5.2)
simplegeneric (0.8.1)
six (1.11.0)
sklearn (0.0)
speaklater (1.3)
SQLAlchemy (1.2.3)
tensorflow-gpu (1.4.0)
tensorflow-tensorboard (0.4.0rc3)
testpath (0.3.1)
tflearn (0.3.2)
tornado (4.5.3)
tqdm (4.11.2)
traitlets (4.3.2)
tzlocal (1.5.1)
urllib3 (1.22)
viivakoodi (0.8.0)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper-win (1.2.5)
wcwidth (0.1.7)
Werkzeug (0.14.1)
wheel (0.30.0)
widgetsnbextension (3.1.0)
wrapt (1.10.11)
WTForms (2.1)
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by scoder** [comment]
Since this is almost certainly the same problem as #1953, I'd like to keep these two together.
