### ISSUE TITLE
Coverage file tracer exception

### ISSUE THREAD

**Issue by pitrou** [cython/cython#2265]
At some point during my investigations I stumbled on the following:
```
Coverage.py warning: Disabling plug-in 'Cython.Coverage.Plugin' due to an exception:
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/_pytest/config.py", line 328, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/antoine/arrow/python/pyarrow/tests')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/_pytest/config.py", line 359, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/antoine/arrow/python/pyarrow/tests/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/coverage/control.py", line 505, in _should_trace_internal
    file_tracer = plugin.file_tracer(canonical)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/Cython/Coverage.py", line 72, in file_tracer
    c_file, py_file = self._find_source_files(filename)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/Cython/Coverage.py", line 127, in _find_source_files
    if filename in self._c_files_map:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jakirkham** [comment]
Looks sort of similar to issue ( https://github.com/cython/cython/issues/1985 ).
