### ISSUE TITLE
Failing tests with 0.28.3

### ISSUE THREAD

**Issue by FRidh** [cython/cython#2319]
Build and test log:
https://nix-cache.s3.amazonaws.com/log/y3ml3jck19injwk6m3i2g28wjs5plkdv-python3.6-Cython-0.28.3.drv

Build information:
https://hydra.nixos.org/build/75722086

```
Error compiling Cython file:
------------------------------------------------------------
...



def __invoke():
    del f''
       ^
------------------------------------------------------------

/build/.cython/inline/_cython_inline_beb4bbef1343875f738b6e0127fe9a71.pyx:5:8: Cannot assign to or delete this

Error compiling Cython file:
------------------------------------------------------------
...



def __invoke():
    del '' f''
       ^
------------------------------------------------------------

/build/.cython/inline/_cython_inline_f66f65e88fbde95f5e537752d0e758e3.pyx:5:8: Cannot assign to or delete this
warning: /build/.cython/inline/_cython_inline_110bb1f5cf1c6d3fb43b12861e28eee1.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_2ac7e6d6135b0017092e3efaa0600c37.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_fef576f0414b8f0066acfb95092b1cbc.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_8462394424805248103b68f3371f1adb.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_38bd97cf321167b7480fcdefa9cdaa3d.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_8b8c347ab142fd959ba0ed0749fee3e0.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_659bc900a2ef89b4a630f165063dc8d1.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_7eb5b4430795aa4e7d2ff64237002c6e.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_bcfcd314c3e2b90452a153cbfa6a5cdf.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_67426d6ad1ce69a583797c9ecdb6a9ef.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_16bb4a61d5b5583bd60b5a4c19e91149.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_3cced159f9c00cecf34a8e10b0dc1aec.pyx:6:4: Unreachable code
warning: /build/.cython/inline/_cython_inline_e18ca7d3560aaf715bd6f7982617025f.pyx:6:4: Unreachable code

Error compiling Cython file:
------------------------------------------------------------
...



def __invoke():
    del f''
       ^
------------------------------------------------------------

/build/.cython/inline/_cython_inline_beb4bbef1343875f738b6e0127fe9a71.pyx:5:8: Cannot assign to or delete this

Error compiling Cython file:
------------------------------------------------------------
...



def __invoke():
    del '' f''
       ^
------------------------------------------------------------

/build/.cython/inline/_cython_inline_f66f65e88fbde95f5e537752d0e758e3.pyx:5:8: Cannot assign to or delete this
unused.c:1275:18: warning: ‘__pyx_f_6unused_c_unused_optional’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_6unused_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_6unused_c_unused_optional *__pyx_optional_args) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unused.c:1228:18: warning: ‘__pyx_f_6unused_c_unused_simple’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_6unused_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unused.cpp:1289:18: warning: ‘PyObject* __pyx_f_6unused_c_unused_optional(PyObject*, PyObject*, __pyx_opt_args_6unused_c_unused_optional*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_6unused_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_6unused_c_unused_optional *__pyx_optional_args) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unused.cpp:1242:18: warning: ‘PyObject* __pyx_f_6unused_c_unused_simple(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_6unused_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unused_args.c:1290:18: warning: ‘__pyx_f_11unused_args_c_unused_optional’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_11unused_args_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_11unused_args_c_unused_optional *__pyx_optional_args) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unused_args.c:1243:18: warning: ‘__pyx_f_11unused_args_c_unused_simple’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_11unused_args_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unused_args.cpp:1304:18: warning: ‘PyObject* __pyx_f_11unused_args_c_unused_optional(PyObject*, PyObject*, __pyx_opt_args_11unused_args_c_unused_optional*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_11unused_args_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_11unused_args_c_unused_optional *__pyx_optional_args) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unused_args.cpp:1257:18: warning: ‘PyObject* __pyx_f_11unused_args_c_unused_simple(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_f_11unused_args_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exception ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7fff73704eb8>
Traceback (most recent call last):
  File "tests/run/yield_from_pep380.pyx", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__
    1/0
ZeroDivisionError: integer division or modulo by zero
Exception ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7fff73704da0>
Traceback (most recent call last):
  File "tests/run/yield_from_pep380.pyx", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__
    1/0
ZeroDivisionError: integer division or modulo by zero
Exception ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7ffee74bde48>
Traceback (most recent call last):
  File "tests/run/yield_from_pep380.pyx", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__
    1/0
ZeroDivisionError: integer division or modulo by zero
Exception ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7ffee74bd828>
Traceback (most recent call last):
  File "tests/run/yield_from_pep380.pyx", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__
    1/0
ZeroDivisionError: integer division or modulo by zero
runtests.py:1586: DeprecationWarning: Please use assertTrue instead.
  "make PYTHON='%s' CYTHON='%s' LIBDIR1='%s' test > make.output" % (sys.executable, cython, libdir)) == 0)
======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c) and running fstring
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1114, in run
    ext_so_path = self.runCompileTest()
  File "runtests.py", line 803, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "runtests.py", line 1038, in compile
    self._match_output(expected_errors, errors, tostderr)
  File "runtests.py", line 1084, in _match_output
    self.assertEqual(None, unexpected)
AssertionError: None != "509:0: Expected path '//AddNode' not found in result tree"

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (cpp) and running fstring
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1114, in run
    ext_so_path = self.runCompileTest()
  File "runtests.py", line 803, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "runtests.py", line 1038, in compile
    self._match_output(expected_errors, errors, tostderr)
  File "runtests.py", line 1084, in _match_output
    self.assertEqual(None, unexpected)
AssertionError: None != "509:0: Expected path '//AddNode' not found in result tree"

----------------------------------------------------------------------
Ran 11246 tests in 9091.778s
```

**Comment by scoder** [comment]
> Does that mean the PyPI sdist corresponds to a build from just before the tagged version?

Yes.
