### ISSUE TITLE
cython *.pyx does not work on raspberry 

### ISSUE THREAD

**Issue by douglasbsf** [cython/cython#2328]
pi@raspberrypi:~/Projects/cython-call-python-in-c $ cython *.pyx
Traceback (most recent call last):
  File "/usr/local/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/pi/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 712, in setuptools_main
    return main(command_line = 1)
  File "/home/pi/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 730, in main
    result = compile(sources, options)
  File "/home/pi/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 702, in compile
    return compile_multiple(source, options)
  File "/home/pi/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 672, in compile_multiple
    context = options.create_context()
  File "/home/pi/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 596, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/pi/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 77, in __init__
    from . import Builtin, CythonScope
  File "/home/pi/.local/lib/python2.7/site-packages/Cython/Compiler/Builtin.py", line 16, in <module>
    iter_next_utility_code = UtilityCode.load("IterNext", "ObjectHandling.c")
  File "Cython/Compiler/Code.py", line 362, in Cython.Compiler.Code.UtilityCodeBase.load
  File "Cython/Compiler/Code.py", line 286, in Cython.Compiler.Code.UtilityCodeBase.load_utilities_from_file
  File "Cython/Compiler/Code.py", line 287, in Cython.Compiler.Code.UtilityCodeBase.load_utilities_from_file
  File "/usr/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf5 in position 3163: invalid start byte

**Comment by douglasbsf** [comment]
solved using sudo cython *.pyx
