### ISSUE TITLE
submodule with name "cython.pyx" doesn't build

### ISSUE THREAD

**Issue by realead** [cython/cython#2496]
The[ fix for #2422](https://github.com/cython/cython/commit/6c91bf8e5bc99b625405919f9318d5626ecfa782#diff-26945d164aa2d5cb24bbe2cb4b8903ed) introduced a regression: submodules called cython.pyx are no longer built, i.e. for such a test case:

```
######## my_module/__init__.py ########
######## mymodule/cython.pyx ########
```

It might be a little bit inconsistent to build cython.pyx in one case (submodule) but not in the other, but it is probably better not to break existing workflows.

**Comment by realead** [comment]
Actually the problem is when the module and not submodule is called "cython":
```
######## src/cython/__init__.py ########
######## src/cython/ttt.pyx ########
```

leads to 

```
cythonize cython/ttt.pyx -i
Compiling /home/ed/python_stuff/cython/test_build/cython/ttt.pyx because it changed.
[1/1] Cythonizing /home/ed/python_stuff/cython/test_build/cython/ttt.pyx

Error compiling Cython file:
------------------------------------------------------------
...
^
------------------------------------------------------------

cython:0:0: cython.ttt is not available
Traceback (most recent call last):
  File "/home/ed/anaconda3/bin/cythonize", line 11, in <module>
    sys.exit(main())
  File "/home/ed/anaconda3/lib/python3.6/site-packages/Cython/Build/Cythonize.py", line 196, in main
    cython_compile(path, options)
  File "/home/ed/anaconda3/lib/python3.6/site-packages/Cython/Build/Cythonize.py", line 90, in cython_compile
    **options.options)
  File "/home/ed/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/home/ed/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/ed/python_stuff/cython/test_build/cython/ttt.pyx

```
