### ISSUE TITLE
syntax error in build scripts of 0.28.5

### ISSUE THREAD

**Issue by ThomasWaldmann** [cython/cython#2550]
```
   wheezy32: Collecting Cython!=0.27 (from -r requirements.d/development.txt (line 10))                                                                                                         [20/11247]
    wheezy32:   Downloading https://files.pythonhosted.org/packages/21/89/ca320e5b45d381ae0df74c4b5694f1471c1b2453c5eb4bac3449f5970481/Cython-0.28.5.tar.gz (1.9MB)
    wheezy32:     Complete output from command python setup.py egg_info:
    wheezy32:     running egg_info
    wheezy32:     creating pip-egg-info/Cython.egg-info
    wheezy32:     writing pip-egg-info/Cython.egg-info/PKG-INFO
    wheezy32:     writing top-level names to pip-egg-info/Cython.egg-info/top_level.txt
    wheezy32:     writing dependency_links to pip-egg-info/Cython.egg-info/dependency_links.txt
    wheezy32:     writing entry points to pip-egg-info/Cython.egg-info/entry_points.txt
    wheezy32:     writing manifest file 'pip-egg-info/Cython.egg-info/SOURCES.txt'
    wheezy32:     Unable to find pgen, not compiling formal grammar.
    wheezy32:     /usr/lib/python3.2/distutils/dist.py:257: UserWarning: Unknown distribution option: 'python_requires'
    wheezy32:       warnings.warn(msg)
    wheezy32:     warning: manifest_maker: standard file '-c' not found
    wheezy32:     
    wheezy32:     Traceback (most recent call last):
    wheezy32:       File "<string>", line 20, in <module>
    wheezy32:       File "/tmp/pip-build-ly0szd/Cython/setup.py", line 285, in <module>
    wheezy32:         **setup_args
    wheezy32:       File "/usr/lib/python3.2/distutils/core.py", line 148, in setup
    wheezy32:         dist.run_commands()
    wheezy32:       File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands
    wheezy32:         self.run_command(cmd)
    wheezy32:       File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command
    wheezy32:         cmd_obj.run()
    wheezy32:       File "<string>", line 15, in replacement_run
    wheezy32:       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 254, in find_sources
    wheezy32:         mm.run()
    wheezy32:       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 308, in run
    wheezy32:         self.add_defaults()
    wheezy32:       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 332, in add_defaults
    wheezy32:         sdist.add_defaults(self)
    wheezy32:       File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 191, in add_defaults
    wheezy32:         build_ext = self.get_finalized_command('build_ext')
    wheezy32:       File "/usr/lib/python3.2/distutils/cmd.py", line 299, in get_finalized_command
    wheezy32:         cmd_obj.ensure_finalized()
    wheezy32:       File "/usr/lib/python3.2/distutils/cmd.py", line 107, in ensure_finalized
    wheezy32:         self.finalize_options()
    wheezy32:       File "Cython/Distutils/build_ext.py", line 19, in finalize_options
    wheezy32:         from Cython.Build.Dependencies import cythonize
    wheezy32:       File "Cython/Build/__init__.py", line 1, in <module>
    wheezy32:         from .Dependencies import cythonize
    wheezy32:       File "Cython/Build/Dependencies.py", line 333
    wheezy32:         if code[q-1] == u'\\':
    wheezy32:                             ^
    wheezy32:     SyntaxError: invalid syntax
```

```
vagrant@debian7-i386:~$ python3
Python 3.2.3 (default, Mar 25 2017, 10:08:27) 
[GCC 4.7.2] on linux2
```

**Comment by ThomasWaldmann** [comment]
Hmm, maybe this is related to pyenv not installing the desired Python 3.5.6.
I'll check that and reopen if the issue persists.
