### ISSUE TITLE
flaky test: Interrupted system call in longlongindex

### ISSUE THREAD

**Issue by nh2** [cython/cython#2602]
I observed the following non-deterministic test failure:

```
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c) and running longlongindex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1117, in run
    self.run_tests(result, ext_so_path)
  File "runtests.py", line 1132, in run_tests
    self.run_doctests(self.module, result, ext_so_path)
  File "runtests.py", line 1142, in run_doctests
    run_forked_test(result, run_test, self.shortDescription(), self.fork)
  File "runtests.py", line 1195, in run_forked_test
    cid, result_code = os.waitpid(child_id, 0)
OSError: [Errno 4] Interrupted system call
```

Found on Ubuntu 16.04 when building cython 0.28.3 with `nix (see this issue: https://github.com/nh2/static-haskell-nix/issues/6#issuecomment-420452838), but I don't know yet if any of that is relevant.

The `waitpid()` syscall can return `EINTR` (see man page). In normal code the correct action is to retry. For cython's tests, I am not sure. Does the test do anything that could result in a signal arriving at the thread that's `waitpid`ing?

**Comment by scoder** [comment]
The tests use forking to prevent the whole test runner from crashing if one test does. The above stack trace only shows the part on the side of the test runner and is therefore unhelpful (ok, it's the doctests that are failing and not the compilation, so it's not a C compiler/platform issue, at least). The actual reason might be given in the test logs at the place where the test ran. Could you dig those up?

**Comment by nh2** [comment]
How can I run a specific tests using `runtests.py`, such as `longlongindex`? I could spot only `--exclude` in `--help`.

**Comment by scoder** [comment]
Just pass that name as argument, it'll be used as a regex filter.
