### ISSUE TITLE
Bug: NamedTuple doesn't work after cythonization

### ISSUE THREAD

**Issue by vvegorova** [cython/cython#2649]
I have some module defining a `NamedTuple`: 

`nmt.py`:

```python
from typing import NamedTuple

class Employee(NamedTuple):
    name: str
    id: int
```
and a simple `setup.py`:

```python
from distutils.core import setup
from Cython.Build import cythonize

setup(ext_modules=cythonize("nmt.py"))
```
I build the module like this
```bash
python setup.py build_ext --inplace
```
The result class `Employee` can't be properly instantiated:
```python
>>> from nmt import Employee

>>> Employee("a", 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() takes 1 positional argument but 3 were given

>>> Employee("a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() takes 1 positional argument but 2 were given

>>> Employee()
Employee()

**Comment by scoder** [comment]
Duplicate of #2552.

**Comment by beruhan** [comment]
does any one has alternative plan? this usage is heavily used in the project.，and I don't know how to
