### ISSUE TITLE
cdef classes fails at pickling using `__setstate__` interface in Python 2.

### ISSUE THREAD

**Issue by rainwoodman** [cython/cython#2757]
Here is an example (for Python 2)

```
def _create_A_from_state(kls, state):
    obj = A.__new__(kls)
    obj.__setstate__(state)
    return obj

cdef class A:
    def __cinit__(self): pass
    def __init__(self): pass
    def __reduce__(self): return (_create_A_from_state, (type(self), self.__getstate__()))
    def __getstate__(self): return ()
    def __setstate__(self, state): return None

cdef class B:
    def __cinit__(self): pass
    def __init__(self): pass
    def __getstate__(self): return ()

    def __setstate__(self, state): return None

class AA(A): pass
class BB(B): pass

def main():
    import pickle
    obj = AA()
    s = pickle.dumps(obj)
    obj2 = pickle.loads(s)
    assert type(obj2) == AA

    obj = BB()
    s = pickle.dumps(obj)
    obj2 = pickle.loads(s)
    assert type(obj2) == BB

```
If one provides `__reduce__`, pickling works (the first assertion).
If one omits `__reduce__`, the second case (BB) fails at line 31:

```
$ python -c 'import pyximport; pyximport.install(); import failcy; failcy.main()'

...

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "failcy.pyx", line 31, in failcy.main
    s = pickle.dumps(obj)
  File "/home/yfeng1/anaconda3/install/envs/2.7/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/home/yfeng1/anaconda3/install/envs/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/home/yfeng1/anaconda3/install/envs/2.7/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/home/yfeng1/anaconda3/install/envs/2.7/lib/python2.7/copy_reg.py", line 71, in _reduce_ex
    state = base(self)
TypeError: __init__() takes exactly 0 positional arguments (1 given)

```

**Comment by rainwoodman** [comment]
The documentation was not clear that the BB case shall fail, and a google search on 'cython pickle' lands to an example that uses the BB case:

https://snorfalorpagus.net/blog/2016/04/16/pickling-cython-classes/

Since Python is not going through the `__new__` function, I do not think the BB case shall work at all. But it could be just a bug in Cython that reported a wrong signature for __init__ to Python.
