### ISSUE TITLE
Error while trying to build helloworld example

### ISSUE THREAD

**Issue by dmadeka** [cython/cython#2821]
```python
>>> import sys, Cython, numpy; print(Cython.__version__, numpy.__version__, sys.version_info)
0.29.2 1.15.4 sys.version_info(major=3, minor=5, micro=0, releaselevel='final', serial=0)
```

Trying to recreate the `helloworld` example- I get a strange error

```python
maded@uc4346b707fc2594ae9f1:~/dev/helloworld $ vim helloworld.pyx
maded@uc4346b707fc2594ae9f1:~/dev/helloworld $ vim setup.py
maded@uc4346b707fc2594ae9f1:~/dev/helloworld $ python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    ext_modules = cythonize("helloworld.pyx")
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 958, in cythonize
    ctx = c_options.create_context()
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
```

@rgommers Moving this from scipy https://github.com/scipy/scipy/issues/9744 to here

**Comment by dmadeka** [comment]
Cython was installed from `pip`

**Comment by rgommers** [comment]
Pretty sure that you'll want to install Cython with `conda` if you use Python from `conda`. Can you try that?

**Comment by dmadeka** [comment]
Good catch - the `pip` was from the anaconda install too so I didnt expect this
