### ISSUE TITLE
ImportError DLL load failed: %1 is not a valid win32 application from wheel packaged library

### ISSUE THREAD

**Issue by jtmorrisbytes** [cython/cython#2837]
Python Version: python 3.7.1
Windows 10 build 17763
64-bit processor
Visual studio 2017 installed

I am writing a library called [pyjtmorrisbytes](https://github.com/jtmorrisbytes/pyjtmorrisbytes/tree/dev) that holds common code that I will use across all [flask](https://github.com/pallets/flask) applications. flask depends on [werkzeug](https://github.com/pallets/werkzeug) which is imported from pyjtmorrisbytes.factories.flaskfactory and called from pyjtmorrisbytes.factories.flaskfactory::create_app. When imported from inside the same project, no error is thrown. I can call the create_app function inside tests and other code inside the same package, but when I package and distribute the application in another project inside the same computer, I get the following traceback while trying to import the function:
```
>>> from pyjtmorrisbytes.factories.flaskfactory import create_app
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\pyjtmorrisbytes\factories\flaskfactory.pyx", line 31, in init pyjtmorrisbytes.factories.flaskfactory
  File "C:\Users\jthec\.virtualenvs\flask-app-template-zB0k0H-c\lib\site-packages\flask\__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "C:\Users\jthec\.virtualenvs\flask-app-template-zB0k0H-c\lib\site-packages\werkzeug\__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "C:\Users\jthec\.virtualenvs\flask-app-template-zB0k0H-c\lib\site-packages\werkzeug\exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

Is this a problem with cython or is the way werkzeug importing libraries causing the import to fail? I can resort to just using a python library if necessary, but I would like to know why it happens

**Comment by scoder** [comment]
Doesn't look like a Cython issue at all. I would suggest deleting your venv and recreating it.
