### ISSUE TITLE
cython 0.29.3 runtest.py compilation errors

### ISSUE THREAD

**Issue by rickardcronholm** [cython/cython#2922]
I'm trying to build and run tests of cython 0.29.3 but get loads of compilation issues like
`+ 7:14: Syntax error in simple statement list`

I'm on
Ubuntu18.04
python3.6
gcc 8.2.0 (same issues with gcc 7.3.0)

I execute runtest.py with the following flags
`--exit-ok --xml-output=${workspace}/cython_reports/ --no-doctest --no-code-style --no-examples -3 --compiler gcc-8 -v`

This is a typical example
```
======================================================================
FAIL [1.598s]: runTest (__main__.CythonCompileTestCase)
compiling (cpp) cpdef
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 939, in runTest
    self.runCompileTest()
  File "runtests.py", line 945, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "runtests.py", line 1183, in compile
    self._match_output(expected_errors, errors, tostderr)
  File "runtests.py", line 1232, in _match_output
    self.assertEqual(None, unexpected)
AssertionError: None != '8:10: Syntax error in simple statement list'
```

**Comment by scoder** [comment]
Don't use `-3` for running the test suite.
