### ISSUE TITLE
AttributeError: 'PyObjectWrapper' object has no attribute '_set_name'

### ISSUE THREAD

**Issue by zaoqi** [cython/cython#2923]
https://gitlab.com/the-language/the-language/blob/f8a45e8ba920c2d0b39c73d36cfc46e12645e010/core/pure/python3/lang.py
```
$ ~/.local/bin/cython  lang.py 
/home/zaoqi/.local/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/zaoqi/src/the-language/core/pure/python3/lang.py
  tree = Parsing.p_module(s, pxd, full_module_name)
$ gcc -shared -pthread -fPIC -fwrapv -O0 -Wall -fno-strict-aliasing -I/usr/include/python3.7m/ -o lang.so lang.c
$ mkdir native
$ cd native/
$ mv ../lang.so ./
$ python
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lang
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lang.py", line 1287, in init lang
AttributeError: 'PyObjectWrapper' object has no attribute '_set_name'
>>> 
```

**Comment by scoder** [comment]
Looks like js2py does not support Cython compiled functions.
https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/base.py
