### ISSUE TITLE
Compiler crashes when fused type is used as part of C++ template specialization

### ISSUE THREAD

**Issue by atsuoishimoto** [cython/cython#2943]
Following Cython code with fused type cannot be compiled  with Cython 0.29.7/ Python 3.7.2/Ubuntu linux 18.04.

This error happends only if I use fused type to specialize template.

```python

cdef extern from "func.h":
    void func1[L](L arg);

ctypedef fused Num:
    long

def test(Num n):
    cdef void (*p_func1) (Num)
    p_func1 = func1[Num]
```

The error is:

```
1/1] Cythonizing test.pyx
/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/ishimoto/src/cython_bug/test.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
ctypedef fused Num:
    long

def test(Num n):
    cdef void (*p_func1) (Num)
    p_func1 = func1[Num]
                  ^
------------------------------------------------------------

test.pyx:10:19: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(test.pyx:2:0)
StatListNode.stats[1] = FusedCFuncDefNode(test.pyx:8:0,
    defaults = [...]/1,
    fused_compound_types = [...]/1,
    match = "dest_sig[{{dest_sig_idx}}] = '{{specialized_type_name}}'",
    no_match = 'dest_sig[{{dest_sig_idx}}] = None',
    nodes = [...]/1,
    specialized_pycfuncs = [...]/1)
FusedCFuncDefNode.stats[1] = DefNode(test.pyx:8:0,
    modifiers = [...]/0,
    name = 'test',
    np_args_idx = [...]/0,
    num_required_args = 1,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    specialized_signature_string = 'long',
    used = True)
File 'Nodes.py', line 436, in analyse_expressions: StatListNode(test.pyx:9:4)
File 'Nodes.py', line 5156, in analyse_expressions: SingleAssignmentNode(test.pyx:10:19)
File 'Nodes.py', line 5309, in analyse_types: SingleAssignmentNode(test.pyx:10:19)
File 'ExprNodes.py', line 895, in coerce_to: IndexNode(test.pyx:10:19,
    is_subscript = True,
    result_is_used = True,
    type_indices = [...]/1,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 895, in coerce_to
    for signature in src_type.get_all_specialized_function_types():
  File "/usr/local/lib/python3.7/site-packages/Cython/Compiler/PyrexTypes.py", line 2986, in get_all_specialized_function_types
    if self.entry.fused_cfunction:
AttributeError: 'CFuncType' object has no attribute 'entry'
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ext_modules=cythonize(ext_modules),
  File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: test.pyx
```

**Comment by oliverhaas** [comment]
I encountered what I think is the same error, but with different error message. I just post this here to make it easier to find if somebody looks for my error.

Code is

```
from libcpp.unordered_map cimport unordered_map
cimport cython

cdef:
    unordered_map[int, double] data
    unordered_map[cython.integral, double] data
```

Error message is

```
python3 setup.py build_ext --inplace
running build_ext
skipping 'test_000.cpp' Cython extension (up-to-date)
cythoning test_001.pyx to test_001.cpp
/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/ohaas/HESSENBOX-DA/PhD/code/openChargeState/test/unorderedMapc++ArrayKey/test_001.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
cimport cython


cdef:
    unordered_map[int, double] data
    unordered_map[cython.integral, double] data
                 ^
------------------------------------------------------------

test_001.pyx:9:18: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 124, in analyse_declarations: ModuleNode(test_001.pyx:2:0,
    full_module_name = 'test_001')
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(test_001.pyx:2:0)
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(test_001.pyx:8:4)
File 'Nodes.py', line 1327, in analyse_declarations: CVarDefNode(test_001.pyx:9:4,
    modifiers = [...]/0,
    visibility = 'private')
File 'Nodes.py', line 1158, in analyse: TemplatedTypeNode(test_001.pyx:9:18)

Compiler crash traceback from this point on:
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Nodes.py", line 1158, in analyse
    self.type = base_type.specialize_here(self.pos, template_types)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3677, in specialize_here
    return self.specialize(dict(zip(self.templates, template_values)))
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3695, in specialize
    specialized.scope = self.scope.specialize(values, specialized)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2483, in specialize
    entry.type.specialize(values),
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 415, in specialize
    base_type = self.typedef_base_type.specialize(values)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3695, in specialize
    specialized.scope = self.scope.specialize(values, specialized)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2493, in specialize
    utility_code=e.utility_code)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2431, in declare_cfunction
    cname=cname, visibility=visibility)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2395, in declare_var
    entry.func_cname = "%s::%s" % (self.type.empty_declaration_code(), cname)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 51, in empty_declaration_code
    self._empty_declaration = self.declaration_code('')
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3749, in declaration_code
    for param in template_params
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3750, in <listcomp>
    if not is_optional_template_param(param) and not param.is_fused]
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 1582, in declaration_code
    return self.const_base_type.declaration_code("const %s" % entity_code, for_display, dll_linkage, pyrex)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 1649, in declaration_code
    raise Exception("This may never happen, please report a bug")
Exception: This may never happen, please report a bug
```

**Comment by da-woods** [comment]
@oliverhaas I don't think it is the same bug. You're trying to declare a fused variable at the module scope. That definitely doesn't make sense. In a function Cython can pick which "version" of the function gets run; here there's never an opportunity to decide so it stays in an indeterminate "could be any of these types"-state.

It should probably give you a better error message though.

**Comment by oliverhaas** [comment]
Yes, you're right. When I was simplifying my use case I went too far and made a nonsensical example.

This one should be more fitting:

```
from libcpp.unordered_map cimport unordered_map
cimport cython

cdef void someFun(cython.integral var) nogil:
    cdef unordered_map[int, double] data
    cdef unordered_map[cython.integral, double] data
    return
```

```
python3 setup.py build_ext --inplace
running build_ext
skipping 'test_000.cpp' Cython extension (up-to-date)
cythoning test_001.pyx to test_001.cpp
/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/ohaas/HESSENBOX-DA/PhD/code/openChargeState/test/unorderedMapc++ArrayKey/test_001.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.unordered_map cimport unordered_map
cimport cython

cdef void someFun(cython.integral var) nogil:
    cdef unordered_map[int, double] data
    cdef unordered_map[cython.integral, double] data
                      ^
------------------------------------------------------------

test_001.pyx:7:23: Compiler crash in AnalyseDeclarationsTransform

ModuleNode.body = StatListNode(test_001.pyx:2:0)
StatListNode.stats[2] = StatListNode(test_001.pyx:5:5)
StatListNode.stats[0] = CFuncDefNode(test_001.pyx:5:5,
    args = [...]/1,
    has_fused_arguments = True,
    modifiers = [...]/0,
    visibility = 'private')
FusedCFuncDefNode.stats[0] = CFuncDefNode(test_001.pyx:5:5,
    args = [...]/1,
    modifiers = [...]/0,
    visibility = 'private')
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(test_001.pyx:6:4,
    is_terminator = True)
File 'Nodes.py', line 1327, in analyse_declarations: CVarDefNode(test_001.pyx:7:9,
    modifiers = [...]/0,
    visibility = 'private')
File 'Nodes.py', line 1158, in analyse: TemplatedTypeNode(test_001.pyx:7:23)

Compiler crash traceback from this point on:
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Nodes.py", line 1158, in analyse
    self.type = base_type.specialize_here(self.pos, template_types)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3677, in specialize_here
    return self.specialize(dict(zip(self.templates, template_values)))
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3695, in specialize
    specialized.scope = self.scope.specialize(values, specialized)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2483, in specialize
    entry.type.specialize(values),
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 415, in specialize
    base_type = self.typedef_base_type.specialize(values)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3695, in specialize
    specialized.scope = self.scope.specialize(values, specialized)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2493, in specialize
    utility_code=e.utility_code)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2431, in declare_cfunction
    cname=cname, visibility=visibility)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/Symtab.py", line 2395, in declare_var
    entry.func_cname = "%s::%s" % (self.type.empty_declaration_code(), cname)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 51, in empty_declaration_code
    self._empty_declaration = self.declaration_code('')
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3749, in declaration_code
    for param in template_params
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 3750, in <listcomp>
    if not is_optional_template_param(param) and not param.is_fused]
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 1582, in declaration_code
    return self.const_base_type.declaration_code("const %s" % entity_code, for_display, dll_linkage, pyrex)
  File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/PyrexTypes.py", line 1649, in declaration_code
    raise Exception("This may never happen, please report a bug")
Exception: This may never happen, please report a bug
building 'test_001' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/local/include/ -I/usr/include/python3.5m -c test_001.cpp -o build/temp.linux-x86_64-3.5/test_001.o -O1 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
test_001.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by scoder** [comment]
I don't see why this shouldn't generally work, so it's a bug.
Needs investigation to find where things go wrong, but might be easy to fix in the end.
This line in the traceback seems suggestive:
```cython
if not is_optional_template_param(param) and not param.is_fused]
```
Apparently, `param` was not detected as fused type, probably during the original analysis of the template arguments.

**Comment by william-silversmith** [comment]
I ran into this too. My code looked like this.

```python
from libc.stdint cimport (
  int8_t, int16_t, int32_t, int64_t,
  uint8_t, uint16_t, uint32_t, uint64_t,
)
from libcpp.vector cimport vector
from libcpp.map cimport map as mapcpp
from libcpp.utility cimport pair as cpp_pair
cimport numpy as cnp
ctypedef fused UINT:
  uint8_t
  uint16_t
  uint32_t
  uint64_t

def _runs(
    cnp.ndarray[UINT, ndim=1, cast=True] labels
  ):
  cdef mapcpp[UINT, vector[cpp_pair[size_t,size_t]]] rns
```
