### ISSUE TITLE
Unit tests crash

### ISSUE THREAD

**Issue by adamjstewart** [cython/cython#2957]
I'm trying to run the unit tests using:
```console
$ python setup.py test
```
but I get the following error message:
```
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
    **setup_args
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/py-setuptools-41.0.1-yb2o74z5d2gebqo3ouu2coc7hetrxv5w/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/py-setuptools-41.0.1-yb2o74z5d2gebqo3ouu2coc7hetrxv5w/lib/python3.7/site-packages/setuptools/command/test.py", line 229, in run
    self.run_tests()
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/py-setuptools-41.0.1-yb2o74z5d2gebqo3ouu2coc7hetrxv5w/lib/python3.7/site-packages/setuptools/command/test.py", line 251, in run_tests
    exit=False,
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/py-setuptools-41.0.1-yb2o74z5d2gebqo3ouu2coc7hetrxv5w/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/py-setuptools-41.0.1-yb2o74z5d2gebqo3ouu2coc7hetrxv5w/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/python-3.7.3-75lu7r2nitkq4glntkhgr2zfmagnhqeh/lib/python3.7/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: __init__() missing 1 required positional argument: 'dist'
```
This is on a pretty minimal Python 3.7.3 installation with only `setuptools` installed.

**Comment by scoder** [comment]
Cython has its own test runner (`runtests.py`), so this is not intended to work. I would consider a PR that makes it work, though, it case that's not too complicated.

**Comment by adamjstewart** [comment]
Thanks, this works for me!
