### ISSUE TITLE
Cython ValueError: no signature found for builtin <cyfunction.lambda>

### ISSUE THREAD

**Issue by zyukyunman** [cython/cython#2983]
how can i fix this bug?using cython 0.29.10

**Comment by scoder** [comment]
Could you be more specific about the problem that you see?

**Comment by Marshall0304** [comment]
hello， do u fixed this bug? i have met this bug too when using keras.layers.lambda with cython 0.29, 0.28 and 0.27

**Comment by scoder** [comment]
See https://github.com/cython/cython/issues/2983#issuecomment-499769108 above.

**Comment by scoder** [comment]
More specifically, does it work if you rebuild keras with Cython 0.29.10 ?
You can check the Cython version that was used to generate the C/C++ files by looking at their first line.

**Comment by scoder** [comment]
(Lacking further information, my guess is that this is a duplicate of #1470)

**Comment by scoder** [comment]
Lacking further information, my guess is that this is a duplicate of #1470, but it's unclear since the title suggests a Python exception and not a "core dump". I have no idea what keras does here. Maybe it needs to enable the `binding=True` directive? I also don't know what the specific use case is for inspecting its signature here.

**Comment by wang229837** [comment]
I got this issue too, but with tensorflow.python.keras._impl.keras.layers.Lambda, and I got ValueError: no signature found for builtin <cyfunction .....<locals>.<lambda> at 0x7f6bd03f0328>

**Comment by scoder** [comment]
Please provide more details, preferably a minimal sequence of steps that can be executed to reproduce this.

**Comment by feeeper** [comment]
@scoder I have the same issue with `keras.layers.Lambda`. 

I have three files: 
1. `model.py` with some code that uses `keras.layers.Lambda`
2. `main.py` instantiates class from `model.py`
3. `compile.py` compiles only `model.py`

If I started `main.py` without compiling `model.py` script works fine.

If I compile `model.py` with comand `python compile.py build_ext --build-lib=bin` and start `main.py` from `bin` directory I got the error:

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    mrcnn = MaskRCNN()
  File "model.py", line 23, in model.MaskRCNN.__init__
  File "model.py", line 17, in model.build_rpn_model
  File "model.py", line 9, in model.rpn_graph
  File "c:\ArioPython\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "c:\ArioPython\lib\site-packages\keras\layers\core.py", line 685, in call
    if has_arg(self.function, 'mask'):
  File "c:\ArioPython\lib\site-packages\keras\utils\generic_utils.py", line 274, in has_arg
    signature = inspect.signature(fn)
  File "c:\ArioPython\lib\inspect.py", line 3001, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "c:\ArioPython\lib\inspect.py", line 2751, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "c:\ArioPython\lib\inspect.py", line 2230, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "c:\ArioPython\lib\inspect.py", line 2060, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <cyfunction rpn_graph.<locals>.<lambda> at 0x00000035E6F478E8>
```

Minimal reproducable example here:

`model.py`
``` python
import tensorflow as tf
import keras
import keras.layers as KL
import keras.models as KM


def rpn_graph(feature_map):
    rpn_class_logits = KL.Lambda(
        lambda t: tf.reshape(t, [tf.shape(t)[0], -1, 2]))(feature_map)

    return [rpn_class_logits]


def build_rpn_model():
    input_feature_map = KL.Input(shape=[None, None, 256],
                                 name="input_rpn_feature_map")
    outputs = rpn_graph(input_feature_map)
    return KM.Model([input_feature_map], outputs, name="rpn_model")


class MaskRCNN:
    def __init__(self):
        self.rpn = build_rpn_model()
```

`main.py`
``` python
from model import MaskRCNN
import numpy as np


mrcnn = MaskRCNN()
print(mrcnn)
```

`compily.py`
``` python
from Cython.Distutils import build_ext
from distutils.extension import Extension as dExtension
from distutils.core import setup as dsetup


dsetup(
    name='Keras Lambda Layer Example',
    cmdclass={'build_ext': build_ext},
    ext_modules=[dExtension('model', ['model.py'])]
)
```

Versions
```
>>> import cython as c
>>> c.__version__
'0.29.13'
>>> import keras as k
Using TensorFlow backend.
>>> k.__version__
'2.2.4'
>>> import tensorflow as tf
>>> tf.__version__
'1.10.0'
```

**Comment by Mrzhang3389** [comment]
@feeeper 
Have you solved your problem? I have the same problem

**Comment by feeeper** [comment]
> @feeeper
> Have you solved your problem? I have the same problem

Nope. Still waiting.

**Comment by Mrzhang3389** [comment]
@feeeper I have a tensorflow problem.
################################################################################
Traceback (most recent call last):
  File "/home/z/miniconda3/envs/tf2/lib/python3.7/inspect.py", line 1119, in getfullargspec
    sigcls=Signature)
  File "/home/z/miniconda3/envs/tf2/lib/python3.7/inspect.py", line 2281, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/home/z/miniconda3/envs/tf2/lib/python3.7/inspect.py", line 2105, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <tensorflow.python.keras.saving.saved_model.save_impl.LayerCall object at 0x7f15d04e3550>
################################################################################
Remove keras.layers.timedistributed to run normally
At first, I thought our problems were the same

**Comment by feeeper** [comment]
@Mrzhang3389 Hmm... I'm not sure that I got what you mean. Could you please point me where I should remove `keras.layers.timedistributed`?

**Comment by vincentkk6356** [comment]
> @scoder I have the same issue with `keras.layers.Lambda`.
> 
> I have three files:
> 
> 1. `model.py` with some code that uses `keras.layers.Lambda`
> 2. `main.py` instantiates class from `model.py`
> 3. `compile.py` compiles only `model.py`
> 
> If I started `main.py` without compiling `model.py` script works fine.
> 
> If I compile `model.py` with comand `python compile.py build_ext --build-lib=bin` and start `main.py` from `bin` directory I got the error:
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 5, in <module>
>     mrcnn = MaskRCNN()
>   File "model.py", line 23, in model.MaskRCNN.__init__
>   File "model.py", line 17, in model.build_rpn_model
>   File "model.py", line 9, in model.rpn_graph
>   File "c:\ArioPython\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
>     output = self.call(inputs, **kwargs)
>   File "c:\ArioPython\lib\site-packages\keras\layers\core.py", line 685, in call
>     if has_arg(self.function, 'mask'):
>   File "c:\ArioPython\lib\site-packages\keras\utils\generic_utils.py", line 274, in has_arg
>     signature = inspect.signature(fn)
>   File "c:\ArioPython\lib\inspect.py", line 3001, in signature
>     return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
>   File "c:\ArioPython\lib\inspect.py", line 2751, in from_callable
>     follow_wrapper_chains=follow_wrapped)
>   File "c:\ArioPython\lib\inspect.py", line 2230, in _signature_from_callable
>     skip_bound_arg=skip_bound_arg)
>   File "c:\ArioPython\lib\inspect.py", line 2060, in _signature_from_builtin
>     raise ValueError("no signature found for builtin {!r}".format(func))
> ValueError: no signature found for builtin <cyfunction rpn_graph.<locals>.<lambda> at 0x00000035E6F478E8>
> ```
> 
> Minimal reproducable example here:
> 
> `model.py`
> 
> ```python
> import tensorflow as tf
> import keras
> import keras.layers as KL
> import keras.models as KM
> 
> 
> def rpn_graph(feature_map):
>     rpn_class_logits = KL.Lambda(
>         lambda t: tf.reshape(t, [tf.shape(t)[0], -1, 2]))(feature_map)
> 
>     return [rpn_class_logits]
> 
> 
> def build_rpn_model():
>     input_feature_map = KL.Input(shape=[None, None, 256],
>                                  name="input_rpn_feature_map")
>     outputs = rpn_graph(input_feature_map)
>     return KM.Model([input_feature_map], outputs, name="rpn_model")
> 
> 
> class MaskRCNN:
>     def __init__(self):
>         self.rpn = build_rpn_model()
> ```
> 
> `main.py`
> 
> ```python
> from model import MaskRCNN
> import numpy as np
> 
> 
> mrcnn = MaskRCNN()
> print(mrcnn)
> ```
> 
> `compily.py`
> 
> ```python
> from Cython.Distutils import build_ext
> from distutils.extension import Extension as dExtension
> from distutils.core import setup as dsetup
> 
> 
> dsetup(
>     name='Keras Lambda Layer Example',
>     cmdclass={'build_ext': build_ext},
>     ext_modules=[dExtension('model', ['model.py'])]
> )
> ```
> 
> Versions
> 
> ```
> >>> import cython as c
> >>> c.__version__
> '0.29.13'
> >>> import keras as k
> Using TensorFlow backend.
> >>> k.__version__
> '2.2.4'
> >>> import tensorflow as tf
> >>> tf.__version__
> '1.10.0'
> ```

I just solved the problem by "not using lambda. I don't know the exact reason why lambda does not work in cython but apparently it is. Just replace the lambda functions with a standard defined function, e.g.:
```python
import tensorflow as tf
import keras
import keras.layers as KL
import keras.models as KM

# define the lambda function in standard way
def get_rpn_graph_lambda_func(t):
    return tf.reshape(t, [tf.shape(t)[0], -1, 2])

def rpn_graph(feature_map):
    rpn_class_logits = KL.Lambda(
        get_rpn_graph_lambda_func)(feature_map)  #pass the newly defined function as an arg
    return [rpn_class_logits]


def build_rpn_model():
    input_feature_map = KL.Input(shape=[None, None, 256],
                                 name="input_rpn_feature_map")
    outputs = rpn_graph(input_feature_map)
    return KM.Model([input_feature_map], outputs, name="rpn_model")


class MaskRCNN:
    def __init__(self):
        self.rpn = build_rpn_model()
```

**Comment by scoder** [comment]
I added failing tests in 035850127868bbd87390eb143b1eea64c5fa3c80 (branch [gh2983_lambda_sig](https://github.com/cython/cython/tree/gh2983_lambda_sig)).
PR welcome.

**Comment by scoder** [comment]
The tests show that the `__code__` attribute of lambda functions is not set. Probably related to (or the same as) #1864. Might actually be easy to fix, help (debugging/PR) appreciated.

**Comment by vForce825** [comment]
Anyone still fixing this problem?

**Comment by rishacha** [comment]
@scoder I want to help fix this problem if this is not taken up. But I have no clue how to go about fixing it. Is there someone who can guide me through this for a `first-issue`?

**Comment by da-woods** [comment]
@rishacha The issue is that `LambdaNode` (in ExprNodes.py) doesn't set up the attribute `code_object`. For a regular function the code object is created in the call to `PyCFunctionNode.from_defnode` (which happens during the `AnalyseDeclarationsTransfrom` stage of Cython.

I'd suggest that `LambdaNode` should create the code object at the same stage. Therefore look in `LambdaNode.analyse_declarations`. See if you can create a `CodeObjectNode` at this stage and and assign it to `self.code_object`

**Comment by dtczest** [comment]
@scoder just to confirm, this is slated to be fixed in 3.1 based on this PR: https://github.com/cython/cython/pull/6144? I just ran into it in 3.0.11.

**Comment by da-woods** [comment]
#6144 has absolutely nothing to do with this issue.

**Comment by dtczest** [comment]
> #6144 has absolutely nothing to do with this issue.

Oh, interesting. #4810, which fixes this, was closed in favor of #6144 so I made the assumption it was supposed to fix this.

**Comment by da-woods** [comment]
Quite possibly I'm wrong actually. This wasn't the core purpose of #6144 but it looks it might have added code objects to lambdas (mostly to achieve something else).

I'm not sure then. If you have some code that shows the issue it might be worth trying it with the current master branch and seeing - if it is fixed then we can close the issue.

**Comment by scoder** [comment]
Yes, this is fixed as part of https://github.com/cython/cython/pull/6144. The test that I added back in 2020 now passes: https://github.com/cython/cython/commit/ea46cb228e10e0ecb956d2f852f73613a6879c5e

**Comment by dtczest** [comment]
Thank you, @scoder !
