### ISSUE TITLE
Cython 0.29.12: ValueError during test suite on Python 3.6 and musl

### ISSUE THREAD

**Issue by awilfox** [cython/cython#3045]
I'm attempting to package Cython for [Adélie Linux](https://www.adelielinux.org/), which is a Linux distribution that uses the musl libc.  While trying to run the test suite, I'm seeing the following error on ppc64:

```
Unable to find pgen, not compiling formal grammar.
running test
running egg_info
creating Cython.egg-info
writing Cython.egg-info/PKG-INFO
writing dependency_links to Cython.egg-info/dependency_links.txt
writing entry points to Cython.egg-info/entry_points.txt
writing top-level names to Cython.egg-info/top_level.txt
writing manifest file 'Cython.egg-info/SOURCES.txt'
reading manifest file 'Cython.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Doc/*'
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
warning: no files found matching 'pyximport/README'
writing manifest file 'Cython.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-ppc64-3.6/Cython/Plex/Scanners.cpython-36m-powerpc64-linux-gnu.so -> Cython/Plex
copying build/lib.linux-ppc64-3.6/Cython/Plex/Actions.cpython-36m-powerpc64-linux-gnu.so -> Cython/Plex
copying build/lib.linux-ppc64-3.6/Cython/Compiler/Scanning.cpython-36m-powerpc64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc64-3.6/Cython/Compiler/Visitor.cpython-36m-powerpc64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc64-3.6/Cython/Compiler/FlowControl.cpython-36m-powerpc64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc64-3.6/Cython/Runtime/refnanny.cpython-36m-powerpc64-linux-gnu.so -> Cython/Runtime
copying build/lib.linux-ppc64-3.6/Cython/Compiler/FusedNode.cpython-36m-powerpc64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc64-3.6/Cython/Tempita/_tempita.cpython-36m-powerpc64-linux-gnu.so -> Cython/Tempita
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
    **setup_args
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "Cython/Compiler/FlowControl.py", line 1, in init Cython.Compiler.FlowControl
    from __future__ import absolute_import
ValueError: Cython.Compiler.Visitor.TreeVisitor size changed, may indicate binary incompatibility. Expected 40 from C header, got 32 from PyObject
```

And a very similar error on ppc:

```
Unable to find pgen, not compiling formal grammar.
running test
running egg_info
creating Cython.egg-info
writing Cython.egg-info/PKG-INFO
writing dependency_links to Cython.egg-info/dependency_links.txt
writing entry points to Cython.egg-info/entry_points.txt
writing top-level names to Cython.egg-info/top_level.txt
writing manifest file 'Cython.egg-info/SOURCES.txt'
reading manifest file 'Cython.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Doc/*'
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
warning: no files found matching 'pyximport/README'
writing manifest file 'Cython.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-ppc-3.6/Cython/Plex/Scanners.cpython-36m-powerpc-linux-gnu.so -> Cython/Plex
copying build/lib.linux-ppc-3.6/Cython/Plex/Actions.cpython-36m-powerpc-linux-gnu.so -> Cython/Plex
copying build/lib.linux-ppc-3.6/Cython/Compiler/Scanning.cpython-36m-powerpc-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc-3.6/Cython/Compiler/Visitor.cpython-36m-powerpc-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc-3.6/Cython/Compiler/FlowControl.cpython-36m-powerpc-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc-3.6/Cython/Runtime/refnanny.cpython-36m-powerpc-linux-gnu.so -> Cython/Runtime
copying build/lib.linux-ppc-3.6/Cython/Compiler/FusedNode.cpython-36m-powerpc-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-ppc-3.6/Cython/Tempita/_tempita.cpython-36m-powerpc-linux-gnu.so -> Cython/Tempita
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
    **setup_args
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "Cython/Compiler/FlowControl.py", line 1, in init Cython.Compiler.FlowControl
    from __future__ import absolute_import
ValueError: Cython.Compiler.Visitor.TreeVisitor size changed, may indicate binary incompatibility. Expected 20 from C header, got 16 from PyObject
```

**Comment by scoder** [comment]
Hmm, this could suggests a problem in the configuration of the C compiler. The extension module that it built seems to have a different configuration than the CPython runtime, or there's some other mismatch of the configuration between compile time and runtime, which leads to different struct sizes for extension types. Any idea if there's something on the platform that might cause this?

**Comment by phodina** [comment]
Hi,
I'm packaging Cython for [Guix](https://guix.gnu.org/) and I get the same error on x86_64 architecture.

```
starting phase `check'
running "python setup.py" with command "test" and parameters ()
running test
running egg_info
writing Cython.egg-info/PKG-INFO
writing dependency_links to Cython.egg-info/dependency_links.txt
writing entry points to Cython.egg-info/entry_points.txt
writing top-level names to Cython.egg-info/top_level.txt
reading manifest file 'Cython.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
Unable to find pgen, not compiling formal grammar.
warning: no files found matching 'Doc/*'
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
warning: no files found matching 'pyximport/README'
writing manifest file 'Cython.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.8/Cython/Plex/Scanners.cpython-38-x86_64-linux-gnu.so -> Cython/Plex
copying build/lib.linux-x86_64-3.8/Cython/Plex/Actions.cpython-38-x86_64-linux-gnu.so -> Cython/Plex
copying build/lib.linux-x86_64-3.8/Cython/Compiler/Scanning.cpython-38-x86_64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-x86_64-3.8/Cython/Compiler/Visitor.cpython-38-x86_64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-x86_64-3.8/Cython/Compiler/FlowControl.cpython-38-x86_64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-x86_64-3.8/Cython/Runtime/refnanny.cpython-38-x86_64-linux-gnu.so -> Cython/Runtime
copying build/lib.linux-x86_64-3.8/Cython/Compiler/FusedNode.cpython-38-x86_64-linux-gnu.so -> Cython/Compiler
copying build/lib.linux-x86_64-3.8/Cython/Tempita/_tempita.cpython-38-x86_64-linux-gnu.so -> Cython/Tempita
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 228, in <module>
    setup(
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/site-packages/setuptools/command/test.py", line 229, in run
    self.run_tests()
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/site-packages/setuptools/command/test.py", line 247, in run_tests
    test = unittest.main(
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/guix-build-python-cython-0.29.24.drv-0/Cython-0.29.24/Cython/Compiler/Tests/TestFlowControl.py", line 7, in <module>
    from Cython.Compiler.FlowControl import (
  File "Cython/Compiler/FlowControl.py", line 1, in init Cython.Compiler.FlowControl
    from __future__ import absolute_import
ValueError: Cython.Compiler.Visitor.TreeVisitor size changed, may indicate binary incompatibility. Expected 40 from C header, got 32 from PyObject
command "python" "-c" "import setuptools, tokenize;__file__='setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))" "test" failed with status 1
builder for `/gnu/store/4p8lpy5q703wd1gh945hirrri9lgh51l-python-cython-0.29.24.drv' failed with exit code 1
build of /gnu/store/4p8lpy5q703wd1gh945hirrri9lgh51l-python-cython-0.29.24.drv failed
View build log at '/var/log/guix/drvs/4p/8lpy5q703wd1gh945hirrri9lgh51l-python-cython-0.29.24.drv.bz2'.
guix build: error: build of `/gnu/store/4p8lpy5q703wd1gh945hirrri9lgh51l-python-cython-0.29.24.drv' failed
```

If I skip the test the package builds.

@awilfox @scoder could it be due to the `-O3` flag?

```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/gnu/store/9w9jvy3bgjg4qaqmrij01nbppiccqr7c-python-3.8.2/include/python3.8 -c /tmp/guix-build-python-cython-0.29.24.drv-0/Cython-0.29.24/Cython/Compiler/Scanning.c -o build/temp.linux-x86_64-3.8/tmp/guix-build-python-cython-0.29.24.drv-0/Cython-0.29.24/Cython/Compiler/Scanning.o
```
