### ISSUE TITLE
Possible cython issue with NumPy/SciPy/MatPlotLib/Pandas (possibly pre-release only)

### ISSUE THREAD

**Issue by annalisasnow** [cython/cython#3131]
Good day, I have been trying to install NumPy pre-release, using pip. I am doing that, while testing Python 3.8, which is in beta currently. I don't use virtualenv, I am using ``` Python 3.8.0b4 ``` and pip ```pip 19.2.3```. Python 3.8 is set to be System Interpreter, for the sake of testing.

I also can install ``` Cython ``` with simple: ``` pip install cython ``` and it succeeds.

However if I try ``` $ pip install git+https://github.com/numpy/numpy.git ``` for instance I get:
```
Collecting git+https://github.com/numpy/numpy.git
  Cloning https://github.com/numpy/numpy.git to /private/var/folders/w9/vqby68j57n98vmlc6hk591vm0000gn/T/pip-req-build-0zpbjpo8
  Running command git clone -q https://github.com/numpy/numpy.git /private/var/folders/w9/vqby68j57n98vmlc6hk591vm0000gn/T/pip-req-build-0zpbjpo8
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... error
```

And finally the error:

```
command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w9/vqby68j57n98vmlc6hk591vm0000gn/T/pip-build-env-5hxny6jy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython
       cwd: None
  Complete output (23 lines):
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
  Collecting cython
  Installing collected packages: setuptools, wheel, cython
  ERROR: Exception:
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in main
      status = self.run(options, args)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 398, in run
      installed = install_given_reqs(
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 54, in install_given_reqs
      requirement.install(
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 925, in install
      self.move_wheel_files(
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 453, in move_wheel_files
      wheel.move_wheel_files(
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/wheel.py", line 324, in move_wheel_files
      scheme = distutils_scheme(
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/locations.py", line 104, in distutils_scheme
      assert not (home and prefix), "home={} prefix={}".format(home, prefix)
  AssertionError: home=/private/var/folders/w9/vqby68j57n98vmlc6hk591vm0000gn/T/pip-target-qb0qk201 prefix=/private/var/folders/w9/vqby68j57n98vmlc6hk591vm0000gn/T/pip-build-env-5hxny6jy/overlay
  ----------------------------------------
ERROR: Command errored out with exit status 2: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w9/vqby68j57n98vmlc6hk591vm0000gn/T/pip-build-env-5hxny6jy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython Check the logs for full command output.
```
If I try one of the interim commands:
```
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w9/vqby68j57n98vmlc6hk591vm0000gn/T/pip-build-env-oepwn_cy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython
```
I still get the errors. At the same time, I can install NumPy, SciPy, MatPlotLib, Pandas of different versions (release versions and pre-release, as well) by loading them, building and installing manually.

**Comment by scoder** [comment]
This doesn't really look like an issue specifically with Cython, more like something's wrong in your system setup.
