### ISSUE TITLE
Cannot create NumPy long double arrays with mingw

### ISSUE THREAD

**Issue by david-cortes** [cython/cython#3136]
Following code will produce an error when compiled with mingw32 from anaconda in windows:
```python
import numpy as np
cimport numpy as np
import ctypes

def get_arr():
    cdef np.ndarray[long double, ndim=1] outp = np.zeros(10, dtype=ctypes.c_longdouble)
    return outp
```
setup.py:
```python
try:
	from setuptools import setup
except:
	from distutils.core import setup
import numpy as np
from distutils.extension import Extension
from Cython.Distutils import build_ext

setup(
    name  = "cyext",
    packages = ["cyext"],
    cmdclass = {'build_ext': build_ext},
    ext_modules = [Extension("cyext", sources=["cyfile.pyx"], include_dirs=[np.get_include()])]
    )
```
```python
>>> import cyext
>>> cyext.get_arr()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cyfile.pyx", line 6, in cyext.get_arr
    cdef np.ndarray[long double, ndim = 1] outp = np.zeros(10, dtype = ctypes.c_longdouble)
ValueError: Buffer dtype mismatch, expected 'long double' but got 'double'
```

**Comment by scoder** [comment]
You should probably use the correct NumPy dtype, not anything from ctypes.

**Comment by david-cortes** [comment]
> You should probably use the correct NumPy dtype, not anything from ctypes.

Still throws the same error:
```python
import numpy as np
cimport numpy as np
import ctypes

def get_arr():
	cdef np.ndarray[long double, ndim = 1] outp = np.zeros(10, dtype = np.longdouble)
	return outp
```
```python
import cyext
cyext.get_arr()
```
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cyfile.pyx", line 6, in cyext.get_arr
    cdef np.ndarray[long double, ndim = 1] outp = np.zeros(10, dtype = np.longdouble)
ValueError: Item size of buffer (8 bytes) does not match size of 'long double' (16 bytes)
```
