### ISSUE TITLE
Trouble figuring out how to use -s include_path=... when calling python3 -m Cython.Build.cythonize stanalone

### ISSUE THREAD

**Issue by jtc0de** [cython/cython#3168]
This might be just me doing things wrong, but I have trouble figuring out how to use the command line option `-s include_path=...` when calling `python3 -m Cython.Build.cythonize` for a standalone compilation in a separate process (to work around bug https://github.com/cython/cython/issues/2730 ).

I tried these two calls:

1. As a list: `/usr/bin/python3 -m Cython.Build.Cythonize /tmp/pip-req-build-liyrbm_y/src/wobblui/dragselection.pyx -s include_path=['/tmp/pip-req-build-liyrbm_y/src'] -s gdb_debug=False -X always_allow_keywords=True -X boundscheck=True -X language_level=3 -X profile=False -X linetrace=False`

2. As a string: `/usr/bin/python3 -m Cython.Build.Cythonize /tmp/pip-req-build-zl7im29r/src/wobblui/dragselection.pyx -s include_path=/tmp/pip-req-build-zl7im29r/src -s gdb_debug=False -X always_allow_keywords=True -X boundscheck=True -X language_level=3 -X profile=False -X linetrace=False`

Both give me this error, where Cython seems to become confused accessing the include directories internally:

```
  ERROR: Traceback (most recent call last):
  ERROR:   File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
  ERROR:     "__main__", mod_spec)
  ERROR:   File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
  ERROR:     exec(code, run_globals)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Cythonize.py", line 227, in <module>
  ERROR:     main()
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Cythonize.py", line 223, in main
  ERROR:     cython_compile(path, options)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Cythonize.py", line 106, in cython_compile
  ERROR:     **options.options)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
  ERROR:     aliases=aliases)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Dependencies.py", line 824, in create_extension_list
  ERROR:     kwds = deps.distutils_info(file, aliases, base).values
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Dependencies.py", line 679, in distutils_info
  ERROR:     return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Dependencies.py", line 689, in transitive_merge
  ERROR:     node, extract, merge, seen, {}, self.cimported_files)[0]
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Dependencies.py", line 700, in transitive_merge_helper
  ERROR:     for next in outgoing(node):
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Utils.py", line 54, in wrapper
  ERROR:     res = cache[args] = f(self, *args)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Dependencies.py", line 601, in cimported_files
  ERROR:     pxd_file = self.find_pxd(module, filename)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Utils.py", line 54, in wrapper
  ERROR:     res = cache[args] = f(self, *args)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Build/Dependencies.py", line 583, in find_pxd
  ERROR:     pxd = self.context.find_pxd_file(relative, None)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Compiler/Main.py", line 250, in find_pxd_file
  ERROR:     pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=sys_path)
  ERROR:   File "/tmp/pip-build-env-c95g9yn8/overlay/lib64/python3.7/site-packages/Cython/Compiler/Main.py", line 292, in search_include_directories
  ERROR:     include_dirs = include_dirs + sys.path
  ERROR: TypeError: unsupported operand type(s) for +: 'bool' and 'list'
```

**Comment by WilkAndy** [comment]
I get this too

**Comment by etc0de** [comment]
I think a workaround is to call `python3 -c "from Cython.Build import cythonize; import sys; # ... use sys.argv[1] and cythonize(...arguments...) to do call..."` but I find that considerably more ugly. Hence it'd be nice if supporting this argument via standalone was supported. Is there some more info I could provide to help with fixing this?

**Comment by KimiNewt** [comment]
Any progress with this? Seems easy enough to allow the options that are passed to be other than booleans, or else to allow passing includes directly
