### ISSUE TITLE
Python 3.7 Windows debug build fails

### ISSUE THREAD

**Issue by Dekken** [cython/cython#3185]
Install fresh python 3.7.4 with debug

run:

```
call vcvars64.bat
SET DISTUTILS_USE_SDK=1

python_d -m pip install pip --upgrade
python_d -m pip install wheel
python_d -m pip install cython
python_d setup.py bdist_wheel  # numpy from source
Running from numpy source directory.
C:\pro\py\37d\lib\site-packages\setuptools\depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Cythonizing sources
numpy/random\bounded_integers.pxd.in has not changed
Processing numpy/random\bit_generator.pyx
Traceback (most recent call last):
  File "C:\pro\py\37d\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\pro\py\37d\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\pro\py\37d\lib\site-packages\cython.py", line 16, in <module>
    from Cython.Compiler.Main import main
  File "C:\pro\py\37d\lib\site-packages\Cython\Compiler\Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
ImportError: Module use of python37.dll conflicts with this version of Python.
Traceback (most recent call last):
  File "D:\git\numpy-1.17.2\tools\cythonize.py", line 243, in <module>
    main()
  File "D:\git\numpy-1.17.2\tools\cythonize.py", line 239, in main
    find_process_files(root_dir)
  File "D:\git\numpy-1.17.2\tools\cythonize.py", line 230, in find_process_files
    process(root_dir, fromfile, tofile, function, hash_db)
  File "D:\git\numpy-1.17.2\tools\cythonize.py", line 196, in process
    processor_function(fromfile, tofile)
  File "D:\git\numpy-1.17.2\tools\cythonize.py", line 86, in process_pyx
    [sys.executable, '-m', 'cython'] + flags + ["-o", tofile, fromfile])
  File "C:\pro\py\37d\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\pro\\py\\37d\\python_d.exe', '-m', 'cython', '-3', '--fast-fail', '-o', 'bit_generator.c', 'bit_generator.pyx']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "setup.py", line 443, in <module>
    setup_package()
  File "setup.py", line 426, in setup_package
    generate_cython()
  File "setup.py", line 234, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
```

**Comment by mattip** [comment]
Does pip understand how to install debug versions of wheel packages? I think you need to build each package from source, so you should be using `pip install --no-binary :all: cython`.

**Comment by scoder** [comment]
That, or switch to Python 3.8, in which regular extension modules are ABI compatible with debug builds. I don't see this being a problem in Cython specifically.
