### ISSUE TITLE
Templated constructors

### ISSUE THREAD

**Issue by mje-nz** [cython/cython#3198]
This was [reported on the mailing list](https://mail.python.org/pipermail/cython-devel/2016-February/004674.html) a few years ago but I can't see an issue for it.

```cython
cdef extern from "<any>" namespace "std" nogil: 
    cdef cppclass any: 
        any() 
        any(const any& other) except + 
        any[ValueType](ValueType value) except + 
 
cdef any a 
```

```
Error compiling Cython file:
------------------------------------------------------------
...
cdef extern from "<any>" namespace "std" nogil:
    cdef cppclass any:
        any()
        any(const any& other) except +
        any[ValueType](ValueType value) except +
                    ^
------------------------------------------------------------

test.pyx:5:21: undeclared name not builtin: ValueType

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern from "<any>" namespace "std" nogil:
    cdef cppclass any:
        any()
        any(const any& other) except +
        any[ValueType](ValueType value) except +
                    ^
------------------------------------------------------------

test.pyx:5:21: Array dimension not integer

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern from "<any>" namespace "std" nogil:
    cdef cppclass any:
        any()
        any(const any& other) except +
        any[ValueType](ValueType value) except +
                      ^
------------------------------------------------------------

test.pyx:5:23: 'ValueType' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern from "<any>" namespace "std" nogil:
    cdef cppclass any:
        any()
        any(const any& other) except +
        any[ValueType](ValueType value) except +
                     ^
------------------------------------------------------------

test.pyx:5:22: Missing name in declaration.
```

Yury's workaround works:
```cython
cdef extern from "<any>" namespace "std" nogil: 
    cdef cppclass any: 
        any() 
        any(const any& other) except + 
        any any[ValueType](ValueType value) except + 
 
cdef any a 
```

**Comment by McSinyx** [comment]
How can this constructor be used then?  `any[int](42)` does not seem to work.

**Comment by mje-nz** [comment]
Could you post example code showing what you're trying to do?

**Comment by McSinyx** [comment]
Sure, if I modify [alure.pxd](https://github.com/McSinyx/palace/blob/1d230d3bd44b0c1f035b5a029f137f7fb2fd1b80/alure.pxd#L32) to fit [the header](https://en.cppreference.com/w/cpp/header/chrono) (`template <class Rep2> constexpr explicit duration(const Rep2& r);`):
```cython
cdef extern from '<chrono>' namespace 'std::chrono' nogil:
    cdef cppclass duration[Rep, Period=*]:
        ctypedef Rep rep
        duration() except +
        Rep2 duration[Rep2](const Rep2&) except +
        rep count() except +

    ctypedef duration[int64_t, nano] nanoseconds
    ctypedef duration[int64_t, milli] milliseconds
```
and [call it with](https://github.com/McSinyx/palace/blob/1d230d3bd44b0c1f035b5a029f137f7fb2fd1b80/palace.pyx#L506)
```cython
cimport alure

cdef class Source:
    cdef alure.Source impl

    def fade_out_to_stop(self, gain: float, ms: int) -> None:
        self.impl.fade_out_to_stop(gain, alure.milliseconds(ms))
```
I get this
```
Compiling palace.pyx because it changed.
[1/1] Cythonizing palace.pyx
warning: alure.pxd:308:8: 'Basic' redeclared 
warning: alure.pxd:309:8: 'Full' redeclared 
warning: alure.pxd:310:8: 'Capture' redeclared 
warning: alure.pxd:313:8: 'Basic' redeclared 
warning: alure.pxd:314:8: 'Full' redeclared 
running install
running bdist_egg
running egg_info
writing palace.egg-info/PKG-INFO
writing dependency_links to palace.egg-info/dependency_links.txt
writing top-level names to palace.egg-info/top_level.txt
reading manifest file 'palace.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'palace.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'palace' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/AL/ -I/usr/include/python3.7m -c palace.cpp -o build/temp.linux-x86_64-3.7/palace.o
palace.cpp: In function ‘PyObject* __pyx_pf_6palace_6Source_8fade_out_to_stop(__pyx_obj_6palace_Source*, double, PyObject*)’:
palace.cpp:7172:74: error: no matching function for call to ‘std::chrono::duration<long int, std::ratio<1, 1000> >::duration(PyObject* const&)’
 7172 |     __pyx_t_1 = std::chrono::milliseconds(((PyObject *const &)__pyx_v_ms));
      |                                                                          ^
In file included from palace.cpp:689:
/usr/include/c++/9/chrono:338:14: note: candidate: ‘template<class _Rep2, class _Period2, class> constexpr std::chrono::duration<_Rep, _Period>::duration(const std::chrono::duration<_Rep, _Period>&)’
  338 |    constexpr duration(const duration<_Rep2, _Period2>& __d)
      |              ^~~~~~~~
/usr/include/c++/9/chrono:338:14: note:   template argument deduction/substitution failed:
palace.cpp:7172:74: note:   mismatched types ‘const std::chrono::duration<_Rep1, _Period1>’ and ‘PyObject* const’ {aka ‘_object* const’}
 7172 |     __pyx_t_1 = std::chrono::milliseconds(((PyObject *const &)__pyx_v_ms));
      |                                                                          ^
In file included from palace.cpp:689:
/usr/include/c++/9/chrono:331:23: note: candidate: ‘template<class _Rep2, class> constexpr std::chrono::duration<_Rep, _Period>::duration(const _Rep2&)’
  331 |    constexpr explicit duration(const _Rep2& __rep)
      |                       ^~~~~~~~
/usr/include/c++/9/chrono:331:23: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/9/bits/move.h:55,
                 from /usr/include/c++/9/bits/nested_exception.h:40,
                 from /usr/include/c++/9/exception:144,
                 from /usr/include/c++/9/ios:39,
                 from palace.cpp:680:
/usr/include/c++/9/type_traits: In substitution of ‘template<class ... _Cond> using _Require = typename std::enable_if<std::__and_< <template-parameter-1-1> >::value>::type [with _Cond = {std::is_convertible<_object* const&, long int>, std::__or_<std::chrono::treat_as_floating_point<long int>, std::__not_<std::chrono::treat_as_floating_point<_object*> > >}]’:
/usr/include/c++/9/chrono:328:27:   required from here
/usr/include/c++/9/type_traits:2054:11: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
 2054 |     using _Require = typename enable_if<__and_<_Cond...>::value>::type;
      |           ^~~~~~~~
In file included from palace.cpp:689:
/usr/include/c++/9/chrono:324:2: note: candidate: ‘constexpr std::chrono::duration<_Rep, _Period>::duration(const std::chrono::duration<_Rep, _Period>&) [with _Rep = long int; _Period = std::ratio<1, 1000>]’
  324 |  duration(const duration&) = default;
      |  ^~~~~~~~
/usr/include/c++/9/chrono:324:11: note:   no known conversion for argument 1 from ‘PyObject* const’ {aka ‘_object* const’} to ‘const std::chrono::duration<long int, std::ratio<1, 1000> >&’
  324 |  duration(const duration&) = default;
      |           ^~~~~~~~~~~~~~~
/usr/include/c++/9/chrono:322:12: note: candidate: ‘std::chrono::duration<_Rep, _Period>::duration() [with _Rep = long int; _Period = std::ratio<1, 1000>]’
  322 |  constexpr duration() = default;
      |            ^~~~~~~~
/usr/include/c++/9/chrono:322:12: note:   candidate expects 0 arguments, 1 provided
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

If I change the call to `alure.milliseconds[int64_t](ms)`, this is raised:
```
Compiling palace.pyx because it changed.
[1/1] Cythonizing palace.pyx
warning: alure.pxd:308:8: 'Basic' redeclared 
warning: alure.pxd:309:8: 'Full' redeclared 
warning: alure.pxd:310:8: 'Capture' redeclared 
warning: alure.pxd:313:8: 'Basic' redeclared 
warning: alure.pxd:314:8: 'Full' redeclared 

Error compiling Cython file:
------------------------------------------------------------
...

        Fading is updated during calls to `Context.update`,
        which should be called regularly (30 to 50 times per second)
        for the fading to be smooth.
        """
        self.impl.fade_out_to_stop(gain, alure.milliseconds[int64_t](ms))
                                                          ^
------------------------------------------------------------

palace.pyx:529:59: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(palace.pyx:30:0)
StatListNode.stats[20] = StatListNode(palace.pyx:472:5)
StatListNode.stats[0] = CClassDefNode(palace.pyx:472:5,
    as_name = 'Source',
    class_name = 'Source',
    doc = "Sound source for playing audio.\n\n    There is no practical limit to the number of sources one may create.\n\n    When the source is no longer needed, `destroy` must be called,\n    unless the context manager is used, which guarantees the source's\n    destructioni upon completion of the block, even if an error occurs.\n\n    Parameters\n    ----------\n    context : Context\n        The context from which the source is to be created.\n    ",
    module_name = '',
    punycode_class_name = 'Source',
    visibility = 'private')
CClassDefNode.body = StatListNode(palace.pyx:473:4)
StatListNode.stats[4] = DefNode(palace.pyx:507:4,
    doc = 'Fade the source to `gain` over `ms` milliseconds,\n        at which point playback will stop. `gain` is in addition to\n        the base gain, and must be greater than 0 and less than 1.\n        `ms` must also be positive\n\n        The fading is logarithmic. As a result, the initial drop-off may\n        happen faster than expected but the fading is more perceptually\n        consistant over the given duration. It will take just as much\n        time to go from -6 dB to -12 dB as it will to go from -40 dB\n        to -46 dB, for example.\n\n        Pending playback from a future buffer is not immediately\n        canceled, but the fade timer starts with this call. If the\n        future buffer then becomes ready, it will start mid-fade.\n        Pending playback will be canceled if the fade out completes\n        before the future buffer becomes ready.\n\n        Fading is updated during calls to `Context.update`,\n        which should be called regularly (30 to 50 times per second)\n        for the fading to be smooth.\n        ',
    modifiers = [...]/0,
    name = 'fade_out_to_stop',
    np_args_idx = [...]/0,
    num_required_args = 3,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 389, in analyse_expressions: StatListNode(palace.pyx:508:8)
File 'Nodes.py', line 5300, in analyse_expressions: ExprStatNode(palace.pyx:529:34)
File 'ExprNodes.py', line 587, in analyse_expressions: SimpleCallNode(palace.pyx:529:34,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 5596, in analyse_types: SimpleCallNode(palace.pyx:529:34,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 5556, in analyse_types: SimpleCallNode(palace.pyx:529:68,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 5464, in analyse_as_type_constructor: SimpleCallNode(palace.pyx:529:68,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 3485, in analyse_as_type: IndexNode(palace.pyx:529:59,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)
File 'Nodes.py', line 1156, in analyse: TemplatedTypeNode(palace.pyx:529:59)

Compiler crash traceback from this point on:
  File "/home/cnx/.local/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 1156, in analyse
    if len(self.positional_args) > 1 or self.keyword_args.key_value_pairs:
AttributeError: 'NoneType' object has no attribute 'key_value_pairs'
Traceback (most recent call last):
  File "./setup.py", line 39, in <module>
    c_string_type='str', c_string_encoding='utf8')),
  File "/home/cnx/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1098, in cythonize
    cythonize_one(*args)
  File "/home/cnx/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1221, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: palace.pyx
```

**Comment by mje-nz** [comment]
Okay, I can't get your project to build on my machine, but the workaround in this issue is:

```cpp
duration duration[Rep2](const Rep2&) except +
```

not 

```cpp
Rep2 duration[Rep2](const Rep2&) except +
```

**Comment by McSinyx** [comment]
Oops sorry my mistake, but correcting it still gives the same/similar error.  In my case however it is OK to use the current hack (`duration(const rep&) except +`) though.
