### ISSUE TITLE
Is the type checking can be disabled for the default argument with type hint?

### ISSUE THREAD

**Issue by tedyu002** [cython/cython#3231]
Cython Version: 0.29.14

```
class Test:
   pass
def test(q:str = Test()):
   pass
```
After this code is cythonize and running.
The error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 24, in init test
TypeError: Expected unicode, got Test
```
appeared.

I have tries the compiler directive but no one can resolve this.

Since it's the usage of the FastAPI to declare the type and produces OpenAPI information.
We cannot ignore the type information.
```
@app.get("/items/")
async def read_items(q: str = Query(None, max_length=50)):
    results = {"items": [{"item_id": "Foo"}, {"item_id": "Bar"}]}
    if q:
        results.update({"q": q})
    return results
```

Thanks.

**Comment by da-woods** [comment]
https://github.com/cython/cython/issues/1672

> I have tries the compiler directive but no one can resolve this.

I assume you mean `#cython: annotation_typing=False`? Because it works for me.

**Comment by da-woods** [comment]
With that said, `annotation_typing` wasn't documented so I created a tiny pull request to fix this: https://github.com/cython/cython/pull/3232

**Comment by scoder** [comment]
Your code example does not comply with PEP-484, unless you use something like `# type: ignore`. However, Cython does not currently understand this. We should honour the normal PEP-484 mechanisms here for [disregarding type annotations](https://www.python.org/dev/peps/pep-0484/#compatibility-with-other-uses-of-function-annotations).
