### ISSUE TITLE
Cython 0.29.14 breaks matplotlib

### ISSUE THREAD

**Issue by moubctez** [cython/cython#3269]
Matplotlib built with Cython 0.29.14 (through Numpy) ends with undefinied symbols
```
$ python3.7 -c 'import matplotlib.dates'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/pkg/lib/python3.7/site-packages/matplotlib/dates.py", line 159, in <module>
      import matplotlib.ticker as ticker
    File "/usr/pkg/lib/python3.7/site-packages/matplotlib/ticker.py", line 174, in <module>
      from matplotlib import transforms as mtransforms
    File "/usr/pkg/lib/python3.7/site-packages/matplotlib/transforms.py", line 43, in <module>
      from matplotlib._path import (
  ImportError: /usr/pkg/lib/python3.7/site-packages/matplotlib/_path.so: Undefined symbol "MPL_matplotlib_backends__tkagg_ARRAY_API" (symnum = 27)
```

Reverting this change fixes the problem:
https://github.com/cython/cython/commit/01e00f6cb9ac77d26f92da777d25cebef748eaa7

The issue has been documented here:
https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=54712

Please, fix. :)

**Comment by scoder** [comment]
Thanks for the report. Matplotlib is one of the Python data processing packages that I know does not use Cython at all. Any idea where this issue comes from? What happens at build time that brings Cython into the game and might cause this?

**Comment by mattip** [comment]
Maybe somehow netbsd modifies the linking flags, so that using the original distutil's `build_extensions` command rather than cython's somehow causes the [`_path` c-extension module](https://github.com/matplotlib/matplotlib/blob/v2.2.0/setupext.py#L1365) to be linked differently? Note that for the upcoming matplotlib v3.2, the [`_path` module build](https://github.com/matplotlib/matplotlib/blob/v3.2.0rc3/setupext.py#L698) changed.

In order to reproduce the exact interaction between cython, numpy, and matplotlib on netbsd more infrormation is necessary. Even better would be a way to reproduce this, perhaps via a docker container of a specific version of netbsd, the version of numpy and matplotlib in play.
