### ISSUE TITLE
Treat nullptr_t as CNullPtrType

### ISSUE THREAD

**Issue by navytux** [cython/cython#3314]
Hello up there. I hit Cython bug where `nullptr` is not treated exactly as `NULL`. Please find below a short example that demonstrates the problem. Thanks beforehand, Kirill.

--------

The following module compiles just fine:

```pyx
# distutils: language=c++
# cython: language_level=2

cdef cppclass MyClass nogil:
    int* p

    __init__():
        this.p = NULL
```

However the following one fails:

```pyx
# distutils: language=c++
# cython: language_level=2

from libcpp cimport nullptr

cdef cppclass MyClass nogil:
    int* p

    __init__():
        this.p = nullptr     # NOTE nullptr instead of NULL
```

```
$ cythonize -i nullcxx.pyx 
Compiling /home/kirr/tmp/trashme/nullcxx.pyx because it changed.
[1/1] Cythonizing /home/kirr/tmp/trashme/nullcxx.pyx

Error compiling Cython file:
------------------------------------------------------------
...

cdef cppclass MyClass nogil:
    int* p

    __init__():
        this.p = nullptr
                ^
------------------------------------------------------------

nullcxx.pyx:10:17: Cannot assign type 'nullptr_t' to 'int *'
Traceback (most recent call last):
  File "/home/kirr/src/wendelin/venv/z-dev/bin/cythonize", line 11, in <module>
    load_entry_point('Cython', 'console_scripts', 'cythonize')()
  File "/home/kirr/src/tools/py/cython/Cython/Build/Cythonize.py", line 224, in main
    cython_compile(path, options)
  File "/home/kirr/src/tools/py/cython/Cython/Build/Cythonize.py", line 77, in cython_compile
    **options.options)
  File "/home/kirr/src/tools/py/cython/Cython/Build/Dependencies.py", line 1098, in cythonize
    cythonize_one(*args)
  File "/home/kirr/src/tools/py/cython/Cython/Build/Dependencies.py", line 1221, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/kirr/tmp/trashme/nullcxx.pyx
```

Cython version: `0.29.14-629-ga73815042` (today's master)

Possibly related issue: https://github.com/cython/cython/issues/3020

**Comment by mxmlnkn** [comment]
I have the same issue. It's weird that `nullptr` can be imported but is basically useless because of this.

**Comment by da-woods** [comment]
I think we'd need to make `CNullPtrType` available in the `cython` cimport module and then we could set the type of `nullptr` to that rather than to `void*`. PR welcome
