### ISSUE TITLE
TypeError on list += str

### ISSUE THREAD

**Issue by dscunkel** [cython/cython#3426]
When run via CPython the following function:

```
def appendinline():
    y = []
    y += 'ab'
    return y
```
returns `['a', 'b']`, but when compiled with Cython (0.29.13) the result is
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "concat.py", line 11, in concat.appendinline
    y += 'ab'
TypeError: must be str, not list
```
list +=, like extend, ordinarily accepts any iterable, not just a list.

The following functions work correctly when compiled with Cython, however:
```
def appendchars(x):
    x += 'hello'

def appendto(x):
    y = []
    y += x
    return y
```

The overly restrictive check seems to trigger only if both the target list and the argument to += are local to the function.

**Comment by da-woods** [comment]
I'm struggling to reproduce this (on Cython 0.29.13 -> master). Are you using any compiler directives/options that might be relevant?

**Comment by dscunkel** [comment]
I'm building a module with cythonize -i, using Cython 0.29.13 and then importing that module into CPython 3.7.6.

```
Thu Mar 12 17:46:26 cunkel@cunkel:~/misc
1017$ cat concat.py 
def appendchars(x):
    x += 'hello'

def appendto(x):
    y = []
    y += x
    return y

def appendinline():
    y = []
    y += 'ab'
    return y
Thu Mar 12 17:46:30 cunkel@cunkel:~/misc
1018$ cythonize -3 -i concat.py
Compiling /home/cunkel/misc/concat.py because it changed.
[1/1] Cythonizing /home/cunkel/misc/concat.py
running build_ext
building 'concat' extension
creating /home/cunkel/misc/tmpk25abxp1/home
creating /home/cunkel/misc/tmpk25abxp1/home/cunkel
creating /home/cunkel/misc/tmpk25abxp1/home/cunkel/misc
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.7m -c /home/cunkel/misc/concat.c -o /home/cunkel/misc/tmpk25abxp1/home/cunkel/misc/concat.o
gcc -pthread -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g /home/cunkel/misc/tmpk25abxp1/home/cunkel/misc/concat.o -L/usr/lib64 -lpython3.7m -o /home/cunkel/misc/concat.cpython-37m-x86_64-linux-gnu.so
Thu Mar 12 17:46:36 cunkel@cunkel:~/misc
1019$ python
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import concat
>>> concat.__file__
'/home/cunkel/misc/concat.cpython-37m-x86_64-linux-gnu.so'
>>> concat.appendchars([])
>>> concat.appendto('abc')
['a', 'b', 'c']
>>> concat.appendinline()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "concat.py", line 11, in concat.appendinline
    y += 'ab'
TypeError: must be str, not list
>>> 
```

```
1024$ cython --version
Cython version 0.29.13
Fri Mar 13 11:39:48 cunkel@cunkel:~/misc
1025$ python --version
Python 3.7.6
```

I can try building Cython master from source and seeing if I can still reproduce.

**Comment by da-woods** [comment]
Thanks - can now reproduce. It's the `-3` that makes the difference (i.e. it know what to do with bytes but not with unicode)

**Comment by scoder** [comment]
Thanks for the report @dscunkel and the analysis @da-woods. I think adding an additional type check in a new specialised macro might fix this. Either that, or disabling the optimisation if the LHS isn't known to be a unicode string, since this is actually an incorrect optimisation in general.

PR welcome.
