### ISSUE TITLE
SciPy build breaks with 3.0a4

### ISSUE THREAD

**Issue by ilayn** [cython/cython#3581]
Since not knowing much about the internals of Cython, I'd like to just draw your attention to our recent Cython related build fails in hope that you might actually spot something obvious

The summary is given in https://github.com/scipy/scipy/issues/12037 but so far we haven't find the actual cause for this. Just replicating the error as an example of many similar ones

```bash
Processing scipy/ndimage/src/_cytest.pyx
Processing scipy/ndimage/src/_ni_label.pyx
Processing scipy/optimize/_bglu_dense.pyx

Error compiling Cython file:
------------------------------------------------------------
...

        with nogil:
            while PyArray_ITER_NOTDONE(iti):
                # Optimization - for 2D, line_buffer becomes next iteration's
                # neighbor buffer
                if output.ndim == 2:
                        ^
------------------------------------------------------------

_ni_label.pyx:313:25: Calling gil-requiring function not allowed without gil
Processing scipy/optimize/_group_columns.pyx
Traceback (most recent call last):
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 305, in <module>
    main()
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 301, in main
    find_process_files(root_dir)
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 290, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/mnt/c/Users/treddy/github_projects/spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-6.5.0/python-3.7.4-65ohvllfnv7y2kaul5mcz3hg7cppcbby/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/mnt/c/Users/treddy/github_projects/spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-6.5.0/python-3.7.4-65ohvllfnv7y2kaul5mcz3hg7cppcbby/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 290, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 229, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 94, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
```

Does this look familiar enough to point to any recent changes ?

**Comment by scoder** [comment]
@mattip `PyArray_NDIM()` is not declared with `nogil` in https://github.com/numpy/numpy/pull/16170. I assume that's intentional?

**Comment by scoder** [comment]
… and thanks for the report @ilayn.

**Comment by ilayn** [comment]
I guess @mattip and @tylerjereddy is on top of this problem so I'm closing this one 

Xref : https://github.com/scipy/scipy/pull/12047

**Comment by mattip** [comment]
> @mattip `PyArray_NDIM()` is not declared with `nogil` in [numpy/numpy#16170](https://github.com/numpy/numpy/pull/16170). I assume that's intentional?

No, it was an oversight. Updated, thanks!
