### ISSUE TITLE
cython3.0: 3x compile-time regression compared to 0.29  ; steady growth of compilation time from release to release

### ISSUE THREAD

**Issue by navytux** [cython/cython#3646]
Hello up there. I'm considering to use Cython instead of Python for all files in my projects. Even though Cython parses and compiles plain .py files just fine, and with [fast C compiler](https://bellard.org/tcc/) the time of  `.c -> .so` phase is not an issue, I've noticed that the time for `.pyx -> .c` phase is _much slower_ compared to C compiler, and also that Cython3.0 brings in **3x** slowdown in compilation speed compared to 0.29x.
Please find details below:

Let's consider the following minimal module:

```pyx
# cython: language_level=2
cdef int myfunc(int x):
    y = x
    return y
```

On my computer the time it takes to `.pyx -> .c` it (best of 5) with cython 0.29.19 is **0.23s**, while with cython 3.0a5 it takes **0.63s** for the same operation. With 3.0a5 generated .c file has 3031 lines and with tcc for `.c -> .so` phase it takes only **0.02s** (i.e **_30_ times faster compared to cythonning**) to compile and link it into python module:

```
$ cython --version
Cython version 3.0a5
```
```
$ time cython x.pyx 

real    0m0,639s
user    0m0,578s
sys     0m0,059s
```
```
$ wc -l x.c
3031 x.c
```
```
$ head -1 x.c
/* Generated by Cython 3.0a5 */
```
```
$ time tcc -pthread -DNDEBUG -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing \
           -Wdate-time -fPIC -I/usr/include/python2.7  -shared x.c -o x.so

real    0m0,020s
user    0m0,012s
sys     0m0,008s
```

I've looked around a bit and checked all Cython releases from 2007 regarding compilation time of this simple module and it shows steady increase for Cython release to release with 3x jump at tail for upcoming 3.0 and overall 30x slowdown compared to the point when Cython was originlly forked from Pyrex:

![Cython2007-2020](https://lab.nexedi.com/kirr/misc/raw/5561198/pyx/cython2007-2020.png)

<details>
 <summary>Compilation time by release</summary>

| version | date | t(s,5-best) | wc-l | 
| --- | --- | --- | --- |
| 0.9.6.5       | 2007.08               | **0.02** |                 213 |
| 0.9.6.10      | 2007.12               | 0.03 |                 472 |
| 0.9.6.14      | 2008.05               | 0.04 |                 482 |
| 0.9.8.1.1     | 2008.08               | 0.06 |                 639 |
| 0.10.3        | 2008.12               | 0.06 |                 676 |
| 0.11.3        | 2009.09               | 0.06 |                1111 |
| 0.12.1        | 2010.02               | 0.07 |                1180 |
| 0.13          | 2010.08               | 0.08 |                1117 |
| 0.14.1        | 2011.02               | 0.08 |                1153 |
| 0.15.1        | 2011.09               | 0.12 |                1207 |
| 0.16          | 2012.04               | 0.12 |                1369 |
| 0.17.4        | 2013.01               | 0.12 |                1361 |
| 0.18          | 2013.01               | 0.12 |                1348 |
| 0.19.2        | 2013.10               | 0.13 |                1731 |
| 0.20.2        | 2014.06               | 0.13 |                1470 |
| 0.21.2        | 2014.12               | 0.13 |                1329 |
| 0.22.1        | 2015.06               | 0.13 |                1376 |
| 0.23.5        | 2016.03               | 0.19 |                1588 |
| 0.24.1        | 2016.07               | 0.20 |                1638 |
| 0.25.2        | 2016.12               | 0.21 |                1797 |
| 0.26.1        | 2017.08               | 0.21 |                1916 |
| 0.27.3        | 2017.11               | 0.22 |                2204 |
| 0.28.6        | 2018.11               | 0.22 |                2382 |
| 0.29.12       | 2019.07               | 0.23 |                2512 |
| 0.29.19       | 2020.05               | 0.23 |                2518 |
| 3.0a1         | 2020.04               |**0.63** |                2948 |
| 3.0a5         | 2020.05               |**0.63** |                3031 |

</details>

It would be good to fix that 3x slowdown regression in upcoming Cython3.0. It would be also good to improve Cython compilation time further so that it goes back to be comparable to the time it takes to compile and link `.c -> .so`.

For the record, here is what I currently [get](https://lab.nexedi.com/kirr/cython/commit/562befd3) for [pystone.py](https://github.com/python/cpython/blob/v2.7.18-0-g8d21aa21f2c/Lib/test/pystone.py) translated by Cython and different compilers:

wc -l pystone.py -> 270 lines
wc -l pystone.c created by cython pystone.py -> 11301 lines

benchmarks for compilers (*)

```
name                 op/s
gcccompile           0.53 ± 0%
gcclink              0.02 ± 0%
gcccompile+link      0.55 ± 0%
gcccompile+linkO2    2.29 ± 0%
clangcompile         0.34 ± 0%
clanglink            0.03 ± 0%
clangcompile+link    0.36 ± 1%
clangcompile+linkO2  2.19 ± 1%
tcccompile           0.03 ± 0%
tcclink              0.00 ± 0%
tcccompile+link      0.03 ± 4%
```

- tcc is 17.5x faster than "gcc -O0" and 12x faster than "clang -O0";
- "gcc -O2" is 4x slower than "gcc -O0";
- "clang -O2" is 6x slower than "clang -O0".

Benchmarks for running pystone.py via python interpretation, and via Cython + compilation:

```
name                 pystone/s
pypystone            231k ± 1%
gccpystone           234k ± 2%
gccO2pystone         441k ± 2%
clangpystone         240k ± 2%
clangO2pystone       437k ± 1%
tccpystone           251k ± 6%
```

- gcc/clang/tcc compiled version run a bit faster than interpreted version;
- tcc compiled version runs a bit faster than "gcc -O0" and "clang -O0" ones;
- "gcc -O2" and "clang -O2" bring ~ 2x speedup.

For [pystone.pyx](https://lab.nexedi.com/kirr/cython/blob/74daf44d6/t/compilebench/pystone_pyx.pyx) (original pystone.py with added type annotations), even with tcc, I [get](https://lab.nexedi.com/kirr/cython/commit/74daf44d) 8x speedup, which shows that TinyCC could be useful to speedup things while preserving fast edit-try cycle and Python interactivity **_if_** Cython goes back to be fast again. In that case it probably makes sense to use TinyCC for everything besides files with performance bottlenecks. And for performance bottlenecks, we could have a directive in the build system - similar to `# cython: ...` - to use `gcc -O2` instead of `tcc` for that particular file only, because there runtime speed matters very much.

Thanks beforehand,
Kirill

----

(*) all benchmarks were done with caring about [measurement stability](http://navytux.spb.ru/~kirr/neo.html#measurements-stability).

**Comment by da-woods** [comment]
This doesn't seem right to me. Using your "x.pyx" I get basically identical results for 0.29.19 vs 3.0a5 (checked out from git tags).

What I do see is a 3x speed-up for "Cython compiled with Cython" vs "Cython run from py source". I'd suggest that your dramatic regression is just comparing compiled and un-compiled Cython (maybe this is a packaging error?).

The steady growth sounds more plausible but may just be an inevitable consequence of trying to do more.

**Comment by navytux** [comment]
@da-woods, thanks for feedback. I was previously checking by installing releases from pypi. This time, I've also rechecked from Cython git checkout on 0.29.19 vs 3.0a5 tags in a fresh virtualenv with making sure that Cython modules themselves are actually compiled. Maybe I'm doing something wrong, but the result stays close to what I originlly posted: 0.29.19 -> 0.29s, 3.0a5 -> 0.69s. Full log of verification is provided below.

<details>
<summary>Full log of verification 0.29.19 vs 3.0a5 from Cython.git checkout</summary>

```
kirr@deco:~/tmp/trashme/cyspeed$ git clone https://github.com/cython/cython.git
Клонирование в «cython»…
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 94734 (delta 30), reused 26 (delta 18), pack-reused 94678
Получение объектов: 100% (94734/94734), 57.37 MiB | 14.81 MiB/s, готово.
Определение изменений: 100% (66922/66922), готово.
kirr@deco:~/tmp/trashme/cyspeed$ virtualenv 1.venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/kirr/tmp/trashme/cyspeed/1.venv/bin/python2
Also creating executable in /home/kirr/tmp/trashme/cyspeed/1.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
kirr@deco:~/tmp/trashme/cyspeed$ . 1.venv/bin/activate
(1.venv) kirr@deco:~/tmp/trashme/cyspeed$ cd cython/
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ git checkout 0.29.19
Примечание: переход на «0.29.19».

Вы сейчас в состоянии «отделённого HEAD». Вы можете осмотреться, сделать
экспериментальные изменения и закоммитить их, также вы можете отменить
изменения любых коммитов в этом состоянии не затрагивая любые ветки и
не переходя на них.

Если вы хотите создать новую ветку и сохранить свои коммиты, то вы
можете сделать это (сейчас или позже) вызвав команду checkout снова,
но с параметром -b. Например:

  git checkout -b <имя-новой-ветки>

HEAD сейчас на 2c3a8c12b Prepare release of 0.29.19.
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ pip install -e .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///home/kirr/tmp/trashme/cyspeed/cython
Installing collected packages: Cython
  Running setup.py develop for Cython
Successfully installed Cython
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ which cython
/home/kirr/tmp/trashme/cyspeed/1.venv/bin/cython
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ cython --version
Cython version 0.29.19
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ cat >x.pyx
# cython: language_level=2
cdef int myfunc(int x):
    y = x
    return y
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx

real    0m0,290s
user    0m0,269s
sys     0m0,020s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx

real    0m0,287s
user    0m0,259s
sys     0m0,028s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx

real    0m0,287s
user    0m0,243s
sys     0m0,044s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx

real    0m0,291s
user    0m0,276s
sys     0m0,014s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx

real    0m0,287s
user    0m0,259s
sys     0m0,028s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ git clean -fdX
Удаление Cython.egg-info/
Удаление Cython/Build/Dependencies.pyc
Удаление Cython/Build/Distutils.pyc
Удаление Cython/Build/__init__.pyc
Удаление Cython/CodeWriter.pyc
Удаление Cython/Compiler/AnalysedTreeTransforms.pyc
Удаление Cython/Compiler/Annotate.pyc
Удаление Cython/Compiler/AutoDocTransforms.pyc
Удаление Cython/Compiler/Buffer.pyc
Удаление Cython/Compiler/Builtin.pyc
Удаление Cython/Compiler/CmdLine.pyc
Удаление Cython/Compiler/Code.pyc
Удаление Cython/Compiler/CodeGeneration.pyc
Удаление Cython/Compiler/CythonScope.pyc
Удаление Cython/Compiler/DebugFlags.pyc
Удаление Cython/Compiler/Errors.pyc
Удаление Cython/Compiler/ExprNodes.pyc
Удаление Cython/Compiler/FlowControl.c
Удаление Cython/Compiler/FlowControl.pyc
Удаление Cython/Compiler/FlowControl.so
Удаление Cython/Compiler/FusedNode.c
Удаление Cython/Compiler/FusedNode.so
Удаление Cython/Compiler/Future.pyc
Удаление Cython/Compiler/Interpreter.pyc
Удаление Cython/Compiler/Lexicon.pyc
Удаление Cython/Compiler/Main.pyc
Удаление Cython/Compiler/MemoryView.pyc
Удаление Cython/Compiler/ModuleNode.pyc
Удаление Cython/Compiler/Naming.pyc
Удаление Cython/Compiler/Nodes.pyc
Удаление Cython/Compiler/Optimize.pyc
Удаление Cython/Compiler/Options.pyc
Удаление Cython/Compiler/ParseTreeTransforms.pyc
Удаление Cython/Compiler/Parsing.pyc
Удаление Cython/Compiler/Pipeline.pyc
Удаление Cython/Compiler/PyrexTypes.pyc
Удаление Cython/Compiler/Pythran.pyc
Удаление Cython/Compiler/Scanning.c
Удаление Cython/Compiler/Scanning.pyc
Удаление Cython/Compiler/Scanning.so
Удаление Cython/Compiler/StringEncoding.pyc
Удаление Cython/Compiler/Symtab.pyc
Удаление Cython/Compiler/TreeFragment.pyc
Удаление Cython/Compiler/TypeInference.pyc
Удаление Cython/Compiler/TypeSlots.pyc
Удаление Cython/Compiler/UtilNodes.pyc
Удаление Cython/Compiler/UtilityCode.pyc
Удаление Cython/Compiler/Version.pyc
Удаление Cython/Compiler/Visitor.c
Удаление Cython/Compiler/Visitor.pyc
Удаление Cython/Compiler/Visitor.so
Удаление Cython/Compiler/__init__.pyc
Удаление Cython/Debugging.pyc
Удаление Cython/Distutils/__init__.pyc
Удаление Cython/Distutils/build_ext.pyc
Удаление Cython/Distutils/extension.pyc
Удаление Cython/Distutils/old_build_ext.pyc
Удаление Cython/Plex/Actions.c
Удаление Cython/Plex/Actions.pyc
Удаление Cython/Plex/Actions.so
Удаление Cython/Plex/DFA.pyc
Удаление Cython/Plex/Errors.pyc
Удаление Cython/Plex/Lexicons.pyc
Удаление Cython/Plex/Machines.pyc
Удаление Cython/Plex/Regexps.pyc
Удаление Cython/Plex/Scanners.c
Удаление Cython/Plex/Scanners.pyc
Удаление Cython/Plex/Scanners.so
Удаление Cython/Plex/Transitions.pyc
Удаление Cython/Plex/__init__.pyc
Удаление Cython/Runtime/refnanny.c
Удаление Cython/Runtime/refnanny.so
Удаление Cython/Shadow.pyc
Удаление Cython/StringIOTree.pyc
Удаление Cython/Tempita/__init__.pyc
Удаление Cython/Tempita/_looper.pyc
Удаление Cython/Tempita/_tempita.c
Удаление Cython/Tempita/_tempita.pyc
Удаление Cython/Tempita/_tempita.so
Удаление Cython/Tempita/compat3.pyc
Удаление Cython/Utility/__init__.pyc
Удаление Cython/Utils.pyc
Удаление Cython/__init__.pyc
Удаление build/
Удаление cython.pyc
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ cython
Traceback (most recent call last):
  File "/home/kirr/tmp/trashme/cyspeed/1.venv/bin/cython", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/kirr/tmp/trashme/cyspeed/1.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/kirr/tmp/trashme/cyspeed/1.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/kirr/tmp/trashme/cyspeed/1.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/kirr/tmp/trashme/cyspeed/1.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/kirr/tmp/trashme/cyspeed/1.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/kirr/tmp/trashme/cyspeed/1.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Cython' distribution was not found and is required by the application
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ git checkout 3.0a
3.0a1   3.0a2   3.0a3   3.0a4   3.0a5   
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ git checkout 3.0a5 
Предыдущая позиция HEAD была 2c3a8c12b Prepare release of 0.29.19.
HEAD сейчас на 2ffcb6a0a Merge branch '0.29.x'
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ pip install -e .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///home/kirr/tmp/trashme/cyspeed/cython
Installing collected packages: Cython
  Running setup.py develop for Cython
Successfully installed Cython
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ which cython
/home/kirr/tmp/trashme/cyspeed/1.venv/bin/cython
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ cython --version
Cython version 3.0a5
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx 

real    0m0,698s
user    0m0,646s
sys     0m0,052s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx 

real    0m0,698s
user    0m0,637s
sys     0m0,060s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx 

real    0m0,692s
user    0m0,624s
sys     0m0,068s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx 

real    0m0,696s
user    0m0,657s
sys     0m0,039s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ time cython x.pyx 

real    0m0,697s
user    0m0,638s
sys     0m0,059s
(1.venv) kirr@deco:~/tmp/trashme/cyspeed/cython$ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cython.Compiler import Visitor
>>> Visitor.__file__
'Cython/Compiler/Visitor.so'
>>> 
```

</details>

Kirill

**Comment by da-woods** [comment]
Actually, yes - I can reproduce it now. It does seem suspicious that the timing is so close to the non-compiled performance though.

**Comment by scoder** [comment]
Could you do some profiling to see where the additional time is spent?

Also, please use a realistic input file for the benchmark. Preferably also different ones. It doesn't help to optimise for code that we will never encounter in practice.

I just tried it with lxml's ~20k lines main Cython module and it gives me ~8 seconds for Cython 0.29.19 and ~9 seconds for Cython 3.0a5. That's pretty close, given that 3.0 does a whole lot of things better. But improvements are always welcome.

**Comment by da-woods** [comment]
```
     7012    0.228    0.000    0.329    0.000 Machines.py:162(add_transitions)
   896404    0.101    0.000    0.101    0.000 {built-in method builtins.chr}
```

Sorted by "tottime", Parser/Machines.py `add_transitions" is right at the top of the list for Cython 3.0a, followed by builtins.chr (which I think is mostly used in the parser). It doesn't appear anywhere notable in Cython 0.29.x.  Similarly if you look sort by calls you see builtins.chr right at the top for Cython 3.0 but nowhere for Cython 0.29.19. (It's called 6066 times in 0.29.19)

In 0.29.19 add_transitions is called 946 times, while in 3.0a5 it's called 7012 times.

(This is all for the slightly artificial example).

----------------------------

Tentatively, I think this might be because _someone_ dumped a whole load of unicode characters in Lexicon.py, and this makes it a lot slower to build the parser?

Adding Plex/Machines.py to the list of compiled modules recovers a bit of time (although obviously it isn't typed, so the benefit is limited).

**Comment by scoder** [comment]
Ah, interesting. Thanks for the investigations.

The lexicon used to be pickled in Pyrex, which turned out to be a version specific annoyance with very little benefit at the time, so we removed that years ago. Maybe the complexity of today's scanner is a reason to reconsider that decision? We could make it a part of the build to produce that pickle, so that it gets packaged in the binary wheels.

**Comment by da-woods** [comment]
https://github.com/cython/cython/pull/3649 helps but definitely doesn't get back to where it was (just by compiling and adding a little bit of typing to the slow bit).

**Comment by navytux** [comment]
@da-woods, @scoder, thanks for confirming and trying to get this regression fixed.

I, of course, noticed the slowdown on real code - for example for pygolang the time for cythonize part (`.pyx -> .c`) is 5.4s (0.29.19) vs 6.8s (3.05a), but the issue shows much more visibly on input that does not have type annotations: for example for pystone.py it is 0.49s (0.29.19) vs 0.96s (3.0a) i.e. a 2x difference. Feeding untyped input **_is exactly the situation when one starts to convert large existing codebase like ERP5 to Cython_**.

In addition to what was already noticed, for me it looks like that it would be good to try to have logic to skip doing unneeded work inside Cython compiler.

Thanks again for feedback and for caring about this issue,
Kirill

**Comment by scoder** [comment]
I tried pickling the Lexicon, but it turns out that a) the size of the pickle is ~7MB, still ~2MB when gzip compressed, and b) loading the compressed pickle takes just as long as building the lexicon from scratch, so there is nothing to win here. Loading the uncompressed pickle is about 10% faster, but that would still add those compressed 2MB to the wheels. I don't think that's a good idea.

Let's see if we can make `Machines.py` faster then.

**Comment by scoder** [comment]
447445a should reduce the overhead of the unicode identifiers and makes a `cythonize.py` run of the artificial example ~10% faster for me. Compiling `lxml.etree` is also ~5% faster. Not bad. The compiled `Machines.so` is ~190KB and ~72KB compressed. That's much better than 7/2MB, for about the same win.

**Comment by da-woods** [comment]
The other thing that might be worthwhile is to be able to (lazily) generate unicode/ascii versions of the lexer. Then each file being compiled could be tested to see if it contains any non-ascii characters and if not then the ascii version of the lexer is used instead.

Obviously that adds a bit of complication, and makes compiling a mixture of ascii/non-ascii files marginally worse. But it looks like supporting unicode characters has a surprisingly big cost that probably isnt used most of the time.

I'll have a go at some point. Maybe.

**Comment by scoder** [comment]
> (lazily) generate unicode/ascii versions of the lexer

That sounds like a lot of effort and complexity, for a rare benefit. Most people don't care about 300 msecs in the startup time of Cython when their C compiler (which is usually not tcc) takes minutes to compile and optimise the generated code. As long as Cython's runtime is not a major portion for the average production build of most packages out there, we should prefer maintenance over tuning.

**Comment by scoder** [comment]
> (lazily) generate unicode/ascii versions of the lexer

That sounds like a lot of effort and complexity, for a rare benefit. Most people don't care about 300 msecs in the startup time of Cython when their C compiler (which is usually not tcc) takes minutes to compile and optimise the generated code. As long as Cython's runtime is not a major portion for the average production build of most packages out there, we should prefer maintenance over tuning.

Just for comparison, according to the test logs on travis, `gcc -O0` (i.e. with _all_ optimisations turned off, which usually eat most of the compile time) currently takes about 40 minutes to compile the test suite (1036 C tests) and Cython translates the 1220 tests (including error tests etc.) in 12 minutes. Users will have to wait 4x longer on gcc than on Cython, even just for a debug build. And most users will want their production compiler also for debug builds and not switch to `tcc`, in order to avoid chasing ghost bugs.

**Comment by scoder** [comment]
Profiling shows that at least for not so short pieces of code, the translation time is dominated by the transform runs over the AST. I've considered merging some of the transform classes to reduce the overall traversal time (even doing this automatically by introspection), but it's actually not so easy since some of them logically depend on each other and others have overlapping dispatch methods (e.g. `visit_FuncDefNode` versus `visit_DefNode`) that cannot easily be combined into one. But basically, the more transforms we have that independently traverse the tree, the more time is spent in traversing the tree. Many transforms are rather selective and only dispatch on a few tree node types, so the repeated traversals to search those nodes become costly in comparison.
