### ISSUE TITLE
giacpy fails to build with Cython 3.0

### ISSUE THREAD

**Issue by scoder** [cython/cython#3651]
```
[1/1] Cythonizing giacpy/giacpy.pyx
/usr/lib64/python3.8/site-packages/Cython/Compiler/Main.py:344: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /builddir/build/BUILD/giacpy-0.7.0/giacpy/giacpy.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "setup.py", line 129, in <module>
    ext_modules+=cythonize([Extension(
  File "/usr/lib64/python3.8/site-packages/Cython/Build/Dependencies.py", line 1105, in cythonize
    cythonize_one(*args)
  File "/usr/lib64/python3.8/site-packages/Cython/Build/Dependencies.py", line 1246, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Main.py", line 575, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Main.py", line 503, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 356, in run_pipeline
    data = run(phase, data)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 336, in run
    return phase(data)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 167, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 459, in generate_c_code
    self.generate_module_init_func(modules[:-1], env, globalstate['init_module'])
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 2797, in generate_module_init_func
    self.body.generate_execution_code(code)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 403, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 403, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 5142, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 403, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 5529, in generate_execution_code
    self.generate_assignment_code(code)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 5826, in generate_assignment_code
    self.lhs.generate_assignment_code(self.rhs, code)
  File "/usr/lib64/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 2344, in generate_assignment_code
    namespace = self.entry.scope.namespace_cname
AttributeError: 'PropertyScope' object has no attribute 'namespace_cname'
```

**Comment by mattip** [comment]
Here is a minimum reproducer.
```
cdef class HelpClass:

     def help(self):
        return "help, I need somebody"


     property help:
         def __get__(self):
           return self.help()
```

**Comment by mattip** [comment]
I didn't know about the `property xxx:` syntax. Is it documented somewhere? The only documentation I see is for using it as a decorator: `@property`.

**Comment by da-woods** [comment]
@Mattip https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#properties - it's an older syntax from before Cython supported decorator properties.

I'm not completely sure if it should be possible to have a function called `help` and a property called `help`, but it shouldn't crash.

**Comment by mattip** [comment]
Ahh, thanks for the clarification. Using a decorator gives the same cython `AttributeError`:
```
cdef class HelpClass:

     def help(self):
        return "help, I need somebody"


     @property
     def help(self):
        return self.help()
```
and trying to reuse the property as a method gives a recursion error in CPython (which makes sense since the property, appearing later in the definition, overrides the method)

```help.py
class HelpClass:

     def help(self):
        return "help, I need somebody"


     @property
     def help(self):
        return self.help()


h = HelpClass()
print(h.help)
```

So maybe raising an error here is the correct thing to do. I wonder how/why it works pre-cython-3.0 ?

**Comment by da-woods** [comment]
It fails on the current 0.29.x branch. If I go back to 0.28.6 then it just returns the method (i.e. the property doesn't to have work)

```
>>> HelpClass().help
<built-in method help of prop.HelpClass object at 0x7f65b4a3be80>
```

**Comment by mattip** [comment]
What is the desired behaviour?
- silently allow a property and method to override eachother (like python), which is a change in behaviour between 0.28 and 3.0 and will result in unhappy faces from giacpy since they will get runtime recursion errors
- raise an error if a property has the same name as a class method/attribute when parsing
- easy way out: wrap line 2344 in `generate_assignment_code` with a `try`/`except` to call `error()` instead.

**Comment by mattip** [comment]
Or go back to 0.28 behaviour which seems to be "not override a method/attribute with a property"

**Comment by da-woods** [comment]
Probably one of:

* silently allow a property and method to override eachother (like python), which is a change in behaviour between 0.28 and 3.0 and will result in unhappy faces from giacpy since they will get runtime recursion errors
* raise an error if a property has the same name as a class method/attribute when parsing

Most likely the latter (simply because it's easiest to do).

Personally I don't think the 0.28 behaviour was ever meaningfully correct, but it has the advantage of not changing things.

--------------

It looks like something that really needs to be fixed in giacpy though, even if Cython could handle it better too. Based on the simplified test they could probably just delete the property.

**Comment by mattip** [comment]
Both: cython should handle this better and giacpy needs a fix. I could not figure out how to register to file an issue at [giacpy](https://gitlab.math.univ-paris-diderot.fr/han/giacpy), so I sent an email to the owner. 

I am trying to write a failing test for this, but have run into a problem. Do the tests/error/test*.py tests actually run properly? Modifying the error message in a random error test, say `e_decorators.pyx`, and running `python runtests.py e_decorators` passes, even though the error messages now do not match. Modifying the code to not raise an error also passes the test run. Is this expected?

**Comment by mattip** [comment]
The author of giacpy has [fixed the source](https://gitlab.math.univ-paris-diderot.fr/han/giacpy/-/commit/223018904e80c5d839e1c727ce136d2886b55b2e) and I checked that was sufficient to allow cython to process the file.

**Comment by da-woods** [comment]
> I am trying to write a failing test for this, but have run into a problem. Do the tests/error/test*.py tests actually run properly? Modifying the error message in a random error test, say `e_decorators.pyx`, and running `python runtests.py e_decorators` passes, even though the error messages now do not match. Modifying the code to not raise an error also passes the test run. Is this expected?

They do work in general, but `e_decorators.pyx` in particular looks broken. I'm not 100% sure but I think `_ERRORS` has to be the last thing in the file.

**Comment by mattip** [comment]
I am looking for the correct spot to "raise an error if a property decorator has the same name as a class method/attribute when parsing".  One strategy would be when visiting attributes/methods check for a decorator, and when visiting the decorator check attributes/methods. Is there something like a resolver pass in the ParseTreeTrasforms that would be a good place to do this? 

xref #3975 which fixed the `e_decorators.pyx` test.

**Comment by da-woods** [comment]
I'd think it'd probably be when decorators are set up in [`AnalyseDeclarationsTransform`](https://github.com/cython/cython/blob/master/Cython/Compiler/ParseTreeTransforms.py#L1632) or possibly in `PropertyNode.analyse_expressions` (or `PropertyNode.analyse_declarations`). I'm guessing the difficulty would be that properties usually implemented in terms of a function of the same name, so you need to ignore that.

**Comment by mattip** [comment]
I tried something in #3984, but it is not correct. I am not sure I am on the right track.

**Comment by mattip** [comment]
This discussion is a bit theoretical now that giacpy has cleaned up the code causing this.

I think #3984 is correctly raising an error, but it is a change in parsing behaviour and will require adjusting some other tests. Previously, a property and an attribute/method with the same name could co-exists in a cdef class. The property would externally shadow the attribut/method, and internally would call the shadowed mangled name, so there was no RecursionError. But this behviour is not really correct. 

The [pure-python test](https://github.com/cython/cython/pull/3984/files#diff-cfbf53318ca35a41eb563e59be5296e1342cfa61d8a3b40f6a065ea279b9166fR1) I added, which segfaults in Cython, shows that Cython does not correctly create the RecursionError that python emits.

**Comment by da-woods** [comment]
> The [pure-python test](https://github.com/cython/cython/pull/3984/files#diff-cfbf53318ca35a41eb563e59be5296e1342cfa61d8a3b40f6a065ea279b9166fR1) I added, which segfaults in Cython, shows that Cython does not correctly create the RecursionError that python emits.

I don't think Cython does anything to detect recursion (so I'd expect a crash rather than a RecursionError). It looks like there's a [new API in Python 3.9](https://docs.python.org/3/c-api/exceptions.html#recursion-control) than could be used to detect recursion. Although it seems like it might be more overhead than is justified for the feature.

**Comment by mattip** [comment]
Is there a way to assert that a segfault is the intended result of a test or should I remove the test from the PR?

**Comment by da-woods** [comment]
Could you do

```
@property
def p(self):
  self.call_count += 1
  if self.call_count > 10: raise Recursion error
  return self.p()
```

The objective is to test that the property calls overrides the function and thus calls itself. It doesn't need to go to "completion" to show that.

**Comment by mattip** [comment]
The fixed test shows that overriding an attribute/method with a property works in non-cdef, python classes. But now we are back to the beginning: in a cdef class, nodes with the same name are added to the class's `stats.body` list and do not replace each other. In the example
```
cdef class A:
    def fortytwo(self):
        return 42

    def fortytwo(self):
        return '42'

    @property
    def fortytwo(self):
        return 'fortytwo'
```

there will be three nodes named `fortytwo` on the `CClassDefNode.stats` when it reaches `CClassDefNode.generate_execution_code()`. Shouldn't the second override the first and remove the node, and then the third override the second and remove it as well?

**Comment by scoder** [comment]
> > The [pure-python test](https://github.com/cython/cython/pull/3984/files#diff-cfbf53318ca35a41eb563e59be5296e1342cfa61d8a3b40f6a065ea279b9166fR1) I added, which segfaults in Cython, shows that Cython does not correctly create the RecursionError that python emits.
> 
> I don't think Cython does anything to detect recursion (so I'd expect a crash rather than a RecursionError). It looks like there's a [new API in Python 3.9](https://docs.python.org/3/c-api/exceptions.html#recursion-control) than could be used to detect recursion. Although it seems like it might be more overhead than is justified for the feature.

That's not a new API (it was only added to the _limited_ API in 3.9) and Cython already uses it for "regular" Python calls. I think it's not used in all (optimised) cases, partly due to its overhead, but the calling code is also so specialised by now that there might simply have been oversights, or it might also be unclear in some cases what needs to be wrapped with the recursion counter and what doesn't.

OTOH, many users would value more speed in general over the occasional crash that should have been a recursion error.
