### ISSUE TITLE
Unable to Compile on macOS - ValueError: chr() arg not in range(0x110000)

### ISSUE THREAD

**Issue by WillAyd** [cython/cython#3710]
With Python 3.8.3 on macOS a simple `python setup.py build_ext --inplace` yields the following. On Debian with Python 3.8.3 everything seemed fine

```python-traceback
Unable to find pgen, not compiling formal grammar.
running build_ext
Compiling /Users/willayd/clones/cython/Cython/Plex/Machines.py because it changed.
Compiling /Users/willayd/clones/cython/Cython/Plex/Transitions.py because it changed.
Compiling /Users/willayd/clones/cython/Cython/Plex/DFA.py because it changed.
Compiling /Users/willayd/clones/cython/Cython/Compiler/Scanning.py because it changed.
Compiling /Users/willayd/clones/cython/Cython/Compiler/FlowControl.py because it changed.
Compiling /Users/willayd/clones/cython/Cython/Compiler/FusedNode.py because it changed.
Compiling /Users/willayd/clones/cython/Cython/Tempita/_tempita.py because it changed.
[1/7] Cythonizing /Users/willayd/clones/cython/Cython/Compiler/FlowControl.py
Traceback (most recent call last):
  File "setup.py", line 299, in <module>
    run_build()
  File "setup.py", line 236, in run_build
    setup(
  File "/Users/willayd/miniconda3/envs/cython-dev/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/Users/willayd/miniconda3/envs/cython-dev/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/willayd/miniconda3/envs/cython-dev/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/willayd/miniconda3/envs/cython-dev/lib/python3.8/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/Users/willayd/miniconda3/envs/cython-dev/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/Users/willayd/clones/cython/Cython/Distutils/build_ext.py", line 20, in finalize_options
    self.distribution.ext_modules[:] = cythonize(
  File "/Users/willayd/clones/cython/Cython/Build/Dependencies.py", line 1110, in cythonize
    cythonize_one(*args)
  File "/Users/willayd/clones/cython/Cython/Build/Dependencies.py", line 1256, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/Users/willayd/clones/cython/Cython/Compiler/Main.py", line 575, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/willayd/clones/cython/Cython/Compiler/Main.py", line 492, in run_pipeline
    pipeline = Pipeline.create_py_pipeline(context, options, result)
  File "/Users/willayd/clones/cython/Cython/Compiler/Pipeline.py", line 272, in create_py_pipeline
    return create_pyx_pipeline(context, options, result, py=True)
  File "/Users/willayd/clones/cython/Cython/Compiler/Pipeline.py", line 252, in create_pyx_pipeline
    create_pipeline(context, mode, exclude_classes=exclude_classes),
  File "/Users/willayd/clones/cython/Cython/Compiler/Pipeline.py", line 144, in create_pipeline
    from .ParseTreeTransforms import WithTransform, NormalizeTree, PostParse, PxdPostParse
  File "/Users/willayd/clones/cython/Cython/Compiler/ParseTreeTransforms.py", line 1637, in <module>
    class AnalyseDeclarationsTransform(EnvTransform):
  File "/Users/willayd/clones/cython/Cython/Compiler/ParseTreeTransforms.py", line 1639, in AnalyseDeclarationsTransform
    basic_property = TreeFragment(u"""
  File "/Users/willayd/clones/cython/Cython/Compiler/TreeFragment.py", line 235, in __init__
    mod = t = parse_from_strings(name, fmt_code, fmt_pxds, level=level, initial_pos=initial_pos)
  File "/Users/willayd/clones/cython/Cython/Compiler/TreeFragment.py", line 74, in parse_from_strings
    scanner = PyrexScanner(buf, code_source, source_encoding = encoding,
  File "Cython/Compiler/Scanning.py", line 306, in Cython.Compiler.Scanning.PyrexScanner.__init__
    Scanner.__init__(self, get_lexicon(), file, filename, initial_pos)
  File "Cython/Compiler/Scanning.py", line 35, in Cython.Compiler.Scanning.get_lexicon
    lexicon = make_lexicon()
  File "/Users/willayd/clones/cython/Cython/Compiler/Lexicon.py", line 87, in make_lexicon
    return Lexicon([
  File "/Users/willayd/clones/cython/Cython/Plex/Lexicons.py", line 140, in __init__
    dfa = DFA.nfa_to_dfa(nfa, debug=(debug_flags & 3) == 3 and debug)
  File "/Users/willayd/clones/cython/Cython/Plex/DFA.py", line 47, in nfa_to_dfa
    new_machine.add_transitions(new_state, event, state_map.old_to_new(old_states))
  File "Cython/Plex/Machines.py", line 169, in Cython.Plex.Machines.FastMachine.add_transitions
    def get_initial_state(self, name):
ValueError: chr() arg not in range(0x110000)
```

**Comment by da-woods** [comment]
I know there were a few changes to Plex.Machines recently to try to speed it up. Based on the line numbers it looks like the .so and the .pyx file may have got out of sync - i.e. you may have an Machines.so that was built when it was broken?

The error isn't coming from a line where it makes sense (but is coming from one nearby). Is there a Machines.so that you can find and delete?

**Comment by WillAyd** [comment]
Ah OK I did see one. I tried running a `python setup.py clean --all` before hand (should have mentioned in OP) but I guess that doesn't clear them? Is there a standard way to clean all build artifacts?

**Comment by WillAyd** [comment]
Looks like running `find . -name "*.so" -delete` before the build fixed this, so feel free to close. Thanks for the tip!

**Comment by da-woods** [comment]
> Is there a standard way to clean all build artifacts?

Not sure I'm afraid. I don't usually bother building Cython. I'll close since I think this was just bad luck to have ended up with a broken version.
