### ISSUE TITLE
Can someone help me with cython's bug compilation on buildozer??

### ISSUE THREAD

**Issue by batistadrg** [cython/cython#3760]
jnius/jnius_conversion.pxi:517:45: Cannot assign type 'double' to 'jsize'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/Cython-3.0a5-py3.8-linux-x86_64.egg/Cython/Build/Cythonize.py", line 228, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/Cython-3.0a5-py3.8-linux-x86_64.egg/Cython/Build/Cythonize.py", line 224, in main
    cython_compile(path, options)
  File "/usr/local/lib/python3.8/dist-packages/Cython-3.0a5-py3.8-linux-x86_64.egg/Cython/Build/Cythonize.py", line 68, in cython_compile
    ext_modules = cythonize(
  File "/usr/local/lib/python3.8/dist-packages/Cython-3.0a5-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1110, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.8/dist-packages/Cython-3.0a5-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1277, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/zakk/Documentos/ppp/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius/jnius/jnius.pyx

  STDERR:

**Comment by scoder** [comment]
Note that the bug tracker is not the right place to discuss usage related questions.

In your case, there is probably an incorrect type declaration somewhere, or a missing cast, or you may need a dedicated conversion function. If you need help, please ask on the cython-users mailing list.
