### ISSUE TITLE
[BUG] pyximport fails on Windows with multiprocessing at high concurrency

### ISSUE THREAD

**Issue by steel3d** [cython/cython#3837]
**Describe the bug**
pyximport seems to fail with a moderate to high number of parallel processes. If I build the .pyx explicitly, then there is no problem. I installed cython with pip just today. Windows 10, 16-core AMD Threadripper with 64GB RAM. If I use a low core count, like 2-3, sometimes higher, my scripts succeed. But as I increase the core counts, I'll run into these crashes. Sometimes at the same core count it will pass, while other times it will fail. 

```
c:\>py test2.py
start 123
start 123
start 123
start 123
start 123
c:\>py test2.py
start 123
start 123
start 123
start 123
Traceback (most recent call last):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing test3: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Steve\p4\py\pnet\pnet\test2.py", line 8, in <module>
    from test3 import test3
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 459, in load_module
    module = load_module(fullname, self.path,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: Building module test3 failed: ['ImportError: DLL load failed while importing test3: The specified module could not be found.\n']
```

Another run looked like this:

```
c:\>py test2.py
Traceback (most recent call last):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 214, in load_module
    so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 192, in build_module
    assert os.path.exists(so_path), "Cannot find: %s" % so_path
AssertionError: Cannot find: C:\Users\Steve\.pyxbld\lib.win-amd64-3.8\test3.cp38-win_amd64.pyd.reload2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
start 123
    _fixup_main_from_path(data['init_main_from_path'])
start 123
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
start 123
    main_content = runpy.run_path(main_path,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
start 123
    return _run_module_code(code, init_globals, run_name,
start 123
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Steve\p4\py\pnet\pnet\test2.py", line 8, in <module>
    from test3 import test3
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 459, in load_module
    module = load_module(fullname, self.path,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 214, in load_module
    so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyximport\pyximport.py", line 192, in build_module
    assert os.path.exists(so_path), "Cannot find: %s" % so_path
ImportError: Building module test3 failed: ['AssertionError: Cannot find: C:\\Users\\Steve\\.pyxbld\\lib.win-amd64-3.8\\test3.cp38-win_amd64.pyd.reload2\n']
```

Seems related to https://github.com/cython/cython/issues/3566

**To Reproduce**

test3.pyx
```
def test3(num):
    print("start %d" % num)
```

test2.py
```
import concurrent.futures
import itertools
import pyximport
pyximport.install(setup_args={"script_args":["--compiler=msvc"]},
                reload_support=True)
from test3 import test3

if __name__ == '__main__':
    with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
        executor.map(test3, itertools.repeat(123))
```

It will sometimes fail with max_workers=4. It will always pass with max_workers=2. It will always fail with max_workers=32. It doesn't look like its a memory pressure issue, as my memory usage doesn't move much. 

If I manually compile test3.pyx, it will always pass, since pyximport doesn't need to compile in that case. 

**Expected behavior**
Should not crash at any level of parallelism as long as we're not out of memory. 

**Environment (please complete the following information):**
 - OS:Windows 10
 - Python version 3.8.5
 - Cython version 0.29.21

**Comment by scoder** [comment]
Thanks for the report. It somehow seems to think that it needs to reload the module, thus tries to rebuild it. That that can fail under concurrency is not surprising. The fact that it would try to reload the module is.

Maybe you can do a bit of print debugging to investigate why it thinks that it needs a rebuild inside of the executor. (Pyx-)Importing the module before starting the executor, as you do in your example, is already the right thing to do.

**Comment by steel3d** [comment]
Unfortunately I don't know enough about the expected behavior to do effective debugging. This is my first contact with cython. And no time. I'll try to switch to multithreading instead.

**Comment by scoder** [comment]
> I'll try to switch to multithreading instead.

Your choice, but if you ask me, if multiprocessing otherwise works for you, I'd rather stick with that than add thread-concurrency to my application.

> I don't know enough about the expected behavior to do effective debugging.

I guess it's easy to debug with a couple of prints sprinkled here and there. But if you prefer to degrade your own code rather than helping to fix a problem that others might run into as well, that's obviously your choice, too.

**Comment by steel3d** [comment]
Threading without GIL should be more efficient than spinning up processes, especially on windows without fork, and cross-thread communication should be simpler and possibly more efficient. But it's not easy to get around GIL in cython, I'll give you that :) Sorry, just way too slammed...

**Comment by steel3d** [comment]
I found that reload_support=False doesn't crash. I don't need that, so I'm good.
