### ISSUE TITLE
Class `__annotations__` Dict Should Be Eagerly Evaluated

### ISSUE THREAD

**Issue by seandstewart** [cython/cython#3839]
**Is your feature request related to a problem? Please describe.**
As was found in #3829 - CPython currently supports using a custom mapping implementation for the `__annotations__` object. This is not explicitly stated in the [runtime effects of PEP 526](https://www.python.org/dev/peps/pep-0526/#runtime-effects-of-type-annotations), but there is an explicit test for it in `test_grammar`:

https://github.com/cython/cython/blob/master/tests/run/test_grammar.py#L491-L498

**Describe the solution you'd like**
As of #3829, we support the `__annotations__` mapping on class scopes, but do so by creating the entry after we've analysed the rest of the class body and gathered annotations.

In order to support custom mappings for the `__annotations__` namespace, and also support other side-effects of eager-declaration, such as `del __annotations__`, we should declare the `__annotations__` entry in the scope once the first annotation in the body is encountered, then update the entry as new annotations are encountered.

This will also completely fulfill the requirement that the `__annotations__` dict is [mutable at runtime](https://www.python.org/dev/peps/pep-0526/#runtime-effects-of-type-annotations). As it is currently implemented, the `__annotations__` dict is only mutable/delete-able *after* we construct the class.

Aside from the test in `test_grammar`, there is also additional behavior that should be supported:

```cython

class C:
    var: int
    del __annotations__

C.__annotations__
#> Traceback (most recent call last):
#>   File "<stdin>", line 1, in <module>
#> AttributeError: type object 'C' has no attribute '__annotations__'
```

```cython

class D:
    a: int
    __annotations__['b'] = 'str'

print(D.__annotations__)
#> {'a': 'int', 'b': 'str'}
```

```cython

class E:
    ...

E.__annotations__
#> Traceback (most recent call last):
#>   File "<input>", line 1, in <module>
#> AttributeError: type object 'E' has no attribute '__annotations__'
```

**Comment by da-woods** [comment]
A few other tests that I think should be added to this - I suspect they'll pass fairly naturally with the full implementation, but it's worth making sure:

```
def test_branches(val):
    class C:
        # branches like this are unusual but supported
        if val:
            x: int = 1
        else:
            y: float = 2
    return C.__annotations__

def maybe_raise(val):
    if val:
        raise RuntimeError(val)
    return val

def test_exact_order(val):
    class C:
        try:
           x: int = maybe_raise(val)  # The annotation is set right after the assignment
        except:
           pass
    return C.__annotations__
```

**Comment by scoder** [comment]
I don't think this is done, is it?

**Comment by seandstewart** [comment]
Apologies, I was going through old tickets I'd reported and closing them out if they were old - feel free to leave it open.
