### ISSUE TITLE
32 bit manylinux platform: OverflowError: long int too large to convert to int (line 124, in Cython.Plex.Machines.Node.__hash__)

### ISSUE THREAD

**Issue by jamadden** [cython/cython#3840]
This was reported before in https://github.com/cython/cython/issues/3793, which was marked as a duplicate of https://github.com/cython/cython/issues/3659 and then closed in https://github.com/cython/cython/commit/ef423d1e9c9e67a24db0e61b7b334983858fa581, which was released as part of 3.0a6. However, it still occurs in that version.

I do *not* see this when I build for 32-bit Windows. (e.g., https://ci.appveyor.com/project/jamadden/gevent/build/job/ja58vp06o5av6h46)

**Describe the bug**

Attempting to compile gevent in the 32-bit manylinux image under Python 2 using 3.0a6 results in a stack trace. Full [Travis CI output is here](https://travis-ci.org/github/gevent/gevent/jobs/729367481). Excerpt:
```
Successfully installed cffi-1.14.3 cython-3.0a6 greenlet-0.4.17 pycparser-2.20
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    from _setupares import ARES
  File "/tmp/build/gevent/_setupares.py", line 129, in <module>
    ARES = cythonize1(ARES)
  File "/tmp/build/gevent/_setuputils.py", line 260, in cythonize1
    common_utility_include_dir=COMMON_UTILITY_INCLUDE_DIR,
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1110, in cythonize
    cythonize_one(*args)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 575, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    pipeline = Pipeline.create_pyx_pipeline(context, options, result)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 252, in create_pyx_pipeline
    create_pipeline(context, mode, exclude_classes=exclude_classes),
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 144, in create_pipeline
    from .ParseTreeTransforms import WithTransform, NormalizeTree, PostParse, PxdPostParse
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1632, in <module>
    class AnalyseDeclarationsTransform(EnvTransform):
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1640, in AnalyseDeclarationsTransform
    """, level='c_class', pipeline=[NormalizeTree(None)])
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/TreeFragment.py", line 235, in __init__
    mod = t = parse_from_strings(name, fmt_code, fmt_pxds, level=level, initial_pos=initial_pos)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/TreeFragment.py", line 75, in parse_from_strings
    scope = scope, context = context, initial_pos = initial_pos)
  File "Cython/Compiler/Scanning.py", line 306, in Cython.Compiler.Scanning.PyrexScanner.__init__
  File "Cython/Compiler/Scanning.py", line 35, in Cython.Compiler.Scanning.get_lexicon
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Compiler/Lexicon.py", line 147, in make_lexicon
    (Eof, Method('eof_action'))
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Plex/Lexicons.py", line 129, in __init__
    nfa, default_initial_state, spec, token_number)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Plex/Lexicons.py", line 162, in add_token_to_machine
    match_bol=1, nocase=0)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Plex/Regexps.py", line 301, in build_machine
    re.build_machine(m, s1, s2, match_bol, nocase)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Plex/Regexps.py", line 340, in build_machine
    initial_state = self.build_opt(m, initial_state, BOL)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Plex/Regexps.py", line 136, in build_opt
    initial_state.link_to(s)
  File "Cython/Plex/Machines.py", line 86, in Cython.Plex.Machines.Node.link_to
  File "Cython/Plex/Machines.py", line 82, in Cython.Plex.Machines.Node.add_transition
  File "Cython/Plex/Transitions.py", line 60, in Cython.Plex.Transitions.TransitionMap.add
  File "Cython/Plex/Machines.py", line 124, in Cython.Plex.Machines.Node.__hash__
OverflowError: long int too large to convert to int
```

**To Reproduce**

(Check that the `scripts/releases/make-manylinux` script is using the `DOCKER_IMAGE` environment variable and doesn't have the 64-bit image hard-coded on the next-to-last line. That was a bug in older versions that I have fixed in a branch which should be merged later today.)

```console
$ git clone gevent/gevent
Cloning into 'gevent'...
...
$ cd gevent
$ export DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
$ docker pull $DOCKER_IMAGE
Using default tag: latest
latest: Pulling from pypa/manylinux2010_i686
...
Digest: sha256:e08482836e0dc2ea0789fb51f82918bc612463a318a82702e503afe8b9f4418d
Status: Downloaded newer image for quay.io/pypa/manylinux2010_i686:latest
quay.io/pypa/manylinux2010_i686:latest
$ bash scripts/releases/make-manylinux
...
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: manylinux2010, 32-bit x86
 - Python version: Tested to produce the error in 2.7, 3.5, 3.6 and 3.8.
 - Cython version 3.0a6

**Comment by da-woods** [comment]
On a closer look this seems like a similar (but different) bug to https://github.com/cython/cython/issues/3659. I'm struggling to work out where `py_hash_t` is defined but it seems like `id` can't reliably be fitted in it on 32 bit Windows.

**Comment by scoder** [comment]
> I'm struggling to work out where py_hash_t is defined

https://github.com/python/cpython/blob/de4304dad8e035dbbb57d653e685312eead816df/Include/pyport.h#L112-L114

**Comment by da-woods** [comment]
The default hash seems to be based on `id(self)//16` which I'd think avoids this problem?

**Comment by scoder** [comment]
> The default hash seems to be based on `id(self)//16` which I'd think avoids this problem?

Ah, yes, good call. Depending on the actual (virtual) memory address, the ID can definitely be quite a large unsigned long value.

**Comment by scoder** [comment]
I chose to use `id(self) & maxint` since IDs in PyPy used a simple counter, last I looked. With `maxint == 2**31-1`, this should still be plenty enough for the scanner states.
