### ISSUE TITLE
[BUG] Exception SystemError when using cythonized library with pandarallel

### ISSUE THREAD

**Issue by LuciusV** [cython/cython#3908]
**Describe the bug**
When I use pandarallel in cythonized .so file, I get 

Traceback (most recent call last):
File "./runtest.py", line 6, in 
parallel_process()
File "libtest.py", line 19, in libtest.parallel_process
File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 462, in closure
map_result,
File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 396, in get_workers_result
results = map_result.get()
File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
raise self._value
SystemError: unknown opcode 

**To Reproduce**
Code to reproduce the behaviour:
```To reproduce:

Create library.py and define any function inside which uses parallel_apply on any pandas dataframe
Create run.py, which imports that function from library and runs. It will run normally.
cythonize -i library.py and try to run run.py - it will fail with SystemError: unknown opcode
Without pandarallelization, cythonized library works without exception.
```

**Expected behavior**
Cythoinzed function works normally

**Environment (please complete the following information):**
 - OS: Linux
 - Python version  3.7.3
 - Cython version 0.29.21
 - Pandas 1.1.1
 - Pandarallel 1.5.1

**Additional context**
I am not sure its cython fault or pandarallel fault so I created reports in both projects: https://github.com/nalepae/pandarallel/issues/118

**Comment by da-woods** [comment]
> Create library.py and define any function inside which uses parallel_apply on any pandas dataframe
> Create run.py, which imports that function from library and runs. It will run normally.
> cythonize -i library.py and try to run run.py - it will fail with SystemError: unknown opcode
> Without pandarallelization, cythonized library works without exception.

This is all too vague to be useful. You should assume that people don't know how to use `pandarallel`. Should the function act on the whole dataframe, a row, a column, a cell?

**Comment by LuciusV** [comment]
Sorry for being not clear. I prepared concrete code examples:


[cython_pandarallel_fail.tar.gz](https://github.com/cython/cython/files/5528959/cython_pandarallel_fail.tar.gz)

First they can be run by `python test_run1.py` and so on to see that all works with normal input.
Then, if compile lib1.py lib2.py lib3.py with `cythonize -3 -i lib1.py` every of them will fail with

  `File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 440, in closure
    kwargs,
  File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 303, in get_workers_args
    zip(input_files, output_files, chunk_lengths)
  File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 302, in <listcomp>
    for index, (input_file, output_file, chunk_length) in enumerate(
  File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/pandarallel.py", line 214, in wrapper
    time=time,
  File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/utils/inliner.py", line 34, in wrapper
    return function(*args, **kwargs)
  File "/home/youjin/virtualenvs/science/lib/python3.7/site-packages/pandarallel/utils/inliner.py", line 467, in inline
    func.__closure__,
TypeError: function() argument 1 must be code, not None`

**Comment by da-woods** [comment]
So I get

```
Traceback (most recent call last):
  File "test_run1.py", line 6, in <module>
    result = test_func1()
  File "lib1.py", line 10, in lib1.test_func1
    df["value"] = df["arg_x"].parallel_apply(lambda x: np.sin(x))
  File "<cropped>/pandarallel/pandarallel.py", line 431, in closure
    workers_args, chunk_lengths, input_files, output_files = get_workers_args(
  File "<cropped>/pandarallel/pandarallel.py", line 286, in get_workers_args
    workers_args = [
  File "<cropped>/pandarallel/pandarallel.py", line 295, in <listcomp>
    progress_wrapper(
  File "<cropped>/pandarallel/pandarallel.py", line 205, in wrapper
    wrapped_func = inline(
  File "<cropped>/pandarallel/utils/inliner.py", line 34, in wrapper
    return function(*args, **kwargs)
  File "<cropped>/pandarallel/utils/inliner.py", line 462, in inline
    new_func = FunctionType(
TypeError: function() argument 'code' must be code, not None
```

This is with Python 3.8, Cython 0.29.21.

What it looks like is that `pandarallel` goes through an [elaborate proceedure to try to introspect to code object of the Python lambda](https://github.com/nalepae/pandarallel/blob/master/pandarallel/utils/inliner.py) and do something clever with it. Since Cython lambdas do not have a code object then this fails.

If I changed to using  a function rather than a lambda then it does have a code object (although not one that contains any valid Python code) and I get the "unknown opcode" error. In this case `pandarallel`'s introspection proceedure has converted it into nonsense.

Pretty sure this is a bug/limitation in `pandarallel` - it assumes that everything it receives is a Python callable with introspectable Python code objects and makes no effort to do sanity checks if they aren't. Clearly Cython functions are never going to meet this criteria.

**Comment by LuciusV** [comment]
Thank you so much for detailed introspection!
