### ISSUE TITLE
[BUG] python setup.py build_ext -j4 fails on macOS with Python 3.8+

### ISSUE THREAD

**Issue by adamjstewart** [cython/cython#3973]
**Describe the bug**

It's currently not possible to compile Cython in parallel on macOS with Python 3.8+

**To Reproduce**

```console
$ python setup.py build_ext -j4
Unable to find pgen, not compiling formal grammar.
running build_ext
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Plex/Scanners.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Plex/Actions.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/Scanning.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/Visitor.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/FlowControl.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Runtime/refnanny.pyx because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/FusedNode.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Tempita/_tempita.py because it changed.
Unable to find pgen, not compiling formal grammar.
Unable to find pgen, not compiling formal grammar.
Unable to find pgen, not compiling formal grammar.
Unable to find pgen, not compiling formal grammar.
running build_ext
running build_ext
running build_ext
running build_ext
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Plex/Scanners.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Plex/Actions.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/Scanning.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/Visitor.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/FlowControl.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Runtime/refnanny.pyx because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Compiler/FusedNode.py because it changed.
Compiling /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Tempita/_tempita.py because it changed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/setup.py", line 228, in <module>
    setup(
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/py-setuptools-50.3.2-5wqt7cliuz2gugkukxe3gitnfwaeviyk/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Distutils/build_ext.py", line 20, in finalize_options
    self.distribution.ext_modules[:] = cythonize(
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-cython-0.29.21-tiuclkwj7x2mxlolbc7yvkeeo5umquce/spack-src/Cython/Build/Dependencies.py", line 1078, in cythonize
    pool = multiprocessing.Pool(
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.9.1-gzkonfmwz2asjl54j245h7hyzowrtzhr/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
...
```

**Expected behavior**

I would expect to be able to build Cython in parallel.

**Environment:**
 - OS: macOS
 - Python version: 3.9.1
 - Cython version: 0.29.21

**Additional context**

As you're probably aware, the `multiprocessing` package changed in Python 3.8 and now defaults to the _spawn_ start method on macOS: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

I'm guessing this is the issue, although I could be wrong.

**Comment by adamjstewart** [comment]
Interestingly, `python setup.py build -j4` works fine, not sure what's different about `build_ext`.

**Comment by da-woods** [comment]
Cython does override it to parallelize itself. So it's definitely plausible that they behave differently.

**Comment by scoder** [comment]
> I would expect to be able to build Cython in parallel.

The traceback suggests that it already compiles in parallel by default. What happens here is that it tries to invoke multiprocessing from a spawned subprocess, which then fails.

As the joke goes, don't do what you're doing here, and you'll be fine.

**Comment by adamjstewart** [comment]
> As the joke goes, don't do what you're doing here, and you'll be fine.

In general I agree with this sentiment, but in this case I'm concerned about consistency. If `python setup.py build_ext -j1` doesn't build in serial and `python setup.py build_ext -j4` doesn't build at all, that's a serious bug in my mind.

For more background, I'm a developer for the [Spack](https://spack.io) package manager. Spack has a `PythonPackage` base class that builds all of our Python packages. In https://github.com/spack/spack/pull/20765 I'm trying to enable parallel builds for all of our packages. So far Cython is the only package I've found that doesn't build correctly when invoked with `-j4`.

I'm guessing https://github.com/cython/cython/blob/master/Cython/Distutils/build_ext.py is the source of the default parallelism? I can understand wanting parallelism by default, but it would be good to also support `-j` properly. Any ideas how to do this?

**Comment by adamjstewart** [comment]
I'm unable to reproduce this on `master`, so it's possible that it's already been fixed. If you can point me to the commit that might have fixed it I can try backporting a patch.

**Comment by da-woods** [comment]
> I'm unable to reproduce this on `master`, so it's possible that it's already been fixed. If you can point me to the commit that might have fixed it I can try backporting a patch.

`git bisect` is usually quickest way to track this kind of thing down (apologies if you already know this...)

**Comment by adamjstewart** [comment]
I'm _aware of_ `git bisect`, although I must admit I've never used it. In this case, I'm not sure if `git bisect` would help, as the "failure" case here ends up in an infinite loop instead of crashing with a non-zero exit code.

**Comment by scoder** [comment]
The master branch is very different in many ways, most of which isn't suitable for a backport to a maintenance/legacy branch. If you can work around it for now, I'd prefer that over adding more differences to the legacy branch.

**Comment by da-woods** [comment]
> I'm _aware of_ `git bisect`, although I must admit I've never used it. In this case, I'm not sure if `git bisect` would help, as the "failure" case here ends up in an infinite loop instead of crashing with a non-zero exit code.

Provided you can stop the loop with `<Ctrl-C>` then it's fine. Marking whether a commit is good/bad in a manual process rather than taken from the exit code.

(It may be irrelevant if a backport isn't possible, but `git bisect` should be suitable provided you can see if a commit has worked fairly quickly)

**Comment by webknjaz** [comment]
Looks like this is https://github.com/cython/cython/pull/3263#issuecomment-3358122635 / https://github.com/cython/cython/issues/7146.

**Comment by webknjaz** [comment]
#7183 should complete the fix started in #3263.
