### ISSUE TITLE
[BUG] Compiler crash in AnalyseDeclarationsTransform

### ISSUE THREAD

**Issue by maxbachmann** [cython/cython#4012]
**Describe the bug**
The following code:
```cython
ctypedef fused char_types:
    int
    char

cdef const char_types[:] example(object test):
    pass
```
causes a compiler crash (see below)

**Expected behavior**
A error message about the syntax error instead of a compiler crash is expected

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.9.1
 - Cython version: 0.29.21

**Additional context**
error message:
```
   ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rov9565e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rov9565e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ef1mkj79
         cwd: /tmp/pip-req-build-rov9565e/
    Complete output (52 lines):
    /home/max/.local/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-req-build-rov9565e/src/test.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    ctypedef fused char_types:
        int
        char
    
    cdef const char_types[:] example(object test):
                         ^
    ------------------------------------------------------------
    
    src/test.pyx:5:22: Compiler crash in AnalyseDeclarationsTransform
    
    File 'ModuleNode.py', line 124, in analyse_declarations: ModuleNode(test.pyx:1:0,
        full_module_name = 'rapidfuzz.test')
    File 'Nodes.py', line 431, in analyse_declarations: StatListNode(test.pyx:1:0)
    File 'Nodes.py', line 2350, in analyse_declarations: CFuncDefNode(test.pyx:5:5,
        modifiers = [...]/0,
        visibility = 'private')
    File 'Nodes.py', line 1091, in analyse: MemoryViewSliceTypeNode(test.pyx:5:22,
        name = 'memoryview')
    
    Compiler crash traceback from this point on:
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 1091, in analyse
        self.type = PyrexTypes.MemoryViewSliceType(base_type, axes_specs)
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Compiler/PyrexTypes.py", line 625, in __init__
        self.dtype_name = Buffer.mangle_dtype_name(self.dtype)
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Compiler/Buffer.py", line 631, in mangle_dtype_name
        return prefix + dtype.specialization_name()
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Compiler/PyrexTypes.py", line 57, in specialization_name
        common_subs = (self.empty_declaration_code()
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Compiler/PyrexTypes.py", line 51, in empty_declaration_code
        self._empty_declaration = self.declaration_code('')
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Compiler/PyrexTypes.py", line 1582, in declaration_code
        return self.const_base_type.declaration_code("const %s" % entity_code, for_display, dll_linkage, pyrex)
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Compiler/PyrexTypes.py", line 1649, in declaration_code
        raise Exception("This may never happen, please report a bug")
    Exception: This may never happen, please report a bug
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-rov9565e/setup.py", line 55, in <module>
        ext_modules = cythonize([
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
        cythonize_one(*args)
      File "/home/max/.local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: src/test.pyx
    Compiling src/test.pyx because it changed.
    [1/1] Cythonizing src/test.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by maxbachmann** [comment]
This might be https://github.com/cython/cython/pull/3853 which is not in my release yet

**Comment by da-woods** [comment]
> This might be #3853 which is not in my release yet

This does look to be fixed in the most recent master (which correctly reports `Return type is not specified as argument type`) so I think you're right. I'll close this.
