### ISSUE TITLE
[BUG] AttributeError: 'PyObjectType' object has no attribute 'exception_value'

### ISSUE THREAD

**Issue by kumaraditya303** [cython/cython#4070]
**Describe the bug**
I am getting the following error upon cython compilation:
```console
Traceback (most recent call last):
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kumar Aditya\AppData\Local\Programs\Python\Python39\Scripts\cython.exe\__main__.py", line 7, in <module>
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py", line 840, in setuptools_main
    return main(command_line = 1)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py", line 858, in main
    result = compile(sources, options)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py", line 780, in compile
    return compile_multiple(source, options)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py", line 757, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Pipeline.py", line 335, in run
    return phase(data)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Pipeline.py", line 52, in generate_pyx_code_stage

    module_node.process_implementation(options, result)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\ModuleNode.py", line 143, in process_implementati
on
    self.generate_c_code(env, options, result)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\ModuleNode.py", line 385, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Nodes.py", line 442, in generate_function_definit
ions
    stat.generate_function_definitions(env, code)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Nodes.py", line 4858, in generate_function_defini
tions
    self.body.generate_function_definitions(self.scope, code)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Nodes.py", line 442, in generate_function_definit
ions
    stat.generate_function_definitions(env, code)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Nodes.py", line 442, in generate_function_definit
ions
    stat.generate_function_definitions(env, code)
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Nodes.py", line 2033, in generate_function_defini
tions
    err_val = self.error_value()
  File "c:\users\kumar aditya\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Nodes.py", line 2671, in error_value
    return self.entry.type.exception_value
AttributeError: 'PyObjectType' object has no attribute 'exception_value'

```

**Expected behavior**
It should compile without error

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS] WIndows
 - Python version [e.g. 3.8.4] 3.9.2
 - Cython version [e.g. 0.29.18] 0.29.22

**Additional context**

**Comment by da-woods** [comment]
It's coming from https://github.com/kumaraditya303/python-llhttp/blob/c8aa2bf41f565d670e583608629e4bb0646f3f54/llhttp/_llhttp.pyx#L95

There's two things that are potentially wrong there - first that you say that you'll return an `int` but don't return anything, and second that it appears to override https://github.com/kumaraditya303/python-llhttp/blob/c8aa2bf41f565d670e583608629e4bb0646f3f54/llhttp/_llhttp.pyx#L16 which declared `_on_header_value` as an attribute of type `object`.

With that said, you shouldn't get a compiler crash so we should aim to fix that.
