### ISSUE TITLE
[BUG] More Python 3.10 test failures

### ISSUE THREAD

**Issue by vstinner** [cython/cython#4100]
Follow-up of #4046.

(*) Enum formatting:

```
FAIL: cpdef_enums ()
Doctest: cpdef_enums
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vstinner/python/master/Lib/doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for cpdef_enums
  File "/home/vstinner/dev/cython/TEST_TMP/run/c/cpdef_enums/cpdef_enums.cpython-310d-x86_64-linux-gnu.so", line 1, in cpdef_enums

----------------------------------------------------------------------
File "/home/vstinner/dev/cython/TEST_TMP/run/c/cpdef_enums/cpdef_enums.cpython-310d-x86_64-linux-gnu.so", line 39, in cpdef_enums
Failed example:
    str(PyxEnum.TWO)
Expected:
    'PyxEnum.TWO'
Got:
    'TWO'

======================================================================
FAIL: test_formatting_with_enum (test_unicode.UnicodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/run/test_unicode.pyx", line 1473, in test_unicode.UnicodeTest.test_formatting_with_enum (test_unicode.c:112176)
    self.assertEqual("%s, %s" % (Str.ABC, Str.ABC),
AssertionError: 'ABC, ABC' != 'Str.ABC, Str.ABC'
- ABC, ABC
+ Str.ABC, Str.ABC
```

(*) optimised_pow2_inplace:

```
FAIL: optimised_pow2_inplace (powop)
Doctest: powop.optimised_pow2_inplace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vstinner/python/master/Lib/doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for powop.optimised_pow2_inplace
  File "/home/vstinner/dev/cython/TEST_TMP/run/c/powop/powop.cpython-310d-x86_64-linux-gnu.so", line unknown line number, in optimised_pow2_inplace

----------------------------------------------------------------------
File "/home/vstinner/dev/cython/TEST_TMP/run/c/powop/powop.cpython-310d-x86_64-linux-gnu.so", line ?, in powop.optimised_pow2_inplace
Failed example:
    optimised_pow2_inplace('test')
Expected:
    Traceback (most recent call last):
    TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'str'
Got:
    Traceback (most recent call last):
      File "/home/vstinner/python/master/Lib/doctest.py", line 1337, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest powop.optimised_pow2_inplace[9]>", line 1, in <module>
        optimised_pow2_inplace('test')
      File "tests/run/powop.pyx", line 161, in powop.optimised_pow2_inplace (powop.c:2990)
        x **= n
    TypeError: unsupported operand type(s) for **=: 'int' and 'str'
```

(*) test_embed:

```
FAIL: test_embed (__main__.EmbedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vstinner/dev/cython/runtests.py", line 1797, in test_embed
    self.assertEqual(0, os.system(
AssertionError: 0 != 512
```

**Comment by vstinner** [comment]
There are also many gdb failures like "FAIL: test_updown (Cython.Debugger.Tests.test_libcython_in_gdb.TestUpDown)" but I prefer to ignore them for now (use a different issue for gdb). I don't know if these failures are specific to Python 3.10.

**Comment by tirkarthi** [comment]
Enum related changes were made in https://github.com/python/cpython/pull/22392

**Comment by vstinner** [comment]
Enum formatting: I created https://github.com/cython/cython/pull/4101 to fix it.

**Comment by vstinner** [comment]
> Enum related changes were made in python/cpython#22392

Right. It's a deliberate change: https://docs.python.org/dev/whatsnew/3.10.html#enum

**Comment by vstinner** [comment]
(*) optimised_pow2_inplace: I wrote https://github.com/cython/cython/pull/4102 to fix the test.

**Comment by scoder** [comment]
Should all be resolved now.

**Comment by scoder** [comment]
(Except for `test_embed`)
