### ISSUE TITLE
[BUG] CyGDB doesn't deal properly with .pxi files.

### ISSUE THREAD

**Issue by amol-** [cython/cython#4174]
**Describe the bug**
Running `cy list` against a breakpoint pointing to a function that was defined into a `.pxi` files leads to an empty (or even wrong) source code

**To Reproduce**
The pyarrow project has a module `lib.pyx` that is defined as a series of included `.pxi` files
```
...
# DataType, Field, Schema
include "types.pxi"

# Array scalar values
include "scalar.pxi"

# Array types
include "array.pxi"
...
```
If I set a debug point to the `pyarrow.lib.Array.to_numpy` method which is declared in the `array.pxi` source file (as the whole `Array` class is there) then `cygdb`  is unable to understand what's the source code
```
(gdb) cy break pyarrow.lib.Array.to_numpy
Function "__pyx_pw_7pyarrow_3lib_5Array_62to_numpy" not defined.
Breakpoint 1 (__pyx_pw_7pyarrow_3lib_5Array_62to_numpy) pending.
(gdb) cy run
 Thread 2 hit Breakpoint 1, 0x000000010681f214 in __pyx_pf_7pyarrow_3lib_5Array_61to_numpy(__pyx_obj_7pyarrow_3lib_Array*, _object*, _object*) () from /Users/amol/arrow/python/pyarrow/lib.cpython-39d-darwin.so
[New Thread 0x2703 of process 81180]
[New Thread 0x2503 of process 81180]
(gdb) cy list
(gdb) cy list
Traceback (most recent call last):
  File "/home/amol/arrow/cython/Cython/Debugger/libpython.py", line 1980, in wrapper
    return function(*args, **kwargs)
  File "/home/amol/arrow/cython/Cython/Debugger/libcython.py", line 1097, in invoke
    source = sd.get_source(lineno - 5, lineno + 5, mark_line=lineno,
  File "/home/amol/arrow/cython/Cython/Debugger/libcython.py", line 83, in wrapper
    return function(self, frame, *args, **kwargs)
  File "/home/amol/arrow/cython/Cython/Debugger/libcython.py", line 243, in get_source_desc
    lineno = filename_and_lineno[1]
AssertionError
Python Exception <type 'exceptions.AssertionError'> : 
Error occurred in Python.
```

The problem seems to occur because `get_source_desc` ( https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/Cython/Debugger/libcython.py#L237 ) si comparing that the filename of the module where the function was compiled to matches with the filename where the function was declared. In case of `.pxi`  this is obviously not true as the function is declared in one place and is then injected into another one.

In my case `/home/amol/arrow/arrow/python/pyarrow/lib.pyx` VS `/home/amol/arrow/arrow/python/pyarrow/array.pxi`

**Expected behavior**
`cy list` uses the file where the function was declared into

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.9.4
 - Cython version 3.0a6
 - GDB version 9.1

**Comment by amol-** [comment]
With the propsed PR in place `cy list` seem to work correctly

```
pyarrow/tests/test_array.py::test_to_numpy_zero_copy 
Thread 1 "python" hit Breakpoint 1, __pyx_pf_7pyarrow_3lib_5Array_61to_numpy (__pyx_v_self=0x4310ab <function_code_fastcall+513>, __pyx_v_zero_copy_only=None, __pyx_v_writable=<unknown at remote 0x7ffff52d3440>) at /home/amol/arrow/arrow/python/build/temp.linux-x86_64-3.9-pydebug/lib.cpp:99930
99930	static PyObject *__pyx_pf_7pyarrow_3lib_5Array_61to_numpy(struct __pyx_obj_7pyarrow_3lib_Array *__pyx_v_self, PyObject *__pyx_v_zero_copy_only, PyObject *__pyx_v_writable) {
1134        def to_numpy(self, zero_copy_only=True, writable=False):
(gdb) cy list
  1129            values = self.to_numpy(zero_copy_only=False)
  1130            if dtype is None:
  1131                return values
  1132            return values.astype(dtype)
  1133    
> 1134        def to_numpy(self, zero_copy_only=True, writable=False):
  1135            """
  1136            Return a NumPy view or copy of this array (experimental).
  1137    
  1138            By default, tries to return a view of this array. This is only
```
