### ISSUE TITLE
[BUG] Cython cannot find files under 2 levels of directories

### ISSUE THREAD

**Issue by Bluenix2** [cython/cython#4330]
**Describe the bug**
Cython raises a `ValueError` when trying to specify a file under 2 levels of directories.

**To Reproduce**
With the following directory tree:
```py
primes/
├─ core/
│  ├─ example.py
setup.py
```
And `example.py` having the following content from [Basic Tutorial](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html).
```py
import cython


def primes(nb_primes: cython.int):
    i: cython.int
    p: cython.int[1000]

    if nb_primes > 1000:
        nb_primes = 1000

    if not cython.compiled:  # Only if regular Python is running
        p = [0] * 1000       # Make p work almost like a C array

    len_p: cython.int = 0  # The current number of elements in p.
    n: cython.int = 2
    while len_p < nb_primes:
        # Is n prime?
        for i in p[:len_p]:
            if n % i == 0:
                break

        # If no break occurred in the loop, we have a prime.
        else:
            p[len_p] = n
            len_p += 1
        n += 1

    # Let's copy the result into a Python list:
    result_as_list = [prime for prime in p[:len_p]]
    return result_as_list
```
Along with this `setup.py`:
```py
from Cython.Build import cythonize
from setuptools import setup


setup(
    packages=['primes'],
    ext_modules=cythonize(
        ['primes/core/example.py'],
        language_level=3
    ),
)
```

The following traceback can be seen:
```py
Traceback (most recent call last):
  File "C:\Users\%username%\Projects\cython-bug\venv\lib\site-packages\pep517\in_process\_in_process.py", line 349, in <module>
    main()
  File "C:\Users\%username%\Projects\cython-bug\venv\lib\site-packages\pep517\in_process\_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\%username%\Projects\cython-bug\venv\lib\site-packages\pep517\in_process\_in_process.py", line 117, in get_requires_for_build_wheel
    return hook(config_settings)
  File "C:\Users\%username%\AppData\Local\Temp\build-env-w894fpli\lib\site-packages\setuptools\build_meta.py", line 154, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "C:\Users\%username%\AppData\Local\Temp\build-env-w894fpli\lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "C:\Users\%username%\AppData\Local\Temp\build-env-w894fpli\lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 7, in <module>
    ext_modules=cythonize(
  File "C:\Users\%username%\AppData\Local\Temp\build-env-w894fpli\lib\site-packages\Cython\Build\Dependencies.py", line 965, in cythonize
    module_list, module_metadata = create_extension_list(
  File "C:\Users\%username%\AppData\Local\Temp\build-env-w894fpli\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\Users\%username%\AppData\Local\Temp\build-env-w894fpli\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'primes/core/example.py' doesn't match any files

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```
**Expected behavior**
I don't see any reason why this would not compile. I have tried both `python -m build` and `python setup.py build`.

**Environment (please complete the following information):**
 - OS: Windows
 - Python version: Python 3.9.5
 - Cython version: Tested on most recent on PyPi as well as installed directly from GitHub

**Comment by Bluenix2** [comment]
This is future me!

I don't exactly know what I changed to get it working, but `python setup.py build_ext --inplace` as well as `python setup.py build` both work running the code again.

I do have a hypothesis as to why `python -m build` is failing.. because of how it runs twice, and creates a file called `SOURCES.txt`, the second time Cython may not have the permission required. See the file for the above case becomes:
```
pyproject.toml
setup.py
UNKNOWN.egg-info/PKG-INFO
UNKNOWN.egg-info/SOURCES.txt
UNKNOWN.egg-info/dependency_links.txt
UNKNOWN.egg-info/top_level.txt
primes/core/example.c
primes/core/example.c
```
`primes/core/example.py` isn't present in this file so Cython may not have permission to open it. I'll have to investigate more to see if this is the case, just throwing it out there.

Note that my `pyproject.toml` looks like this:
```toml
[build-system]
requires = ["setuptools", "wheel", "git+https://github.com/cython/cython.git"]
```

**Comment by mulkr** [comment]
I had a similar problem to this, but I have a workaround.

I have a `.pyx` file (though only under 1 diretory), and I got a similar "doesn't match any files" error.
I tried adding the `.pyx` file manually to `SOURCES.txt` like this:
```
dir/foo.cpp
dir/foo.pyx
```
And after re-running `python -m build` it worked.

I hope this workaround helps, or it can lead to a fix in the future.
Or maybe I am missing something... Then please correct me.

OS: Windows 10
Python version: 3.11.0
Cython version: 3.0.11
