### ISSUE TITLE
[BUG] Constants defined in .pxd are not available in .pyx?

### ISSUE THREAD

**Issue by leofang** [cython/cython#4369]
**Describe the bug**
As title.

**To Reproduce**
```cython
# test_def_scope.pxd

DEF MY_CONST = 25
cdef int my_const = MY_CONST
my_const2 = 25

# -------------------
# test_def_scope.pyx

# distutils: language = c++

def get():
    print(my_const)
    print(my_const2)
```
On command line:
```
$ cythonize -i -3 test_def_scope.pyx 
$ python -c "import test_def_scope; test_def_scope.get()"
```
I got an unexpected output:
```
0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test_def_scope.pyx", line 5, in test_def_scope.get
    print(my_const2)
NameError: name 'my_const2' is not defined
```

**Expected behavior**
The output should be
```
25
25
```
I hope I am not being silly due to staying up late...😅

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.8.10
 - Cython version: 0.29.24

**Comment by da-woods** [comment]
I believe this issue is:
```
cdef int my_const = MY_CONST
```
is a C declaration - it declares a C level variable with an initial value of `MY_CONST`.
```
my_const2 = 25
```
is an executable bit of Python code. It creates the Python variable `my_const2` by assigning to the module dict. It is not something that Cython can usefully use at _compile_ time, and therefore it doesn't belong in a .pxd file.
```
cdef object my_const2 = 25
```
would probably work fine (I haven't tested it though), but wouldn't be accessible from Python.

Essentially it's the usual issue that Cython is a weird mix of run-time and compile-time features and it's sometimes hard to know which one you're using.

I'll tag this as "error reporting" since we should probably tell you that it shouldn't be in the pxd.

**Comment by leofang** [comment]
Hmmm... That's odd @da-woods, I am getting more confused. Quoting your notes from [our earlier discussion](https://github.com/cython/cython/issues/3959#issuecomment-753455240):
> 1. Module-level cdef variables can always be cimported
> 2. Module-level variables defined in the normal Python way (abc = "something", no cdef) can always be imported, and are Python objects.

I'd expect both `my_const` and `my_const2` to work. What makes the situation different?

**Comment by leofang** [comment]
Note: I also tried creating another module (say `test_def_scope_blahblah.pyx`) and cimporting/importing `my_const`/`my_const2` from `test_def_scope`, and the result is the same.

**Comment by da-woods** [comment]
> What makes the situation different?

The .pxd file is _only_ for things that can be  cimported. It does not generate any code that is run at module import time[*]. Therefore the Python variable `my_const2` is never initialized.

[*] This isn't _100%_ true, but is pretty close.

**Comment by leofang** [comment]
Thanks, @da-woods. This is very subtle. Also, the reason that `my_const` is still unclear to me. 

Moreover, @kmaehashi has kindly reminded me that if I declare `my_const` as an enum, so instead of 
```cython
cdef int my_const = MY_CONST
```
we do 
```cython
cdef enum: my_const = MY_CONST
```
 it'd work just fine. Something must be wrong here...

**Comment by da-woods** [comment]
I think I'd missed the point slightly and thought that the `my_const` part of the example did work.... Sorry! I'd have to look and work out what's happening, but it could be that Cython splits it into declaring the variable at compile time, then running the assignment in the module init function at runtime (and the latter doesn't happen in a pxd)

The enum should definitely be fine - that has to be set at compile-time.

If the others don't work then we probably should be diagnosing them better - it's obviously unhelpful to accept code then ignore it
