### ISSUE TITLE
[BUG] Compiler crash in AnalyseExpressionsTransform parsing "if v1 in h1:" where h1 is a cython array.

### ISSUE THREAD

**Issue by jon-marks** [cython/cython#4483]
**Bug Trace**

```
Compiling solve_utils.pyx because it changed.
[1/1] Cythonizing solve_utils.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        print("True")
    else:
        print("False")

    v1 = 1
    if v1 in h1: pass  # h1 is a cython array of int
         ^
------------------------------------------------------------

solve_utils.pyx:30:10: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(solve_utils.pyx:3:0)
StatListNode.stats[0] = CFuncDefNode(solve_utils.pyx:5:5,
    args = [...]/2,
    modifiers = [...]/0,
    outer_attrs = [...]/2,
    visibility = 'private')
File 'Nodes.py', line 396, in analyse_expressions: StatListNode(solve_utils.pyx:7:4,
    is_terminator = True)
File 'Nodes.py', line 6785, in analyse_expressions: IfStatNode(solve_utils.pyx:30:4)
File 'Nodes.py', line 6831, in analyse_expressions: IfClauseNode(solve_utils.pyx:30:7)
File 'ExprNodes.py', line 651, in analyse_temp_boolean_expression: PrimaryCmpNode(solve_utils.pyx:30:10,
    operator = 'in',
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 12927, in coerce_to_boolean: PrimaryCmpNode(solve_utils.pyx:30:10,
    operator = 'in',
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "C:\Users\jm\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Compiler\ExprNodes.py", line 12927, in coerce_to_boolean
    if self.is_pycmp:
AttributeError: 'PrimaryCmpNode' object has no attribute 'is_pycmp'
Traceback (most recent call last):
  File "C:\Users\jm\Dropbox\Work\Python\test\setup.py", line 25, in <module>
    ext_modules = cythonize(["solve_utilsi.py", "solve_utils.pyx"],
  File "C:\Users\jm\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 1116, in cythonize
    cythonize_one(*args)
  File "C:\Users\jm\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 1283, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: solve_utils.pyx

Process finished with exit code 1
```

**Expected behavior**
I expected it not to crash

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version 3.9.7
 - Cython versions 0.29.24 and 3.0.0a9

**Additional context**

**Comment by da-woods** [comment]
Could you clarify: do you mean `h1` is typed as `cdef cython.view.array h1`, or something else?

**Comment by jon-marks** [comment]
Hi David, sorry it took so long for me to reply.

`cdef int h1[16]`

Interestingly, Cython crashes when checking for the presence of a value in the array and not when iterating over an array.

`for v in h1:`  

Compiles fine and produces good C code.

Thanks

**Comment by yuvalif** [comment]
any update on this topic?
i get the same error when using the "in" keyword to check for the presence of a value in an array when using cython.
