### ISSUE TITLE
[ENH] If we provide a C-API for pushing and popping introspectable frames, will you use it?

### ISSUE THREAD

**Issue by markshannon** [cython/cython#4484]
We (CPython) should provide a C API for pushing introspectable frames to the call stack, and you (Cython) should use them.

The vast majority of Python-to-Python calls do not need to create a heap allocated frame.
It would be good if Cython could use the same frame stack.

Seeing as Cython would be main user of this API, it seems sensible to have the discussion here, rather than on BPO.

The API could look something like this:
```C
typedef struct _ {
     PyObject *frame_descriptor;
     /* Some opaque fields */
     int line_number; // Writeable line number
     /* Some more opaque fields */
} InterpreterCFrame;

/* Calls these once each for each call to the Cython callable */
InterpreterCFrame *_Py_PushCFrame(PyObject *frame_descriptor);
void _Py_PopCFrame(InterpreterCFrame *frame); 

/* Call this once when the Cython module is loaded */
PyObject *_Py_CreateCFrameDescriptor(char *name, char *filename, int firstlineno);
```

`_Py_PushCFrame` and `_Py_PopCFrame`  should be fast, just changing the refcount of `frame_descriptor` and zeroing a few fields.

The exact layout of `InterpreterCFrame` might change from version to version, but code that only uses the public fields should recompile without changes.

The various opaque fields exists so that Python and C frames have mostly the same binary layout, to avoid runtime checks where possible.

**Comment by markshannon** [comment]
An alternative would be to drop the `_Py_CreateCFrameDescriptor` function, and take Cython callables as the argument to `_Py_PushCFrame`, provided they had the same API for use by `inspect` and `traceback`.

**Comment by da-woods** [comment]
I'm slightly reluctant to comment on this because it's a bit of code I don't understand very well but since no-one else has I'll make an attempt:

currently Cython only generates the frames for the tracebacks on demand (i.e. when there's an exception) rather than creating a frame at every function call. This is an optimization that I think we'd like to keep (for example, a lot of functions are "nogil unless an exception is thrown"). Your proposed scheme seems to be building it from the top down (so every call pushes and pops the frame) whereas our current one builds builds the traceback in reverse order as it propagates up.

> An alternative would be to drop the `_Py_CreateCFrameDescriptor` function, and take Cython callables as the argument to `_Py_PushCFrame`, provided they had the same API for use by `inspect` and `traceback`.

I don't think that would work as a general solution - we do try to create tracebacks from `cdef` functions which are implemented just as C functions and are visible only from within Cython (i.e. there is no associated Python object).

One final comment: it'd be useful if this could end up part of the limited API. Looking at the current code, I think we've struggled to implement anything in our (preliminary) limited API implementation.

**Comment by scoder** [comment]
Right. For cdef functions, any refcount overhead might already be too much, since it implies non-local interaction (and apparently a foreign C function call, which reduces the chance of efficient inlining). For functions with a Python interface, that's probably more acceptable. (Although `cpdef` functions already suffer from some overhead that we should reduce, not grow. Different issue…)

That said, I think the general idea of keeping frame references in a preallocated stack is a good one.

> The various opaque fields exists so that Python and C frames have mostly the same binary layout, to avoid runtime checks where possible.

Do they need to be opaque, though? The current frame object seems to have tracing related fields. Direct access to those would certainly be helpful.

ISTM that a frame fulfils several different use cases:
- tracebacks
- debugging
- introspection
- profiling
- tracing

Tracebacks are needed after the fact, when a function has terminated with an exception. That's costly anyway, and means that the last execution state can be filled in on exit, not on entry. That's what we currently do, and IMHO how it should be.

Debugging is a special need that is not performance critical. Here, we can expect users to C-define a macro that compiles in code to reconfigure the frame on each … source code line or so. Apart from that, linking this to profiling and tracing seems reasonable.

Live introspection – we've tied that to profiling support, which seems an acceptable trade-off (and can be enabled and disabled globally, as well as per function with a decorator).

Profiling doesn't really need a frame, I'd say. Just something that identifies the current piece of code / function. That could be an entirely static thing.

Tracing consists of two parts then, the static profiling part and the current state of execution, especially the line number. Probably also introspection capabilities, but those could be compiled in explicitly, as noted above.

So … could we have an interface that keeps data in C data structures, static for the metadata (ok, possibly a Python object here), C stack allocated for the live state, and then creates frames only when requested / needed ?

I mean, you're currently breaking extensions all over the place. Why not break the profiling / introspection tools and require them to call a "get me the current frame" function? Or, even better, any of several "get me property X of the current execution state" functions?

**Comment by markshannon** [comment]
> Do they need to be opaque, though? The current frame object seems to have tracing related fields. Direct access to those would certainly be helpful.

The fields are opaque because they would be invalid for a CFrame. We're not hiding things, just ensuring that the layout matches.
Frames have no tracing related fields.
https://github.com/python/cpython/blob/main/Include/internal/pycore_frame.h#L27

> Profiling doesn't really need a frame, I'd say. Just something that identifies the current piece of code / function. That could be an entirely static thing.

How could it be static? You need to map from the stack to the callable somehow.

> So … could we have an interface that keeps data in C data structures, static for the metadata (ok, possibly a Python object here), C stack allocated for the live state, and then creates frames only when requested / needed ?

We can't lazily allocate frames, because they are allocated on a (mostly) contiguous stack.


If a call is really too costly (I am skeptical of this, but let's say it is), then we could make `_Py_PushCFrame` and `_Py_PopCFrame` inline functions.

We could even say that it the responsibility of the caller to hold a reference to the `frame_descriptor` for the duration of the call, if you are really that worried about the incref/decref cost.

> I mean, you're currently breaking extensions all over the place.

Are we? Or are you using CPython internals in ways that you shouldn't? It's a matter of perspective.
This is why we need a well defined interface.

> Or, even better, any of several "get me property X of the current execution state" functions?

What properties are you interested in?

**Comment by da-woods** [comment]
Just to follow up a little on this statement and give a concrete example:

> If a call is really too costly (I am skeptical of this, but let's say it is), then we could make _Py_PushCFrame and _Py_PopCFrame inline functions.

> We could even say that it the responsibility of the caller to hold a reference to the frame_descriptor for the duration of the call, if you are really that worried about the incref/decref cost.

what I'm think of is something like this:

```
# cython specific syntax - C function, defined with C "inline", runs with without the GIL, return value of -1 may indicate an error
cdef inline int inner_func(int a, int b) nogil except? -1:
    return a/b  # can throw an exception if b==0

def doloop(int n):
    cdef int sum=0
    cdef int i
    with nogil:
        for i in range(n):
            sum += inner_func(100, i-10)
    return sum
```

This is a fairly artificial example but we have a loop that does does some long computation that runs without the GIL. It calls an optimized inner function that can throw a Python exception in rare circumstances but is otherwise run purely in C. If an exception is thrown then Cython re-acquires the GIL and issues a traceback that includes `inner_func`:

```
>>> example.doloop(20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example.pyx", line 9, in example.doloop
    sum += inner_func(100, i-10)
  File "example.pyx", line 2, in example.inner_func
    return a/b  # can throw an exception if b==0
ZeroDivisionError: integer division or modulo by zero
```

My understanding is that `inner_func` would need to call `_Py_PushCFrame` and `_Py_PopCFrame` on entry and exit and so it would need to re-acquire the GIL on every call. Or we'd need to abandon being able to give tracebacks from this type of function. Or only use `_Py_PushCFrame` and `_Py_PopCFrame` for regular "python-like" functions and continue using the existing version for "C-like" functions (which probably wouldn't be net benefit for maintainability).

------------------------

There are some benefits to your scheme though: one area where Cython isn't compatible with Python is code that inspects that stack usually fails (sympy is an example) because Cython only generates this information as the exception propagates upwards. Having a quick way of supporting that might be a benefit. (Although real code that does looks at the stack often wants more detailed introspection...)

**Comment by maxbachmann** [comment]
> This is a fairly artificial example but we have a loop that does does some long computation that runs without the GIL. It calls an optimized inner function that can throw a Python exception in rare circumstances but is otherwise run purely in C. If an exception is thrown then Cython re-acquires the GIL and issues a traceback that includes inner_func:

I use this pretty heavily in [RapidFuzz](https://github.com/maxbachmann/RapidFuzz) whenever I use multithreading, where each of the threads only requires the GIL in case of an exception (exceptions can usually only occur when the API is misused or memory runs out, so they are really exceptional). Obviously the application would run just fine without having tracebacks at all, but tracebacks are super helpful when debugging error reports. They are one of those features I did not know I needed and after switching to Cython do not want to miss anymore.
