### ISSUE TITLE
[HELP REQUESTED] Cython code not working with nogil 

### ISSUE THREAD

**Issue by SouvikGhosh05** [cython/cython#4496]
My C code:-
```c
//adder.c
#include<stdio.h>

//long adder_fromc(long a, long b);

long adder_fromc(long  a, long b){

    for (long i = 0; i < b; i++)
    {
        a += i;
    }
    return a;
}

/* long subtractor_fromc(long a, long b){
    for (long i = 0; i < b; i++)
    {
        a -= i;
    }
    return a;
}*/
```
Cython code:-
```cython

#loop_adder.pyx
cdef extern from "adder.c":

    long adder_fromc(long  a, long b)


cpdef long adder_py(long ac, long bc):

    

    value= adder_fromc(ac,bc)

    return value


cpdef long subtractor_py():



    cdef long a= 40000

    cdef long b= 10000000

    with nogil:

        for i in range(b):

            a-=i

    return a
```
setup.py file
```python

from setuptools import setup, Extension

from Cython.Build import cythonize





sourcefiles = ["loop_adder.pyx"]

ext_modules = [Extension("loop_adder", 

                        sourcefiles,

                        )]

setup(

    name='Hello world app',

    ext_modules=cythonize(

        ext_modules,

        annotate=True,

        language_level="3str"),

    zip_safe=False,

)

```

**Environment**
 - OS: Linux
 - Python version 3.8.10
 - Cython version 0.29.25

**Error**
```

Compiling loop_adder.pyx because it changed.
[1/1] Cythonizing loop_adder.pyx

Error compiling Cython file:
------------------------------------------------------------
...
cpdef long subtractor_py():

    cdef long a= 40000
    cdef long b= 10000000
    with nogil:
        for i in range(b):
                ^
------------------------------------------------------------

loop_adder.pyx:21:17: Iterating over Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cpdef long subtractor_py():

    cdef long a= 40000
    cdef long b= 10000000
    with nogil:
        for i in range(b):
                     ^
------------------------------------------------------------

loop_adder.pyx:21:22: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cpdef long subtractor_py():

    cdef long a= 40000
    cdef long b= 10000000
    with nogil:
        for i in range(b):
                     ^
------------------------------------------------------------

loop_adder.pyx:21:22: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cpdef long subtractor_py():

    cdef long a= 40000
    cdef long b= 10000000
    with nogil:
        for i in range(b):
                      ^
------------------------------------------------------------

loop_adder.pyx:21:23: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

    cdef long a= 40000
    cdef long b= 10000000
    with nogil:
        for i in range(b):
            a-=i
           ^
------------------------------------------------------------

loop_adder.pyx:22:12: Coercion from Python not allowed without the GIL

Error compiling Cython file:
------------------------------------------------------------
...

    cdef long a= 40000
    cdef long b= 10000000
    with nogil:
        for i in range(b):
            a-=i
           ^
------------------------------------------------------------

loop_adder.pyx:22:12: Operation not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

    cdef long a= 40000
    cdef long b= 10000000
    with nogil:
        for i in range(b):
            a-=i
           ^
------------------------------------------------------------

loop_adder.pyx:22:12: Converting to Python object not allowed without gil
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    ext_modules=cythonize(
  File "/home/souvik/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1103, in cythonize
    cythonize_one(*args)
  File "/home/souvik/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1226, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: loop_adder.pyx
```
If there is any Cython discord group, you can give me in here. I'm looking forward to join in your community for any further assistance. Thank you.

**Comment by da-woods** [comment]
Our main support channel is the Cython-users mailing list. Please do not use the bug tracker for support questions.

You probably just need to set the type of the for loop index. You should also consider if you _really_ need to release the GIL.

**Comment by SouvikGhosh05** [comment]
@da-woods Where can I get further help, there's no common group for the assistance? I'm currently beginner in Cython.

**Comment by da-woods** [comment]
As I said, the Cython-users mailing list (https://groups.google.com/g/cython-users) is our "official" support channel
