### ISSUE TITLE
[BUG] Converting a pointer from a C callback to a memory view causes an exception when trying to index into the array

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#4521]
**Describe the bug**
Miniaudio is a library which allows recording and playback of audio using a C callback which Miniaudio calls on another thread. This callback receives two pointers, input and output, which I am converting to Python memory view objects before passing them to my Python callback. However if the Python callback does something like: output[0] = 5, a strange exception is raised. However things like: output[...] = input work.
**To Reproduce**
I was enable to reproduce this bug by casting a pointer obtained by calling malloc to a memory view, so I made a zip file containing the test code along with Miniaudio which is a single header file.
[testcase.zip](https://github.com/cython/cython/files/7771461/testcase.zip)
Open it, cd into it, "cythonize -i -3 testcase.pyx", then open Python and "import testcase"
**Expected behavior**
The resulting array object is indexable.
**Environment (please complete the following information):**
Windows 10 (64-bit), Python 3.9.5, Cython 0.29.26

**Additional context**
The exception that's raised when indexing into the array is:
Traceback (most recent call last):
  File "stringsource", line 493, in View.MemoryView.memoryview.convert_item_to_object
struct.error: bad char in struct format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testcase.pyx", line 25, in testcase.data_callback
    print(data[0]) # exception
  File "stringsource", line 237, in View.MemoryView.array.__getitem__
  File "stringsource", line 414, in View.MemoryView.memoryview.__getitem__
  File "stringsource", line 495, in View.MemoryView.memoryview.convert_item_to_object
ValueError: Unable to convert item to object

If I explicitly declare a C variable of type float[:] in the testcase and return it to Python, that results in a ValueError with no additional information.

**Comment by da-woods** [comment]
I think this is a bit complex for me to reasonably manage to debug at least. It feels like a memory corruption error to me - somewhere along the line the format string that defines what type of array it is is getting overwritten?

One hint:

```
data = <float[:sample_count]>(input)
print(data[0])
```

This is creating a Python object that wraps the array `input`. `data[0]` goes through the standard Python object `__getitem__` lookup (i.e. is fairly slow).

What you probably want is 

```
cdef float[:] data
data = <float[:sample_count]>(input)
print(data[0])
```

You'll still create the Python object, but have the advantage of the faster direct memory lookup.

I doubt it'll solve your errors though.

**Comment by Keithcat1** [comment]
Assigning data as a Python object was pretty much intensional. The intention of:
print(data[0])
is to demonstrate how accessing the array from Python causes an error. Also, my Miniaudio bindings are creating arrays like this so they can be passed on to pure Python callback functions which can modify the data.
How could a format string get overwritten? Shouldn't it be a constant?
Actually, you've reminded me of something. Replace the line which indexes data with this and see if you get a UnicodeDecodeError:
print(memoryview(data).format)

**Comment by da-woods** [comment]
> How could a format string get overwritten? Shouldn't it be a constant?

Unintentionally, for example, by something writing beyond the end of an array. It is a guess at what might have gone wrong though

**Comment by Keithcat1** [comment]
I was somehow able to solve this problem by manually determining the
arrays info and calling cython.view.array() with the proper format
string, ETC.
I thought that at some point recently I managed to reproduce this
weird bug without Miniaudio, but I can't seem to duplicate it now.

**Comment by speth** [comment]
I've run into a similar problem using memoryviews when trying to enable automatic encoding/decoding of C strings as UTF-8. The `.pyx` file in the example provided by @Keithcat1 above includes the directives to enable this feature, as described [here](https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#auto-encoding-and-decoding):
```py
# cython: embedsignature=True, auto_pickle=False, c_string_encoding="utf-8", c_string_type=str
```
Removing the last two directives, I was able to compile and run the example. I think it was successful, anyway -- it just prints out a long stream of floating point numbers.

---

The case where I encountered this error is with a function like the following:
```pyx
cdef void callback_v_dp(PyFuncInfo& funcInfo, size_array1 sizes, double* arg):
    cdef double[:] view = <double[:sizes[0]]>arg if sizes[0] else None
```
where `size_array1` is a typedef for `std::array<size_t, 1>` and the exception thrown is a `ValueError` with no additional info.

If I try using `arg` to initialize a numpy array as:
```pyx
    data = np.asarray(<double[:sizes[0]]>arg)
```
Then I get the exception:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 0: unexpected end of data
```
which is what led me here. The code above works fine when not including these string encoding directives.
