### ISSUE TITLE
Cython.Compiler.Errors.CompilerError: main.pyx

### ISSUE THREAD

**Issue by DD-2703** [cython/cython#4549]
My `setup.py` file:
```python
from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules=cythonize("main.pyx"),
)
```
When I run this command:
`python setup.py build_ext --inplace`

I get this long error message:
```
Compiling main.pyx because it changed.
[1/1] Cythonizing main.pyx

Error compiling Cython file:
------------------------------------------------------------
...
i = 0  # Creating an iterating variable
^
------------------------------------------------------------

main.pyx:1:0: '2ndPerfectSquareAndCube.main' is not a valid module name
Traceback (most recent call last):
  File "C:\Coding\Python\SmallProjects\2ndPerfectSquareAndCube\setup.py", line 5, in <module>
    ext_modules=cythonize("main.pyx"),
  File "C:\Users\Darsh Dane\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 1103, in cythonize
    cythonize_one(*args)
  File "C:\Users\Darsh Dane\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 1226, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: main.pyx
```

If anyone is wondering, `i = 0` is the first line of my `main.pyx` file. Changing that line to `cdef int i = 0` doesn't work. I don't understand this error message. Can somebody tell me what to do?

Thank You! Any help is appreciated.

**Comment by scoder** [comment]
>main.pyx:1:0: '2ndPerfectSquareAndCube.main' is not a valid module name

You probably have an __init__.py file next to your main.pyx file, which makes the surrounding directory a package. However, a package name cannot start with a number, that's invalid in Python.
