### ISSUE TITLE
[BUG] Assigning an ndarray to a slice of a typed memoryview fails

### ISSUE THREAD

**Issue by c-f-h** [cython/cython#4626]
Assigning to a slice of a typed memoryview causes error "TypeError: only size-1 arrays can be converted to Python scalars".

This seems like such a fundamental issue that I'm wondering if I'm doing something wrong.

**To Reproduce**
Code to reproduce the behaviour:
```cython
# file: slicing.pyx
# cython: language_level=3
import numpy as np

cdef double[:] b
b = np.ones((10,))
b[3:6] = np.ones((3,))
```

Then, e.g., `cythonize -i slicing.pyx && python -c 'import slicing'` leads to:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "slicing.pyx", line 6, in init slicing
    b[3:6] = np.ones((3,))
TypeError: only size-1 arrays can be converted to Python scalars
```

**Expected behavior**
No error should occurs and the assignment into the slice should take place.

It works if I use the underlying numpy array by, say, `np.asanyarray(b)[3:6]`, but it seems like something that should just work.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 on WSL
 - Python version 3.7.4 (conda)
 - Cython version 0.29.20

**Comment by scoder** [comment]
Memory views use broadcasting on slice assignment. This means that the single value you assign will be written into all elements of the slice. It needs to be a scalar (non-array) value for that.

Given that this currently produces an error, there is an opportunity to open this up, but I'm not sure if it's a good idea. Sometimes, overloading an operation with multiple meaning ends up making it more error prone. (Compare, for example, Python's `max()` and `min()` functions, which fail if you only provide a single argument. That's a relict of also accepting iterables.)

**Comment by c-f-h** [comment]
Maybe I'm misunderstanding but I'm not sure how broadcasting plays into this - the slice being assigned to and the array on the right-hand side have the same shape?

**Comment by scoder** [comment]
What I meant was, that the value you assign (apparently) needs to be a single scalar value (and not an array), because it looks like the assignment is trying to broadcast it over the slice. It's clearly not doing a slice assignment here.

**Comment by c-f-h** [comment]
I see. That seems to be a clear deviation from the expected ndarray semantics. I wouldn't really call this assignment "overloading" the operation because these semantics are well-established and expected from numpy.

Also, the assignment works both if I (1) use the underlying untyped ndarray on the LHS or (2) make also the RHS a typed memoryview. So the unexpected behavior only happens when mixing typed/untyped arrays.

At the very least the error message is confusing, I didn't really understand the problem before this discussion.

**Comment by da-woods** [comment]
> That seems to be a clear deviation from the expected ndarray semantics.

It's probably worth saying that Cython memoryviews aren't really expected to provide ndarray semantics. They're largely designed to provide fast, single-element indexing into an array, and fast creation of other memoryviews by slicing. Anything else is largely a bonus.

In terms of assignment I believe:

1. assignment of an array to a whole memoryview sets the memoryview to be a view on that array:
    ```
    cdef double[:] a
    a = some_array
    ```
2. assignment of a memoryview slice to another memoryview slice of the same type and with the same number of dimensions copies element-by-element (checking that the two slices are the same size at runtime).
    ```
    cdef double[:] a = ...
    cdef double[:] b = ...
    a[:] = b  # copy elements from by

3. assignment of a C value to a memoryview slice fills the memoryview slice with that value
    ```
    cdef double val = 1.
    cdef double[:] a = ...
    a[:] = val
    ```

4. Assignment of a Python object to a memoryview slice tries to coerce the python object to a single C value, then does "3".

"2" and "3" (and by "4", by extension) are implemented as very efficient C loops preceded by a quick runtime checks.

If we were to implement what you're asking it would make case 4 perform worse - it'd need to work out whether the Python object was a suitable array-like structure or a single numeric value. There's also the complication: do we require that the right-hand side can be coerced to a memoryview of the same time (essentially trying `a[:] = <double[:]>b`) or do we accept any generic iterable? The latter would give people unexpectedly worse performance (but me much more flexible).

We could definitely improve the error message at no runtime cost. Maybe even suggest the right code in the error message. That's definitely worthwhile because you aren't the first the first person to be confused by this - the error message assumes that you know why it's being coerced.

I sort of think that the "try to coerce to right-hand side to a memoryview" option might be worthwhile. But it does have a cost. Anything more complicated than that I'd definitely be opposed to.

**Comment by ryancinsight** [comment]
I believe I'm running into a similar issue on cython 3.0, windows:

def make_affine(image: Image) -> cython.double[:,:]:
    # get affine transform in LPS
    affine:cython.double[:,:] = np.eye(4, dtype=np.float64)
    direction: cython.double[:,:]= np.asarray(image.GetDirection(),dtype=np.float64).reshape(3,3)
    spacing: cython.double[:]= np.asarray(image.GetSpacing(),dtype=np.float64)
    affine[:3, :3] = np.multiply(direction,spacing)
    affine[:3, 3] = np.asarray(image.GetOrigin(),np.float64)
    return affine

using without cython runs fine but once I cythonize I get the error below:
TypeError: only size-1 arrays can be converted to Python scalars

@da-woods or @c-f-h if similar is there a workaround?
