### ISSUE TITLE
[BUG] PyErr_Occurred() when building python-flint 

### ISSUE THREAD

**Issue by fredrik-johansson** [cython/cython#4633]
**Describe the bug**
Cython errors out with `AssertionError: (<StringSourceDescriptor:(tree fragment)>, 12, 34): PyErr_Occurred()` when building https://github.com/fredrik-johansson/python-flint.

This package built fine until some time last year when I did an OS upgrade (and with it a Python/Cython upgrade).

There may well be a bug in `python-flint` here, but with a nondescript `AssertionError` from Cython, it is very hard to track down the precise cause of the failure. Assuming that this is not an internal Cython bug, Cython should at least print some useful diagnostic about the offending code.

**To Reproduce**
Code to reproduce the behaviour:
```
fredrik@agm:~/src/python-flint$ touch src/flint/pyflint.pyx
fredrik@agm:~/src/python-flint$ python3 ./setup.py build_ext
running build_ext
cythoning src/flint/pyflint.pyx to src/flint/pyflint.c
/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/fredrik/src/python-flint/src/flint/_flint.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "./setup.py", line 39, in <module>
    setup(
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    result = cython_compile(source, options=options,
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_single(source, options, full_module_name)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 143, in process_implementation
    self.generate_c_code(env, options, result)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 385, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 1986, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 1748, in generate_function_body
    self.body.generate_execution_code(code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 448, in generate_execution_code
    stat.generate_execution_code(code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 5194, in generate_execution_code
    self.generate_rhs_evaluation_code(code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 5481, in generate_rhs_evaluation_code
    self.rhs.generate_evaluation_code(code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 773, in generate_evaluation_code
    self.generate_result_code(code)
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 13331, in generate_result_code
    code.putln(self.type.from_py_call_code(
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 511, in from_py_call_code
    return self.typedef_base_type.from_py_call_code(
  File "/home/fredrik/.local/lib/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 2486, in from_py_call_code
    assert not error_condition, '%s: %s' % (error_pos, error_condition)
AssertionError: (<StringSourceDescriptor:(tree fragment)>, 12, 34): PyErr_Occurred()
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Python version: 3.8.10
 - Cython version: 0.29.27

**Comment by mattip** [comment]
I think the unpickling code is being generated for [fmpz_mpoly](https://github.com/fredrik-johansson/python-flint/blob/1a68cffc3b8454f57f5c5ffdd94df3f11b081468/src/flint/pyflint.pxd#L80), which is
```
cdef class fmpz_mpoly:
    cdef fmpz_mpoly_t val
    cdef bint initialized
```

**Comment by da-woods** [comment]
The short-term solution would be to put `@cython.auto_pickle(False)` as a decorator for `fmpz_mpoly`. It doesn't look like it should be pickleable, so I'm not sure why Cython tries to make it pickleable.

Obviously it shouldn't crash though

**Comment by da-woods** [comment]
And I think the thing to diagnose is why Cython believes that `fmpz_mpoly_t` (which is an array of structs containing pointers) is pickleable. The real error occurs much earlier than traceback

**Comment by da-woods** [comment]
Does look to be `fmpz_mpoly_ctx` rather than `fmpz_mpoly` it's trying to pickle

**Comment by da-woods** [comment]
Git bisect suggests the issue is in 1800cbdae7b8c2042df2e1ca5c5e82ad6a5025c3 (which suggests it was last working quite some time ago).

Here's a short chunk of code that reproduces the problem:

```
cdef extern from *:
    ctypedef struct mpoly_ctx_struct:
        int deg

    ctypedef mpoly_ctx_struct mpoly_ctx_t[1]

    ctypedef struct fmpz_mpoly_ctx_struct:
        mpoly_ctx_t minfo

    ctypedef fmpz_mpoly_ctx_struct fmpz_mpoly_ctx_t[1]

cdef class fmpz_mpoly_ctx:
    cdef fmpz_mpoly_ctx_t val
```

Disabling auto_pickle definitely does work, but it's still a bug

**Comment by fredrik-johansson** [comment]
Thanks for the `@cython.auto_pickle(False)` workaround -- I will put that in until a better solution is available.
