### ISSUE TITLE
Wrong indendation in setup.py

### ISSUE THREAD

**Issue by frenzymadness** [cython/cython#4655]
See line 142 in https://github.com/cython/cython/blob/d1b9dda73b03b3e49af535a928900a576a79e1e1/setup.py#L140-L143

Introduced in: https://github.com/cython/cython/commit/d1b9dda73b03b3e49af535a928900a576a79e1e1

It's now not possible to install Cython from its master branch:
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-yizh4xis/setup.py", line 142
          if coverage:
                      ^
      IndentationError: unindent does not match any outer indentation level
```

**Comment by scoder** [comment]
Thanks, hadn't noticed it yet.
