### ISSUE TITLE
[BUG] When trying to compile code with fusedtype of structs?

### ISSUE THREAD

**Issue by adam2392** [cython/cython#4674]
**Describe the bug**
I am trying to compile code that generalizes a function to operate on various structs. I follow [cython docs](https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html) to define a fused type.

The following is the code line that errors out:

```
# I have a function that I want to use the fusedtype in
cpdef do_something(...):
      # the following line errors out when compiling
      cdef axis_oblique_record split

      # do additional functions
```

The following is code related to the fusedtype struct I want to setup.

```cython
# I have two different structs that store sets of similar information
cdef struct ObliqueSplitRecord:
    double test

cdef struct SplitRecord:
    double testtest
    double test

# here I define a fusedtype
ctypedef fused axis_oblique_record:
    SplitRecord
    ObliqueSplitRecord
```

```
 Error compiling Cython file:
  ------------------------------------------------------------
  ...
          cdef SIZE_t parent
          cdef bint is_left
          cdef SIZE_t n_node_samples = splitter.n_samples
          cdef double weighted_n_samples = splitter.weighted_n_samples
          cdef double weighted_n_node_samples
          cdef axis_oblique_record split
              ^
  ------------------------------------------------------------

  sklearn/tree/_tree.pyx:186:13: Compiler crash in AnalyseDeclarationsTransform

  ModuleNode.body = StatListNode(_tree.pyx:15:0)
  StatListNode.stats[36] = StatListNode(_tree.pyx:135:5)
  StatListNode.stats[0] = CClassDefNode(_tree.pyx:135:5,
      as_name = 'DepthFirstTreeBuilder',
      class_name = 'DepthFirstTreeBuilder',
      doc = 'Build a decision tree in depth-first fashion.',
      module_name = '',
      visibility = 'private')
  CClassDefNode.body = StatListNode(_tree.pyx:136:4)
  StatListNode.stats[1] = CFuncDefNode(_tree.pyx:147:10,
      args = [...]/6,
      doc = 'Build a decision tree from the training set (X, y).',
      has_fused_arguments = True,
      is_c_class_method = 1,
      modifiers = [...]/0,
      overridable = 1,
      visibility = 'private')
  FusedCFuncDefNode.stats[0] = CFuncDefNode(_tree.pyx:147:10,
      args = [...]/6,
      doc = 'Build a decision tree from the training set (X, y).',
      is_c_class_method = 1,
      modifiers = [...]/0,
      overridable = 1,
      visibility = 'private')
  File 'Nodes.py', line 431, in analyse_declarations: StatListNode(_tree.pyx:147:10)
  File 'Nodes.py', line 431, in analyse_declarations: StatListNode(_tree.pyx:147:10)
  File 'Nodes.py', line 431, in analyse_declarations: StatListNode(_tree.pyx:149:8)
  File 'Nodes.py', line 1329, in analyse_declarations: CVarDefNode(_tree.pyx:186:13,
      modifiers = [...]/0,
      visibility = 'private')
  File 'Nodes.py', line 1033, in analyse: CSimpleBaseTypeNode(_tree.pyx:186:13,
      module_path = [...]/0,
      name = 'axis_oblique_record',
      signed = 1)

  Compiler crash traceback from this point on:
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 1033, in analyse
      type = scope.lookup_type(self.name)
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/Cython/Compiler/Symtab.py", line 898, in lookup_type
      return entry.type.specialize(self.fused_to_specific)
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 1655, in specialize
      return values[self]
  KeyError: FusedType(name='axis_oblique_record')
  Compiling sklearn/tree/_tree.pyx because it changed.
  [1/1] Cythonizing sklearn/tree/_tree.pyx
  Traceback (most recent call last):
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 316, in <module>
      setup_package()
    File "setup.py", line 312, in setup_package
      setup(**metadata)
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "setup.py", line 187, in configuration
      config.add_subpackage("sklearn")
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 982, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sklearn/setup.py", line 85, in configuration
      cythonize_extensions(top_path, config)
    File "/Users/adam2392/Documents/scikit-learn/sklearn/_build_utils/__init__.py", line 74, in cythonize_extensions
      config.ext_modules = cythonize(
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
      cythonize_one(*args)
    File "/Users/adam2392/miniforge3/envs/conda-sklearn-dev38/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: sklearn/tree/_tree.pyx
```

**Expected behavior**
I would expect that the bug is more informative then `Compiler crash in AnalyseDeclarationsTransform`. Not sure what's going on here?

**Environment (please complete the following information):**
 - OS: macOS M1
 - Python version 3.8.12
 - Cython version 0.29.28

**Comment by da-woods** [comment]
Is `axis_oblique_record` a function argument? Because it needs to be.

Obviously it shouldn't crash...

**Comment by adam2392** [comment]
No I want to define a `axis_oblique_record` variable within the function. I don't pass it because it's just an empty struct that's used by the function.

Is that the only way to make it work? If so, maybe I can pass a blank struct as a default argument in the `cpdef` function.

**Comment by da-woods** [comment]
> Are you saying the only way to use a fusedtype with struct is as a function argument?

Yes - the way that fused functions work is that it generates multiple versions of a function and selects one based on its arguments. That's arguably a limitation that could be improved, but it's unlikely to be soon. A dummy argument is one way around it.

> Is there a way to dynamically define the struct either, based on a boolean? Say:

No. Although you could define both, and pick which one to access based on a boolean.

**Comment by adam2392** [comment]
I see thanks for the explanation!
