### ISSUE TITLE
[BUG] C++ tests fail with Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [cython/cython#4782]
**Describe the bug**
In shards 1 and 6 of the C++ tests some of the test don't pass on Python 3.11 (`3.11.0-beta.1`). See the full log below.

**To Reproduce**
Run Tools/ci-run.sh as [defined](https://github.com/cython/cython/blob/master/.github/workflows/ci.yml#L226) in the CI configuration with Python 3.11. See [this test run](https://github.com/cython/cython/runs/6368577324?check_suite_focus=true).

**Expected behavior**
All CI tests pass, as on other Python versions.

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
 - Python version: `3.11.0-beta.1`
 - Cython version: 812585935131125f8988c38417bb73bfd5a81c05

<details><summary>Full error log</summary>

```
Sharded tests run in 677 seconds (11.3 minutes)
Errors found in shards 1, 6

Errors from shard 1:
======================================================================
FAIL: fail_on_line_trace (line_trace)
Doctest: line_trace.fail_on_line_trace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 2217, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Failed doctest test for line_trace.fail_on_line_trace
  File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line unknown line number, in fail_on_line_trace

----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    len(result)
Expected:
    17
Got:
    16
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[:5]  # py
Expected:
    ['NO ERROR', ('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    ['NO ERROR', ('call', 2), ('line', 2), ('return', 2), ('call', 0)]
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[5:10]  # py
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('line', 3), ('line', 4)]
Got:
    [('line', 1), ('line', 2), ('line', 3), ('line', 4), ('call', 0)]
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[10:14]  # py
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    [('line', 1), ('line', 2), ('return', 2), ('line', 2)]
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[14:]  # py
Expected:
    [('line', 2), ('line', 5), ('return', 5)]
Got:
    [('line', 5), ('return', 5)]


======================================================================
FAIL: run_trace (line_trace)
Doctest: line_trace.run_trace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 2217, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Failed doctest test for line_trace.run_trace
  File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line unknown line number, in run_trace

----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.run_trace
Failed example:
    run_trace(py_add, 1, 2)
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    [('call', 1), ('line', 1), ('line', 797), ('return', 797)]
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/cpp/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.run_trace
Failed example:
    run_trace(py_add, 1, 2, with_sys=True)
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    [('call', 1), ('line', 1), ('line', 797), ('return', 797)]



Errors from shard 6:
======================================================================
FAIL: test_deduplicated_args (tuple_constants)
Doctest: tuple_constants.test_deduplicated_args
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 2217, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Failed doctest test for tuple_constants.test_deduplicated_args
  File "/home/runner/work/cython/cython/TEST_TMP/6/run/cpp/tuple_constants/tuple_constants.cpython-311-x86_64-linux-gnu.so", line unknown line number, in test_deduplicated_args

----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/6/run/cpp/tuple_constants/tuple_constants.cpython-311-x86_64-linux-gnu.so", line ?, in tuple_constants.test_deduplicated_args
Failed example:
    test_deduplicated_args()
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest tuple_constants.test_deduplicated_args[0]>", line 1, in <module>
        test_deduplicated_args()
        ^^^^^^^^^^^^^^^^^^^^^^^^
      File "tests/run/tuple_constants.pyx", line 40, in tuple_constants.test_deduplicated_args (tuple_constants.cpp:3018)
        assert func1.__code__.co_varnames is func2.__code__.co_varnames
    AssertionError

```
</details>

**Comment by da-woods** [comment]
I'll close this as a duplicate of https://github.com/cython/cython/issues/4781 - it looks to be exactly the same issues failing in both cases so I don't think it's worth separate bugs
