### ISSUE TITLE
[BUG] unexpected type Py_UCS4 and base type Python object for indexing 

### ISSUE THREAD

**Issue by NilsBrause** [cython/cython#4829]
Hi!

When trying to cythonize the following source code using `cythonize -3`:
```
str(0)[0]
```
the following error is printed:
```
Traceback (most recent call last):
  File "/home/nils/.local/bin/cythonize", line 8, in <module>
    sys.exit(main())
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Build/Cythonize.py", line 224, in main
    cython_compile(path, options)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Build/Cythonize.py", line 68, in cython_compile
    ext_modules = cythonize(
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1117, in cythonize
    cythonize_one(*args)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1263, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py", line 576, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py", line 504, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/Pipeline.py", line 394, in run_pipeline
    data = run(phase, data)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/Pipeline.py", line 371, in run
    return phase(data)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/ModuleNode.py", line 206, in process_implementation
    self.generate_c_code(env, options, result)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/ModuleNode.py", line 518, in generate_c_code
    self.generate_module_init_func(modules[:-1], env, globalstate['init_module'])
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/ModuleNode.py", line 3101, in generate_module_init_func
    self.body.generate_execution_code(code)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/Nodes.py", line 409, in generate_execution_code
    stat.generate_execution_code(code)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/Nodes.py", line 5700, in generate_execution_code
    self.expr.generate_evaluation_code(code)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/ExprNodes.py", line 834, in generate_evaluation_code
    self.generate_result_code(code)
  File "/home/nils/.local/lib/python3.10/site-packages/Cython/Compiler/ExprNodes.py", line 4213, in generate_result_code
    assert False, "unexpected type %s and base type %s for indexing" % (
AssertionError: unexpected type Py_UCS4 and base type Python object for indexing
```
To my understanding, `str(0)[0]` should evaluate to `'0'`, which is the first character of the string representation of `0`.
Surprisingly, I don't get any error using `cythonize --3str` or `cythonize -2`. It also works to first assign the result of `str(0)` to a variable:
```
a = str(0)
a[0]
```

**Environment:**
- OpenSUSE Leap 15.3
- Python 3.10
- Cython 3.0.0a10

**Comment by matthewdeanmartin** [comment]
I got the same for Cython==3.0.8, windows 11,  python 3.11.1.

I switched to --3str and now I get different errors on fstrings

```
return f"{self.prefix}-{value}"
               ^
helpers\requests.py:58:15: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.
```

**Comment by scoder** [comment]
Thanks for the reports, I could reproduce the original issue on the latest master. It's easy to fix there, because it's limited to Python 3.x. A backport to Cython 3.0 might be less easy.

**Comment by scoder** [comment]
> I switched to --3str and now I get different errors on fstrings
> 
> ```
> return f"{self.prefix}-{value}"
>                ^
> helpers\requests.py:58:15: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.
> ```

You probably declared your return type as `str`. However, f-strings always return unicode strings, not `str` (which is `bytes` in Py2). Declare return type as `unicode` instead.
