### ISSUE TITLE
[BUG] Compiler crash in AnalyseDeclarationsTransform

### ISSUE THREAD

**Issue by rnestler** [cython/cython#4975]
### Describe the bug

Cython crashes when trying to parse a Python function with the following signature:
```python
def foo(self, z: List[float]) -> List[npt.NDArray[np.float64]]:
```
```
Error compiling Cython file:
------------------------------------------------------------
...
import numpy.typing as npt
from dataclasses import dataclass
from typing import List

class Foo:
    def foo(self, z: List[float]) -> List[npt.NDArray[np.float64]]:
                                         ^
------------------------------------------------------------

test.py:7:41: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 187, in analyse_declarations: ModuleNode(test.py:1:0,
    full_module_name = 'test')
File 'Nodes.py', line 393, in analyse_declarations: StatListNode(test.py:1:0)
File 'Nodes.py', line 393, in analyse_declarations: StatListNode(test.py:6:0)
File 'Nodes.py', line 5046, in analyse_declarations: PyClassDefNode(test.py:6:0,
    name = 'Foo')
File 'Nodes.py', line 393, in analyse_declarations: StatListNode(test.py:7:4)
File 'Nodes.py', line 3159, in analyse_declarations: DefNode(test.py:7:4,
    modifiers = [...]/0,
    name = 'foo',
    np_args_idx = [...]/0,
    num_required_args = 2,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0')
File 'ExprNodes.py', line 14116, in analyse_type_annotation: AnnotationNode(test.py:7:37,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 3741, in analyse_pytyping_modifiers: IndexNode(test.py:7:41,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/home/raphael/projects/github/minimal-cython-example/.venv/lib/python3.10/site-packages/Cython/Compiler/ExprNodes.py", line 3741, in analyse_pytyping_modifiers
    if modifier_type.python_type_constructor_name and modifier_type.modifier_name:
AttributeError: 'NoneType' object has no attribute 'python_type_constructor_name'
Traceback (most recent call last):
  File "/home/raphael/projects/github/minimal-cython-example/.venv/bin/cythonize", line 8, in <module>
    sys.exit(main())
  File "/home/raphael/projects/github/minimal-cython-example/.venv/lib/python3.10/site-packages/Cython/Build/Cythonize.py", line 226, in main
    cython_compile(path, options)
  File "/home/raphael/projects/github/minimal-cython-example/.venv/lib/python3.10/site-packages/Cython/Build/Cythonize.py", line 68, in cython_compile
    ext_modules = cythonize(
  File "/home/raphael/projects/github/minimal-cython-example/.venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1129, in cythonize
    cythonize_one(*args)
  File "/home/raphael/projects/github/minimal-cython-example/.venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1296, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/raphael/projects/github/minimal-cython-example/test.py
```

### Code to reproduce the behaviour:

```cython
import numpy as np
import numpy.typing as npt
from dataclasses import dataclass
from typing import List

class Foo:
    def foo(self, z: List[float]) -> List[npt.NDArray[np.float64]]:
        return [np.array(z)]

foo = Foo()
print(foo.foo([1.0]))
```

### Expected behaviour

Not crashing but compiling the code.

### Environment

OS: Linux
Python version 3.10.5
Cython version 3.0.0a11

### Additional context

Repository with a minimal example to reproduce the issue: https://github.com/rnestler/minimal-cython-example/tree/dd5648408bda1305d65a5a8aa22fdebbe0b7c4bf

**Comment by rnestler** [comment]
Changing the `List` annotations to `list` fixes it.

**Comment by da-woods** [comment]
Thanks for the report. A lot of this annotation type analysis is fairly new so the bugs are still falling out.

We don't do much in Cython with the annotations beyond the initial `list` so you don't lose anything by switching to that. If you want to full annotation for documentation purposes then you can always turn off the `annotation_typing` directive locally for the function.

**Comment by rnestler** [comment]
> We don't do much in Cython with the annotations beyond the initial list so you don't lose anything by switching to that. 

Well one looses backwards compatibility with Python 3.8, but apart from that I agree.
