### ISSUE TITLE
[BUG] Cython fails to compile the project dwave-samplers

### ISSUE THREAD

**Issue by yurivict** [cython/cython#4997]
### Describe the bug

The project [dwave-samplers](https://github.com/dwavesystems/dwave-samplers) fails to build with Cython:
```Error compiling Cython file:
------------------------------------------------------------
..

cimport numpy as np
from dimod cimport cyBQM_float64
from dimod.libcpp cimport cppBinaryQuadraticModel

from dwave.samplers.tree.orang cimport samples_type, PyArray_ENABLEFLAGS
^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:31:0: 'dwave/samplers/tree/orang.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
..

cimport numpy as np
from dimod cimport cyBQM_float64
from dimod.libcpp cimport cppBinaryQuadraticModel

from dwave.samplers.tree.orang cimport samples_type, PyArray_ENABLEFLAGS
^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:31:0: 'dwave/samplers/tree/orang/samples_type.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
..

cimport numpy as np
from dimod cimport cyBQM_float64
from dimod.libcpp cimport cppBinaryQuadraticModel

from dwave.samplers.tree.orang cimport samples_type, PyArray_ENABLEFLAGS
^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:31:0: 'dwave/samplers/tree/orang/PyArray_ENABLEFLAGS.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
..
    # pass in pointers so that sample_bqm can fill things in
    cdef double logpf

    # samples
    cdef int srows, scols
    cdef samples_type* samples_pointer
        ^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:110:9: 'samples_type' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
..
              &pair_marginals_pointer, &pmrows, &pmcols,
              &pair_pointer, &prows, &pcols)

    # create a numpy array without making a copy then tell numpy it needs to
    # free the memory
    samples = np.asarray(<samples_type[:srows, :scols]> samples_pointer)
                         ^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:138:26: 'samples_type' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
..
              &pair_marginals_pointer, &pmrows, &pmcols,
              &pair_pointer, &prows, &pcols)

    # create a numpy array without making a copy then tell numpy it needs to
    # free the memory
    samples = np.asarray(<samples_type[:srows, :scols]> samples_pointer)
                                                       ^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:138:56: Can only create cython.array from pointer or array

Error compiling Cython file:
------------------------------------------------------------
..
              &pair_pointer, &prows, &pcols)

    # create a numpy array without making a copy then tell numpy it needs to
    # free the memory
    samples = np.asarray(<samples_type[:srows, :scols]> samples_pointer)
    PyArray_ENABLEFLAGS(samples, np.NPY_OWNDATA)
   ^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:139:4: 'PyArray_ENABLEFLAGS' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
..
                if samples[i, j] == 0:
                    samples[i, j] = -1

    if marginals:
        variable_marginals = np.asarray(<double[:smlen]> single_marginals_pointer)
        PyArray_ENABLEFLAGS(variable_marginals, np.NPY_OWNDATA)
       ^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:151:8: 'PyArray_ENABLEFLAGS' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
..
        variable_marginals = np.asarray(<double[:smlen]> single_marginals_pointer)
        PyArray_ENABLEFLAGS(variable_marginals, np.NPY_OWNDATA)

        if pmrows * pmcols:
            interaction_marginals = np.asarray(<double[:pmrows, :pmcols]> pair_marginals_pointer)
            PyArray_ENABLEFLAGS(interaction_marginals, np.NPY_OWNDATA)
           ^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:155:12: 'PyArray_ENABLEFLAGS' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
..
        else:
            interaction_marginals = np.empty(shape=(pmrows, pmcols), dtype=np.double)

        if prows * pcols:
            interactions = np.asarray(<int[:prows, :pcols]> pair_pointer)
            PyArray_ENABLEFLAGS(interactions, np.NPY_OWNDATA)
           ^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:161:12: 'PyArray_ENABLEFLAGS' is not a constant, variable or function identifier
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 53, in <module>
    ext_modules=cythonize(
  File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: dwave/samplers/tree/sample.pyx
Compiling dwave/samplers/random/cyrandom.pyx because it depends on /usr/local/lib/python3.9/site-packages/dimod/quadratic/cyqm/cyqm_template.pxd.pxi.
Compiling dwave/samplers/tree/sample.pyx because it depends on /usr/local/lib/python3.9/site-packages/dimod/quadratic/cyqm/cyqm_template.pxd.pxi.
Compiling dwave/samplers/tree/solve.pyx because it depends on /usr/local/lib/python3.9/site-packages/dimod/quadratic/cyqm/cyqm_template.pxd.pxi.
Compiling dwave/samplers/tree/utilities.pyx because it depends on /usr/local/lib/python3.9/site-packages/dimod/quadratic/cyqm/cyqm_template.pxd.pxi.
[1/4] Cythonizing dwave/samplers/random/cyrandom.pyx
[2/4] Cythonizing dwave/samplers/tree/sample.pyx
*** Error code 1
```

Full [log](http://beefy16.nyi.freebsd.org/data/130amd64-default/1b5765194c92/logs/py39-dwave-samplers-1.0.0.d1.log) (IPv6 URL).

Cython fails to find files that are in the project.

Also this failure occurs on some systems and not on other systems,

### Code to reproduce the behaviour:

```cython
# example code
```

### Expected behaviour

n/a

### Environment

OS: FreeBSD 13.1
Python version 3.9
Cython version 0.29.32

**Comment by da-woods** [comment]
Your other report of this https://github.com/dwavesystems/dwave-samplers/issues/32

To be honest I'm not convinced that this is a Cython issue (although I'm not sure it isn't). I'll leave this open because it might be, but I don't think I can be of any help debugging it.

**Comment by yurivict** [comment]
> To be honest I'm not convinced that this is a Cython issue [...]

Why? What is the problem then? The files in question do exist in the repository.

**Comment by da-woods** [comment]
Don't know. But it feels like something specific to where FreeBSD puts files when it builds things. I don't have FreeBSD though (and don't really know how to use it) hence I don't think I can really help.

Obviously if you can identify something that Cython is doing wrong here then we'll happily fix it, but for this problem I wouldn't know where to start.

**Comment by yurivict** [comment]
This doesn't happen with any other port using Cython.
And the problem is intermittent.
