### ISSUE TITLE
[BUG] RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by excubo-jg** [cython/cython#5011]
### Describe the bug

In a large pyc program these two lines

                    with open("error_log.txt", "a") as f:  
                        f.write(f"Failed: {var_1} {var_2}\n") 

cause this crash - when commented out, codes compiles without problems

Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Visual Studio 2019\Projects\DominionSolver\setup.py", line 41, in <module>
    ext_modules = cythonize([
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Build\Dependencies.py", line 1129, in cythonize
    cythonize_one(*args)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Build\Dependencies.py", line 1275, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Main.py", line 579, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Main.py", line 503, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Pipeline.py", line 397, in run_pipeline
    data = run(phase, data)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Pipeline.py", line 374, in run
    return phase(data)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\ModuleNode.py", line 206, in process_implementation
    self.generate_c_code(env, options, result)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\ModuleNode.py", line 501, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 404, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 404, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 5366, in generate_function_definitions
    self.body.generate_function_definitions(self.scope, code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 404, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 3458, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 2157, in generate_function_definitions
    self.generate_function_body(env, code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 1918, in generate_function_body
    self.body.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 410, in generate_execution_code
    stat.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 7156, in generate_execution_code
    self.body.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 410, in generate_execution_code
    stat.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 7156, in generate_execution_code
    self.body.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 410, in generate_execution_code
    stat.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 6974, in generate_execution_code
    if_clause.generate_execution_code(code, end_label, is_last=i == last)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 7021, in generate_execution_code
    self.body.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 410, in generate_execution_code
    stat.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 7800, in generate_execution_code
    self.body.generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 8296, in generate_execution_code
    fresh_finally_clause().generate_execution_code(code)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\site-packages\Cython\Compiler\Nodes.py", line 8284, in fresh_finally_clause
    node_copy = copy.deepcopy(node)

  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\Admin\anaconda3\envs\dominion\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
repeats until
RecursionError: maximum recursion depth exceeded

### Code to reproduce the behaviour:

```cython
# example code
```

### Expected behaviour

no crash

### Environment

OS: Windows 10 Pro
Python 3.10.4
Cython version 3.0.0a11

**Comment by da-woods** [comment]
This definitely looks like a bug, but I can't reproduce it from the information given so it's unlikely to get fixed.

**Comment by excubo-jg** [comment]
That will be quite tricky and my first try failed... What I could ascertain is that var_1 is an int and does not cause problems but var_2 is a npt.NDArray / cdef public int[:] and causes the crash. Does this help?

**Comment by 0dminnimda** [comment]
Is `error_log.txt` empty/nonexistant at the moment error happens?
Give an example of the `var_1` and `var_2`

**Comment by da-woods** [comment]
> Is `error_log.txt` empty/nonexistant at the moment error happens?

I don't think error_log.txt matters - it's a compilation error rather than a runtime error.

**Comment by excubo-jg** [comment]
I have played around with this quite a bit and the smallest size I can limit it down is 1k LOC and 6 files... What puzzles me is that further deleting unrelated lines makes the error go away but I don't see a pattern what causes the problem. If you were willing to investigate further I could set up a repo and give you access

**Comment by da-woods** [comment]
It's just about possible that it's not a runaway recursion and just a deep recursion - Cython does work by traversing a tree recursively so it is possible to trigger recursion errors in some rare cases just by having a sufficiently complex source file. `a+b+c+d+e+f+...` will do it if you make it long enough...

Could you try changing the recursion limit (https://docs.python.org/3/library/sys.html?highlight=sys#sys.setrecursionlimit) to make it a bit bigger and see if that fixes it - say 4000. If you put `sys.setrecursionlimit` in your setup.py that'll probably do it.

Failing that, 1k LOC is better than nothing. It'd at least let me try to see if I can spot anything in the debugger. No promises of course (and definitely no promises of anything immediate) but I could have a look

**Comment by excubo-jg** [comment]
Many thanks for the hint - increasing the limit did process the original code base. Closing this
