### ISSUE TITLE
[BUG] Compiler Crash in Pre Release Alpha Caused by Dataclass Dict

### ISSUE THREAD

**Issue by ideonrandy** [cython/cython#5033]
### Describe the bug

```
Compiling dt.py because it changed.
[1/1] Cythonizing dt.py
Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(dt.py:1:0)
StatListNode.stats[2] = PyClassDefNode(dt.py:5:0,
    name = 'Dummy')
PyClassDefNode.body = StatListNode(dt.py:6:4)
StatListNode.stats[2] = CompilerDirectivesNode(dt.py:8:4)
CompilerDirectivesNode.body = StatListNode(dt.py:8:4)
StatListNode.stats[0] = DefNode(dt.py:8:4,
    is_cyfunction = True,
    is_staticmethod = True,
    modifiers = [...]/0,
    name = 'get_document',
    np_args_idx = [...]/0,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 397, in analyse_expressions: StatListNode(dt.py:10:8,
    is_terminator = True)
File 'Nodes.py', line 6652, in analyse_expressions: ReturnStatNode(dt.py:10:8,
    is_terminator = True)
File 'ExprNodes.py', line 7043, in coerce_to: AttributeNode(dt.py:10:22,
    attribute = '__dict__',
    initialized_check = True,
    is_attribute = 1,
    is_py_attr = 1,
    is_temp = 1,
    member = '__dict__',
    needs_none_check = True,
    op = '.',
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 1040, in coerce_to: AttributeNode(dt.py:10:22,
    attribute = '__dict__',
    initialized_check = True,
    is_attribute = 1,
    is_py_attr = 1,
    is_temp = 1,
    member = '__dict__',
    needs_none_check = True,
    op = '.',
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 13381, in __init__: PyTypeTestNode(exact_builtin_type = True,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/usr/local/lib/python3.8/dist-packages/Cython/Compiler/ExprNodes.py", line 13381, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, \
AssertionError: PyTypeTest for Python object against non extension type Python object
Traceback (most recent call last):
  File "compile.py", line 17, in <module>
    setup(
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.8/dist-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
    new_ext = cythonize(
  File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 1129, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 1296, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: dt.py
```

### Code to reproduce the behaviour:

compile.py:

```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
import Cython.Compiler.Options
Cython.Compiler.Options.docstrings = False

ext_modules = [
    Extension(
        "dt",
        ["dt.py"]
    ),
]

for e in ext_modules:
    e.cython_directives = {'language_level': "3"} #all are Python-3

setup(
    name = 'Sample Program',
    cmdclass = {'build_ext': build_ext},
    ext_modules = ext_modules
)
```

dt.py:

```
from dataclasses import dataclass
from typing import Dict

@dataclass
class Dummy:
    dummy:int=None

    @staticmethod
    def get_document() -> Dict:
        return Dummy().__dict__
```

### Expected behaviour

```
Compiling dt.py because it changed.
[1/1] Cythonizing dt.py
building 'dt' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c dt.c -o build/temp.linux-x86_64-3.8/dt.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/dt.o -o /home/ideon/dt.cpython-38-x86_64-linux-gnu.so
```

### Environment

OS: Linux (Docker)
Python version 3.8.10
Cython version 3.0.0a11

### Additional context

Copy compile.py and dt.py to the same directory and run: `python3 compile.py build_ext --inplace` - do this for both Cython 3.0.0a10 and Cython 3.0.0a11 and notice it succeeds in the former and fails in the later.

**Comment by ideonrandy** [comment]
The issue disappears when `def get_document() -> Dict:` is changed to `def get_document() -> dict:`

**Comment by da-woods** [comment]
Ah thanks for the report. I think we do know about this one. We recently started adding support to try to use imports from `typing` intelligently, but forgot that people may not always subscript them.
