### ISSUE TITLE
[ENH] read-only memory views do not work with fused dtypes

### ISSUE THREAD

**Issue by maxnoe** [cython/cython#5039]
### Is your feature request related to a problem? Please describe.

In my code, I would like to use a read-only memoryview using fused dtypes:
```cython
# cython: language_level = 3

ctypedef fused dtype_t:
    float
    double

cpdef bint _foo(const dtype_t[:] value):
    return False
```

But this leads to the following "not-implemented" error:

```
❯ cythonize -a -i fused_readonly.pyx
Compiling /home/maxnoe/test_Cython/fused_readonly.pyx because it changed.
[1/1] Cythonizing /home/maxnoe/test_Cython/fused_readonly.pyx

Error compiling Cython file:
------------------------------------------------------------
...

ctypedef fused dtype_t:
    float
    double

cpdef bint _foo(const dtype_t[:] value):
                             ^
------------------------------------------------------------

fused_readonly.pyx:7:30: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 124, in analyse_declarations: ModuleNode(fused_readonly.pyx:1:0,
    full_module_name = 'fused_readonly')
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(fused_readonly.pyx:3:0)
File 'Nodes.py', line 2359, in analyse_declarations: CFuncDefNode(fused_readonly.pyx:7:6,
    modifiers = [...]/0,
    overridable = 1,
    visibility = 'private')
File 'Nodes.py', line 681, in analyse: CFuncDeclaratorNode(fused_readonly.pyx:7:15,
    calling_convention = '',
    overridable = 1)
File 'Nodes.py', line 891, in analyse: CArgDeclNode(fused_readonly.pyx:7:16,
    is_generic = 1,
    outer_attrs = [...]/2)
File 'Nodes.py', line 1093, in analyse: MemoryViewSliceTypeNode(fused_readonly.pyx:7:30,
    is_arg = True,
    name = 'memoryview')

Compiler crash traceback from this point on:
  File "/usr/lib/python3.10/site-packages/Cython/Compiler/Nodes.py", line 1093, in analyse
    self.type = PyrexTypes.MemoryViewSliceType(base_type, axes_specs)
  File "/usr/lib/python3.10/site-packages/Cython/Compiler/PyrexTypes.py", line 625, in __init__
    self.dtype_name = Buffer.mangle_dtype_name(self.dtype)
  File "/usr/lib/python3.10/site-packages/Cython/Compiler/Buffer.py", line 631, in mangle_dtype_name
    return prefix + dtype.specialization_name()
  File "/usr/lib/python3.10/site-packages/Cython/Compiler/PyrexTypes.py", line 57, in specialization_name
    common_subs = (self.empty_declaration_code()
  File "/usr/lib/python3.10/site-packages/Cython/Compiler/PyrexTypes.py", line 51, in empty_declaration_code
    self._empty_declaration = self.declaration_code('')
  File "/usr/lib/python3.10/site-packages/Cython/Compiler/PyrexTypes.py", line 1582, in declaration_code
    return self.const_base_type.declaration_code("const %s" % entity_code, for_display, dll_linkage, pyrex)
  File "/usr/lib/python3.10/site-packages/Cython/Compiler/PyrexTypes.py", line 1649, in declaration_code
    raise Exception("This may never happen, please report a bug")
Exception: This may never happen, please report a bug
Traceback (most recent call last):
  File "/usr/bin/cythonize", line 33, in <module>
    sys.exit(load_entry_point('Cython==0.29.32', 'console_scripts', 'cythonize')())
  File "/usr/lib/python3.10/site-packages/Cython/Build/Cythonize.py", line 225, in main
    cython_compile(path, options)
  File "/usr/lib/python3.10/site-packages/Cython/Build/Cythonize.py", line 97, in cython_compile
    ext_modules = cythonize(
  File "/usr/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/maxnoe/test_Cython/fused_readonly.pyx
```

### Describe the solution you'd like.

Support read-only memoryviews for fused dtypes

**Comment by da-woods** [comment]
This is fixed in the 3.0 alpha releases (I think in https://github.com/cython/cython/pull/3853, but I haven't checked that for sure). It probably won't be backported to the stable branch.

**Comment by maxnoe** [comment]
Good to know! Thanks

**Comment by da-woods** [comment]
FWIW there is a *very* hacky way to transform a read-only memoryview into a read-write memoryview. I'd much rather people just used the Cython 3 alpha though. However if you want to look it's at https://github.com/scikit-learn/scikit-learn/blob/2a391bea9a409745e5c297c70bcebe51274b9d39/sklearn/utils/_readonly_array_wrapper.pyx
