### ISSUE TITLE
[BUG] type annotation Optional[Tuple[float, float]] does not compile: "typing.Optional[...] cannot be applied to non-Python type (double, double)"

### ISSUE THREAD

**Issue by AlexElvers** [cython/cython#5099]
### Describe the bug

Since Cython 3.0.0a11, using the type annotation `Optional[Tuple[float, float]]` leads to a compile error:

```
$ python ../cythonize.py -3 -b ex_fail.py
Compiling /home/alex/dev/cython/examples/ex_fail.py because it changed.
[1/1] Cythonizing /home/alex/dev/cython/examples/ex_fail.py

Error compiling Cython file:
------------------------------------------------------------
...
from typing import Optional, Tuple

def foo(a: Optional[Tuple[float, float]]):
                         ^
------------------------------------------------------------

ex_fail.py:3:25: typing.Optional[...] cannot be applied to non-Python type (double, double)
Traceback (most recent call last):
  File "/home/alex/dev/cython/examples/../cythonize.py", line 9, in <module>
    main()
  File "/home/alex/dev/cython/Cython/Build/Cythonize.py", line 234, in main
    cython_compile(path, options)
  File "/home/alex/dev/cython/Cython/Build/Cythonize.py", line 68, in cython_compile
    ext_modules = cythonize(
  File "/home/alex/dev/cython/Cython/Build/Dependencies.py", line 1132, in cythonize
    cythonize_one(*args)
  File "/home/alex/dev/cython/Cython/Build/Dependencies.py", line 1299, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/alex/dev/cython/examples/ex_fail.py
```

Whereas the following examples _do_ work:
```python
from typing import Optional, Tuple

# using int instead of float
def foo(a: Optional[Tuple[int, int]]):
    print(a)

def foo(a: tuple[int, int] | None):
    print(a)

# using standard generic classes instead of typing module (valid since Python 3.10)
def foo(a: tuple[float, float] | None):
    print(a)

# combining typing.Optional and builtin tuple (valid since Python 3.9)
def foo(a: Optional[tuple[float, float]]):
    print(a)

# combining typing.Tuple and '| None' (valid since Python 3.10)
def foo(a: Tuple[float, float] | None):
    print(a)

# combining float and int
def foo(a: Optional[Tuple[float, int]]):
    print(a)

# not using a tuple
def foo(a: Optional[float]):
    print(a)
```

The last working release is 3.0.0a10.

### Code to reproduce the behaviour:

```python
from typing import Optional, Tuple

def foo(a: Optional[Tuple[float, float]]):
    print(a)
```

### Expected behaviour

The code should compile since `Optional[Tuple[float, float]]` is a correct type annotation.

### Environment

OS: Linux
Python 3.10.8
Cython 3.0.0a11/master

**Comment by da-woods** [comment]
If you want the previous behaviour back, just decorate the function with `@cython.annotation_typing(False)`

What's happening here is that the tuple is getting converted to what Cython calls a "ctuple" (a direct C struct). In this case that is conflicting with `Optional`.

Thanks for the report

**Comment by da-woods** [comment]
For most of your other examples there's reasons why Cython can't (yet) do much with the type annotation so they don't fail.
