### ISSUE TITLE
[BUG] `pip install git+https://github.com/cython/cython@master` fails

### ISSUE THREAD

**Issue by jan-philipp-hoffmann** [cython/cython#5207]
### Describe the bug

`pip install git+https://github.com/cython/cython@master` raises ValueError at 

```
File "Cython/Utils.py", line 624, in build_hex_version 
  digits.append(int(digit))
ValueError: invalid literal for int() with base 10: 'dev0'
```

### Code to reproduce the behaviour:

pip install git+https://github.com/cython/cython@master

### Expected behaviour

[...]
 Compiling /private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Parsing.py because it changed.
      [1/1] Cythonizing /private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Parsing.py
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/setup.py", line 317, in <module>
          run_build()
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/setup.py", line 245, in run_build
          setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Build/Dependencies.py", line 1280, in cythonize_one
          result = compile_single(pyx_file, options, full_module_name=full_module_name)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Main.py", line 604, in compile_single
          return run_pipeline(source, options, full_module_name)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Main.py", line 528, in run_pipeline
          err, enddata = Pipeline.run_pipeline(pipeline, source)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Pipeline.py", line 397, in run_pipeline
          data = run(phase, data)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Pipeline.py", line 374, in run
          return phase(data)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
          module_node.process_implementation(options, result)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/ModuleNode.py", line 206, in process_implementation
          self.generate_c_code(env, options, result)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/ModuleNode.py", line 475, in generate_c_code
          self.generate_module_preamble(env, options, modules, result.embedded_metadata, h_code)
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Compiler/ModuleNode.py", line 783, in generate_module_preamble
          code.putln('#define CYTHON_HEX_VERSION %s' % build_hex_version(__version__))
        File "/private/var/folders/y0/20z6xcjj5zjb8cs6dv5f2hfr0000gn/T/pip-req-build-l5w75mzk/Cython/Utils.py", line 624, in build_hex_version
          digits.append(int(digit))
      ValueError: invalid literal for int() with base 10: 'dev0'

### Environment

OS: [e.g. Linux, Windows, macOS]
Python version [e.g. 3.10.2]
Cython version [e.g. 3.0.0a11]

**Comment by 0dminnimda** [comment]
Yes, it is ok, #5204 was merged too quickly, it will soon be fixed

**Comment by 0dminnimda** [comment]
For now you can target eebfaf7ef30c843844490c400634cd1989227243 for installation

**Comment by scoder** [comment]
Fixed in https://github.com/cython/cython/commit/d798d65557d4926db70232b482cb41daec4c8250

**Comment by lesteve** [comment]
Thanks a lot for the quick fix!
