### ISSUE TITLE
[BUG] cpdef method used to create iterator from child class fails

### ISSUE THREAD

**Issue by Tortar** [cython/cython#5240]
### Describe the bug

Working on some Cython code I encountered a problem in using code with a cpdef method in a class used inside a generator in a child class. The compilation step doesn't fail but  it gives a strange warning:

```
/home/bob/Desktop/mesa-perf/mesa_perf/bug_cython.c: In function ‘__pyx_pf_10bug_cython_1b_func’:
/home/bob/Desktop/mesa-perf/mesa_perf/bug_cython.c:3214:220: warning: passing argument 1 of ‘__Pyx_CFunc_7b59a9__object__lParena__comma_object__comma_int__dunderpyx_skip_dispatch__rParen__etc_to_py_4self_1i’ from incompatible pointer type [-Wincompatible-pointer-types]
 3214 | vtabstruct_10bug_cython_b *)__pyx_v_self->__pyx_base.__pyx_vtab)->__pyx_base.filt); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 11, __pyx_L1_error)
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
      |                                                                             |
      |                                                                             PyObject * (*)(struct __pyx_obj_10bug_cython_a *, PyObject *, int) {aka struct _object * (*)(struct __pyx_obj_10bug_cython_a *, struct _object *, int)}
/home/bob/Desktop/mesa-perf/mesa_perf/bug_cython.c:1959:132: note: expected ‘PyObject * (*)(struct __pyx_obj_10bug_cython_a *, PyObject *)’ {aka ‘struct _object * (*)(struct __pyx_obj_10bug_cython_a *, struct _object *)’} but argument is of type ‘PyObject * (*)(struct __pyx_obj_10bug_cython_a *, PyObject *, int)’ {aka ‘struct _object * (*)(struct __pyx_obj_10bug_cython_a *, struct _object *, int)’}
 1959 | omma_object__comma_int__dunderpyx_skip_dispatch__rParen__etc_to_py_4self_1i(PyObject *(*)(struct __pyx_obj_10bug_cython_a *, PyObject *)); /*proto*/
      |                  
```                                                           

And then, trying to use the function gives an error:

```
>>> from bug_cython import b
>>> s = b()
>>> s.func([2])
<filter object at 0x7f62c6e2a620>
>>> list(s.func([2])=
  File "<stdin>", line 1
    list(s.func([2])=
         ^^^^^^^^^^^^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
>>> list(s.func([2]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stringsource>", line 67, in cfunc.to_py.__Pyx_CFunc_7b59a9__object__lParena__comma_object__comma_int__dunderpyx_skip_dispatch__rParen__etc_to_py_4self_1i.wrap
TypeError: wrap() takes exactly 2 positional arguments (1 given)
```

Experimenting a bit it seems that if the cpdef function is muted in a def function or if it is moved in the child class the code instead works.

### Code to reproduce the behaviour:

```cython
cdef class a:
    
    cpdef filt(self, i):
        
        return True
        
cdef class b(a):
        
    def func(self, list_):

        return filter(self.filt, list_) # it fails also with other iterator 
                                        # functions: map, itertools.filterfalse, ...
```

### Expected behaviour

No Compilation 

### Environment

OS: Linux
Python version: 3.10.6
Cython version: 3.0.0a11

**Comment by fantix** [comment]
This is now an error in GCC 14: https://github.com/gcc-mirror/gcc/commit/9715c545d33b3a32ddc1ae817ba9356ade1fb9df .

A temporary workaround is to set `CFLAGS="${CFLAGS} -Wno-error=incompatible-pointer-types"`.
