### ISSUE TITLE
[BUG] Compile error when typing.Optional and tuple[float] used in function annotation

### ISSUE THREAD

**Issue by HellLord77** [cython/cython#5263]
### Describe the bug

Cython compile throwing unexpected error. No error when annotated variable though. Used to work correctly in last alpha (3.0.0a11).

Command:
cythonize -3 test.py    

Traceback:
test.py:10:27: typing.Optional[...] cannot be applied to non-Python type (double)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Scripts\cythonize.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\Cython\Build\Cythonize.py", line 243, in main
    _cython_compile_files(all_paths, options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\Cython\Build\Cythonize.py", line 70, in _cython_compile_files
    ext_modules = cythonize(
                  ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\Cython\Build\Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\Cython\Build\Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: D:\Projects\cyth\test.py

### Code to reproduce the behaviour:

```cython
from typing import Optional, Union

foo: Optional[tuple[float]] = 1.0,  # No error


def bar() -> Optional[tuple[int]]:  # No error
    return 1,


def baz() -> Optional[tuple[float]]:  # Error
    return 1.0,


def qux() -> Union[None, tuple[float]]:  # No error
    return 1.0,

```

### Environment

OS: Windows
Python version 3.11
Cython version 3.0.0b1

**Comment by da-woods** [comment]
Thanks. A lot of this subscripted type annotation code is pretty new so we won't have caught all the corner cases.

I suspect what's happening is
```
tuple[float]
```
Is evaluating to a "c tuple" type. And it's falling to apply `Optional` to that. We should make sure that it doesn't do the "c tuple" change in places where it's expecting a Python type.
