### ISSUE TITLE
Cython could warn/error on invalid default values during compilation

### ISSUE THREAD

**Issue by anntzer** [cython/cython#538]
```
$ python --version; cython --version                                      
Python 3.5.2
Cython version 0.24.1

$ cat foo.pyx && cythonize -b foo.pyx && python -c 'import foo'
def foo(float x=None):
    return x
<elided cythonize output (with no warning)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "foo.pyx", line 1, in init foo (/tmp/foo/foo.c:882)
    def foo(float x=None):
TypeError: a float is required
```

Actually, having an error at import time (rather than either compile-time or call-time) is a bit weird (at least from a naive POV).

**Comment by robertwb** [comment]
If in Python you wrote

```
def foo(x=float(...)):
   ...
```
in Python you'd have the same behavior. But I suppose warning you earlier could be nice (if you know the rhs type is not coercible).

**Comment by anntzer** [comment]
To be honest I don't feel very strongly about this, but yes, it's mostly about warning the user as soon as possible.
