### ISSUE TITLE
unpack-assign-to-memoryview crashes cython

### ISSUE THREAD

**Issue by anntzer** [cython/cython#541]
```
$ cat /etc/*-release | grep \^NAME; python --version; cython --version                
NAME="Arch Linux"
Python 3.5.2
Cython version 0.24.1
```
In the code below, you can think of `y` as a one-tuple that contains an element that can be assigned to a memoryview slice, e.g. a single integer, or another integer array.
```
$ cat foo.pyx && cythonize -b foo.pyx >/dev/null && python -c 'import foo'
def assign(int[:] x, object y):
    x[:], = y
Traceback (most recent call last):
  File "/usr/bin/cythonize", line 9, in <module>
    load_entry_point('Cython==0.24.1', 'console_scripts', 'cythonize')()
  File "/usr/lib/python3.5/site-packages/Cython/Build/Cythonize.py", line 196, in main
    cython_compile(path, options)
  File "/usr/lib/python3.5/site-packages/Cython/Build/Cythonize.py", line 90, in cython_compile
    **options.options)
  File "/usr/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 915, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1020, in cythonize_one
    result = compile([pyx_file], options)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 690, in compile
    return compile_multiple(source, options)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 668, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 495, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Pipeline.py", line 365, in run_pipeline
    data = phase(data)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/ModuleNode.py", line 131, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/ModuleNode.py", line 359, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Nodes.py", line 435, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Nodes.py", line 3067, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Nodes.py", line 1944, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Nodes.py", line 1698, in generate_function_body
    self.body.generate_execution_code(code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Nodes.py", line 441, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Nodes.py", line 4787, in generate_execution_code
    self.generate_assignment_code(code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/Nodes.py", line 5084, in generate_assignment_code
    self.lhs.generate_assignment_code(self.rhs, code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/ExprNodes.py", line 6945, in generate_assignment_code
    self.generate_parallel_assignment_code(rhs, code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/ExprNodes.py", line 6980, in generate_parallel_assignment_code
    self.coerced_unpacked_items[i], code)
  File "/usr/lib/python3.5/site-packages/Cython/Compiler/ExprNodes.py", line 4250, in generate_assignment_code
    self.generate_memoryviewslice_setslice_code(rhs, code)
AttributeError: 'MemoryViewSliceNode' object has no attribute 'generate_memoryviewslice_setslice_code'
```

(Initially reported (a while ago) on cython-users.)

**Comment by excubo-jg** [comment]
I am running into the same `AttributeError` message. Has there been any update on this?
