### ISSUE TITLE
[BUG] Signature mismatch TypeError with const arguments

### ISSUE THREAD

**Issue by lysnikolaou** [cython/cython#5488]
### Describe the bug

Cython raises a `TypeError` that there's a signature mismatch, even if the only difference is that the runtime function has `const` in some of the argument, while the built function does not. This is something that C/C++ semantics allow, but Cython currently doesn't. Is it expected?

I've created a [minimal easily-reproducible project](https://github.com/lysnikolaou/const-cython) that showcases all of this. I'm copying the `README` from that project here, so that it's more easily accessible.

---------------------------------------------
This project aims to create a small easily-reproducible example of how Cython does not support
the following scenario:

- A library package `libcythonconst` defines a Cython `cdef` function that does not have `const`
  in its arguments in version 1.0.0. In version 1.0.1, it adds `const` to the function.
- A client package `cythonconst` depends on `libcythonconst` and, specifically, to the
  above-mentioned function. It is built against version 1.0.0 (without `const`), but it's installed alongside
  version 1.0.1 (with `const`).
  
Importing `cythonconst` in this scenario fails. *This is in contrast to C/C++ semantics, which would allow it.*
Here's the stack trace:

```python3
const-cython on  main via 🐍 pyenv 3.11.3 (venv) 
❯ python
Python 3.11.3 (main, May  8 2023, 13:16:43) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cythonconst
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lysnikolaou/repos/python/const-cython/venv/lib/python3.11/site-packages/cythonconst/__init__.py", line 1, in <module>
    from cythonconst.plus import plus_1
  File "cythonconst/plus.pyx", line 1, in init cythonconst.plus
TypeError: C function libcythonconst.lsum.lsum has wrong signature (expected PyObject *(int, int), got PyObject *(int const , int const ))
```

In order to reproduce this, you can do the following (or run `make test`):

```zsh
const-cython on  main via 🐍 pyenv 3.11.3
❯ python -m venv venv

const-cython on  main [?] via 🐍 pyenv 3.11.3 took 2s
❯ source venv/bin/activate

const-cython on  main [?] via 🐍 pyenv 3.11.3 (venv)
❯ python -m pip install cythonconst
Collecting cythonconst
  Using cached cythonconst-1.1.0-cp311-cp311-macosx_13_0_arm64.whl (29 kB)
Collecting libcythonconst
  Using cached libcythonconst-1.0.1-cp311-cp311-macosx_13_0_arm64.whl (27 kB)
Installing collected packages: libcythonconst, cythonconst
Successfully installed cythonconst-1.1.0 libcythonconst-1.0.1

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

const-cython on  main [?] via 🐍 pyenv 3.11.3 (.venv)
❯ python
Python 3.11.3 (main, May  8 2023, 13:16:43) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cythonconst
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lysnikolaou/repos/python/const-cython/.venv/lib/python3.11/site-packages/cythonconst/__init__.py", line 1, in <module>
    from cythonconst.plus import plus_1
  File "cythonconst/plus.pyx", line 1, in init cythonconst.plus
TypeError: C function libcythonconst.lsum.lsum has wrong signature (expected PyObject *(int const , int const ), got PyObject *(int, int))
```

See [`pyproject.toml` in client](client/pyproject.toml) for some extra info on how this is built to fail.

### Expected behaviour

No `TypeError` raised.

### OS

macOS

### Python version

3.11.3

### Cython version

0.29.35

**Comment by da-woods** [comment]
I think we just do a dumb string comparison for these functions. And we'd probably be reluctant to change that (because dumb string comparisons are easy).

In principle we could strip the consts from the function arguments when generating the string, but that'd break existing code in a very similar way. I guess we could have a stripped and unstripped string and check both. Still probably hard to do that without breaking existing code though.

If it were to be fixed it probably wouldn't be done in the 0.29.x branch since I don't think it's a regression. Cython 3.0 would be a convenient time to do it with minimal breakage, but I doubt that we want this to block the release.

**Comment by lysnikolaou** [comment]
Understood.

The context here, which might be interesting, is that we're trying to add `const` to the Cython wrappers of BLAS and Lapack on SciPy. Without this, it'd be impossible, since we would be breaking downstream packages built without the `const` in the signature (more info in [this scipy issue](https://github.com/scipy/scipy/issues/18377)).

**Comment by da-woods** [comment]
I wonder if we could use the PyCapsule "context" pointer to store a const-free version of the signature and use that as a secondary match. I'd propose allowing a colon separated string in case we need to add other compatible signatures in future. That seems to be the most obvious way of loading extra information into our existing mechanism.

Definitely can't promise that it can be done in the near future, but that's my proposal for how it could be done without breaking backwards compatibility on our end.
