### ISSUE TITLE
[BUG] Compilation failure when raising an exception within nogil function returning pointer

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5530]
### Describe the bug

When raising an exception within cython nogil function returning pointer value following error is raised:

```
Compiling /Users/matus/dev/cython/test/nogil.pyx because it changed.
[1/1] Cythonizing /Users/matus/dev/cython/test/nogil.pyx

Error compiling Cython file:
------------------------------------------------------------
...

cdef int *bar() nogil:
    raise ValueError
    ^
------------------------------------------------------------

nogil.pyx:10:4: Raising exception not allowed without gil
Traceback (most recent call last):
  File "/Users/matus/dev/cython39/bin/cythonize", line 33, in <module>
    sys.exit(load_entry_point('Cython', 'console_scripts', 'cythonize')())
  File "/Users/matus/dev/cython/Cython/Build/Cythonize.py", line 243, in main
    _cython_compile_files(all_paths, options)
  File "/Users/matus/dev/cython/Cython/Build/Cythonize.py", line 70, in _cython_compile_files
    ext_modules = cythonize(
  File "/Users/matus/dev/cython/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/Users/matus/dev/cython/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /Users/matus/dev/cython/test/nogil.pyx
```

### Code to reproduce the behaviour:

```cython
cdef int *bar() nogil:
    raise ValueError

bar()
```

### Expected behaviour

Compilation is successful

### OS

MacOS

### Python version

3.9

### Cython version

master

### Additional context

Compilation is successful for pure-python variant of example:
```python
import cython

@cython.cfunc
@cython.nogil
def bar() -> cython.p_int:
    raise ValueError

bar()
```

Also compilation is successful when function returns simple value (instead of pointer):
```cython
cdef int bar() nogil:
    raise ValueError

bar()
```

**Comment by matusvalo** [comment]
OK I found the reason why it fails when function returns pointer. In this line 

https://github.com/cython/cython/blob/0713b78ac3b2619d056792e75d42e67e933f8ffa/Cython/Compiler/ParseTreeTransforms.py#L3480

`node.declarator` is instance of `Cython.Compiler.Nodes.CPtrDeclaratorNode` in case when function returns pointer.
