### ISSUE TITLE
[BUG] typedef'd fused types cannot be used as a C++ template type

### ISSUE THREAD

**Issue by leofang** [cython/cython#5544]
### Describe the bug

The compiler crashes when compiling the `test3()` function, see below. (The other two functions compile fine, by the way.)
```bash
$ cythonize -i -3 test_fused.pyx 
Compiling /home/leof/dev/cuquantum/python/test_fused.pyx because it changed.
[1/1] Cythonizing /home/leof/dev/cuquantum/python/test_fused.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef vector[int64_t] x = [20, 21]
    return func[int64_t](x)

def test3():
    cdef vector[myT] x = [22, 23]
    return func[myT](x)
               ^
------------------------------------------------------------

test_fused.pyx:27:15: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(test_fused.pyx:3:0)
StatListNode.stats[8] = DefNode(test_fused.pyx:25:0,
    is_cyfunction = True,
    modifiers = [...]/0,
    name = 'test3',
    np_args_idx = [...]/0,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 397, in analyse_expressions: StatListNode(test_fused.pyx:26:4,
    is_terminator = True)
File 'Nodes.py', line 6781, in analyse_expressions: ReturnStatNode(test_fused.pyx:27:4,
    is_terminator = True)
File 'ExprNodes.py', line 6041, in analyse_types: SimpleCallNode(test_fused.pyx:27:20,
    analysed = True,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 4031, in analyse_types: IndexNode(test_fused.pyx:27:15,
    is_called = 1,
    is_fused_index = True,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 4103, in analyse_base_and_index_types: IndexNode(test_fused.pyx:27:15,
    is_called = 1,
    is_fused_index = True,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 4211, in analyse_as_c_function: IndexNode(test_fused.pyx:27:15,
    is_called = 1,
    is_fused_index = True,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 4409, in parse_indexed_fused_cdef: IndexNode(test_fused.pyx:27:15,
    is_called = 1,
    is_fused_index = True,
    is_subscript = True,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 4409, in parse_indexed_fused_cdef
    raise InternalError("Couldn't find the right signature")
InternalError: Internal compiler error: Couldn't find the right signature
Traceback (most recent call last):
  File "/home/leof/miniforge3/envs/opt_einsum_dev/bin/cythonize", line 11, in <module>
    sys.exit(main())
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/Cython/Build/Cythonize.py", line 243, in main
    _cython_compile_files(all_paths, options)
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/Cython/Build/Cythonize.py", line 70, in _cython_compile_files
    ext_modules = cythonize(
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/leof/dev/cuquantum/python/test_fused.pyx
```

### Code to reproduce the behaviour:

```cython
# distutils: language = c++

from libc.stdint cimport int32_t, int64_t
from libcpp.vector cimport vector


ctypedef int64_t myT

ctypedef fused numT:
    int32_t
    int64_t

cdef int func(vector[numT] x):
    x.push_back(1)
    return 0

def test1():
    cdef vector[int32_t] x = [18, 19]
    return func[int32_t](x)

def test2():
    cdef vector[int64_t] x = [20, 21]
    return func[int64_t](x)

def test3():
    cdef vector[myT] x = [22, 23]
    return func[myT](x)
```

### Expected behaviour

The typedef `myT` should be properly recognized as a valid fused type. It actually works fine if I don't use it as the C++ container template type, so for example, something like
```cython
cdef int func(numT x): 
    ... 

cdef int a = func[myT](x)
```
would actually compile and work as expected.

### OS

Linux

### Python version

3.8.13

### Cython version

3.0.0

### Additional context

btw since I don't have access to the old (0.29.x) docs due to #5535, let I also ask here: Is this new feature that I am trying with fused types only supported since Cython 3.0? I tried with 0.29.24+ and while it didn't crash, it raised an error "Can only parameterize template functions."

**Comment by da-woods** [comment]
That looks like a bug I think. I don't think the intended behaviour has changed between 0.29.x and 3.0 so the documentation won't be informative.

**Comment by leofang** [comment]
Tested with the latest Cython (3.0.10) and it still crashed the Cython compiler... 😢
