### ISSUE TITLE
[BUG] Class object type-hint results in "is not subscriptable" TypeError

### ISSUE THREAD

**Issue by LordAro** [cython/cython#5563]
### Describe the bug

Trying to use `type` class object type hint doesn't seem to work with compiled Python code:

```
$ python3 -c "import test4"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test4.py", line 4, in init test4
    FooType = type[Element]
TypeError: 'type' object is not subscriptable
```

Where test4.py has been compiled into a .so library.

### Code to reproduce the behaviour:

```python
class Element: pass

FooType = type[Element]
# OriginalType = defaultdict[type[Element], list[DifferentClass]]
```

compiled with:
```
cython -Wextra -X always_allow_keywords=True -3 -o test4.c test4.py
gcc -fPIC -shared -lpython3.11 -o test4.so test4.c
```

### Expected behaviour

No error, ideally. Python3.11 is fine with it normally:

$ python3
Python 3.11.4 (main, Jul 21 2023, 09:59:36) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class Element: pass
...
>>> FooType = type[Element]
>>>

### OS

Linux

### Python version

3.11.4

### Cython version

3.0.0

**Comment by da-woods** [comment]
Thanks for the report

It looks like `type[item]` is specifically special-cased in CPython so doesn't follow the normal rules:

https://github.com/python/cpython/blob/188000ae4b486cfffaeaa0a06902e4844d1b2bbc/Objects/abstract.c#L180-L183

```
        // Special case type[int], but disallow other types so str[int] fails
        if ((PyTypeObject*)o == &PyType_Type) {
            return Py_GenericAlias(o, key);
        }
```

So I guess Cython will have to add its own specific special-case

**Comment by federicocarne** [comment]
Hi! Just wondering if there are any updates on this issue. Thanks!
