### ISSUE TITLE
[BUG] Running into "Directory not empty" error with Cython 3.0.0

### ISSUE THREAD

**Issue by xwjiang2010** [cython/cython#5568]
### Describe the bug

```
OSError: [Errno 66] Directory not empty: '/Users/xwjiang/ray/python/.eggs/Cython-3.0.0-py3.9-macosx-10.9-x86_64.egg/Cython-3.0.0.dist-info' -> '/Users/xwjiang/ray/python/.eggs/Cython-3.0.0-py3.9-macosx-10.9-x86_64.egg/EGG-INFO'
```

Had to pin to lower version to unblock.

### Code to reproduce the behaviour:

```cython
# example code
```

**Comment by mattip** [comment]
Please give more complete information: when did you run into this error, what else was printed, how to reproduce.

**Comment by xwjiang2010** [comment]
It was encountered when running `pip install -e . --verbose` following [building ray](https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray-on-linux-macos-full).

I will link a full log capture when I get some time. But basically I had to pin the version number [here](https://github.com/ray-project/ray/blob/master/python/setup.py#L815) to successfully build ray.

**Comment by Ezibenroc** [comment]
Hello,
We observed the same problem on [pyroaring](https://github.com/Ezibenroc/PyRoaringBitMap).
We did not pin Cython version, so the recent release of version 3.0.0 broke our build. This [PR](https://github.com/Ezibenroc/PyRoaringBitMap/pull/94) fixed the issues, except for this last error that only happens on MacOS. See [these logs](https://github.com/Ezibenroc/PyRoaringBitMap/actions/runs/5674738787/job/15378812311?pr=94) for instance.

**Comment by arcondello** [comment]
This has also been encountered by `rectangle-packer`, see https://github.com/Penlect/rectangle-packer/pull/21.

Part of the stacktrace
```
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/Users/runner/work/rectangle-packer/rectangle-packer/setup.py", line 46, in <module>
        setup(
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 86, in setup
        _install_setup_requires(attrs)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 789, in resolve
        dist = best[req.key] = env.best_match(
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1075, in best_match
        return self.obtain(req, installer)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1087, in obtain
        return installer(requirement)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 110, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-hhb28qqb/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
        os.rename(dist_info, egg_info)
    OSError: [Errno 66] Directory not empty: '/Users/runner/work/rectangle-packer/rectangle-packer/.eggs/Cython-3.0.2-py3.9-macosx-10.9-x86_64.egg/Cython-3.0.2.dist-info' -> '/Users/runner/work/rectangle-packer/rectangle-packer/.eggs/Cython-3.0.2-py3.9-macosx-10.9-x86_64.egg/EGG-INFO'
    error: subprocess-exited-with-error
```

The full thing can be found [here](https://github.com/Penlect/rectangle-packer/actions/runs/5931975792/job/16322711130?pr=21).

**Comment by scoder** [comment]
So, if I understand this correctly, setuptools is trying to install Cython as a `setup_requires` dependency here. Apparently, it does this by converting our wheel to an egg, and then fails to convert the metadata to the older `.egg` format.

This looks much rather like an problem in setuptools than in Cython. Could you please report the issue on their side?

**Comment by arcondello** [comment]
Thanks!

Now that you've pointed me in the right direction, I _think_ this has actually been fixed in subsequent setuptools releases. The error we saw was using `setuptool==65.6.3`. I can't speak for the other users in this thread but in the case of rectangle-packer this version comes from a build script defined by cibuildwheel. So I'll head there next :smile:.

**Comment by arcondello** [comment]
No luck chasing it down on cibuildwheel/setuptools so far. But an additional datapoint is that it does seem to be exclusively an issues with Cython 3. See https://github.com/Penlect/rectangle-packer/pull/23. Specifically [build with Cython<3](https://github.com/Penlect/rectangle-packer/actions/runs/6470942550/job/17568257813?pr=23) vs [unbounded Cython](https://github.com/Penlect/rectangle-packer/actions/runs/6470666327/job/17567373248?pr=23).

Both are using the latest setuptools, pip, cibuildwheel etc.

**Comment by pydsigner** [comment]
I just hit this same issue with cffi 1.16.0 on MacOS with cibw, so it's not unique to Cython.

**Comment by ThomasWaldmann** [comment]
Just as a side note: `setup_requires` is deprecated and problematic.

Projects should use `pyproject.toml`, declare setup requirements there and remove `setup_requires` from setup.py.

**Comment by MissiontoMars** [comment]
> It was encountered when running `pip install -e . --verbose` following [building ray](https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray-on-linux-macos-full).
> 
> I will link a full log capture when I get some time. But basically I had to pin the cython version number [here](https://github.com/ray-project/ray/blob/master/python/setup.py#L815) to successfully build ray.

I encountered the same issue while building Ray, and it can only be resolved by specifying Cython < 3.

**Comment by tdewolff** [comment]
This was happening only on MacOS using Python 3.9 (and possibly higher), with CIBuildWheel. Fixed by moving the `setup_requires` from `setup.py` to `pyproject.toml`:

```
[build-system]
requires = ["setuptools>=42", "cffi>=1.0.0"]
build-backend = "setuptools.build_meta"
```

and removing the `setup_requires` line from `setup.py`.

**Comment by polm** [comment]
I was able to fix this issue on OSX builds by upgrading cibuildwheel rather than by moving `setup_requires` out of `setup.py`.

**Comment by aslonnie** [comment]
this is happening again when `setup_requires` is picking up cython 3.1.2

**Comment by lucasjinreal** [comment]
Same here
