### ISSUE TITLE
[BUG] cythonize crashes if pyx file contains unmatched string

### ISSUE THREAD

**Issue by dionhaefner** [cython/cython#5583]
### Describe the bug

Running `cybug.py` below leads to an infinite loop with unbounded memory growth until the OS kills it. (Run at your own risk.)

Traceback when interrupting:

```
^CTraceback (most recent call last):
  File "/Users/dion/codes/blocky/cybug.py", line 4, in <module>
    cythonize(Extension("*", ["cybug.pyx"], ))
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 990, in cythonize
    module_list, module_metadata = create_extension_list(
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 839, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 691, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 700, in transitive_merge
    return self.transitive_merge_helper(
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 706, in transitive_merge_helper
    deps = extract(node)
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 669, in distutils_info0
    info = self.parse_dependencies(filename)[3]
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 530, in parse_dependencies
    return parse_dependencies(source_filename)
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Utils.py", line 90, in wrapper
    res = cache[args] = f(*args)
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 493, in parse_dependencies
    source, literals = strip_string_literals(source)
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 361, in strip_string_literals
    label = "%s%s_" % (prefix, counter)
KeyboardInterrupt
```

### Code to reproduce the behaviour:

cybug.pyx
```cython
cdef foo():
   """A docstring with an extra quote at the end.""""
    pass


def bar():
    """A well-formed docstring."""
    # a comment in the prime of its years
    pass
```

cybug.py
```python
from Cython.Build import cythonize
from setuptools.extension import Extension

cythonize(Extension("*", ["cybug.pyx"], ))
```

### Expected behaviour

A helpful exception, such as the one that I get when removing the `bar` function:

```
Compiling cybug.pyx because it changed.
[1/1] Cythonizing cybug.pyx
/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /Users/dion/codes/blocky/cybug.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
cdef foo():
   """A docstring with an extra quote at the end.""""
                                                     ^
------------------------------------------------------------

cybug.pyx:2:53: Unclosed string literal
Traceback (most recent call last):
  File "/Users/dion/codes/blocky/cybug.py", line 4, in <module>
    cythonize(Extension("*", ["cybug.pyx"], ))
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/Users/dion/.virtualenvs/tempenv-6981144277dbb/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cybug.pyx
```

### OS

macOS

### Python version

3.11

### Cython version

3.0.0

**Comment by leftys** [comment]
wow, this got me.
still happens with 3.0.11, glad I found this issue :)

**Comment by da-woods** [comment]
This was fixed in the master branch in a8a2d41d7799b485b829bb95c36b4dacbeba5173.

I suspect it's enough of a corner case that we probably shouldn't backport it.
