### ISSUE TITLE
[BUG] FAIL: test_beta (cpp_stl_cmath_cpp17)

### ISSUE THREAD

**Issue by mtelka** [cython/cython#5599]
### Describe the bug

I see these test failures with Cython 3.0.0:
```
======================================================================
FAIL: test_beta (cpp_stl_cmath_cpp17)
Doctest: cpp_stl_cmath_cpp17.test_beta
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for cpp_stl_cmath_cpp17.test_beta
  File "$(BUILD_DIR)/TEST_TMP/run/cpp/cpp_stl_cmath_cpp17/cpp_stl_cmath_cpp17.cpython-39.so", line unknown line number, in test_beta
   
----------------------------------------------------------------------
File "$(BUILD_DIR)/TEST_TMP/run/cpp/cpp_stl_cmath_cpp17/cpp_stl_cmath_cpp17.cpython-39.so", line ?, in cpp_stl_cmath_cpp17.test_beta
Failed example:
    test_beta(1.0, 2.0) 
Expected:
    0.5
Got:
    0.49999999999999994


======================================================================
FAIL: test_beta (cpp_stl_cmath_cpp17)
Doctest: cpp_stl_cmath_cpp17.test_beta
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for cpp_stl_cmath_cpp17.test_beta
  File "$(BUILD_DIR)/TEST_TMP/run/cpp/cpp_stl_cmath_cpp17_directives_cpp_locals_True/cpp_stl_cmath_cpp17.cpython-39.so", line unknown line number, in test_beta

----------------------------------------------------------------------
File "$(BUILD_DIR)/TEST_TMP/run/cpp/cpp_stl_cmath_cpp17_directives_cpp_locals_True/cpp_stl_cmath_cpp17.cpython-39.so", line ?, in cpp_stl_cmath_cpp17.test_beta
Failed example:
    test_beta(1.0, 2.0)
Expected:
    0.5
Got:
    0.49999999999999994
```

### Code to reproduce the behaviour:

```
tox --current-env --no-provision --recreate -e py39
```

### Expected behaviour

Tests pass

### OS

OpenIndiana

### Python version

3.9.16

### Cython version

3.0.0

### Additional context

Maybe this is platform bug (see also #5198), but I'm not sure how to confirm that.

**Comment by da-woods** [comment]
This just looks like a small rounding error so I wouldn't worry about it - nothing significant is wrong. That's kind of an issue with doctests that a small difference in output can lead to test failure.

We're only really testing that we've wrapped the functions to the extent that we can call them. We're not really interested in testing the C++ standard library. So if you want to submit a PR to change the test so it passes for you that'd be fine.

Either way, not a big issue
