### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'cname'

### ISSUE THREAD

**Issue by albireox** [cython/cython#5645]
### Describe the bug

I'm receiving this error when trying to install [sep](https://pypi.org/project/sep/) on Ubuntu

```
  [1/1] Cythonizing sep.pyx
  Traceback (most recent call last):
    File "/opt/pyenv/versions/3.11.3/envs/gallegoj/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/pyenv/versions/3.11.3/envs/gallegoj/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/pyenv/versions/3.11.3/envs/gallegoj/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 38, in <module>
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
      cythonize_one(*args)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1280, in cythonize_one
      result = compile_single(pyx_file, options, full_module_name=full_module_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py", line 618, in compile_single
      return run_pipeline(source, options, full_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py", line 542, in run_pipeline
      err, enddata = Pipeline.run_pipeline(pipeline, source)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Pipeline.py", line 398, in run_pipeline
      data = run(phase, data)
             ^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Pipeline.py", line 375, in run
      return phase(data)
             ^^^^^^^^^^^
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
      module_node.process_implementation(options, result)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ModuleNode.py", line 222, in process_implementation
      self.generate_c_code(env, options, result)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ModuleNode.py", line 516, in generate_c_code
      self.body.generate_function_definitions(env, code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 404, in generate_function_definitions
      stat.generate_function_definitions(env, code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 404, in generate_function_definitions
      stat.generate_function_definitions(env, code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 3499, in generate_function_definitions
      self.defaults_getter.generate_function_definitions(env.global_scope(), code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 3506, in generate_function_definitions
      FuncDefNode.generate_function_definitions(self, env, code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 2200, in generate_function_definitions
      self.generate_function_body(env, code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 1953, in generate_function_body
      self.body.generate_execution_code(code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 6856, in generate_execution_code
      value.generate_evaluation_code(code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 831, in generate_evaluation_code
      self.generate_subexpr_evaluation_code(code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 846, in generate_subexpr_evaluation_code
      node.generate_evaluation_code(code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 837, in generate_evaluation_code
      self.generate_result_code(code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 8017, in generate_result_code
      self.generate_operation_code(code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 8576, in generate_operation_code
      self.generate_sequence_packing_code(code)
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 8084, in generate_sequence_packing_code
      code.put_incref(arg.result(), arg.ctype())
                      ^^^^^^^^^^^^
    File "/tmp/pip-build-env-gsjt32r2/overlay/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 10113, in result
      self.defaults_struct.lookup(self.arg.name).cname)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'cname'
```

This seems to fail only with Python 3.11. The same install worked last night, so I assume that this was broken by the update to Cython 3.0.1, which seems to have modified [this file](https://github.com/cython/cython/blob/master/Cython/Compiler/ExprNodes.py).

### Code to reproduce the behaviour:

No code, but I think it's quite reproducible by trying to install `sep` with Python 3.11 on Linux (Ubuntu, but probably other distros as well).

### OS

Linux

### Python version

3.11.3

### Cython version

3.0.1

**Comment by albireox** [comment]
Closing in favour of #5643 that was open while I typed this!
