### ISSUE TITLE
[BUG] AttributeError: 'PyObjectType' object has no attribute 'entry'

### ISSUE THREAD

**Issue by scottbelden** [cython/cython#5704]
### Describe the bug

When trying to run the fastavro CI with Cython 3, I get the following error. It works when I use Cython<3, but I'd like to be able to upgrade and unfortunately I'm not sure what the problem is. Here's a [link to the PR that uses Cython 3](https://github.com/fastavro/fastavro/pull/703), but the error itself is below:

[1/1] Cythonizing fastavro/_read.pyx
...
            writer_schema, named_schemas, offset, size, options,
        )

class Block:
    def __init__(
    ^
------------------------------------------------------------

fastavro/_read.pyx:962:4: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 203, in analyse_declarations: ModuleNode(_read.pyx:1:0,
    doc = 'Python code for reading AVRO files',
    full_module_name = 'fastavro._read')
File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:10:0)
File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:961:0)
File 'Nodes.py', line 5169, in analyse_declarations: PyClassDefNode(_read.pyx:961:0,
    name = 'Block')
File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:962:4)
File 'Nodes.py', line 2712, in analyse_declarations: CFuncDefNode(_read.pyx:962:4,
    args = [...]/10,
    modifiers = [...]/0,
    outer_attrs = [...]/2,
    overridable = True,
    visibility = 'private')
File 'Nodes.py', line 27[23](https://github.com/fastavro/fastavro/actions/runs/6193366151/job/16814773207?pr=703#step:7:24), in declare_cpdef_wrapper: CFuncDefNode(_read.pyx:962:4,
    args = [...]/10,
    modifiers = [...]/0,
    outer_attrs = [...]/2,
    overridable = True,
    visibility = 'private')
File 'Nodes.py', line 2789, in call_self_node: CFuncDefNode(_read.pyx:962:4,
    args = [...]/10,
    modifiers = [...]/0,
    outer_attrs = [...]/2,
    overridable = True,
    visibility = 'private')

Compiler crash traceback from this point on:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 2789, in call_self_node
    type_entry = self.type.args[0].type.entry
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PyObjectType' object has no attribute 'entry'
Traceback (most recent call last):
  File "/Users/runner/work/fastavro/fastavro/setup.py", line 37, in <module>
    setup(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/build_ext.py", line [24](https://github.com/fastavro/fastavro/actions/runs/6193366151/job/16814773207?pr=703#step:7:25)6, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
    new_ext = cythonize(
              ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1[30](https://github.com/fastavro/fastavro/actions/runs/6193366151/job/16814773207?pr=703#step:7:31)1, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: fastavro/_read.pyx
Error: Process completed with exit code 1.

### Code to reproduce the behaviour:

Unfortunately I don't have a minimal reproducible case because I don't fully understand the error. But this does reproduce the problem currently

```
git clone git@github.com:fastavro/fastavro.git
cd fastavro
git checkout dependabot/pip/cython-lt-4
python3.11 -m venv py311
source py311/bin/activate
pip install .
```

### Expected behaviour

No error

### OS

Linux, Windows, and macOS

### Python version

At least 3.9, 3.10, 3.11

### Cython version

3.0.2

**Comment by da-woods** [comment]
This bisects to 16aba7eb35b2a6f0c88b53da00539a5d875ebfdf

It really isn't obvious what's going wrong right now - it looks like a fairly standard definition of `__init__`

**Comment by da-woods** [comment]
Actually, the one unusual thing you're doing is `# cython: auto_cpdef=True` which practically isn't used much (so probably isn't tested much). At very least `__init__` should excluded from `cpdef`

**Comment by scottbelden** [comment]
Thanks for the hint. I think this might be on the right track. I removed those `auto_cpdef` comments and it still failed, but with RuntimeErrors about generators that I should be able to look into further myself. When I have time to look at that I'll comment back and let you know the outcome.

**Comment by scottbelden** [comment]
I removed the auto_cpdef and it revealed the underlying issue with my code. I'm not sure if there's anything to be done on the cython side, so feel free to close this if you'd like.

**Comment by da-woods** [comment]
I think we should at least have some tests for methods+`auto_cpdef` so I'll leave this open for now. Since I'm not convinced the bug is completely on your side
