### ISSUE TITLE
[BUG] Function pointer type variable is recognized as a non-function type by cython.

### ISSUE THREAD

**Issue by zoj613** [cython/cython#5766]
### Describe the bug

I have been testing out numpy's Iterator API and realized that I cannot correctly compile cython files that make use of the `NpyIter_IterNextFunc*` function pointer type. For some reason cython recognizes a variable assigned this type as a "non-function" type and fails to compile, as a result. I am not sure exactly why this happens and hope to find some pointer here on how to fix this issue?

Cc @seberg 

Here is the error message:
```

Error compiling Cython file:
------------------------------------------------------------
...
    iternext = NpyIter_GetIterNext(it, NULL)
    dataptr = NpyIter_GetDataPtrArray(it)

    while True:
        dataptr[2][0] = do_something(dataptr[0][0], dataptr[1][0])
        if not iternext(it):
                      ^
------------------------------------------------------------

example.pyx:63:23: Calling non-function type 'NpyIter_IterNextFunc'
Traceback (most recent call last):
  File "/home/zoj/.local/share/micromamba/envs/bin/cythonize", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zoj/.local/share/micromamba/envs/lib/python3.12/site-packages/Cython/Build/Cythonize.py", line 225, in main
    cython_compile(path, options)
  File "/home/zoj/.local/share/micromamba/envs/lib/python3.12/site-packages/Cython/Build/Cythonize.py", line 97, in cython_compile
    ext_modules = cythonize(
                  ^^^^^^^^^^
  File "/home/zoj/.local/share/micromamba/envs/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
    cythonize_one(*args)
  File "/home/zoj/.local/share/micromamba/envs/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/zoj/dev/example.pyx
```

### Code to reproduce the behaviour:

```cython
# cython: language_level=3
cimport numpy as np
from cpython.ref cimport Py_INCREF

np.import_array()


cdef extern from "numpy/ndarrayobject.h":
    np.PyArray_Descr* PyArray_DescrFromType(int)

    ctypedef struct NpyIter:
        pass

    cdef enum:
        NPY_FAIL
        NPY_SUCCEED

    cdef enum:
        NPY_ITER_ALLOCATE
        NPY_ITER_READONLY
        NPY_ITER_WRITEONLY
        NPY_ITER_ZEROSIZE_OK

    NpyIter* NpyIter_MultiNew(np.npy_intp nop, np.PyArrayObject** op,
                              np.npy_uint32 flags, np.NPY_ORDER order,
                              np.NPY_CASTING casting, np.npy_uint32* op_flags,
                              np.PyArray_Descr** op_dtypes) except? NULL

    ctypedef int (*NpyIter_IterNextFunc)(NpyIter* it) nogil
    NpyIter_IterNextFunc* NpyIter_GetIterNext(NpyIter* it, char** errmsg)
    char** NpyIter_GetDataPtrArray(NpyIter* it) nogil
    np.PyArrayObject** NpyIter_GetOperandArray(NpyIter* it)
    int NpyIter_Deallocate(NpyIter* it)


cdef double add(double x, double y) nogil:
    cdef double z = x + y
    return z


cdef object broadcasted_add(np.ndarray a, np.ndarray b):
    cdef:
        char** dataptr
        NpyIter* nditer
        NpyIter_IterNextFunc* iternext
        np.npy_uint32* op_flags = [NPY_ITER_READONLY, NPY_ITER_READONLY,
                                   NPY_ITER_WRITEONLY | NPY_ITER_ALLOCATE]
        np.PyArrayObject** ops = [<np.PyArrayObject*>h, <np.PyArrayObject*>z, NULL]

    it = NpyIter_MultiNew(3, &ops[0], NPY_ITER_ZEROSIZE_OK, np.NPY_KEEPORDER,
                          np.NPY_NO_CASTING, &op_flags[0], NULL)

    iternext = NpyIter_GetIterNext(it, NULL)
    dataptr = NpyIter_GetDataPtrArray(it)

    while True:
        dataptr[2][0] = add(dataptr[0][0], dataptr[1][0])
        if not iternext(it):
             break

    out = <np.ndarray>NpyIter_GetOperandArray(it)[2]
    Py_INCREF(out)
    NpyIter_Deallocate(it)
    return out
```

### Expected behaviour

I expected this to compile with no issues but I get the error message shown above.

### OS

Linux

### Python version

3.12 and 3.9

### Cython version

0.29.36 and 3.0.3

**Comment by da-woods** [comment]
```
NpyIter_IterNextFunc* iternext
```

This defines a pointer to a function pointer. Change it to

```
NpyIter_IterNextFunc iternext
```

**Comment by zoj613** [comment]
> ```
> NpyIter_IterNextFunc* iternext
> ```
> 
> This defines a pointer to a function pointer. Change it to
> 
> ```
> NpyIter_IterNextFunc iternext
> ```

I'm not sure this solves the issue because now I get:
```
rror compiling Cython file:
------------------------------------------------------------
...
        np.PyArrayObject** ops = [<np.PyArrayObject*>h, <np.PyArrayObject*>z, NULL]

    it = NpyIter_MultiNew(3, &ops[0], NPY_ITER_ZEROSIZE_OK, np.NPY_KEEPORDER,
                          np.NPY_NO_CASTING, &op_flags[0], NULL)

    iternext = NpyIter_GetIterNext(it, NULL)
                                  ^
------------------------------------------------------------

example.pyx:53:34: Cannot assign type 'NpyIter_IterNextFunc *' to 'NpyIter_IterNextFunc'
```

`NpyIter_GetIterNext` returns a `NpyIter_IterNextFunc *` not `NpyIter_IterNextFunc`. If I add something like 
```cython
	cdef:
        NpyIter_IterNextFunc iternext
        NpyIter_IterNextFunc* iternext_ptr
	...
    iternext_ptr = NpyIter_GetIterNext(it, NULL)
    iternext = iternext_ptr[0]
```
It compiles, but using the code raises this error:
```
error: subscripted value is pointer to function
       3452 |   __pyx_v_iternext = (__pyx_v_iternext_ptr[0]);
```
Clearly im doing something wrong here but not sure what. Any more suggestions @da-woods ?

**Comment by da-woods** [comment]
Final comment from me on the issue because this isn't a Cython bug and support questions should be asked on the Cython user's mailing list instead

This looks to be to do with how `NpyIter_IterNextFunc` is defined in Numpy which doesn't match your Cython definition:

https://github.com/numpy/numpy/blob/972c06c78cba81875ceb0aa7f5b14dcb19cce58b/numpy/core/include/numpy/ndarraytypes.h#L1004

```
typedef int (NpyIter_IterNextFunc)(NpyIter *iter);
```

The definition here isn't a pointer - and thus in the C code `NpyIter_IterNextFunc*` is a function pointer.

However in your Cython definition you define it as a pointer

```
    ctypedef int (*NpyIter_IterNextFunc)(NpyIter* it) nogil
```

And thus as far as Cython knows `NpyIter_IterNextFunc*` is a pointer to a function pointer. You need to make sure the two match.

That may involve defining a non-extern type

```
ctypedef int (*NpyIter_IterNextFunc_ptr)(NpyIter* it) nogil
```

and then using that type in your Cython code instead.

**Comment by da-woods** [comment]
Quick clarification (since I think my previous comment was a little vague on the actual solution):

You definitely can't do a "non-pointer function type" in Cython, so can't declare `NpyIter_IterNextFunc` exactly as it appears in the Numpy headers.

Therefore you do want to define your own function pointer typedef outside the extern block to use in Cython.

So to spell it out more fully:

```
ctypedef int (*NpyIter_IterNextFunc_ptr)(NpyIter* it) nogil

cdef extern from "numpy/ndarrayobject.h":
     # Note that this definition isn't exactly the same as the Numpy header, but that's fine - it returns the same type under
     # a typedef name
    NpyIter_IterNextFunc_ptr NpyIter_GetIterNext(NpyIter* it, char** errmsg)

    # ...

cdef object broadcasted_add(np.ndarray a, np.ndarray b):
    cdef:
        NpyIter_IterNextFunc_ptr iternext
    # ...
    iternext = NpyIter_GetIterNext(it, NULL)
    # ...
```

The inability to declare `NpyIter_IterNextFunc` as it appears in the Numpy headers is probably a bit of an omission from Cython, but  it's a slightly odd way of writing C code.

**Comment by zoj613** [comment]
Your suggestion worked very well, thanks @da-woods
