### ISSUE TITLE
[BUG] 3.0.5: test suite fails

### ISSUE THREAD

**Issue by kloczek** [cython/cython#5788]
### Describe the bug

Looks like test suite fails in `End-to-end coverage_cmd_src_pkg_layout` unit

### Code to reproduce the behaviour:

I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using 'installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

### Expected behaviour

test suite should not fail

### OS

Linux x86/64

### Python version

3.8.18

### Cython version

3.0.5

### Additional context

Here is last part of pytest log:
```console
======================================================================
FAIL: runTest (__main__.EndToEndTest)
[-1] End-to-end coverage_cmd_src_pkg_layout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 2079, in runTest
    self.assertEqual(0, res, "non-zero exit status, last output was:\n%r\n-- stdout:%s\n-- stderr:%s\n" % (
AssertionError: 0 != 1 : non-zero exit status, last output was:
'/usr/bin/python3 -m pip install .'
-- stdout:Defaulting to user installation because normal site-packages is not writeable
Processing /home/tkloczko/rpmbuild/BUILD/cython-3.0.5/TEST_TMP/run/coverage_cmd_src_pkg_layout
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: pkg
  Building wheel for pkg (setup.py): started
  Building wheel for pkg (setup.py): finished with status 'done'
  Created wheel for pkg: filename=pkg-0.0.0-cp38-cp38-linux_x86_64.whl size=88126 sha256=c0ae9b7b09f7f070084972c0d82c224b17ccbe8653796fee2d513e4cd8b045d7
  Stored in directory: /tmp/pip-ephem-wheel-cache-e0osouer/wheels/72/08/2b/23800fa4a838e2f3cea3689bef0cc5da1a80e1ca75e5915aab
Successfully built pkg
Installing collected packages: pkg

-- stderr:ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/tkloczko/.local/lib/python3.8/site-packages/pkg'
Check the permissions.




----------------------------------------------------------------------
Ran 15463 tests in 10665.013s

FAILED (failures=1, skipped=78)
Following tests excluded because of missing dependencies on your system:
   run.numpy_pythran
   run.numpy_pythran_unit
   TestCodeFormat
Most expensive pipeline stages: 'AnalyseDeclarationsTransform': 368.07 / 8321 (0.044 / run, 31.0%), 'generate_pyx_code_stage': 234.13 / 2736 (0.086 / run, 19.7%), 'inject_utility_code_stage': 152.02 / 3077 (0.049 / run, 12.8%), 'parse': 95.82 / 6449 (0.015 / run, 8.1%), 'AnalyseExpressionsTransform': 33.69 / 7163 (0.005 / run, 2.8%), 'ControlFlowAnalysis': 25.47 / 7164 (0.004 / run, 2.1%), 'RemoveUnreachableCode': 19.30 / 15487 (0.001 / run, 1.6%), 'MarkClosureVisitor': 16.29 / 8323 (0.002 / run, 1.4%), 'PostParse': 13.67 / 8323 (0.002 / run, 1.2%), 'InterpretCompilerDirectives': 13.39 / 8323 (0.002 / run, 1.1%)
Times:
compile-cpp :  4337.84 sec  (1386,  3.130 / run) - slowest: 'cpp:test_dataclasses' (172.31s), 'cpp:test_unicode' (105.07s), 'cpp:test_coroutines_pep492' (77.83s), 'cpp:test_grammar' (47.00s), 'cpp:test_asyncgen' (41.49s), 'cpp:memslice' (36.29s), 'cpp:numpy_test' (35.01s), 'cpp:test_exceptions' (30.93s)
compile-c   :  3785.97 sec  (1211,  3.126 / run) - slowest: 'c:test_dataclasses' (172.37s), 'c:test_unicode' (133.42s), 'c:test_coroutines_pep492' (91.82s), 'c:test_grammar' (55.27s), 'c:memslice' (47.98s), 'c:test_asyncgen' (44.24s), 'c:numpy_test' (39.17s), 'c:test_exceptions' (34.65s)
cython      :   839.03 sec  (2831,  0.296 / run) - slowest: 'cpp:test_dataclasses' (24.34s), 'c:test_dataclasses' (9.88s), 'c:test_unicode' (6.88s), 'cpp:test_unicode' (6.43s), 'cpp:test_coroutines_pep492' (6.22s), 'c:test_coroutines_pep492' (5.76s), 'cpp:numpy_test' (5.46s), 'c:cyfunction_defaults' (5.20s)
run         :   470.26 sec  (1656,  0.284 / run) - slowest: 'c:test_coroutines_pep492' (164.46s), 'c:test_fstring' (84.30s), 'cpp:memslice' (33.21s), 'c:memslice' (32.53s), 'c:trashcan' (26.41s), 'cpp:trashcan' (26.11s), 'c:test_named_expressions' (13.64s), 'c:test_grammar' (6.31s)
etoe-build  :   467.40 sec  (  99,  4.721 / run) - slowest: 'c:memoryview_compare_type_pointers(1)' (18.03s), 'c:relative_cimport(1)' (15.99s), 'c:memoryview_acq_count(1)' (15.08s), 'c:public_fused_types(1)' (14.11s), 'c:pure_pxd(1)' (12.61s), 'c:cdef_multiple_inheritance_errors(1)' (11.89s), 'c:relative_cimport_compare(1)' (10.41s), 'c:coverage_api(2)' (10.24s)
etoe-run    :    79.54 sec  ( 200,  0.398 / run) - slowest: 'c:coverage_cmd_src_pkg_layout(1)' (7.10s), 'c:cpdef_pickle(1)' (4.01s), 'c:importas_from_package(1)' (3.47s), 'c:importas_from_package(4)' (3.40s), 'c:cythonize_with_annotate_via_cli(5)' (3.27s), 'c:cythonize_script_package(1)' (3.12s), 'c:cythonize_script(1)' (2.80s), 'c:cythonize_with_annotate_via_cli(3)' (2.48s)
import      :     2.89 sec  (1656,  0.002 / run) - slowest: 'c:test_dataclasses' (0.04s), 'cpp:test_dataclasses' (0.02s), 'c:pep526_variable_annotations' (0.02s), 'c:r_pyclassdefault' (0.01s), 'c:memslice' (0.01s), 'c:test_exceptions' (0.01s), 'c:r_lepage_3' (0.01s), 'cpp:cpp_stl_numeric_ops' (0.01s)
pyrun       :     0.68 sec  (  74,  0.009 / run) - slowest: 'py:posonly' (0.06s), 'py:pure_py' (0.05s), 'py:constant_folding' (0.04s), 'py:generators_py' (0.04s), 'py:methodmangling_T5' (0.03s), 'py:withstat_py' (0.02s), 'py:uninitialized' (0.02s), 'py:ext_auto_richcmp' (0.02s)
pyimport    :     0.09 sec  (  74,  0.001 / run) - slowest: 'py:constant_folding' (0.00s), 'py:pure_py' (0.00s), 'py:pep526_variable_annotations' (0.00s), 'py:pure_cdef_class_dataclass' (0.00s), 'py:posonly' (0.00s), 'py:pep557_dataclasses' (0.00s), 'py:generators_py' (0.00s), 'py:methodmangling_T5' (0.00s)
ALL DONE
Compiler output for module parallel:
parallel.cpp: In function ‘int __pyx_pymod_exec_parallel(PyObject*)’:
parallel.cpp:2477:47: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 2477 |                 for (__pyx_t_5 = 0; __pyx_t_5 < __pyx_t_4; __pyx_t_5+=1) {
      |                                     ~~~~~~~~~~^~~~~~~~~~~

Compiler output for module parallel:
parallel.cpp: In function ‘int __pyx_pymod_exec_parallel(PyObject*)’:
parallel.cpp:2463:47: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 2463 |                 for (__pyx_t_5 = 0; __pyx_t_5 < __pyx_t_4; __pyx_t_5+=1) {
      |                                     ~~~~~~~~~~^~~~~~~~~~~

```

**Comment by kloczek** [comment]
Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -------
alabaster                     0.7.13
Babel                         2.13.1
build                         1.0.0
charset-normalizer            3.3.1
coverage                      7.3.2
cppclean                      0.13
distro                        1.8.0
docutils                      0.20.1
gpg                           1.23.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.8.0
installer                     0.7.0
jedi                          0.19.1
Jinja2                        3.1.2
MarkupSafe                    2.1.3
numpy                         1.24.4
packaging                     23.2
parso                         0.8.3
Pygments                      2.16.1
pyproject_hooks               1.0.0
python-dateutil               2.8.2
pytz                          2023.3
requests                      2.31.0
setuptools                    68.2.2
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        7.1.2
sphinx-issues                 3.0.1
sphinx-tabs                   3.4.1
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.9
tomli                         2.0.1
urllib3                       1.26.18
wheel                         0.41.2
zipp                          3.17.0
```
</details>

**Comment by scoder** [comment]
> ```
> '/usr/bin/python3 -m pip install .'
> ```

I don't understand that line in the test. It probably won't work outside of venvs, and it modifies the venv just by running the test. That's bad, we should never do that.

The test was added in https://github.com/cython/cython/pull/3831. It fails without that line.

**Comment by scoder** [comment]
In any case, it's a bug in the test, not in Cython itself. Excluding the test is fine if you want to make the test suite pass again.

**Comment by kloczek** [comment]
> In any case, it's a bug in the test, not in Cython itself. 

OK. So I give green lit to star use it 👍 
Thx for your expertise 😄 
Is it possible somehow exclude that ingle unit on test suite execution?
I'm asking because whole whole cython test suite is executed as single pytest unit? 🤔 

BTW: it would be really good to star moving current test suite units piece by piece under the pytest hood to be able speedup test suite execution by use for example with xdist pytest extension. I know that it may be long and not easy proces but at least some new units should not longer go under current hood.

> Excluding the test is fine if you want to make the test suite pass again.

That would be used only as temporary workaround because in my packaging process test suite is executed one time.

**Comment by kloczek** [comment]
Correction: I forgot that current test suite has nothing to do with pytest 😞

**Comment by kloczek** [comment]
Just tested 3.0.6 and test suite still fails
<details>

```console
runTest (__main__.CythonCompileTestCase)
[-1] compiling (cpp/cy2) vector_demo ... ok
runTest (__main__.CythonCompileTestCase)
[-1] compiling (cpp/cy2) wrapper_vector ... ok

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
[-1] compiling (c/cy2) and running numpy_math
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 266, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runtests.py", line 1550, in run
    ext_so_path = self.runCompileTest()
  File "runtests.py", line 1163, in runCompileTest
    return self.compile(
  File "runtests.py", line 1482, in compile
    so_path = self.run_distutils(test_directory, module, workdir, incdir)
  File "runtests.py", line 1378, in run_distutils
    build_extension.run()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "runtests.py", line 637, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 572, in build_extension
    self.compiler.link_shared_object(
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 752, in link_shared_object
    self.link(
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
    raise LinkError(msg)
distutils.errors.LinkError: command '/usr/bin/gcc' failed with exit code 1

======================================================================
FAIL: runTest (__main__.EndToEndTest)
[-1] End-to-end coverage_cmd_src_pkg_layout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 2097, in runTest
    self.assertEqual(0, res, "non-zero exit status, last output was:\n%r\n-- stdout:%s\n-- stderr:%s\n" % (
AssertionError: 0 != 1 : non-zero exit status, last output was:
'/usr/bin/python3 -m pip install .'
-- stdout:Defaulting to user installation because normal site-packages is not writeable
Processing /home/tkloczko/rpmbuild/BUILD/cython-3.0.6/TEST_TMP/run/coverage_cmd_src_pkg_layout
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: pkg
  Building wheel for pkg (setup.py): started
  Building wheel for pkg (setup.py): finished with status 'done'
  Created wheel for pkg: filename=pkg-0.0.0-cp38-cp38-linux_x86_64.whl size=88223 sha256=d5461010286373f928737ecd2ea0c411c31ff1875e860fa98b44b1a4cfaeed76
  Stored in directory: /tmp/pip-ephem-wheel-cache-i8dvatiu/wheels/0a/d5/77/700c2371a971e875ea860bb1371ac44147d80449dfe350d569
Successfully built pkg
Installing collected packages: pkg

-- stderr:ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/tkloczko/.local/lib/python3.8/site-packages/pkg'
Check the permissions.




----------------------------------------------------------------------
Ran 15453 tests in 15569.114s

FAILED (failures=1, errors=1, skipped=78)
Following tests excluded because of missing dependencies on your system:
   run.numpy_pythran
   run.numpy_pythran_unit
   TestCodeFormat
Most expensive pipeline stages: 'AnalyseDeclarationsTransform': 318.87 / 8351 (0.038 / run, 29.8%), 'generate_pyx_code_stage': 216.35 / 2721 (0.080 / run, 20.2%), 'inject_utility_code_stage': 140.63 / 3062 (0.046 / run, 13.1%), 'parse': 85.12 / 6479 (0.013 / run, 7.9%), 'AnalyseExpressionsTransform': 30.87 / 7193 (0.004 / run, 2.9%), 'ControlFlowAnalysis': 25.94 / 7194 (0.004 / run, 2.4%), 'RemoveUnreachableCode': 17.67 / 15547 (0.001 / run, 1.6%), 'MarkClosureVisitor': 15.44 / 8353 (0.002 / run, 1.4%), 'PostParse': 12.59 / 8353 (0.002 / run, 1.2%), 'InterpretCompilerDirectives': 11.63 / 8353 (0.001 / run, 1.1%)
Times:
compile-cpp :  6709.57 sec  (1386,  4.841 / run) - slowest: 'cpp:test_dataclasses' (222.39s), 'cpp:test_unicode' (180.71s), 'cpp:numpy_test' (150.09s), 'cpp:test_coroutines_pep492' (142.35s), 'cpp:test_grammar' (81.44s), 'cpp:test_asyncgen' (77.25s), 'cpp:memslice' (65.47s), 'cpp:test_exceptions' (53.79s)
compile-c   :  6266.12 sec  (1210,  5.179 / run) - slowest: 'c:test_dataclasses' (251.07s), 'c:test_unicode' (228.96s), 'c:numpy_test' (169.21s), 'c:test_coroutines_pep492' (157.36s), 'c:test_grammar' (94.13s), 'c:test_asyncgen' (81.69s), 'c:memslice' (77.00s), 'c:test_exceptions' (59.36s)
cython      :   760.33 sec  (2831,  0.269 / run) - slowest: 'cpp:numpy_test' (11.69s), 'cpp:test_dataclasses' (11.17s), 'c:test_dataclasses' (10.66s), 'c:test_unicode' (6.42s), 'cpp:test_unicode' (5.93s), 'cpp:test_coroutines_pep492' (5.80s), 'c:parallel' (5.51s), 'c:test_coroutines_pep492' (5.47s)
etoe-build  :   652.80 sec  (  99,  6.594 / run) - slowest: 'c:extern_varobject_extensions(1)' (28.89s), 'c:memoryview_compare_type_pointers(1)' (28.34s), 'c:memoryview_acq_count(1)' (23.40s), 'c:public_fused_types(1)' (22.38s), 'c:cdef_multiple_inheritance_errors(1)' (19.16s), 'c:pure_pxd(1)' (18.15s), 'c:line_profile_test(1)' (17.06s), 'c:pep442_tp_finalize_cimport(1)' (16.78s)
run         :   608.80 sec  (1655,  0.368 / run) - slowest: 'c:test_coroutines_pep492' (271.78s), 'c:test_fstring' (138.65s), 'cpp:memslice' (25.43s), 'c:memslice' (24.97s), 'c:trashcan' (22.28s), 'cpp:trashcan' (22.15s), 'c:test_named_expressions' (18.51s), 'c:test_grammar' (8.71s)
etoe-run    :    82.44 sec  ( 200,  0.412 / run) - slowest: 'c:cpdef_pickle(1)' (5.55s), 'c:coverage_cmd_src_pkg_layout(1)' (4.80s), 'c:importas_from_package(4)' (4.25s), 'c:importas_from_package(1)' (4.19s), 'c:cythonize_script_package(1)' (3.84s), 'c:cythonize_with_annotate_via_cli(5)' (3.74s), 'c:cythonize_script(1)' (3.26s), 'c:cythonize_with_annotate_via_cli(3)' (3.19s)
import      :     2.63 sec  (1655,  0.002 / run) - slowest: 'c:pep526_variable_annotations' (0.05s), 'cpp:external_ref_reassignment' (0.03s), 'c:special_methods_T561_py3' (0.02s), 'c:test_dataclasses' (0.02s), 'cpp:test_dataclasses' (0.02s), 'c:extra_walrus' (0.02s), 'cpp:methodmangling_pure' (0.02s), 'cpp:numpy_test' (0.01s)
pyrun       :     0.71 sec  (  74,  0.010 / run) - slowest: 'py:posonly' (0.07s), 'py:methodmangling_T5' (0.07s), 'py:pure_py' (0.05s), 'py:pep526_variable_annotations' (0.04s), 'py:generators_py' (0.03s), 'py:constant_folding' (0.03s), 'py:withstat_py' (0.02s), 'py:uninitialized' (0.02s)
pyimport    :     0.10 sec  (  74,  0.001 / run) - slowest: 'py:pep526_variable_annotations' (0.01s), 'py:onelinesuite' (0.00s), 'py:methodmangling_T5' (0.00s), 'py:pep557_dataclasses' (0.00s), 'py:pure_py' (0.00s), 'py:extra_walrus' (0.00s), 'py:posonly' (0.00s), 'py:constant_folding' (0.00s)
ALL DONE
Compiler output for module function_pointer_struct:
function_pointer_struct.cpp:2510:18: warning: ‘PyObject* __Pyx_CFunc_int__lParenint__comma_int__rParenexcept__3F__2D1_to_py_1a_1b(int (*)(int, int))’ defined but not used [-Wunused-function]
 2510 | static PyObject *__Pyx_CFunc_int__lParenint__comma_int__rParenexcept__3F__2D1_to_py_1a_1b(int (*__pyx_v_f)(int, int)) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compiler output for module breaking_loop:
breaking_loop.c:1955:12: warning: ‘__pyx_f_13breaking_loop_func’ defined but not used [-Wunused-function]
 1955 | static int __pyx_f_13breaking_loop_func(CYTHON_UNUSED Py_ssize_t __pyx_v_n) {
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compiler output for module breaking_loop:
breaking_loop.cpp:1967:12: warning: ‘int __pyx_f_13breaking_loop_func(Py_ssize_t)’ defined but not used [-Wunused-function]
 1967 | static int __pyx_f_13breaking_loop_func(CYTHON_UNUSED Py_ssize_t __pyx_v_n) {
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compiler output for module breaking_loop:
breaking_loop.c:1949:12: warning: ‘__pyx_f_13breaking_loop_func’ defined but not used [-Wunused-function]
 1949 | static int __pyx_f_13breaking_loop_func(CYTHON_UNUSED Py_ssize_t __pyx_v_n) {
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compiler output for module breaking_loop:
breaking_loop.cpp:1961:12: warning: ‘int __pyx_f_13breaking_loop_func(Py_ssize_t)’ defined but not used [-Wunused-function]
 1961 | static int __pyx_f_13breaking_loop_func(CYTHON_UNUSED Py_ssize_t __pyx_v_n) {
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compiler output for module parallel:
parallel.cpp: In function ‘int __pyx_pymod_exec_parallel(PyObject*)’:
parallel.cpp:2477:47: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 2477 |                 for (__pyx_t_5 = 0; __pyx_t_5 < __pyx_t_4; __pyx_t_5+=1) {
      |                                     ~~~~~~~~~~^~~~~~~~~~~

Compiler output for module parallel:
parallel.cpp: In function ‘int __pyx_pymod_exec_parallel(PyObject*)’:
parallel.cpp:2463:47: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 2463 |                 for (__pyx_t_5 = 0; __pyx_t_5 < __pyx_t_4; __pyx_t_5+=1) {
      |                                     ~~~~~~~~~~^~~~~~~~~~~

```
</details>

So test suite still tries to install module in account sitelib directory.
