### ISSUE TITLE
[BUG] cannot install insightface which depend cython>=3.0.0

### ISSUE THREAD

**Issue by HShan886** [cython/cython#5880]
### Describe the bug

build python cinder version with `nvcr.io/nvidia/pytorch:22.08-py3` container, then install insightface by pip in virtual environment. however, pip reports a error:
```
(cpython3.10-a3c6e07ed141-compat-2d3356be745c) root@SINIAN-01:/opt# pip install -U insightface
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting insightface
  Downloading insightface-0.7.3.tar.gz (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 8.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      WARNING: pandoc not enabled
      Traceback (most recent call last):
        File "/opt/venv/cpython3.10-a3c6e07ed141-compat-2d3356be745c/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/venv/cpython3.10-a3c6e07ed141-compat-2d3356be745c/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/venv/cpython3.10-a3c6e07ed141-compat-2d3356be745c/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1008, in cythonize
          ctx = Context.from_options(c_options)
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py", line 100, in from_options
          return cls(options.include_path, options.compiler_directives,
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py", line 80, in __init__
          self.cython_scope = CythonScope.create_cython_scope(self)
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/Cython/Compiler/CythonScope.py", line 154, in create_cython_scope
          return CythonScope(context)
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/Cython/Compiler/CythonScope.py", line 17, in __init__
          ModuleScope.__init__(self, u'cython', None, None)
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/Cython/Compiler/Symtab.py", line 1324, in __init__
          self.process_include(Code.IncludeCode("Python.h", initial=True))
        File "/tmp/pip-build-env-z9mcptwz/overlay/lib/python3.10/site-packages/Cython/Compiler/Symtab.py", line 1493, in process_include
          key = inc.mainpiece()
      TypeError: mainpiece() takes exactly one argument (1152921504606846977 given)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Due to insightface depend cython, and it will install latest cython-3.0.6, the error could reproduce. when downgrade cython version to 0.29.36, it run successfully.
maybe it's a bug after 0.29.36

### Expected behaviour

run successfully

### OS

Linux

### Python version

3.10.5+cinder

### Cython version

>= 3.0.0

**Comment by da-woods** [comment]
My guess would be that this is a Cinder bug. Cinder isn't something we've said support (or even something that Meta say they support, according to their own readme).

Based on this comment https://github.com/facebookincubator/cinder/issues/129#issuecomment-1821168928 I suspect it isn't handling vectorcall and `PY_VECTORCALL_ARGUMENTS_OFFSET` correctly. You could try defining the CFLAG `CYTHON_VECTORCALL` to 0, or you could try to use a try installing Cython with `--no-cython-compile` (I don't know how you do that when it's a dependency).

I think unless you can reproduce this with a "proper" Python version then you're on your own.

We'd be happy to merge a PR to ModuleSetupCode.c that makes Cinder work, but someone else would have to do it I think.
