### ISSUE TITLE
[BUG] test failure: cpp_stl_any.cast_test on i386 in Debian CI

### ISSUE THREAD

**Issue by stefanor** [cython/cython#5928]
### Describe the bug

`cpp_stl_any.cast_test` is failing on i386 (32bit x86) in Debian's CI.

Logs: https://ci.debian.net/packages/c/cython/

The cause isn't obvious so we'll skip the test, but I'm filing this so that someone can investigate more deeply.

### OS

Linux (Debian)

### Python version

3.12.1

### Cython version

3.0.6

### Additional context

```
======================================================================
FAIL: cast_test (cpp_stl_any)
Doctest: cpp_stl_any.cast_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/doctest.py", line 2247, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for cpp_stl_any.cast_test
  File "/tmp/autopkgtest-lxc.uq29_z3h/downtmp/autopkgtest_tmp/test-work-dir/1/run/cpp/cpp_stl_any/cpp_stl_any.cpython-312-i386-linux-gnu.so", line unknown line number, in cast_test

----------------------------------------------------------------------
File "/tmp/autopkgtest-lxc.uq29_z3h/downtmp/autopkgtest_tmp/test-work-dir/1/run/cpp/cpp_stl_any/cpp_stl_any.cpython-312-i386-linux-gnu.so", line ?, in cpp_stl_any.cast_test
Failed example:
    cast_test()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1359, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest cpp_stl_any.cast_test[0]>", line 1, in <module>
        cast_test()
      File "tests/run/cpp_stl_any.pyx", line 44, in cpp_stl_any.cast_test (cpp_stl_any.cpp:2882)
        assert any_cast[double](a) == 3.14
    AssertionError


======================================================================
FAIL: cast_test (cpp_stl_any)
Doctest: cpp_stl_any.cast_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/doctest.py", line 2247, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for cpp_stl_any.cast_test
  File "/tmp/autopkgtest-lxc.uq29_z3h/downtmp/autopkgtest_tmp/test-work-dir/1/run/cpp/cpp_stl_any_directives_cpp_locals_True/cpp_stl_any.cpython-312-i386-linux-gnu.so", line unknown line number, in cast_test

----------------------------------------------------------------------
File "/tmp/autopkgtest-lxc.uq29_z3h/downtmp/autopkgtest_tmp/test-work-dir/1/run/cpp/cpp_stl_any_directives_cpp_locals_True/cpp_stl_any.cpython-312-i386-linux-gnu.so", line ?, in cpp_stl_any.cast_test
Failed example:
    cast_test()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1359, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest cpp_stl_any.cast_test[0]>", line 1, in <module>
        cast_test()
      File "tests/run/cpp_stl_any.pyx", line 44, in cpp_stl_any.cast_test (cpp_stl_any.cpp:2882)
        assert any_cast[double](a) == 3.14
    AssertionError
```

**Comment by matoro** [comment]
Also see this on python 3.11.7, cython 3.0.8.
