### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by YoSTEALTH** [cython/cython#5976]
### Describe the bug

Error `ModuleNotFoundError: No module named 'distutils'` is raised while running https://github.com/YoSTEALTH/Dynamic-Import/blob/master/.github/workflows/test.yml#L26-L28
Test is located at https://github.com/YoSTEALTH/Dynamic-Import/blob/master/test/extract_test.py

### Code to reproduce the behaviour:

```bash
Run python -m pytest
============================= test session starts ==============================
platform linux -- Python 3.12.1, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/runner/work/Dynamic-Import/Dynamic-Import
collected 20 items

test/cache_test.py ......                                                [ 30%]
test/check_test.py ...                                                   [ 45%]
test/extract_test.py .F                                                  [ 55%]
test/other_test.py ..                                                    [ 65%]
test/prep_test.py ...                                                    [ 80%]
test/special_test.py ....                                                [100%]

=================================== FAILURES ===================================
___________________________ test_extract_so_variable ___________________________

tmp_dir = PosixPath('/tmp/pytest-of-runner-holder/tmpf7gmgmh5')

    @pytest.mark.skipif(skip_cython, reason='Cython/Cythonize NOT Installed!')
    def test_extract_so_variable(tmp_dir):
        # create 'pkg' directory
        pkg_path = tmp_dir / 'pkg'
        pkg_path.mkdir()
    
        # create '__init__.pyx'
        pyx = pkg_path / '__init__.py'
        pyx.write_text('')
    
        # create 'one.pyx'
        one_pyx = pkg_path / 'one.pyx'
        one_pyx.write_text('cpdef hello_one(name):\n\treturn f"Hello {name}!"\n\n')
    
        # create 'two.pyx'
        two_pyx = pkg_path / 'two.pyx'
        two_pyx.write_text('__all__ = ["hello_two"]\ncpdef hello_two(name):\n\treturn f"Hello {name}!"\n\n')
    
        # create 'three.pyx'
        three_pyx = pkg_path / 'three.pyx'
        three_pyx.write_text('__all__ = "hello_three"\ncpdef hello_three(name):\n\treturn f"Hello {name}!"\n\n')
    
        # create 'error.pyx'
        error_pyx = pkg_path / 'error.pyx'
        error_pyx.write_text('__all__ = 123\ncpdef hello_error(name):\n\treturn f"Hello {name}!"\n\n')
    
        # compile all `.so` file
>       assert subprocess.run([cythonize, '--inplace', f'--parallel={jobs}',
                              str(one_pyx), str(two_pyx), str(three_pyx), str(error_pyx)],
                              capture_output=False).returncode == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = CompletedProcess(args=['/opt/hostedtoolcache/Python/3.12.1/x64/bin/cythonize', '--inplace', '--parallel=4', '/tmp/pyte...t-of-runner-holder/tmpf7gmgmh5/pkg/three.pyx', '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/error.pyx'], returncode=1).returncode
E        +    where CompletedProcess(args=['/opt/hostedtoolcache/Python/3.12.1/x64/bin/cythonize', '--inplace', '--parallel=4', '/tmp/pyte...t-of-runner-holder/tmpf7gmgmh5/pkg/three.pyx', '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/error.pyx'], returncode=1) = <function run at 0x7fab61393420>(['/opt/hostedtoolcache/Python/3.12.1/x64/bin/cythonize', '--inplace', '--parallel=4', '/tmp/pytest-of-runner-holder/tm... '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/two.pyx', '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/three.pyx', ...], capture_output=False)
E        +      where <function run at 0x7fab61393420> = subprocess.run

test/extract_test.py:52: AssertionError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.1/x64/bin/cythonize", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/Cython/Build/Cythonize.py", line 251, in main
    _cython_compile_files(all_paths, options)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/Cython/Build/Cythonize.py", line 67, in _cython_compile_files
    ext_modules = cythonize(
                  ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
    module_list, module_metadata = create_extension_list(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 784, in create_extension_list
    from distutils.extension import Extension
ModuleNotFoundError: No module named 'distutils'
=========================== short test summary info ============================
FAILED test/extract_test.py::test_extract_so_variable - AssertionError: assert 1 == 0
 +  where 1 = CompletedProcess(args=['/opt/hostedtoolcache/Python/3.12.1/x64/bin/cythonize', '--inplace', '--parallel=4', '/tmp/pyte...t-of-runner-holder/tmpf7gmgmh5/pkg/three.pyx', '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/error.pyx'], returncode=1).returncode
 +    where CompletedProcess(args=['/opt/hostedtoolcache/Python/3.12.1/x64/bin/cythonize', '--inplace', '--parallel=4', '/tmp/pyte...t-of-runner-holder/tmpf7gmgmh5/pkg/three.pyx', '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/error.pyx'], returncode=1) = <function run at 0x7fab61393420>(['/opt/hostedtoolcache/Python/3.12.1/x64/bin/cythonize', '--inplace', '--parallel=4', '/tmp/pytest-of-runner-holder/tm... '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/two.pyx', '/tmp/pytest-of-runner-holder/tmpf7gmgmh5/pkg/three.pyx', ...], capture_output=False)
 +      where <function run at 0x7fab61393420> = subprocess.run
========================= 1 failed, 19 passed in 0.54s =========================
Error: Process completed with exit code 1.
```

### OS

Linux, MacOS

### Python version

3.12

### Cython version

Cython-3.0.8

### Additional context

Running same test for python `3.8` there is no error

**Comment by da-woods** [comment]
Distutils was removed from the standard library in Python 3.12 but you get it as part of setuptools.

There's been a bit of work on trying to fix the distutils/setuptools dependency mess, but I'm not sure it's reached it's final state.  I think we I've made some improvements to the error messages to direct people to setuptools now, but they may not have made it into a release yet.

**Comment by YoSTEALTH** [comment]
@da-woods from what I can tell `from distutils.extension import Extension` was hard-coded https://github.com/cython/cython/blob/master/Cython/Build/Dependencies.py#L764 inside a function. This doesn't account for `setuptools`

**Comment by da-woods** [comment]
Yes but if you install setuptools then it makes distutils available for import (directly, with `import distutils`):

```
Python 3.12.1 (main, Dec 15 2023, 10:49:50) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils
>>> distutils.__file__
'<path to home>/.local/lib/python3.12/site-packages/setuptools/_distutils/__init__.py'
```

**Comment by YoSTEALTH** [comment]
@da-woods thanks for clarifying, I will leave it at that. I did account for it on my test code as well so its good for now.

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/76691103/13086128

**Comment by user202729** [comment]
Can we leave this issue open until the error is fixed somehow? (e.g. for now the stopgap is to declare setuptools as a dependency of cython)

**Comment by da-woods** [comment]
> (e.g. for now the stopgap is to declare setuptools as a dependency of cython)

It isn't really a dependency of the "cython" command (which just does pyx->c). It's a dependency of the cythonize command, and the cythonize function in setup.py. But there's also alternative ways of building Cython modules like scikit-build and meson which I don't think use setuptools at all. 

I suspect we should add some clarification to the error message to tell people they want setuptools rather than distutils. But adding a dependency doesn't seem like the right thing to do

**Comment by user202729** [comment]
Sounds reasonable.

Actually it isn't all that difficult (a quick online search can explain which pip module to install). Maybe just something that indicates "this isn't a bug because of ⟨reasons explained above⟩" to prevent people such as myself from reporting it.
