### ISSUE TITLE
[ENH] `extern +catcher` syntax for non extern cdef functions and methods

### ISSUE THREAD

**Issue by fried** [cython/cython#5981]
### Is your feature request related to a problem? Please describe.

In my code, I would like to do [...]
```cython
cdef _somefunc(...) except +catcher
     # make some calls to C++ code that has arguments with  Rvalue move semantics produced by C++ calls that get screwed up if they themselves were marked except+
```
in 3.0.8 this produces: `Only extern functions can throw C++ exceptions.` error at compile

This was working in 3.0a6 and is used by at least one extension at Meta.  There is some advanced C++ with `folly::SemiFuture` that are not copyable and we get away with it because the code generator usually produces `cxx_call_schedule_future[FutureResultType](cxx_call2_get_future(args), future_handler_written_in_cython, <PyObject *> fut)`. The issue is some times `cxx_call2_get_future` throw exceptions, but if we make that def `except+`, it screws up code generation and makes invalid C++.  

But being able to wrap a cython `cdef` in an `except +catcher` is quite handy. 

### Describe the solution you'd like.

We go back to allowing except+ on cdef methods not extern

### Describe alternatives you've considered.

In the past I have fixed this by producing a `.h` file that has a helper that wraps the future in yet another future so the exception gets caught up in the future so the `future_handler_written_in_cython` can examine the results of the future and handle the exception in a way that doesn't produce broken C++ code.   This can be very problematic as it requires a helper function in C++ to exist for every C++ function we want to use from cython that has this behavior. 

I have a workaround i'm going to try in that I can set `cxx_call_schedule_future` as except+ and see if that works and I think it might.

**Comment by fried** [comment]
I have had similar issues with non extern cdef functions that return unique_ptr.   I have to produce my own definition for make_unique that doesn't include the except+.   Otherwise the exception handling breaks the C++ code.

**Comment by fried** [comment]
Also as this seems to have been made a compile error on purpose I don't call this a bug but a feature request

**Comment by da-woods** [comment]
If I understand correctly, inside `_somefunc` you call some c++ functions that can throw exceptions but which you're unable to mark as `except+`  because Cython fails to generate usable code for their return types. Therefore you're using `except +handler` to translate outside the Cython-defined function.

I don't think it was ever intended that this worked in Cython. With that said, the error message was targeting plain `except+` (which did nothing) rather than `except +handler` (which does something, even if not intended).

The big problem is that a c++ exception will break any reference counting that happens inside `_somefunc`.

I guess we could re-enable it for functions with no reference counted variables. I'd be very wary of re-enabling it generally though.

**Comment by fried** [comment]
Changing the error to a warning in Nodes.py does re-enable the expected behavior so it still works technically

**Comment by fried** [comment]
Would be nice if there was a mechanism to inject a C++ try/catch  at arbitrary points

**Comment by da-woods** [comment]
I've made a PR, although I'm in two minds if it's a good idea so I'm not going to merge it myself.

What I'm more interested in is having an example of code where the temp-handling doesn't work. We now move rather than copy a lot of temps in Cython 3, so my belief is that this type of code generally should work. If there's something we could improve with that, it'd probably be a much better fix.

**Comment by scoder** [comment]
I agree with @da-woods that having a concrete (toy, if necessary) example that exposes this issue would help. I would like to avoid covering up a bug that we can fixed by allowing users to do things that we cannot fix.

**Comment by navytux** [comment]
Hello up there.

Let me add a comment here because Pygolang is also using `except +topyexc` for
non-extern functions which stopped to work with Cython 3 and so Pygolang is
currently  using `Cython < 3` as its build dependency.

First to note: there is a whole "nogil" subsystem inside Pygolang: there are
nogil functions to create channels, do operations on them, and more. Overview
of this subsystem is in https://pypi.org/project/pygolang/#cython-nogil-api .

Practically all functions exposed by that subsystem can raise C++ exceptions -
a panic in pygolang speak. For example if a user does `ch.send(...)` and the
channel `ch` was already closed, it will raise a C++ exception saying that it is
invalid to send on a closed channel.

Then all those functions exposed by the nogil subsystem are _not_ marked as
`except +`.  They are not marked as such so that _it is possible to do nogil
programming on the user side with calling nogil pygolang only inside leaf
functions while still being able to organize user program with subroutines_.
For example:

```cy
cdef nogil:

    void fff(chan[int] ch):
         ggg(ch)
         
    void ggg(chan[int] ch):
         ch.send(1)
```

Here if `chan.send` would be marked as `except +...` any C++ exception raised
by that `chan.send`, would be converted to Python equivalent right after the
call and would be _not propagated_ to `fff`. Which is not good from nogil point
of view because `fff`, and _all_ its nogil callers, want to see the nogil C++
exception as it is originally raised.

Then sure, when nogil part of the program is interfaced to python part, there
is a need to convert C++ exceptions to python-level exceptions. What pygolang
is using to do that is that for every nogil C++ function that is invoked from
gil python-related part, it is creating `_pyexc` wrapper with `except +topyexc`
annotation so that that `X_pyexc` wrapper calls `X` with C++-level
`try/catch`, and upon catching C++ exception translates it to Python-level
exception with the help of custom `topyexc` converter:

```cy
cdef extern from "golang/libgolang.h" namespace "golang" nogil:
    _chan  *_makechan(unsigned elemsize, unsigned size)
    ...
    
cdef nogil:
    _chan* _makechan_pyexc(unsigned elemsize, unsigned size)    except +topyexc:
        return _makechan(elemsize, size)

    ...
        
cdef class pychan:
    def __cinit__(pychan pych, size=0, dtype=object):
        pych.dtype = parse_dtype(dtype)
        pych._ch = _makechan_pyexc(dtypeRegistry[<int>pych.dtype].size, size)
```

(see https://lab.nexedi.com/nexedi/pygolang/-/blob/044deb35/golang/_golang.pyx for full source)

This **works correctly** because there is no py-level refcounting happening inside
nogil part of the program. But Cython 3 stopped to support this and gives
compilation error with saying that

```
cdef nogil:

    _chan* _makechan_pyexc(unsigned elemsize, unsigned size)    except +topyexc:
    ^
------------------------------------------------------------

golang/_golang.pyx:569:4: Only extern functions can throw C++ exceptions.
```

A minimal example to demonstrate this problem is below:

---- 8< ---- (`x.pyx`)
```cy
# cython: language_level=2
# distutils: language = c++

cdef extern from * nogil:
    """
    #include <stdexcept>

    void panic() {
        throw std::runtime_error("panic");
    }
    """
    void panic()


cdef void topyexc() except *:
    raise RuntimeError('zzz')

cdef nogil:
    void do_aaa():
        do_bbb()
    void do_bbb():
        panic()

    void do_bbb_pyexc() except +topyexc:
        do_bbb()


do_bbb_pyexc()
```

With Cython 0.29.37 it works correctly as expected:

```console
(z-dev) kirr@deca:~/tmp/trashme/cy$ cythonize -i x.pyx && python -c 'import x'
Compiling /home/kirr/tmp/trashme/cy/x.pyx because it changed.
[1/1] Cythonizing /home/kirr/tmp/trashme/cy/x.pyx
running build_ext
building 'x' extension
...
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -ffile-prefix-map=/build/python2.7-vgIf7a/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -ffile-prefix-map=/build/python2.7-vgIf7a/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC /home/kirr/tmp/trashme/cy/tmpFtZphD/home/kirr/tmp/trashme/cy/x.o -o /home/kirr/tmp/trashme/cy/x.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "x.pyx", line 28, in init x
    do_bbb_pyexc()
  File "x.pyx", line 16, in x.topyexc
    raise RuntimeError('zzz')
RuntimeError: zzz
```

However with Cython 3.0.10 the build fails with `Only extern functions can throw C++ exceptions`:

```console
(1.venv) kirr@deca:~/tmp/trashme/cy$ cythonize -i x.pyx && python -c 'import x'
Compiling /home/kirr/tmp/trashme/cy/x.pyx because it changed.
[1/1] Cythonizing /home/kirr/tmp/trashme/cy/x.pyx
performance hint: x.pyx:19:4: Exception check on 'do_aaa' will always require the GIL to be acquired.
Possible solutions:
        1. Declare 'do_aaa' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on 'do_aaa' to allow an error code to be returned.
performance hint: x.pyx:21:4: Exception check on 'do_bbb' will always require the GIL to be acquired.
Possible solutions:
        1. Declare 'do_bbb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on 'do_bbb' to allow an error code to be returned.

Error compiling Cython file:
------------------------------------------------------------
...
    void do_aaa():
        do_bbb()
    void do_bbb():
        panic()

    void do_bbb_pyexc() except +topyexc:
    ^
------------------------------------------------------------

x.pyx:24:4: Only extern functions can throw C++ exceptions.
Traceback (most recent call last):
  File "/home/kirr/tmp/trashme/cy/1.venv/bin/cythonize", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kirr/tmp/trashme/cy/1.venv/lib/python3.11/site-packages/Cython/Build/Cythonize.py", line 251, in main
    _cython_compile_files(all_paths, options)
  File "/home/kirr/tmp/trashme/cy/1.venv/lib/python3.11/site-packages/Cython/Build/Cythonize.py", line 67, in _cython_compile_files
    ext_modules = cythonize(
                  ^^^^^^^^^^
  File "/home/kirr/tmp/trashme/cy/1.venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/home/kirr/tmp/trashme/cy/1.venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/kirr/tmp/trashme/cy/x.pyx
```

So would you please restore `except +topyexc` to be possible to do for at least nogil functions?

Thanks beforehand,
Kirill

**Comment by da-woods** [comment]
> This **works correctly** because there is no py-level refcounting happening inside
> nogil part of the program. But Cython 3 stopped to support this and gives
> compilation error with saying that
 
> So would you please restore except +topyexc to be possible to do for at least nogil functions?

The trouble is that this isn't true and that actually refcounting *does* happen in the `nogil` part of programs. Memoryviews are specifically designed to have reference counting that can happen without the gil for example:

```
cdef void f(double[:] a) nogil:
    cdef double[:] b = a
```

`f` has reference counting and needs to correctly decrement the reference count of `b` on exit.

```
cdef void g() nogil:
    with gil:
        print(None)
```

`g` has a `with gil:` block so although the function is `nogil` it isn't generally safe for a C++ exception to propagate through it.

```
cdef extern int some_func()

cdef int h() nogil:
    raise RuntimeError(some_func())
```

`h` has an implicit `with gil` block. The complication here is that `some_func` is actually run inside that implicit block, so if it raises a C++ exception then it'll fail to release the GIL again appropriately.

----------------------------------------------

In general there's a surprising number of places where Cython generates cleanup code that needs to be run that doesn't involve the GIL. While I did propose a PR to restore the misfeature (with a suitable warning) it's not really ever safe to use.

**Comment by navytux** [comment]
@da-woods, thanks for feedback.

I see. After rechecking things a bit all your examples fall into the category
where nogil function needs to take the gil inside. This is true for both `with
gil` and for `raise RuntimeError`, which is taking the gil implicitly. And it is
also true for memoryviews, which, internally do the same "with gil" logic inside e.g. `__Pyx_INC_MEMVIEW`:

https://github.com/cython/cython/blob/cf10ea12e3fc3637cf14e1bf962b295f53cc1a50/Cython/Utility/MemoryView_C.c#L529-L555

I would say one of the solutions could be to track whether a nogil function
reacquires gil internally and to reject `except +topyexc` only for those who
does.

Note that it is also generally possible to adjust utility code to be
C++-exception safe, e.g. in C++ mode to release the references via C++
destructors, which are cared to be automatically invoked by all C++ conformant
compilers. But I'm not pushing for that.

Please note that here we are not talking about new feature. Here we are talking
about the feature that was already provided and used to be there. Sure, it was
generally unsafe to use, but the codes who used it with care, did so correctly.

So if Cython is to remove the feature to prevent incorrect usage, in my view it
should provide a way for that existing codes to continue to work. I would say
more careful filtering-out could work (disable only under conditions that are
known not to work correctly and leave it possible to be used when everything
can be proven to be safe), or add a "safety-belt off" directive for those who
know what they are doing.

Without any of that there is simply _no_ _way_ for things like Pygolang
Cython/nogil mode to be upgraded to Cython 3.

Kirill

**Comment by navytux** [comment]
> Without any of that there is simply _no way_ for things like Pygolang
Cython/nogil mode to be upgraded to Cython 3.


For what it is worth: having no feedback from upstream about this backward-compatibility breakage I'm working around it via the following runtime patch which allows `cdef ... +topyexc` if there is no refcounted variables inside the function:

---- 8< ---- (kcythonize)
```py
#!/usr/bin/env python
import sys
        
from Cython.Compiler import Errors
import inspect  
 
cy_error = Errors.error
def k_cy_error(position, message): 
    if message == 'Only extern functions can throw C++ exceptions.':
        fcaller = inspect.currentframe().f_back                     
        if fcaller.f_code.co_name == 'analyse_declarations':
            fcaller.f_locals['self']._cxx_except = True
            return
    return cy_error(position, message)
Errors.error = k_cy_error
 
 
from Cython.Compiler.Nodes import CFuncDefNode
CFuncDefNode._cxx_except = False
cf_analyse_expressions = CFuncDefNode.analyse_expressions
def k_analyse_expressions(self, env):
    if self._cxx_except:
        for entry in self.local_scope.var_entries:
            if entry.type.needs_refcounting:
                cy_error(self.pos, "cdef funcion %s cannot throw C++ exception because it has refcounted variable %s" % (self.declarator.declared_name(), entry.name))
 
    return cf_analyse_expressions(self, env)
CFuncDefNode.analyse_expressions = k_analyse_expressions
 
    
from Cython.Build.Cythonize import main
sys.exit(main())
```

---- 8< ---- (x.pyx)
```py
# cython: language_level=2
# distutils: language = c++
# cython: legacy_implicit_noexcept = True
 
cdef extern from * nogil:
    """
    #include <stdexcept>
 
    void panic() {
        throw std::runtime_error("panic");
    }   
    """
    void panic()
 
 
cdef void topyexc() except *:
    raise RuntimeError('zzz !!!!')
        
cdef object gobj = '123'
            
cdef nogil: 
    void do_bbb():
        panic()
 
    void do_bbb_pyexc(double[:] a) except +topyexc:
        cdef double[:] b = a
        do_bbb()
 
 
do_bbb_pyexc(None)
```

```console
((1.venv) ) kirr@deca:~/tmp/trashme/pyexc$ ./kcythonize -i x.pyx && python -c 'import x'
Compiling /home/kirr/tmp/trashme/pyexc/x.pyx because it changed.
[1/1] Cythonizing /home/kirr/tmp/trashme/pyexc/x.pyx
warning: x.pyx:22:15: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "x.pyx", line 29, in init x
    do_bbb_pyexc()
  File "x.pyx", line 17, in x.topyexc
    raise RuntimeError('zzz !!!!')
RuntimeError: zzz !!!!
```


---- 8< ---- (y.pyx)
```
# cython: language_level=2
# distutils: language = c++
# cython: legacy_implicit_noexcept = True
 
cdef extern from * nogil:
    """
    #include <stdexcept>
 
    void panic() {
        throw std::runtime_error("panic");
    }
    """
    void panic()
 
 
cdef void topyexc() except *:
    raise RuntimeError('zzz !!!!')
 
cdef object gobj = '123'
 
cdef nogil: 
    void do_bbb():
        panic()
 
    void do_bbb_pyexc(double[:] a) except +topyexc:
        cdef double[:] b = a
        do_bbb()
 
 
do_bbb_pyexc(None)
```

```console
((1.venv) ) kirr@deca:~/tmp/trashme/pyexc$ ./kcythonize -i y.pyx && python -c 'import y'
Compiling /home/kirr/tmp/trashme/pyexc/y.pyx because it changed.
[1/1] Cythonizing /home/kirr/tmp/trashme/pyexc/y.pyx
warning: y.pyx:22:15: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.
 
Error compiling Cython file:
------------------------------------------------------------
...
 
cdef nogil:
    void do_bbb():
        panic()
 
    void do_bbb_pyexc(double[:] a) except +topyexc:
    ^
------------------------------------------------------------
 
y.pyx:25:4: cdef funcion do_bbb_pyexc cannot throw C++ exception because it has refcounted variable b
```


-------

@da-woods, @scoder will you be willing to accept such approach into Cython itself?

**Comment by da-woods** [comment]
I'm still a bit unclear on why you need this.

> Here if `chan.send` would be marked as `except +...` any C++ exception raised
by that `chan.send`, would be converted to Python equivalent right after the
call and would be not propagated to `fff`.

"not propagated" isn't right. In Cython 3 and higher it's propagated by default (unless you mark the function as `noexcept`). Even in Cython 0.29 it would be propagated if you marked the function as `except *`.

**However** - it isn't particularly efficient to check if an exception is raised and that is a real problem. One way round that is to return an `int` rather than a `void` and use `except -1?`.

So the question is:
* Is there something about these functions that means they're used somewhere that absolutely cannot ever acquire the GIL?
* Is it that you're losing information when translating to a Python exception?
  * For example, are you calling Cython code from external C++ code and the C++ code wants to see the original C++ exception?
* Or is it mainly a performance concern about the cost of checking?

----------------------------------------------------------------------------

If we wanted to allow this again, I think I actually have a better scheme in that we can save C++ exceptions into `std::exception_pointer` and then rethrow them using `std::rethrow_exception`. Under this scheme you'd have to declare `do_bbb` as `except+` but it'd mean we could fairly easily pass C++ exceptions through arbitrary Cython code (with a little bit of runtime cost round each call). I'd be much happier with that than with trying to work out which Cython functions are "safe" to throw exceptions through.

**Comment by navytux** [comment]
@da-woods, thanks for feedback.

Yes, those functions do not want to acquire the GIL:

[Libgolang](https://lab.nexedi.com/nexedi/pygolang/-/blob/master/golang/libgolang.h) is C++ library that allows threads to interoperate via channels. It is just C++ and does not depend nor involve Python runtime at all. As the result several threads can run simultaneously without being blocked by the GIL. [Pygolang Cython/nogil](https://pygolang.nexedi.com/#cython-nogil-api) API is just a plain wrapper over that.

That's about "efficiency", but there is also "correctness" part: in my use-case of wendelin.core, if we let any of those functions to acquire the GIL it will _deadlock_ the system. From https://lab.nexedi.com/nexedi/wendelin.core/-/blob/e8a00ac0/wcfs/client/client_test.py#L56-90 :

```py
        # NOTE access to memory goes _with_ GIL: this verifies that wcfs pinner
        # is implemented in fully nogil mode because if that was not the case,
        # the pinner would deadlock trying to acquire GIL in its thread while
        # user thread that triggered the access is already holding the GIL.
        #
        #      - - - - - -
        #     |           |
        #        pinner <------.
        #     |           |   wcfs
        #        client -------^
        #     |           |
        #      - - - - - -
        #     client process
        #
```

So yes, here we do not want to acquire the GIL for both correctness and efficiency reasons.

And even if that would not be the case, mixing in Python runtime in places where Cython is used to wrap just plain C++ without py bits, in my view, is just adding extra unnecessary overhead. For me Pyrex/Cython could be always used in two modes: first, for interacting with and doing py bits, and second, for doing non-py bits in Python-like language. My take is that for the second use case conveying C++ exception through Python runtime is undesirable.


Hope it clarifies things a bit,
Kirill
