### ISSUE TITLE
[BUG] Fused type inference does not handle cpdef enum class at runtime

### ISSUE THREAD

**Issue by vyasr** [cython/cython#5984]
### Describe the bug

If a cpdef enum class is used as part of a fused type, functions using that fused type as an enum do not properly dispatch code paths at runtime.

### Code to reproduce the behaviour:

We first need one file defining the fused type and associated function.
```cython
# declarations.pxd
# distutils: language = c++

cpdef enum class my_enum:
    FOO
    BAR

ctypedef fused my_fused:
    int
    my_enum

cpdef void g(my_fused baz)

# declarations.pyx
cpdef void g(my_fused baz):
    if my_fused is my_enum:
        print("Got the enum")
    else:
        print("Don't know what I am")
```

If we now try and use this in a pure Python context (no cdefing the variables holding enum values)
```
# definitions.pyx
from declarations import g, my_enum

def h():
    g(my_enum.FOO)

h()
```

Then we see:
```
(main) dt08% python -c "import definitions"
Don't know what I am
```

If we instead called `g` with another type it did not understand, e.g. a string, we get a more reasonable runtime failure:
```
(main) dt08% python -c "import definitions"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "definitions.pyx", line 7, in init definitions
    h()
  File "definitions.pyx", line 5, in definitions.h
    g('str')
  File "declarations.pyx", line 1, in declarations.__pyx_fused_cpdef
    cpdef void g(my_fused baz):
TypeError: No matching signature found
```

### Expected behaviour

Ideally the Cython enum should be properly understood as one of the overloaded types and have the correct enum selected at both compile-time and runtime. However, I think it would be a good starting point to at least make the runtime case error in a more predictable manner. The current behavior is potentially very confusing, seemingly undefined behavior from the caller's perspective.

I don't know enough about how Cython handles fused types to be sure, but I suspect that properly enabling runtime translation of the Python wrapper enum down to the C++ enum is a bit tricky to handle since I imagine that Cython would want to do something smarter than check every PyObject input (what I assume it's seeing at runtime) against every known enum class type, and I don't know what information Cython has available to make a smarter decision.

### OS

Linux

### Python version

3.11.4

### Cython version

3.0.8

**Comment by da-woods** [comment]
Yes I think this should work. I doubt it's actually too hard since it's just an isinstance check of the enum types in the fused type (i.e. the same as what we'd do if it was a `cdef class` in the fused type).

The only complication is that sometimes we can't import the enum type at runtime (for cpdef enum types defined in a pxd that doesn't have a matching pyx file)

**Comment by vyasr** [comment]
> for cpdef enum types defined in a pxd that doesn't have a matching pyx file

I don't think this case should be an issue. If there's no pyx file then the Python will never be created so a user also wouldn't be able to instantiate it, right? So any internal check could just be ignored if the object in question didn't exist (I'm hand-waving through the internals since I don't know them!).
