### ISSUE TITLE
[BUG] Incompatibility of Integers for Arithmetic Operations with Floating-Point Numbers in Class Instance Methods

### ISSUE THREAD

**Issue by yudonglin** [cython/cython#6004]
### Describe the bug

Cannot add/minus/divide/multiply a integer number with a floating number in a class instance method.
You can do it outside the class instance method, but not inside.
Current release of cython 3.0.8 works just fine, getting this error only when using cython that build from source (master-e9b08d3)

### Code to reproduce the behaviour:

```cython
button_width_t: int = 20
print(button_width_t * 8.5)

count_t: int = 20
print(count_t / button_width_t)


class M:
    def new(self) -> None:
        button_width: int = 20
        # print(button_width * 8.5) # << error
        count: int = 100
        rows: float = count / button_width # << also cause error
```

### Expected behaviour

Getting error:
```
[1/1] Cythonizing src\testfolder\__init__.py

Error compiling Cython file:
------------------------------------------------------------
...
print(button_width_i * 8.5)

class M:
    def new(self) -> None:
        button_width: int = 20
        print(button_width * 8.5)
                           ^
------------------------------------------------------------

src\testfolder\__init__.py:8:27: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(__init__.py:2:0)
StatListNode.stats[2] = PyClassDefNode(__init__.py:5:0,
    name = 'M')
PyClassDefNode.body = StatListNode(__init__.py:6:4)
StatListNode.stats[0] = DefNode(__init__.py:6:4,
    is_cyfunction = True,
    modifiers = [...]/0,
    name = 'new',
    np_args_idx = [...]/0,
    num_required_args = 1,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 390, in analyse_expressions: StatListNode(__init__.py:7:8)
File 'Nodes.py', line 5982, in analyse_expressions: ExprStatNode(__init__.py:8:13)
File 'ExprNodes.py', line 618, in analyse_expressions: SimpleCallNode(__init__.py:8:13,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 6112, in analyse_types: SimpleCallNode(__init__.py:8:13,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 8598, in analyse_types: TupleNode(__init__.py:8:13,
    is_sequence_constructor = 1,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 12193, in analyse_types: MulNode(__init__.py:8:27,
    infix = True,
    operator = '*',
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 11760, in analyse_operation: MulNode(__init__.py:8:27,
    infix = True,
    operator = '*',
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "C:\Program Files\Python312\Lib\site-packages\Cython\Compiler\ExprNodes.py", line 11760, in analyse_operation
    assert self.type.is_pyobject
AssertionError:
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yudon\AppData\Roaming\Python\Python312\site-packages\linpgtoolbox\_compiler.py", line 21, in _compile_file
    ext_modules=cythonize(
                ^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\Cython\Build\Dependencies.py", line 1168, in cythonize
    cythonize_one(*args)
  File "C:\Program Files\Python312\Lib\site-packages\Cython\Build\Dependencies.py", line 1331, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src\testfolder\__init__.py
```

### OS

Windows 11

### Python version

python 3.12.2

### Cython version

3.1.0a0

**Comment by da-woods** [comment]
Thanks - this bisects to 0adbcde2377c2712b833f697a5ee5c64490fdeee

**Comment by da-woods** [comment]
Annotations are largely ignored at the module scope, so that's likely the cause of the difference
