### ISSUE TITLE
[ENH] 

### ISSUE THREAD

**Issue by winer632** [cython/cython#6097]
### Is your feature request related to a problem? Please describe.

In my code, I would like to use the vector database function of redis. I compiled this method using Cython3.0.9 version, but got the following error
```python
def search_documents(
        self,
        query_vector: bytes,
        doc_ids: List[str],
        topk: int = 5,
    ) -> List[Any]:
        """
        Searches the redis index using the query vector.

        Args:
            query_vector (np.ndarray): Embedded query vector.
            doc_ids (List[str]): id of docs, if doc_ids is empty search the whole database
            topk (int, optional): Number of results. Defaults to 5.

        Returns:
            List[Any]: Search result documents.
        """
        if len(doc_ids) == 0:
            return []
        else:
            formatted_doc_ids = "|".join(doc_ids)
            q = f"""(@doc_id:{{{formatted_doc_ids}}})=>[KNN {topk} \
                    @{self.config.vector_field_name} $vec_param AS vector_score]"""

        query = (
            Query(q)
            .sort_by("vector_score")
            .paging(0, topk)
            .return_fields(
                "chunk_id",
                "page_id",
                "doc_id",
                "vector_score",
                "text",
                "parents",
                "children",
                "jump_index",
                "links",
                "lang"
            )
            .dialect(2)
        )
        params_dict = {"vec_param": query_vector}
        result_documents = self.redis_connection.ft().search(
            query, query_params=params_dict).docs

        out = list()
        for document in result_documents:
            if getattr(document, "text", None) is not None:
                doc_dict = document_to_dict(document)
                doc_dict["links"] = doc_dict["links"].split("|") if "links" in doc_dict else []
                out.append(doc_dict)

        return out
```

```cython
 /* "app/datastore/doc_store.py":99
 *                 document['links'] = '|'.join(document['links'])
 *             redis_pipeline.hset(key, mapping=document)
 *         redis_pipeline.execute()             # <<<<<<<<<<<<<<
 * 
 *     def search_documents(
 */
  __pyx_t_10 = __Pyx_PyObject_GetAttrStr(__pyx_v_redis_pipeline, __pyx_n_s_execute); if (unlikely(!__pyx_t_10)) __PYX_ERR(0, 99, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_10);
  __pyx_t_9 = NULL;
  __pyx_t_11 = 0;
  #if CYTHON_UNPACK_METHODS
  if (likely(PyMethod_Check(__pyx_t_10))) {
    __pyx_t_9 = PyMethod_GET_SELF(__pyx_t_10);
    if (likely(__pyx_t_9)) {
      PyObject* function = PyMethod_GET_FUNCTION(__pyx_t_10);
      __Pyx_INCREF(__pyx_t_9);
      __Pyx_INCREF(function);
      __Pyx_DECREF_SET(__pyx_t_10, function);
      __pyx_t_11 = 1;
    }
  }
  #endif
  {
    PyObject *__pyx_callargs[2] = {__pyx_t_9, NULL};
    __pyx_t_3 = __Pyx_PyObject_FastCall(__pyx_t_10, __pyx_callargs+1-__pyx_t_11, 0+__pyx_t_11);
    __Pyx_XDECREF(__pyx_t_9); __pyx_t_9 = 0;
    if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 99, __pyx_L1_error)
    __Pyx_GOTREF(__pyx_t_3);
    __Pyx_DECREF(__pyx_t_10); __pyx_t_10 = 0;
  }
  __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;

```

The following is the error message

```
  File "/data/miniconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 81, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 76, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 101, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app/common/loggin_middleware.py", line 16, in app.common.loggin_middleware.LoggingMiddleware.dispatch
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/miniconda3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/miniconda3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "app/query_system/message_api.py", line 317, in message_docs
  File "app/datastore/doc_store.py", line 144, in app.datastore.doc_store.DocDataStore.search_documents
  File "/data/miniconda3/lib/python3.11/site-packages/redis/commands/search/commands.py", line 420, in search
    res = self.execute_command(SEARCH_CMD, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/redis/client.py", line 1269, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/redis/client.py", line 1270, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/redis/client.py", line 1246, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/lib/python3.11/site-packages/redis/connection.py", line 905, in read_response
    raise response
redis.exceptions.ResponseError: Syntax error at offset 55 near \

^C
```

**Comment by da-woods** [comment]
If you want someone to try to fix this then you need to reduce this down to a short reproducible example. There definitely isn't enough information to debug this. It also really isn't clear from the traceback that the error has anything to do with the code you've shown.

This also doesn't look like the sort of code that benefits from using Cython, so maybe consider whether it's worth trying to translate it?

**Comment by winer632** [comment]
> If you want someone to try to fix this then you need to reduce this down to a short reproducible example. There definitely isn't enough information to debug this. It also really isn't clear from the traceback that the error has anything to do with the code you've shown.
> 
> This also doesn't look like the sort of code that benefits from using Cython, so maybe consider whether it's worth trying to translate it?

I use Cython and want to encrypt python code. I Can benefit from encryption.

**Comment by winer632** [comment]
> If you want someone to try to fix this then you need to reduce this down to a short reproducible example. There definitely isn't enough information to debug this. It also really isn't clear from the traceback that the error has anything to do with the code you've shown.
> 
> This also doesn't look like the sort of code that benefits from using Cython, so maybe consider whether it's worth trying to translate it?

I will try to write a demo to demonstrate the problem I encountered with later when I got time. Thanks for your work! Cython is a great project to keep python project safe!
