### ISSUE TITLE
source code string cannot contain null bytes

### ISSUE THREAD

**Issue by codes-team** [cython/cython#6184]
### Describe the bug

Hello Sir, when i use cython to compile python code i found this issue

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/cythonize", line 5, in <module>
    from Cython.Build.Cythonize import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Cython/Build/__init__.py", line 1, in <module>
    from .Dependencies import cythonize
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 3, in <module>
    import cython
SyntaxError: source code string cannot contain null bytes

I have had this problem for a long time, but I wanted to search for a solution on the Internet first before bothering you with my small problem but i don't found any sultion i try install old versions from cython but i got the same issue

"""i have this issue in phone so i don't know if this is cause of the problem"""

"""the compiled sources with cython work with me in phone but when i try compile it in phone i got this error"""

i hope you have nice day, and thanks so much for cython project it's perfect❤

### Code to reproduce the behaviour:

```cython
# example code
```

**Comment by da-woods** [comment]
I don't know. This does seem more likely to be an issue with Termux than with Cython since we don't have this issue on other platforms. Maybe try to work out were the null byte is:

```
with open(filename) as f:
  contents = f.read().encode("utf-8")
print(contents.find(b"\0"))
```

But I'm not really sure what you do when you find out.

**Comment by codes-team** [comment]
> I don't know. This does seem more likely to be an issue with Termux than with Cython since we don't have this issue on other platforms. Maybe try to work out were the null byte is:
> 
> ```
> with open(filename) as f:
>   contents = f.read().encode("utf-8")
> print(contents.find(b"\0"))
> ```
> 
> But I'm not really sure what you do when you find out.

thank you so much i will try it
