### ISSUE TITLE
[BUG]   call to undeclared function `PyDataType_ELSIZE`; ISO C99 and later do not support implicit function declarations.

### ISSUE THREAD

**Issue by zoj613** [cython/cython#6488]
### Describe the bug

When trying to build a downstream project on OSX I get the error in the issue title. I'm not sure what is causing this. I tried all cython versions > 3.0.0 and also installed cython using the master branch but it still won't go away. Here is a snippet of this error log message:

```
2024-11-08T10:04:16.0408150Z x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem $PREFIX/include -fPIC -O2 -isystem $PREFIX/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/polyagamma-2.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.13 -mmacosx-version-min=10.13 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I$PREFIX/lib/python3.10/site-packages/numpy/core/include -I./include -I$PREFIX/include/python3.10 -c polyagamma/_polyagamma.c -o build/temp.macosx-10.13-x86_64-cpython-310/polyagamma/_polyagamma.o -O2 -std=c99
2024-11-08T10:04:16.2801860Z polyagamma/_polyagamma.c:3411:13: error: call to undeclared function 'PyDataType_ELSIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.2802910Z  3411 |   __pyx_r = PyDataType_ELSIZE(__pyx_v_self);
2024-11-08T10:04:16.2804000Z       |             ^
2024-11-08T10:04:16.2845860Z polyagamma/_polyagamma.c:3445:13: error: call to undeclared function 'PyDataType_ALIGNMENT'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.2847760Z  3445 |   __pyx_r = PyDataType_ALIGNMENT(__pyx_v_self);
2024-11-08T10:04:16.2848310Z       |             ^
2024-11-08T10:04:16.2878450Z polyagamma/_polyagamma.c:3483:15: error: call to undeclared function 'PyDataType_FIELDS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.2881870Z  3483 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
2024-11-08T10:04:16.2882480Z       |               ^
2024-11-08T10:04:16.2883380Z polyagamma/_polyagamma.c:3483:13: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
2024-11-08T10:04:16.2884750Z  3483 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
2024-11-08T10:04:16.2885410Z       |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-11-08T10:04:16.2909080Z polyagamma/_polyagamma.c:3525:15: error: call to undeclared function 'PyDataType_NAMES'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.2910980Z  3525 |   __pyx_t_1 = PyDataType_NAMES(__pyx_v_self);
2024-11-08T10:04:16.2916760Z       |               ^
2024-11-08T10:04:16.2917680Z polyagamma/_polyagamma.c:3525:13: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
2024-11-08T10:04:16.2918390Z  3525 |   __pyx_t_1 = PyDataType_NAMES(__pyx_v_self);
2024-11-08T10:04:16.2918930Z       |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-11-08T10:04:16.2950050Z polyagamma/_polyagamma.c:3563:13: error: call to undeclared function 'PyDataType_SUBARRAY'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.2952610Z  3563 |   __pyx_r = PyDataType_SUBARRAY(__pyx_v_self);
2024-11-08T10:04:16.2953220Z       |             ^
2024-11-08T10:04:16.2954560Z polyagamma/_polyagamma.c:3563:11: error: incompatible integer to pointer conversion assigning to 'PyArray_ArrayDescr *' (aka 'struct _arr_descr *') from 'int' [-Wint-conversion]
2024-11-08T10:04:16.2955490Z  3563 |   __pyx_r = PyDataType_SUBARRAY(__pyx_v_self);
2024-11-08T10:04:16.2956030Z       |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-11-08T10:04:16.2981070Z polyagamma/_polyagamma.c:3597:13: error: call to undeclared function 'PyDataType_FLAGS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.2981930Z  3597 |   __pyx_r = PyDataType_FLAGS(__pyx_v_self);
2024-11-08T10:04:16.2983180Z       |             ^
2024-11-08T10:04:16.3050140Z polyagamma/_polyagamma.c:3631:13: error: call to undeclared function 'PyArray_MultiIter_NUMITER'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.3051670Z  3631 |   __pyx_r = PyArray_MultiIter_NUMITER(__pyx_v_self);
2024-11-08T10:04:16.3052260Z       |             ^
2024-11-08T10:04:16.3113890Z polyagamma/_polyagamma.c:3665:13: error: call to undeclared function 'PyArray_MultiIter_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.3114990Z  3665 |   __pyx_r = PyArray_MultiIter_SIZE(__pyx_v_self);
2024-11-08T10:04:16.3115520Z       |             ^
2024-11-08T10:04:16.3164380Z polyagamma/_polyagamma.c:3699:13: error: call to undeclared function 'PyArray_MultiIter_INDEX'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.3165920Z  3699 |   __pyx_r = PyArray_MultiIter_INDEX(__pyx_v_self);
2024-11-08T10:04:16.3166470Z       |             ^
2024-11-08T10:04:16.3214810Z polyagamma/_polyagamma.c:3733:13: error: call to undeclared function 'PyArray_MultiIter_NDIM'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.3215700Z  3733 |   __pyx_r = PyArray_MultiIter_NDIM(__pyx_v_self);
2024-11-08T10:04:16.3216090Z       |             ^
2024-11-08T10:04:16.3264700Z polyagamma/_polyagamma.c:3767:13: error: call to undeclared function 'PyArray_MultiIter_DIMS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.3265730Z  3767 |   __pyx_r = PyArray_MultiIter_DIMS(__pyx_v_self);
2024-11-08T10:04:16.3266860Z       |             ^
2024-11-08T10:04:16.3267750Z polyagamma/_polyagamma.c:3767:11: error: incompatible integer to pointer conversion assigning to 'npy_intp *' (aka 'long *') from 'int' [-Wint-conversion]
2024-11-08T10:04:16.3268500Z  3767 |   __pyx_r = PyArray_MultiIter_DIMS(__pyx_v_self);
2024-11-08T10:04:16.3269990Z       |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-11-08T10:04:16.3313890Z polyagamma/_polyagamma.c:3801:13: error: call to undeclared function 'PyArray_MultiIter_ITERS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
2024-11-08T10:04:16.3315220Z  3801 |   __pyx_r = PyArray_MultiIter_ITERS(__pyx_v_self);
2024-11-08T10:04:16.3316890Z       |             ^
2024-11-08T10:04:16.3317850Z polyagamma/_polyagamma.c:3801:11: error: incompatible integer to pointer conversion assigning to 'void **' from 'int' [-Wint-conversion]
2024-11-08T10:04:16.3319120Z  3801 |   __pyx_r = PyArray_MultiIter_ITERS(__pyx_v_self);
2024-11-08T10:04:16.3319740Z       |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-11-08T10:04:16.4145060Z 17 errors generated.
2024-11-08T10:04:16.4188690Z error: command '/Users/runner/miniforge3/conda-bld/polyagamma_1731060005143/_build_env/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
2024-11-08T10:04:17.0924870Z Traceback (most recent call last):
2024-11-08T10:04:17.0930810Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/build.py", line 2555, in build
2024-11-08T10:04:17.0937540Z     utils.check_call_env(
2024-11-08T10:04:17.0938440Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/utils.py", line 404, in check_call_env
2024-11-08T10:04:17.0939500Z     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
2024-11-08T10:04:17.0944980Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-08T10:04:17.0952980Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
2024-11-08T10:04:17.0956600Z     raise subprocess.CalledProcessError(proc.returncode, _args)
2024-11-08T10:04:17.0963110Z subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/polyagamma_1731060005143/work/conda_build.sh']' returned non-zero exit status 1.
2024-11-08T10:04:17.0966550Z 
2024-11-08T10:04:17.0973220Z The above exception was the direct cause of the following exception:
2024-11-08T10:04:17.0976260Z 
2024-11-08T10:04:17.0988080Z Traceback (most recent call last):
2024-11-08T10:04:17.0990650Z   File "/Users/runner/miniforge3/bin/conda-build", line 11, in <module>
2024-11-08T10:04:17.0996670Z     sys.exit(execute())
2024-11-08T10:04:17.1003350Z              ^^^^^^^^^
2024-11-08T10:04:17.1015980Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 589, in execute
2024-11-08T10:04:17.1017580Z     api.build(
2024-11-08T10:04:17.1034300Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/api.py", line 209, in build
2024-11-08T10:04:17.1036680Z     return build_tree(
2024-11-08T10:04:17.1046760Z            ^^^^^^^^^^^
2024-11-08T10:04:17.1050030Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/build.py", line 3655, in build_tree
2024-11-08T10:04:17.1053350Z     packages_from_this = build(
2024-11-08T10:04:17.1058420Z                          ^^^^^^
2024-11-08T10:04:17.1062640Z   File "/Users/runner/miniforge3/lib/python3.12/site-packages/conda_build/build.py", line 2563, in build
2024-11-08T10:04:17.1064920Z     raise BuildScriptException(str(exc), caused_by=exc) from exc
2024-11-08T10:04:17.1066580Z conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/polyagamma_1731060005143/work/conda_build.sh']' returned non-zero exit status 1.
```

### Code to reproduce the behaviour:

```cython
# example code
```

### Expected behaviour

successful compilation

### OS

macOS

### Python version

3.10 - 3.13

### Cython version

3.1.0

### Additional context

here is the raw log file of one of these runs:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/1075118/logs/83

Not that the compilation completes successfully on Linux and Windows for all Cython > 3.0.0

**Comment by da-woods** [comment]
`PyDataType_ELSIZE` doesn't appear in the Cython source code so I don't think this is on us.

It looks like this is something that was added to the Numpy C API with Numpy version 2. I'd suggest you aren't passing the correct path to the Numpy headers to your C compiler.
