### ISSUE TITLE
[BUG] Can't import module with name memoryview in cython>=3

### ISSUE THREAD

**Issue by ZzEeKkAa** [cython/cython#6535]
### Describe the bug

Any package that named memoryview is interpreted as a builtin type. This will crash at runtime (see code) `from cpython cimport memoryview as _memoryview`, however this works `from cpython.memoryview cimport PyMemoryView_FromMemory`

### Code to reproduce the behaviour:

```cython
cimport cpython
from cpython cimport memoryview as _memoryview
import numpy as _numpy

from libc.stdlib cimport malloc
from libc.stdint cimport intptr_t

cpdef test_mem(size_t size):
    cdef int* vec = <int*> malloc(size * sizeof(int))

    for i in range(size):
        vec[i] = i

    cdef object buf = _memoryview.PyMemoryView_FromMemory(
        <char*><intptr_t>vec, size * sizeof(int), cpython.PyBUF_READ)
    return _numpy.ndarray((size,), buffer=buf, dtype=_numpy.int32)
```

```python
from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules = cythonize("example.pyx")
)
```

```bash
$ python3.12 -m venv .venv
$ source ./.venv/bin/activate
$ pip install 'cython>=3' setuptools numpy
$ python setup.py build_ext --inplace
$ python -c "import example; print(example.test_mem(10))"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "example.pyx", line 8, in example.test_mem
    cpdef test_mem(size_t size):
  File "example.pyx", line 14, in example.test_mem
    cdef object buf = _memoryview.PyMemoryView_FromMemory(
AttributeError: type object 'memoryview' has no attribute 'PyMemoryView_FromMemory'

$ pip install 'cython<3' setuptools numpy
$ python setup.py build_ext --inplace
$ python -c "import example; print(example.test_mem(10))"

[0 1 2 3 4 5 6 7 8 9]
```

### Expected behaviour

Work as prior to Cython 3.0.0 or compilation time error.

### OS

Linux, MacOS, others not tested

### Python version

3.12.7

### Cython version

any 3.*

**Comment by da-woods** [comment]
For reference the basic bug is also an issue in earlier versions of Cython

```
from cpython cimport list as _lst

def test_list():
    return _lst.PyList_New(0);
```

This fails similarly on 0.29.x.

The difference is that `memoryview` is specifically recognised as a builtin type on Cython 3+
