### ISSUE TITLE
[BUG] Test test_plus_one_twice (ufunc) fails with NumPy 2.2.x

### ISSUE THREAD

**Issue by penguinpee** [cython/cython#6581]
### Describe the bug

We see one test failing when building Cython with NumPy 2.2.x. First seen with NumPy 2.2.0 and still present when building with NumPy 2.2.1.

I searched through issues and saw #6072, which mentioned the same error among many others. We only see this one issue with `np.complex128` mentioned below.

```
======================================================================
FAIL: test_plus_one_twice (ufunc)
Doctest: ufunc.test_plus_one_twice
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.13/doctest.py", line 2327, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for ufunc.test_plus_one_twice
  File "/builddir/build/BUILD/Cython-3.0.11-build/cython-3.0.11/TEST_TMP/36/run/c/ufunc/ufunc.cpython-313-x86_64-linux-gnu.so", line unknown line number, in test_plus_one_twice
----------------------------------------------------------------------
File "/builddir/build/BUILD/Cython-3.0.11-build/cython-3.0.11/TEST_TMP/36/run/c/ufunc/ufunc.cpython-313-x86_64-linux-gnu.so", line ?, in ufunc.test_plus_one_twice
Failed example:
    plus_one_twice(1.j)
Expected:
    ((1+1j), (1+1j))
Got:
    (np.complex128(1+1j), np.complex128(1+1j))
======================================================================
FAIL: test_plus_one_twice (ufunc)
Doctest: ufunc.test_plus_one_twice
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.13/doctest.py", line 2327, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for ufunc.test_plus_one_twice
  File "/builddir/build/BUILD/Cython-3.0.11-build/cython-3.0.11/TEST_TMP/36/run/cpp/ufunc/ufunc.cpython-313-x86_64-linux-gnu.so", line unknown line number, in test_plus_one_twice
----------------------------------------------------------------------
File "/builddir/build/BUILD/Cython-3.0.11-build/cython-3.0.11/TEST_TMP/36/run/cpp/ufunc/ufunc.cpython-313-x86_64-linux-gnu.so", line ?, in ufunc.test_plus_one_twice
Failed example:
    plus_one_twice(1.j)
Expected:
    ((1+1j), (1+1j))
Got:
    (np.complex128(1+1j), np.complex128(1+1j))
```

### OS

Linux

### Python version

3.13.1

### Cython version

3.0.11

**Comment by da-woods** [comment]
Fixed in 852286242.

It's only an issue with how the tests are displayed though - you don't need to treat it as a "real" failure.
